src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to the actual Contact record for dereferencing the complete set of Contact fields in formulas and validations</description>
        <inlineHelpText>The student contact field is set automatically when the account record is created or updated</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Contact</relationshipLabel>
        <relationshipName>StudentContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ProspectRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Prospects</description>
        <label>ProspectRecord</label>
    </recordTypes>
</CustomObject>

src/objects/CAREProgram__c.object
<CustomObject>
    <description>The object to handle all of the CARE Programs and their codes</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProgramLabel__c</fullName>
        <description>This is the field that is used for EC Assignment</description>
        <label>Program Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CARE Program</label>
    <nameField>
        <label>CARE Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CareProgramMiddleEarth__c.object
<CustomObject>
    <description>Used to bring together the CARE Program code and the PAMS program code together.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BannerProgramCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banner Program Code</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>CARE Programs Middle Earth</relationshipLabel>
        <relationshipName>CAREProgramsMiddleEarth</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CAREProgramCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CARE Program Code</label>
        <referenceTo>CAREProgram__c</referenceTo>
        <relationshipLabel>CARE Programs Middle Earth</relationshipLabel>
        <relationshipName>CAREProgramsMiddleEarth</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CARE Program Middle Earth</label>
    <nameField>
        <label>Program Middle Earth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs Middle Earth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for wguProgram</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ProspectRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Prospects</description>
        <label>ProspectRecord</label>
    </recordTypes>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MarketingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Program</label>
        <referenceTo>CareProgramMiddleEarth__c</referenceTo>
        <relationshipLabel>CAREProfile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonalPageIdentifier__c</fullName>
        <description>This is for the personal page to store the ID to support the public personal page.</description>
        <label>Personal Page Identifier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAttributes__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Convenience lookup for Informatica to grab all information about a Paid Applicant in one shot instead of splitting into multiple jobs.</description>
        <label>Student Attributes</label>
        <referenceTo>StudentAttributes__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>StudentContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CARE Profile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>IntakeInterviewReady</fullName>
        <active>true</active>
        <businessProcess>Intake</businessProcess>
        <label>IntakeInterviewReady</label>
    </recordTypes>
</CustomObject>

src/objects/Personal_Pages_Link__c.object
<CustomObject>
    <description>Personal Pages Links is for the creation and maintenance of links on the personal pages.</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>affiliation__c</fullName>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>WGU-SLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TEX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TEN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>image__c</fullName>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>label__c</fullName>
        <description>The display name for the link.</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>link__c</fullName>
        <label>Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sort_order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Personal Pages Link</label>
    <nameField>
        <label>Personal Pages Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Pages Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/StudentAttributes__c.object
<CustomObject>
    <description>Custom object to manage student attributes via portal and sites, with update triggers to Contact/Account</description>
    <fields>
        <fullName>Affiliation__c</fullName>
        <description>WGU affiliate the student belongs to</description>
        <inlineHelpText>Set the student&apos;s WGU affiliation.</inlineHelpText>
        <label>University Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>WGU</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related contact record for this student&apos;s attributes</description>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students Attributes</relationshipLabel>
        <relationshipName>Students_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Attributes</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Degree Program is active and can be used.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CatalogTerm__c</fullName>
        <description>The catalog Term this program was built. This is the Major Version in the PAMS database.</description>
        <label>Catalog Term</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PAMSID__c</fullName>
        <description>The ID that represents the program in PAMS.</description>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestPersonalPages.cls
@IsTest
public class TestPersonalPages{
    
 /*   class JsonOutput
    {
        String firstName;
        String lastName;
        String ecName;
        String programName;
        List<Personal_Pages_Link__c> personalPagesLinks;
        String identifier;
        String errorMessage;
        
    }
*/    
    
    
    @IsTest
        public static void helloWorld(){
            
            System.assert(true);
            
        }
    
    //Tests simple name no special characters, valid
    @IsTest
        public static void testGenerateIdentifier(){
            
            Test.startTest();
            Contact contact = new Contact(firstName='Sync', lastName = 'MacTester', email='MACTESTER@Msn.com',  pidm__C = '12356321' );
            contact.recordtypeid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id; 
            
            insert contact;
            
            Account student = [Select id, pidm__C from Account where studentcontact__r.id = :contact.id];
            
            Opportunity care = new Opportunity(AccountId=student.Id, StudentContact__c = contact.id,  Name='Sync MacTester', CloseDate=date.today(), StageName='Intake', RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
            insert care;
            
            
            Test.stopTest();
            
            Contact testContact = [Select id, lastName, FirstName from Contact where id = :contact.id];
            Opportunity testOpportunity = [select PersonalPageIdentifier__c from Opportunity where id = :care.id];
            
            System.assert(testOpportunity.PersonalPageIdentifier__c == null);
            
            PersonalPages.generateIdentifier(care.id, testContact.id);
            
            testOpportunity = [select PersonalPageIdentifier__c from Opportunity where id = :care.id];
            
            String contactId = (String) contact.id;
            String lastFour = contactId.substring(contactId.length()- 7, contactId.length() - 3);
            String idenf = 'syncmactester' + lastFour;
            System.debug('idenf ' + idenf);
            System.debug('testOpportunity ' + testOpportunity.PersonalPageIdentifier__c);
            
            System.assert(idenf.equals(testOpportunity.PersonalPageIdentifier__c));
            
            
        }
    
    //Tests simple name with special characters/numbers, valid
   @IsTest
        public static void testGenerateIdentifierspecialCharacters(){
            
            Test.startTest();
            Contact contact = new Contact(firstName='Sync568', lastName = 'Mac&%$Tester', email='MACTESTER@Msn.com',  pidm__C = '12356321' );
            contact.recordtypeid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id; 
            
            insert contact;
            
            Account student = [Select id, pidm__C from Account where studentcontact__r.id = :contact.id];
            
            Opportunity care = new Opportunity(AccountId=student.Id, StudentContact__c = contact.id,  Name='Sync MacTester', CloseDate=date.today(), StageName='Intake', RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
            insert care;
            
            
            Test.stopTest();
            
            Contact testContact = [Select id, lastName, FirstName from Contact where id = :contact.id];
            Opportunity testOpportunity = [select PersonalPageIdentifier__c from Opportunity where id = :care.id];
            
            System.assert(testOpportunity.PersonalPageIdentifier__c == null);
            
            PersonalPages.generateIdentifier(care.id, testContact.id);
            
            testOpportunity = [select PersonalPageIdentifier__c from Opportunity where id = :care.id];
            
            String contactId = (String) contact.id;
            String lastFour = contactId.substring(contactId.length()- 7, contactId.length() - 3);
            String idenf = 'syncmactester' + lastFour;
            System.assert(idenf.equals(testOpportunity.PersonalPageIdentifier__c));
            
            
        }
    
    /*
    @IsTest
        public static void incorrectStudent()
    {
        
        Test.startTest();
        
        
        
        
        String jsn = PersonalPages.identifierDataGather('not a real possible url');
        System.debug(jsn);
        
        JsonOutput j = (JsonOutput) JSON.deserialize(jsn ,jsonOutput.class);
        
        
        
        Test.stopTest();
        
        System.assert(j.errorMessage.equals('Student Not Found')); 
        

        
        
        
        
    }
    
    @IsTest
        public static void nullUrl()
    {
        
        
        String json = PersonalPages.identifierDataGather(null);
        System.debug(json);
        System.Assert(json == null );
        
        
        
    }
    
 @IsTest
        public static void goodPathSinglePageLink()
    {
        
        
        CAREProgram__c cProgram = new CAREProgram__c(Name='CTEST1', Active__c=true, ProgramLabel__c='CARE Program Test');
        insert cProgram;
        
        WGUDegreeProgram__c original = new WGUDegreeProgram__c(name='PTEST1', PAMSID__c=1, Active__c=true, CatalogTerm__c='200711', Title__c='PAMS Program Test');
        insert original;
        
        CareProgramMiddleEarth__c middleEarth = new CareProgramMiddleEarth__c(Name=cProgram.ProgramLabel__c, Active__c=true, CAREProgramCode__c=cProgram.Id, BannerProgramCode__c=original.Id);
        insert middleEarth;
        
        
        Contact contact = new Contact(firstName='Sync', lastName = 'MacTester', email='MACTESTER@Msn.com',  pidm__C = '12356321' );
        contact.recordtypeid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id; 
        
        
        insert contact;
        
           StudentAttributes__c studentAttr = new StudentAttributes__c(Affiliation__c = 'WGU');

        insert studentAttr; 
        
        
        
        Account student = [Select id, pidm__C from Account where studentcontact__r.id = :contact.id];
        
        Opportunity care = new Opportunity(AccountId=student.Id, StudentContact__c = contact.id,  
                                           Name='Sync MacTester', CloseDate=date.today(), 
                                           StageName='Intake', StudentAttributes__c = studentAttr.id, 
                                           RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
        care.MarketingProgram__c = middleEarth.id;
        insert care;
        
        PersonalPages.generateIdentifier(care.id, contact.id);

        
        Personal_Pages_Link__c pplink = new Personal_Pages_Link__c(active__c = true,
                                                                   affiliation__c = 'WGU',
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page1.html',
                                                                   Program__c = 'CARE Program Test',
                                                                   sort_order__c = 0);
        insert pplink;
        
        Test.startTest();
        
        String contactid = contact.id;
        String lastFour = contactid.substring(contactid.length()- 7, contactid.length() - 3);
  
        List<Personal_Pages_Link__c> testppl  = [Select id, affiliation__c, active__c,
                                             sort_order__c, image__c, link__c,
                                             Program__c
                                             from Personal_Pages_Link__c
                                             where active__C = true
                                             and affiliation__c = 'WGU'
                                             order by sort_order__c];
    //    System.debug('HERE2' + testppl);
  
        String jsn = PersonalPages.identifierDataGather('http://url.does.not.matter/' + 'syncmactester' + lastFour );
   //     System.debug(jsn);
        
        JsonOutput j = (JsonOutput) JSON.deserialize(jsn ,jsonOutput.class);
        
        Test.stopTest();
    //    system.debug(j);
        
      //  system.debug('JPPL: ' + j.personalPagesLinks);
     //   system.debug('JPPLS: ' + j.personalPagesLinks.size());
        System.assert(j.personalPagesLinks.siZe() == 1);
        System.assert(j.personalPagesLinks.get(0).link__c.equals('http://link.to.me/page1.html'));
        System.assert(j.personalPagesLinks.get(0).affiliation__c.equals('WGU'));
        
        
        
        
    }
    
     @IsTest
    public static void goodPathMultipleLinksOnlyOneForProgram()
    {
        
        
        CAREProgram__c cProgram = new CAREProgram__c(Name='CTEST1', Active__c=true, ProgramLabel__c='CARE Program Test');
        insert cProgram;
        
        WGUDegreeProgram__c original = new WGUDegreeProgram__c(name='PTEST1', PAMSID__c=1, Active__c=true, CatalogTerm__c='200711', Title__c='PAMS Program Test');
        insert original;
        
        CareProgramMiddleEarth__c middleEarth = new CareProgramMiddleEarth__c(Name=cProgram.ProgramLabel__c, Active__c=true, CAREProgramCode__c=cProgram.Id, BannerProgramCode__c=original.Id);
        insert middleEarth;
        
                CAREProgram__c cProgram2 = new CAREProgram__c(Name='CTEST2', Active__c=true, ProgramLabel__c='CARE2 Program Test2');
        insert cProgram2;
        
        WGUDegreeProgram__c original2 = new WGUDegreeProgram__c(name='PTEST2', PAMSID__c=2, Active__c=true, CatalogTerm__c='200711', Title__c='PAMS2 Program Test2');
        insert original2;
        
        CareProgramMiddleEarth__c middleEarth2 = new CareProgramMiddleEarth__c(Name=cProgram2.ProgramLabel__c, Active__c=true, CAREProgramCode__c=cProgram2.Id, BannerProgramCode__c=original2.Id);
        insert middleEarth2;
        
        Contact contact = new Contact(firstName='Sync', lastName = 'MacTester', email='MACTESTER@Msn.com',  pidm__C = '12356321' );
        contact.recordtypeid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id; 
        
        
        insert contact;
        
           StudentAttributes__c studentAttr = new StudentAttributes__c(Affiliation__c = 'WGU');

        insert studentAttr; 
        
        
        
        Account student = [Select id, pidm__C from Account where studentcontact__r.id = :contact.id];
        
        Opportunity care = new Opportunity(AccountId=student.Id, StudentContact__c = contact.id,  
                                           Name='Sync MacTester', CloseDate=date.today(), 
                                           StageName='Intake', StudentAttributes__c = studentAttr.id, 
                                           RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
        care.MarketingProgram__c = middleEarth.id;
        insert care;
        
        PersonalPages.generateIdentifier(care.id, contact.id);

        
        Personal_Pages_Link__c pplink2 = new Personal_Pages_Link__c(active__c = true,
                                                                   affiliation__c = 'WGU',
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page1.html',
                                                                   Program__c = 'CARE Program Test',
                                                                   sort_order__c = 0);
        insert pplink2;
        
        
             Personal_Pages_Link__c pplink = new Personal_Pages_Link__c(active__c = true,
                                                                   affiliation__c = 'WGU',
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://notlink.to.me/page1.html',
                                                                   Program__c = 'Not CARE Program Test',
                                                                   sort_order__c = 0);
                                                                   
        insert pplink;
        
        Test.startTest();
        
        String contactid = contact.id;
        String lastFour = contactid.substring(contactid.length()- 7, contactid.length() - 3);
  
        List<Personal_Pages_Link__c> testppl  = [Select id, affiliation__c, active__c,
                                             sort_order__c, image__c, link__c,
                                             Program__c
                                             from Personal_Pages_Link__c
                                             where active__C = true
                                             and affiliation__c = 'WGU'
                                             order by sort_order__c];
 
  
        String jsn = PersonalPages.identifierDataGather('http://url.does.not.matter/' + 'syncmactester' + lastFour );

        
        JsonOutput j = (JsonOutput) JSON.deserialize(jsn ,jsonOutput.class);
        
        Test.stopTest();

     
        
        System.assert(j.personalPagesLinks.siZe() == 1);
        System.assert(j.personalPagesLinks.get(0).link__c.equals('http://link.to.me/page1.html'));
        System.assert(j.personalPagesLinks.get(0).affiliation__c.equals('WGU'));
        
        
        
        
    }
    
    
    
   

        

                                                                   
   //////////////////////////////////////////////////////////////////////////////////////////////////////////////////                                                                
                                                                   
    @IsTest
    public static void goodPathOneLinkWithMoreThenOneProgram()
    {
        
        
        CAREProgram__c cProgram = new CAREProgram__c(Name='CTEST1', Active__c=true, ProgramLabel__c='CARE Program Test');
        insert cProgram;
        
        WGUDegreeProgram__c original = new WGUDegreeProgram__c(name='PTEST1', PAMSID__c=1, Active__c=true, CatalogTerm__c='200711', Title__c='PAMS Program Test');
        insert original;
        
        CareProgramMiddleEarth__c middleEarth = new CareProgramMiddleEarth__c(Name=cProgram.ProgramLabel__c, Active__c=true, CAREProgramCode__c=cProgram.Id, BannerProgramCode__c=original.Id);
        insert middleEarth;
        
                CAREProgram__c cProgram2 = new CAREProgram__c(Name='CTEST2', Active__c=true, ProgramLabel__c='CARE2 Program Test2');
        insert cProgram2;
        
        WGUDegreeProgram__c original2 = new WGUDegreeProgram__c(name='PTEST2', PAMSID__c=2, Active__c=true, CatalogTerm__c='200711', Title__c='PAMS2 Program Test2');
        insert original2;
        
        CareProgramMiddleEarth__c middleEarth2 = new CareProgramMiddleEarth__c(Name=cProgram2.ProgramLabel__c, Active__c=true, CAREProgramCode__c=cProgram2.Id, BannerProgramCode__c=original2.Id);
        insert middleEarth2;
        
        Contact contact = new Contact(firstName='Sync', lastName = 'MacTester', email='MACTESTER@Msn.com',  pidm__C = '12356321' );
        contact.recordtypeid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id; 
        
        
        insert contact;
        
           StudentAttributes__c studentAttr = new StudentAttributes__c(Affiliation__c = 'WGU');

        insert studentAttr; 
        
        
        
        Account student = [Select id, pidm__C from Account where studentcontact__r.id = :contact.id];
        
        Opportunity care = new Opportunity(AccountId=student.Id, StudentContact__c = contact.id,  
                                           Name='Sync MacTester', CloseDate=date.today(), 
                                           StageName='Intake', StudentAttributes__c = studentAttr.id, 
                                           RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
        care.MarketingProgram__c = middleEarth.id;
        insert care;
        
        PersonalPages.generateIdentifier(care.id, contact.id);
    
            Personal_Pages_Link__c pplink2 = new Personal_Pages_Link__c(active__c = true,
                                                                   affiliation__c = 'WGU',
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page1.html',
                                                                   Program__c = 'CARE Program Test; Not CARE Program Test',
                                                                   sort_order__c = 0);
        insert pplink2;
        
        

        
        
 
        
        Test.startTest();
        
        String contactid = contact.id;
        String lastFour = contactid.substring(contactid.length()- 7, contactid.length() - 3);
  
        List<Personal_Pages_Link__c> testppl  = [Select id, affiliation__c, active__c,
                                             sort_order__c, image__c, link__c,
                                             Program__c
                                             from Personal_Pages_Link__c
                                             where active__C = true
                                             and affiliation__c = 'WGU'
                                             order by sort_order__c];
 
  
        String jsn = PersonalPages.identifierDataGather('http://url.does.not.matter/' + 'syncmactester' + lastFour );
        System.debug(jsn);
        
        JsonOutput j = (JsonOutput) JSON.deserialize(jsn ,jsonOutput.class);
        
        Test.stopTest();
       

     
        
        System.assert(j.personalPagesLinks.siZe() == 1);
        System.assert(j.personalPagesLinks.get(0).link__c.equals('http://link.to.me/page1.html'));
        System.assert(j.personalPagesLinks.get(0).affiliation__c.equals('WGU'));
        
        
        
        
    }
    
     public static void goodPathMutipleLinskWithMoreThenOneProgram()
    {
        
        
        CAREProgram__c cProgram = new CAREProgram__c(Name='CTEST1', Active__c=true, ProgramLabel__c='CARE Program Test');
        insert cProgram;
        
        WGUDegreeProgram__c original = new WGUDegreeProgram__c(name='PTEST1', PAMSID__c=1, Active__c=true, CatalogTerm__c='200711', Title__c='PAMS Program Test');
        insert original;
        
        CareProgramMiddleEarth__c middleEarth = new CareProgramMiddleEarth__c(Name=cProgram.ProgramLabel__c, Active__c=true, CAREProgramCode__c=cProgram.Id, BannerProgramCode__c=original.Id);
        insert middleEarth;
        
        CAREProgram__c cProgram2 = new CAREProgram__c(Name='CTEST2', Active__c=true, ProgramLabel__c='CARE2 Program Test2');
        insert cProgram2;
        
        WGUDegreeProgram__c original2 = new WGUDegreeProgram__c(name='PTEST2', PAMSID__c=2, Active__c=true, CatalogTerm__c='200711', Title__c='PAMS2 Program Test2');
        insert original2;
        
        CareProgramMiddleEarth__c middleEarth2 = new CareProgramMiddleEarth__c(Name=cProgram2.ProgramLabel__c, Active__c=true, CAREProgramCode__c=cProgram2.Id, BannerProgramCode__c=original2.Id);
        insert middleEarth2;
        
        Contact contact = new Contact(firstName='Sync', lastName = 'MacTester', email='MACTESTER@Msn.com',  pidm__C = '12356321' );
        contact.recordtypeid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id; 
        
        
        insert contact;
        
           StudentAttributes__c studentAttr = new StudentAttributes__c(Affiliation__c = 'WGU');

        insert studentAttr; 
        
        
        
        Account student = [Select id, pidm__C from Account where studentcontact__r.id = :contact.id];
        
        Opportunity care = new Opportunity(AccountId=student.Id, StudentContact__c = contact.id,  
                                           Name='Sync MacTester', CloseDate=date.today(), 
                                           StageName='Intake', StudentAttributes__c = studentAttr.id, 
                                           RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
        care.MarketingProgram__c = middleEarth.id;
        insert care;
        
        PersonalPages.generateIdentifier(care.id, contact.id);
       
       
               Personal_Pages_Link__c pplink2 = new Personal_Pages_Link__c(active__c = true,
                                                                   affiliation__c = 'WGU',
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page1.html',
                                                                   Program__c = 'CARE Program Test',
                                                                   sort_order__c = 0);
        insert pplink2;
        
        
             Personal_Pages_Link__c pplink = new Personal_Pages_Link__c(active__c = true,
                                                                   affiliation__c = 'WGU',
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://notlink.to.me/page1.html',
                                                                   Program__c = 'CARE Program Test;Not CARE Program Test',
                                                                   sort_order__c = 0);
                                                                   
        insert pplink;
        
        
        
 
        
        Test.startTest();
        
        String contactid = contact.id;
        String lastFour = contactid.substring(contactid.length()- 7, contactid.length() - 3);
  
        List<Personal_Pages_Link__c> testppl  = [Select id, affiliation__c, active__c,
                                             sort_order__c, image__c, link__c,
                                             Program__c
                                             from Personal_Pages_Link__c
                                             where active__C = true
                                             and affiliation__c = 'WGU'
                                             order by sort_order__c];

  
        String jsn = PersonalPages.identifierDataGather('http://url.does.not.matter/' + 'syncmactester' + lastFour );
        System.debug(jsn);
        
        JsonOutput j = (JsonOutput) JSON.deserialize(jsn ,jsonOutput.class);
        
        Test.stopTest();

     
        
        System.assert(j.personalPagesLinks.siZe() == 2);
        System.assert(j.personalPagesLinks.get(0).link__c.equals('http://link.to.me/page1.html'));
        System.assert(j.personalPagesLinks.get(1).link__c.equals('http://notlink.to.me/page1.html'));
        System.assert(j.personalPagesLinks.get(0).affiliation__c.equals('WGU'));
        
        
        
        
        
    }
    
*/
    
    
}