src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to the actual Contact record for dereferencing the complete set of Contact fields in formulas and validations</description>
        <inlineHelpText>The student contact field is set automatically when the account record is created or updated</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Contact</relationshipLabel>
        <relationshipName>StudentContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ProspectRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Prospects</description>
        <label>ProspectRecord</label>
    </recordTypes>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/CareerServices__c.object
<CustomObject>
    <description>This object allows the Career Services team to track all appointment sessions completed for students related to career services..</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Career Services</relationshipLabel>
        <relationshipName>Student</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Career Services</label>
    <nameField>
        <displayFormat>CS# {00}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Career Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>ProspectRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Prospects</description>
        <label>ProspectRecord</label>
    </recordTypes>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/FieldExperience__c.object
<CustomObject>
    <description>This object represents the field experiences application. Students have access to the this object in the customer portal. There are multiple record types including PCE/DT, BSHI, MSSP, etc.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When a student beings a second field experience, such as in needing to reapply for DT when PCE is complete, there can be multiple FE objects per student. This field identifies the active object. Upon a new application, the current active object is archived for historical review and reason fields used to document the change.</description>
        <inlineHelpText>Check to set this Field Experience as the active application/process</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experiences</relationshipLabel>
        <relationshipName>FieldExperiences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentProcess__c.object
<CustomObject>
    <description>Custom object to manage student processes by record type.</description>
    <fields>
        <fullName>FieldExperience__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Field Experience</label>
        <referenceTo>FieldExperience__c</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>StudentProcesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the student process.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated/Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Response Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Response Needed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentPIDM__c</fullName>
        <formula>Student__r.PIDM__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student PIDM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup field to the contact of the student process object.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>StudentProcesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Process</label>
    <nameField>
        <label>Student Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WithdrawalToBanner__c.object
<CustomObject>
    <description>Control object for pushing student drops to Oracle/Banner</description>
    <fields>
        <fullName>ActionNeeded__c</fullName>
        <label>Action Needed</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RefId__c</fullName>
        <externalId>true</externalId>
        <label>Ref Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentPIDM__c</fullName>
        <label>Student PIDM</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentProcess__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Process</label>
        <referenceTo>StudentProcess__c</referenceTo>
        <relationshipLabel>Withdrawals To Banner</relationshipLabel>
        <relationshipName>WithdrawalsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Withdrawal To Banner</label>
    <nameField>
        <displayFormat>W2B-{0000000}</displayFormat>
        <label>Withdraw To Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Withdrawals To Banner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StudentProcessUtility.cls
/***************************************************************************************************
* Name: StudentProcessUtility
* Author: Will Slade
* Purpose: Utility Class for Student Process Object - multiple functions
* Revisions: 
*    5-31-2013 - Created Class
*    7-09-2013 - Modified class to avoid multiple/duplicate calls spawned by workflows - Will Slade
*
****************************************************************************************************/

public with sharing class StudentProcessUtility 
{    
    public static boolean firstRun = true;
       
    ///////////////////// Begin Create Withdrawals to Banner /////////////////////
    public static void createWithdrawalsToBanner(String wdListJSON)
    {       
        if (Limits.getFutureCalls() > 8 || System.isFuture() || System.isBatch() || System.isScheduled() )
        {
            processCreateWithdrawalsToBanner(wdListJSON);
        }
        else
        {
            asyncCreateWithdrawalsToBanner(wdListJSON);
        }
    }
    
    @future
    public static void asyncCreateWithdrawalsToBanner(String wdListJSON)
    {
        processCreateWithdrawalsToBanner(wdListJSON);
    }    

    public static void processCreateWithdrawalsToBanner(String wdListJSON)
    {     
        List<StudentProcess__c> wdList = (List<StudentProcess__c>) JSON.deserialize(wdListJSON, List<StudentProcess__c>.class);   
        List<WithdrawalToBanner__c> wdToBanInsertList = new List<WithdrawalToBanner__c>();
        Map<Id, Id> wdToCtrlMap = new Map<Id, Id>();
        
        //Loop through the list of Withdrawals and populate the keyset of the map with the record ids
        for (StudentProcess__c wd : wdList)
        {
            wdToCtrlMap.put(wd.Id, null);
        }
        
        Set<Id> wdIdSet = wdToCtrlMap.keySet();
        
        wdList = [SELECT Id, StudentPidm__c, Student__r.Pidm__c
                  FROM StudentProcess__c
                  WHERE Id IN :wdIdSet];
        
        List<WithdrawalToBanner__c> wdToBanUpdateList = [SELECT Id, RefId__c, ActionNeeded__c, StudentProcess__c, StudentProcess__r.Student__r.Pidm__c
                                                         FROM WithdrawalToBanner__c
                                                         WHERE StudentProcess__c IN :wdIdSet];
        
        //2nd pass through map - update values with existing control object ids and mark them as Update needed                                         
        for (WithdrawalToBanner__c wdToBan : wdToBanUpdateList)
        {
            wdToCtrlMap.put(wdToBan.StudentProcess__c, wdToBan.Id);            
            wdToBan.actionNeeded__c = wdToBan.actionNeeded__c == 'Insert' ? 'Insert' : 'Update';
            wdToBan.StudentPidm__c = wdToBan.StudentProcess__r.Student__r.Pidm__c;
        }                                          
        
        for (StudentProcess__c wd : wdList)
        {
            if (wdToCtrlMap.get(wd.Id) == null)
            {
                System.debug('=======> size ' + wdList.size() + wd.Id);
                wdToBanInsertList.add(new WithdrawalToBanner__c(StudentProcess__c = wd.Id,
                                                                RefId__c = String.valueOf(wd.Id),
                                                                ActionNeeded__c = 'Insert',
                                                                StudentPidm__c = wd.Student__r.Pidm__c));
            }
        }
        
        update wdToBanUpdateList;
        insert wdToBanInsertList;
    }
    ////////////////////// End Create Withdrawals to Banner //////////////////////
  
    Set<Id> feContacts = new Set<Id>();  
    public static void createMissingStudentUsers(String contactIdsJSON ) 
    {
        if ( Limits.getFutureCalls() > 8 || System.isFuture() || System.isBatch() || System.isScheduled() ) 
        {
            processCreateMissingStudentUsers(contactIdsJSON);
        }         
        else 
        {
            asyncCreateMissingStudentUsers(contactIdsJSON);
        }
    } 
     
    @future
    private static void asyncCreateMissingStudentUsers(String contactIdsJSON ) 
    {
        processCreateMissingStudentUsers(contactIdsJSON);
    }
     
    private static void processCreateMissingStudentUsers(String contactIdsJSON ) 
    {           
        Set<Id> contactIds = (Set<Id>)JSON.deserialize(contactIdsJSON, Set<Id>.class);
        
        Map<Id,String> statusResetMap = new Map<Id,String>();
        List<Contact> contactsForUpdate = new List<Contact>();
        
        for ( Contact thisContact : [SELECT Id, Status__c FROM Contact c WHERE PIDM__c != null AND AccountId != null AND Account.isCustomerPortal = false 
                                     AND Account.StudentContact__c != null AND RecordType.DeveloperName IN ('ProspectRecord','StudentRecord') AND Id in :contactIds] ) 
        { 
            if ( thisContact.Status__c != 'AS' && thisContact.Status__c != 'TB' ) 
            {
                statusResetMap.put( thisContact.Id, thisContact.Status__c );
            }
            
            contactsForUpdate.add( new Contact( Id = thisContact.Id, Status__c = (( thisContact.Status__c != 'AS' && thisContact.Status__c != 'TB' ) ? 'AS' : thisContact.Status__c ))); 
        }
        
        if ( !contactsForUpdate.isEmpty() ) 
        {
            update contactsForUpdate;
            
            for (Contact thisContact : contactsForUpdate)
            {
                if (statusResetMap.containsKey(thisContact.Id))
                {
                    thisContact.Status__c = statusResetMap.get(thisContact.Id);
                }
            }           
            update contactsForUpdate;
        }
    }
    
    
    // get the active FE record  for the student and populate in Student Process
    
     public static void populateFEonSdtProcess(String stdprocListJSON){
        if ( Limits.getFutureCalls() > 8 || System.isFuture() || System.isBatch() || System.isScheduled() ) {
            processpopulateFEonSdtProcess(stdprocListJSON);
        }else{
            asyncpopulateFEonSdtProcess(stdprocListJSON);
        }
     } 
     
     @future
     private static void asyncpopulateFEonSdtProcess(String stdprocListJSON){
        processpopulateFEonSdtProcess(stdprocListJSON);
     }
     
     private static void processpopulateFEonSdtProcess(String stdprocListJSON){  
         List<StudentProcess__c> TriggerNew = (List<StudentProcess__c>)JSON.deserialize(stdprocListJSON, List<StudentProcess__c>.class );         
         //Map<String,String> StdprocessMap = new Map<String,String>();
         List<StudentProcess__c> updateList = new List<StudentProcess__c>();
         Set<Id> studentSet = new Set<Id>();
         for(StudentProcess__c stdprocess : TriggerNew){
             if(stdprocess.Student__c != null){
                 //StdprocessMap.put(stdprocess.Id,stdprocess.Student__c);    
                 studentSet.add(stdprocess.Student__c);
             }
         }
         
         Map<String,String> stdFeMap = new Map<String,String>();
         for(FieldExperience__c fe : [Select Id,Student__c from FieldExperience__c  Where Student__c in : studentSet and Active__c = true]){
                 stdFeMap.put(fe.Student__c,fe.Id);
         }       
         for(StudentProcess__c  stdproc :TriggerNew){
             if(stdFeMap != null && stdproc.Student__c!=null && stdFeMap.get(stdproc.Student__c)!=null){
               stdproc.FieldExperience__c = stdFeMap.get(stdproc.Student__c);   
               updateList.add(stdproc);
             }
         
         
         }
         
         if(updateList!= null && updateList.size() > 0)
         {
             Update updateList;
         }
        
     }
}