src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>WGUPlacesStudents__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean value that determines if WGU should place students for Practical Clinical Experience (PCE) for all schools in this district.</description>
        <inlineHelpText>Should WGU place PCE students for all schools in this district (vs. self serve)?</inlineHelpText>
        <label>WGU Places Students</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/FieldExperience__c.object
<CustomObject>
    <description>This object represents the field experiences application. Students have access to the this object in the customer portal. There are multiple record types including PCE/DT, BSHI, MSSP, etc.</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experiences</relationshipLabel>
        <relationshipName>FieldExperiences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieldExperienceProcess__c.object
<CustomObject>
    <description>The object that represents field experience-related processes such as placements, observations, appeals, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Field Experience Processes (District)</relationshipLabel>
        <relationshipName>Districts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldExperience__c</fullName>
        <label>Field Experience</label>
        <referenceTo>FieldExperience__c</referenceTo>
        <relationshipLabel>Field Experience Processes</relationshipLabel>
        <relationshipName>FieldExperiencesProcesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Field Experience Processes (School)</relationshipLabel>
        <relationshipName>Schools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experience Processes</relationshipLabel>
        <relationshipName>Field_Experience_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Experience Process</label>
    <nameField>
        <label>Field Experiences Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experience Processes</pluralLabel>
    <recordTypes>
        <fullName>PlacementAttempt</fullName>
        <active>true</active>
        <label>Placement Attempt</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FieldExperienceProcessUtility.cls
/*
 * Author Raavi
 * Western Governors University
 *
 * Date February 11, 2013 @ 1322 hrs
 * Revised: PersonAccount Refactor, try/catch correction for future calls - Paul Coleman 
 *
 * Utility class to support static and @future method calls from FieldExperienceProcess__c object's Trigger class
 *
 * DECLARED WITHOUT SHARING TO ENSURE PROPER RECORD SYNCRHONIZATION
 *
 */
 public without sharing class FieldExperienceProcessUtility {
 
 
/////////////////////////////////////////// START CREATE CASE ///////////////////////////////////////////////// 
    public static void createWGUPlacesStudentCase(String TriggerNewJSON) {
        if ( Limits.getFutureCalls() > 8 || System.isFuture() || System.isBatch() || System.isScheduled() ) {
          processCreateWGUPlacesStudentCase( TriggerNewJSON );
       } else {
          asyncCreateWGUPlacesStudentCase( TriggerNewJSON );
       }
    }
    
    @future
    private static void asyncCreateWGUPlacesStudentCase(String TriggerNewJSON) {
         processCreateWGUPlacesStudentCase(TriggerNewJSON);
    }
    
    private static void processCreateWGUPlacesStudentCase(String TriggerNewJSON) {
        
      List<FieldExperienceProcess__c> TriggerNew = (List<FieldExperienceProcess__c>)JSON.deserialize(TriggerNewJSON, List<FieldExperienceProcess__c>.class );
      List<Case> casesForInsert = new List<Case>();
        Id QueueId = [SELECT QueueId FROM QueueSobject WHERE sobjecttype ='Case' AND Queue.DeveloperName='FELogisticsQueue' LIMIT 1].QueueId;
        Id RecordTypeId = [SELECT Id FROM RecordType WHERE sobjecttype ='Case' AND DeveloperName='FieldPlacement' LIMIT 1].Id;
        system.debug('raavi==============' +RecordTypeId);
        System.debug( LoggingLevel.DEBUG, 'TriggerNew ARRAY in createWGUPlacesStudentCase: ' + JSON.serialize(TriggerNew));
        
            for(FieldExperienceProcess__c fep : [Select Id,Student__c,FieldExperience__r.Student__c,District__r.Name,School__r.Name,District__r.WGUPlacesStudents__c,School__r.WGUPlacesStudents__c from FieldExperienceProcess__c WHERE Id in :TriggerNew AND RecordType.DeveloperName = 'PlacementAttempt'] ) {

                    if( (fep.Student__c != null || (fep.FieldExperience__c != null && fep.FieldExperience__r.Student__c != null)) && ((fep.District__c != null && fep.District__r.WGUPlacesStudents__c==true) || (fep.School__c != null && fep.School__r.WGUPlacesStudents__c ==true)) ) {
                        casesForInsert.add( new Case(Status='New',Priority ='High',Origin='Web',Subject='WGU Places Student',OwnerId=QueueId,RecordTypeId =RecordTypeId, contactId=(fep.Student__c!=null? fep.Student__c : fep.FieldExperience__r.Student__c),Description=((fep.District__c != null && fep.District__r.WGUPlacesStudents__c==true)? fep.District__r.Name : fep.School__r.Name)) );
                    }

            }
        if ( !casesForInsert.isEmpty() ) { 
            insert casesForInsert;
        System.debug( LoggingLevel.DEBUG, 'casesForInsert ARRAY in createWGUPlacesStudentCase: ' + JSON.serialize(casesForInsert));
        }
    }
/////////////////////////////////////////// END CREATE CASE ///////////////////////////////////////////////// 

   
}