src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/States__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>State Attributes</description>
    <fields>
        <fullName>DefaultTimeZoneKey__c</fullName>
        <description>Default TimeZone Key value for use in User.TimeZoneSidKey field values.</description>
        <label>Default Time Zone Key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>States</label>
</CustomObject>

src/objects/TimeZoneByZip__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Zip Code to TimeZone Lookup</description>
    <fields>
        <fullName>TimeZoneKey__c</fullName>
        <description>Time Zone code from IANA time zone database, used by Salesforce for TimeZoneSidKey on the User record</description>
        <label>TimeZoneKey</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TimeZoneByZip</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IsEmployee__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this user is an employee please check this</description>
        <inlineHelpText>Checked if this user is an employee</inlineHelpText>
        <label>IsEmployee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NewUserName__c</fullName>
        <description>Temporary field for holding anew Username value while Email notification is disabled.</description>
        <label>NewUserName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WGUPostalCode__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUState__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/UserAttributes__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>CollegeTeam__c</fullName>
        <label>College Team</label>
        <picklist>
            <picklistValues>
                <fullName>Admissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Enrollment Counselor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Undergrad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Professions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HP Prelicensure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teachers College El Ed/SoSci</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teachers College Math/Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teachers College MEd</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserAttributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Attributes</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserAttributes</pluralLabel>
    <recordTypes>
        <fullName>EnrollmentTeam</fullName>
        <active>true</active>
        <description>Attributes as they pertain to the enrollment team</description>
        <label>Enrollment Team</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UserUtility.cls
/*
 * Author Paul Coleman
 * Western Governors University
 *
 * Date Feb 20, 2013 @ 1500 hrs
 * Revised: Added recoverFromUsernameChange block - Paul Coleman 
 *
 * Revised Dec 17 2012 @ 1709 hrs
 * Revised: added After Insert logic for creating UserAttributes__c object for enrollment process users - Paul Coleman 
 * 
 * Date October 30, 2012 @ 1130 hrs
 * Revised: (security audit compliance: with sharing) - Paul Coleman 
 *
 * User object's Utility methods
 *
 */
public with sharing class UserUtility {
  
    //User: before Insert (do not use before or after 'Update' for timezone updates, because the User needs to be able to override the timezone setting based on current location [for scheduling])
    public static void UserTimeZoneSetTrigger( List<User> TriggerNew ) {
        ID studentProfileID = [select id from Profile where Name = 'Student Profile' LIMIT 1].id;
        ID WGUChatterProfileID = [select id from Profile where Name = 'WGU Chatter Only'].id;

        for (User thisUser: TriggerNew ) {
            
          String pidm = thisUser.pidm__c;
          String communityName = Test.isRunningTest()? 't'+String.ValueOf(Crypto.getRandomLong()) : pidm; //generate a unique value if testing
          String[] emailParts = thisUser.Email.split('@');
          String federatedId = Test.isRunningTest()? emailParts[0]+'@wgu.edu'+'.'+communityName: emailParts[0]+'@wgu.edu'; //generate a unique value if testing
            
            thisUser.Alias = thisUser.Alias == null? pidm: thisUser.Alias;
            thisUser.CommunityNickname = thisUser.CommunityNickname == null? communityName: thisUser.CommunityNickname;
            thisUser.FederationIdentifier = thisUser.FederationIdentifier == null? federatedId: thisUser.FederationIdentifier;  
            thisUser.IsEmployee__c = ( thisUser.ProfileID != studentProfileID );
            
          //ensure that any new Employee User records become Standard Licenses, and have the default profile of Chatter Only
            thisUser.ProfileId = ( thisUser.ProfileId == null && thisUser.IsEmployee__c == true )? WGUChatterProfileID: thisUser.ProfileID; 
            
            //ensure that any new Student User records become Customer Portal Licenses, and have the default profile of Student Profile
          thisUser.ProfileId = ( thisUser.IsEmployee__c == false )? studentProfileID: thisUser.ProfileID;

          if ( thisUser.ProfileId != studentProfileID ) {  //student timezones are processed in the Account trigger
             //try timezone lookup by zipcode first (private address zip first, then profile zipcode)
             String zipcode = ( thisUser.WGUPostalCode__c==null? thisUser.PostalCode: thisUser.WGUPostalCode__c );
                    zipcode = ( zipcode!=null && zipcode!='-' ? ( zipcode.contains('-')? zipcode.split('-')[0]: zipcode ) : (zipcode=='-'? null: zipcode));
             System.debug( LoggingLevel.DEBUG, 'ZIPCODE: '+ zipcode );
             String timeZoneValue = ( zipcode != null && TimeZoneByZip__c.getValues(zipcode) != null )? TimeZoneByZip__c.getValues(zipcode).TimeZoneKey__c : null;
                    timeZoneValue =   timeZoneValue==null? ( ( thisUser.WGUState__c != null && States__c.getValues(thisUser.WGUState__c) != null )? States__c.getValues(thisUser.WGUState__c).DefaultTimeZoneKey__c: null ): timeZoneValue;
                    timeZoneValue =   timeZoneValue==null? ( ( thisUser.State != null && States__c.getValues(thisUser.State) != null )? States__c.getValues(thisUser.State).DefaultTimeZoneKey__c: 'America/Denver' ): timeZoneValue;
             
             //TimeZoneSidKey is a required field on User and need only be set when a record is first created, hence before insert
             thisUser.TimeZoneSidKey = timeZoneValue;
          }

        }
    }
  
  
  
/////////////////////////// START SECTION: CREATE User Attributes for enrollment personnel ///////////////////////////////////
     public static void createEnrollmentAttributes( String ListTriggerNewJSON, String MapEnrollmentRolesJSON  ) {
       if ( Limits.getFutureCalls() > 8 || System.isFuture() || System.isBatch() || System.isScheduled() ) {
          processCreateEnrollmentAttributes(ListTriggerNewJSON, MapEnrollmentRolesJSON);
       } else {
          asyncCreateEnrollmentAttributes(ListTriggerNewJSON, MapEnrollmentRolesJSON);
       }
     }
     
     @future
     private static void asyncCreateEnrollmentAttributes( String ListTriggerNewJSON, String MapEnrollmentRolesJSON ) {
          processCreateEnrollmentAttributes(ListTriggerNewJSON, MapEnrollmentRolesJSON);
     }
     
     //User: after Update, Create new User Attribute record  
     private static void processCreateEnrollmentAttributes( String ListTriggerNewJSON, String MapEnrollmentRolesJSON ) {
        
          Id targetRecordTypeId = [select id from RecordType where sObjectType = 'UserAttributes__c' AND DeveloperName = 'EnrollmentTeam' LIMIT 1].Id;
          List<User> TriggerNew = (List<User>)JSON.deserialize( ListTriggerNewJSON, List<User>.class );
          Map<Id,UserRole> EnrollmentRolesMap = (Map<Id,UserRole>)JSON.deserialize( MapEnrollmentRolesJSON, Map<Id,UserRole>.class );
          List<UserAttributes__c> userAttributesForInsert = new List<UserAttributes__c>();
          Map<Id,UserAttributes__c> userAttributesMap = new Map<Id,UserAttributes__c>();
          for (UserAttributes__c thisAttrib: [select id,User__c from userAttributes__c where User__c in :TriggerNew] ) {
             if ( !userAttributesMap.containsKey(thisAttrib.User__c) ) {
                  userAttributesMap.put( thisAttrib.User__c, thisAttrib);
             }
          }
           
          for( User thisUser: TriggerNew ) {
                if ( !userAttributesMap.containsKey(thisUser.Id) && EnrollmentRolesMap.containsKey( thisUser.UserRoleId ) ) {
                    UserRole thisUserRole = EnrollmentRolesMap.get(thisUser.UserRoleId); 
                    userAttributesForInsert.add( new UserAttributes__c(Name=thisUser.FirstName+' '+thisUser.LastName+' Attributes', User__c=thisUser.Id, CollegeTeam__c=thisUserRole.Name, RecordTypeId=targetRecordTypeId) );
                }
          }
          
          if ( !userAttributesForInsert.isEmpty() ) {
            insert userAttributesForInsert;
          }
              
      } //END FUNCTION : private static void processCreateEnrollmentAttributes
        
/////////////////////////// END SECTION: CREATE User Attributes for enrollment personnel ///////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
        
 
//////////////////////////////////// START SECTION: recover from Username change /////////////////////////////////////////////// 
     //User: AFTER UPDATE, recover from Username change by removing notify_bogify from the front of the Email address 
     public static void recoverFromUsernameChange( String ListTriggerNewJSON ) {
       if ( Limits.getFutureCalls() > 8 || System.isFuture() || System.isBatch() || System.isScheduled() ) {
          processRecoverFromUsernameChange(ListTriggerNewJSON);
       } else {
          asyncRecoverFromUsernameChange(ListTriggerNewJSON); 
       }
     }
     
     @future
     private static void asyncRecoverFromUsernameChange( String ListTriggerNewJSON ) {
          processRecoverFromUsernameChange(ListTriggerNewJSON);
     }
     
     //User: AFTER UPDATE, recover from Username change by removing notify_bogify from the front of the Email address   
     private static void processRecoverFromUsernameChange( String ListTriggerNewJSON ) {
        
              List<User> triggerNew = (List<User>)JSON.deserialize( ListTriggerNewJSON, List<User>.class );
              List<User> usersForUpdateList = new List<User>();
               
                for( User thisUser: triggerNew ) {
                    if ( thisUser.Email.startsWith('notify_bogify.') && thisUser.NewUserName__c != null ) {
                        String[] emailParts = thisUser.Email.split('notify_bogify\\.');
                        String emailStr = emailParts[1]; 
                        usersForUpdateList.add( new User(Id=thisUser.Id,Email=emailStr,Username=thisUser.NewUserName__c) );
                    }
                }
              
              if ( !usersForUpdateList.isEmpty() ) {
                update usersForUpdateList;
              }
              
        } //END FUNCTION : private static void processRecoverFromUsernameChange
        
//////////////////////////////////// END CREATE User Attributes for enrollment personnel /////////////////////////////// 
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
        
  
}