src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to the actual Contact record for dereferencing the complete set of Contact fields in formulas and validations</description>
        <inlineHelpText>The student contact field is set automatically when the account record is created or updated</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Contact</relationshipLabel>
        <relationshipName>StudentContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ProspectRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Prospects</description>
        <label>ProspectRecord</label>
    </recordTypes>
</CustomObject>

src/objects/CareProgramMiddleEarth__c.object
<CustomObject>
    <description>Used to bring together the CARE Program code and the PAMS program code together.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BannerProgramCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banner Program Code</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>CARE Programs Middle Earth</relationshipLabel>
        <relationshipName>CAREProgramsMiddleEarth</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InquiryProgram__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this program on the Inquiry form?</inlineHelpText>
        <label>Inquiry Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProgramGroups__c</fullName>
        <label>Program Groups</label>
        <picklist>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education (initial teaching licensure programs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education (programs for current teachers and others)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CARE Program Middle Earth</label>
    <nameField>
        <label>Program Middle Earth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs Middle Earth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for wguProgram</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ProspectRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Prospects</description>
        <label>ProspectRecord</label>
    </recordTypes>
</CustomObject>

src/objects/ExternalLeadContactControl__c.object
<CustomObject>
    <description>This object will control the integration with LeadQual and allow the modification of parameters for 
the assignment of pre-leads to external vendor 
ExternalLeadContactControl</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this external vendor active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MonthlyLimit__c</fullName>
        <description>Max number of lead that should be send to the external vendor in a 24 hour period</description>
        <label>Monthly Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PercentOfLeadsToAssignPicklist__c</fullName>
        <label>Percent Of Leads To Assign</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartHour__c</fullName>
        <description>The hour (24) when the leads should be start to be sent to the external vendor</description>
        <inlineHelpText>The hour (24) when the leads should be start to be sent to the external vendor</inlineHelpText>
        <label>Start Hour</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StopHour__c</fullName>
        <description>The hour (24) at which the leads should stop being send to the external vendor</description>
        <inlineHelpText>The hour (24) at which the leads should stop being send to the external vendor</inlineHelpText>
        <label>Stop Hour</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>External Lead Contact Control</label>
    <nameField>
        <label>ExternalLeadContactControl Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Lead Contact Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ExternalLeadContactControl__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Lead Contact Control</label>
        <referenceTo>ExternalLeadContactControl__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastCallDisposition__c</fullName>
        <label>Last Call Disposition</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadGrade__c</fullName>
        <description>The grade that was given from the inquiry</description>
        <label>Lead Grade</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Program</label>
        <referenceTo>CareProgramMiddleEarth__c</referenceTo>
        <relationshipLabel>CAREProfile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>StudentContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CARE Profile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>IntakeInterviewReady</fullName>
        <active>true</active>
        <businessProcess>Intake</businessProcess>
        <label>IntakeInterviewReady</label>
    </recordTypes>
</CustomObject>

src/objects/Runtime__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Store sandbox related values for runtime context</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Runtime</label>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Degree Program is active and can be used.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PAMSID__c</fullName>
        <description>The ID that represents the program in PAMS.</description>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCAREforceUtilityExternalLeads.cls
@isTest
public class TestCAREforceUtilityExternalLeads {

 
    @IsTest
    public static void testAssignLeadToVendors() {
    
        ExternalLeadContactControl__c wguELCC= new ExternalLeadContactControl__c();
        wguELCC.Name= 'WGU';
        wguELCC.Active__C = true;
        wguELCC.MonthlyLimit__c = 1000;
        wguELCC.StartHour__c = 0;
        wguELCC.StopHour__c = 24;
        
        insert wguELCC;
    
    
        Contact contact = new Contact(firstName='Sync', lastName = 'MacTester', email='MACTESTER@Msn.com',  pidm__C = '12356321' );
        contact.recordtypeid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id; 
    
        insert contact;
       
        Account student = [Select id, pidm__C from Account where studentcontact__r.id = :contact.id];

        Opportunity care = new Opportunity(AccountId=student.Id, StudentContact__c = contact.id,  Name='Sync MacTester', CloseDate=date.today(), StageName='Intake', RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
        insert care;   
        
        
        CAREforceUtility.assignLeadToVendor(care, wguELCC);
 

        System.assert(care.ExternalLeadContactControl__c == wguELCC.id );   

    } 

    @IsTest
    public static void testCreateExternalLeadsAllWGU (){

        ExternalLeadContactControl__c wguELCC= new ExternalLeadContactControl__c();
        wguELCC.Name= 'WGU';
        wguELCC.Active__C = true;
        wguELCC.MonthlyLimit__c = 1000;
        wguELCC.StartHour__c = 0;
        wguELCC.StopHour__c = 24;
        wguELCC.PercentOfLeadsToAssignPicklist__c = '50';
        
        insert wguELCC;
   

        Contact contact2 = new Contact(firstName='Jinky', lastName = 'OTester', email='JinkyOTester@yahoo.com',  pidm__C = '123321' );
        contact2.recordtypeid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id; 
    
        insert contact2;
       
        Account student2 = [Select id, pidm__C from Account where studentcontact__r.id = :contact2.id];

        Opportunity care2 = new Opportunity(AccountId=student2.Id, StudentContact__c = contact2.id,  Name='Jinky OTester', CloseDate=date.today(), StageName='Intake', RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
        care2.LeadGrade__c = 'B';
        insert care2;   
        
             
        CAREforceUtility.createExternalLeads(care2);

        /////////////////////////////////////////////////////////////////
        //                 Test Only WGU Exists                        //
        /////////////////////////////////////////////////////////////////
        ExternalLeadContactControl__c exc = [SELECT Id, Name FROM ExternalLeadContactControl__c WHERE Name = 'WGU'];
        Opportunity otest2 = [SELECT Id, Name, ExternalLeadContactControl__c , ExternalLeadContactControl__r.id, ExternalLeadContactControl__r.name  FROM Opportunity where id = :care2.id];
        System.assert(otest2.ExternalLeadContactControl__r.id == exc.id );  
        
            
        
        
        ExternalLeadContactControl__c notwguELCC= new ExternalLeadContactControl__c();
        notwguELCC.Name= 'NotWGU';
        notwguELCC.Active__C = false;
        notwguELCC.MonthlyLimit__c = 1000;
        notwguELCC.StartHour__c = 0;
        notwguELCC.StopHour__c = 24;
        
        notwguELCC.PercentOfLeadsToAssignPicklist__c = '50';
    
        insert notwguELCC;
            
        
        Contact contact = new Contact(firstName='Sync', lastName = 'MacTester', email='MACTESTER@Msn.com',  pidm__C = '12356321' );
        contact.recordtypeid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id; 
    
        insert contact;
       
        Account student = [Select id, pidm__C from Account where studentcontact__r.id = :contact.id];

        Opportunity care = new Opportunity(AccountId=student.Id, StudentContact__c = contact.id,  Name='Sync MacTester', CloseDate=date.today(), StageName='Intake', RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
        care.LeadGrade__c = 'B';
        insert care;  
        
            
        CAREforceUtility.createExternalLeads(care);

        
        /////////////////////////////////////////////////////////////////
        //                 Test Only WGU Active//
        /////////////////////////////////////////////////////////////////
 
        Opportunity otest = [SELECT Id, Name, ExternalLeadContactControl__c , ExternalLeadContactControl__r.id, ExternalLeadContactControl__r.name  FROM Opportunity where id = :care.id];

        System.assert(otest.ExternalLeadContactControl__r.id == exc.id );  
     
        
        DateTime nowTime = DateTime.now();
        integer h = nowTime.hour(); 
        
        notwguELCC.Active__C = true;
        notwguELCC.StartHour__c = 0;
        if (h-1 > 0)
        {
            notwguELCC.StopHour__c = h-1;
        }
        else
        {
            notwguELCC.Active__C = false;
        }
        update notwguELCC;
              
 
        Contact contact3 = new Contact(firstName='Pinky', lastName = 'OTester', email='PinkyOTester@yahoo.com',  pidm__C = '1234321' );
        contact3.recordtypeid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id; 
    
        insert contact3;
       
        Account student3 = [Select id, pidm__C from Account where studentcontact__r.id = :contact3.id];

        Opportunity care3 = new Opportunity(AccountId=student2.Id, StudentContact__c = contact2.id,  Name='Pinky OTester', CloseDate=date.today(), StageName='Intake', RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
        care3.LeadGrade__c = 'B';
        insert care3;   
               
        
        CAREforceUtility.createExternalLeads(care3);


        Opportunity otest3 = [SELECT Id, Name, ExternalLeadContactControl__c , ExternalLeadContactControl__r.id, ExternalLeadContactControl__r.name  FROM Opportunity where id = :care3.id];

        System.assert(otest3.ExternalLeadContactControl__r.id == exc.id );  
        
  
        
    
    }
    
    
     @IsTest
    public static void testCreateExternalLeadsNoLeadsLeft (){ 
    
    
    List<ExternalLeadContactControl__c> elist = new List<ExternalLeadContactControl__c>();
    
    String letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
      ExternalLeadContactControl__c wguELCC= new ExternalLeadContactControl__c();
        wguELCC.Name= 'WGU';
        wguELCC.Active__C = true;
        wguELCC.MonthlyLimit__c = 1000;
        wguELCC.StartHour__c = 0;
        wguELCC.StopHour__c = 24;
        wguELCC.PercentOfLeadsToAssignPicklist__c = '50';
        
        
        elist.add(wguELCC);
        
        
        ExternalLeadContactControl__c notwguELCC= new ExternalLeadContactControl__c();
        notwguELCC.Name= 'NotWGU';
        notwguELCC.Active__C = true;
        notwguELCC.MonthlyLimit__c = 1;
        notwguELCC.StartHour__c = 0;
        notwguELCC.StopHour__c = 24;
        
        notwguELCC.PercentOfLeadsToAssignPicklist__c = '50';
    
        elist.add(notwguELCC);
   

        insert elist;
        
        List<Contact> myContacts = new List<Contact>();
        
        
        Id recid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id;
        Id rec2id = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id; 
        
        for (Integer i =0; i < 6; i++)
        {
              
        
        String supper = letters.substring(i+1, i+ 2);
        String slower = supper.toLowerCase();
        Contact contact2 = new Contact(firstName=supper + 'inky', lastName = 'OT' + slower + 'ster', email= supper + 'inkyOTester' + slower + '@yahoo.com',  pidm__C = '123321' + i );
        contact2.recordtypeid = recid;
    
        myContacts.add(contact2);
        
        }
        
    //    System.debug(myContacts);
        
        insert myContacts;
         
        System.assert(true);
         
        List<Account> myAccounts =  [Select id, pidm__C from Account];
         
        List<Opportunity> myCares1 = new List<Opportunity>();
        List<Opportunity> myCares2 = new List<Opportunity>();
        List<Opportunity> myCares3 = new List<Opportunity>();
       Test.startTest();
        for (Integer i =0; i < 6; i++)
        {
               Opportunity care2 = new Opportunity(AccountId=myAccounts[i].Id, StudentContact__c = myContacts[i].id,  
                                                   Name= myContacts[i].firstName + ' ' + myContacts[i].lastName , 
                                                   CloseDate=date.today(), StageName='Intake', 
                                                  RecordTypeId  = rec2id);
               care2.LeadGrade__c = 'B';
               
                insert care2;
                CAREforceUtility.createExternalLeads(care2);
           
        }
    
        
        Test.stopTest();
        
        List<Opportunity> myOtests = [SELECT Id, Name, 
                                    ExternalLeadContactControl__c , 
                                    ExternalLeadContactControl__r.id,
                                    ExternalLeadContactControl__r.name  FROM Opportunity];
                                    
        Integer j = 0;       
        
    //   System.debug('notwguELCC.id: ' + notwguELCC.id);
    //   System.debug('wguELCC.id: ' + wguELCC.id);               
        for (Opportunity o: myOtests)
        {
          // System.debug(o);
         //  System.debug(o.ExternalLeadContactControl__r.name);
            if (j == 0)
            {
                System.assert(o.ExternalLeadContactControl__c == notwguELCC.id);
                
            }
            else
            {
                 System.assert(o.ExternalLeadContactControl__r.id == wguELCC.id); 
            }   
            j++;                        
        }
     
        
    
    }
    
    
       @IsTest
    public static void testCreateExternalLeadsOneNotWGU (){ 
    
    
    List<ExternalLeadContactControl__c> elist = new List<ExternalLeadContactControl__c>();
    
    String letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
      ExternalLeadContactControl__c wguELCC= new ExternalLeadContactControl__c();
        wguELCC.Name= 'WGU';
        wguELCC.Active__C = true;
        wguELCC.MonthlyLimit__c = 1000;
        wguELCC.StartHour__c = 0;
        wguELCC.StopHour__c = 24;
        wguELCC.PercentOfLeadsToAssignPicklist__c = '50';
        
        
        elist.add(wguELCC);
        
        
        ExternalLeadContactControl__c notwguELCC= new ExternalLeadContactControl__c();
        notwguELCC.Name= 'NotWGU';
        notwguELCC.Active__C = true;
        notwguELCC.MonthlyLimit__c = 1000;
        notwguELCC.StartHour__c = 0;
        notwguELCC.StopHour__c = 24;
        
        notwguELCC.PercentOfLeadsToAssignPicklist__c = '50';
    
        elist.add(notwguELCC);
   

        insert elist;
        
        List<Contact> myContacts = new List<Contact>();
        
        
        Id recid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id;
        Id rec2id = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id; 
        
        for (Integer i =0; i < 6; i++)
        {
              
        
        String supper = letters.substring(i+1, i+ 2);
        String slower = supper.toLowerCase();
        Contact contact2 = new Contact(firstName=supper + 'inky', lastName = 'OT' + slower + 'ster', email= supper + 'inkyOTester' + slower + '@yahoo.com',  pidm__C = '123321' + i );
        contact2.recordtypeid = recid;
    
        myContacts.add(contact2);
        
        }
        
     //   System.debug(myContacts);
        
        insert myContacts;
         
        System.assert(true);
         
        List<Account> myAccounts =  [Select id, pidm__C from Account];
         
        List<Opportunity> myCares1 = new List<Opportunity>();

       Test.startTest();
       List<Opportunity> myCares2 = new List<Opportunity>();
       
        for (Integer i =0; i < 6; i++)
        {
               Opportunity care2 = new Opportunity(AccountId=myAccounts[i].Id, StudentContact__c = myContacts[i].id,  
                                                   Name= myContacts[i].firstName + ' ' + myContacts[i].lastName , 
                                                   CloseDate=date.today(), StageName='Intake', 
                                                  RecordTypeId  = rec2id);
               care2.LeadGrade__c = 'B';
               
              
            insert care2;
                CAREforceUtility.createExternalLeads(care2);
           
        }
       
        
       Test.stopTest();
        
        List<Opportunity> myOtests = [SELECT Id, Name, 
                                    ExternalLeadContactControl__c , 
                                    ExternalLeadContactControl__r.id,
                                    ExternalLeadContactControl__r.name  FROM Opportunity];
                                    
        Integer j = 0;       
  //            System.debug('notwguELCC.id: ' + notwguELCC.id);
  //      System.debug('wguELCC.id: ' + wguELCC.id);               
        for (Opportunity o: myOtests)
        {
   //         System.debug(o);
    //       System.debug(o.ExternalLeadContactControl__r.name);
            if (math.mod(j,10) < 5)
            {
                System.assert(o.ExternalLeadContactControl__c == notwguELCC.id);
                
            }
            else
            {
                 System.assert(o.ExternalLeadContactControl__r.id == wguELCC.id); 
            }   
            j++;                        
        }
     
        
    
    }
    
       @IsTest
    public static void testCreateExternalLeadsThird (){ 
    
    
    List<ExternalLeadContactControl__c> elist = new List<ExternalLeadContactControl__c>();
    
    String letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
      ExternalLeadContactControl__c wguELCC= new ExternalLeadContactControl__c();
        wguELCC.Name= 'WGU';
        wguELCC.Active__C = true;
        wguELCC.MonthlyLimit__c = 1000;
        wguELCC.StartHour__c = 0;
        wguELCC.StopHour__c = 24;
        wguELCC.PercentOfLeadsToAssignPicklist__c = '20';
        
        
        elist.add(wguELCC);
        
        
        ExternalLeadContactControl__c notwguELCC= new ExternalLeadContactControl__c();
        notwguELCC.Name= 'NotWGU';
        notwguELCC.Active__C = true;
        notwguELCC.MonthlyLimit__c = 1000;
        notwguELCC.StartHour__c = 0;
        notwguELCC.StopHour__c = 24;
        
        notwguELCC.PercentOfLeadsToAssignPicklist__c = '30';
    
        elist.add(notwguELCC);
        
       ExternalLeadContactControl__c thirdNotELCC= new ExternalLeadContactControl__c();
        thirdNotELCC.Name= 'ThirdNot';
        thirdNotELCC.Active__C = true;
        thirdNotELCC.MonthlyLimit__c = 1000;
        thirdNotELCC.StartHour__c = 0;
        thirdNotELCC.StopHour__c = 24;
        
        thirdNotELCC.PercentOfLeadsToAssignPicklist__c = '30';
    
        elist.add(thirdNotELCC);
   

        insert elist;
        
        List<Contact> myContacts = new List<Contact>();
        
        
        Id recid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id;
        Id rec2id = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id; 
        
        for (Integer i =0; i < 6; i++)
        {
              
        
        String supper = letters.substring(i+1, i+ 2);
        String slower = supper.toLowerCase();
        Contact contact2 = new Contact(firstName=supper + 'inky', lastName = 'OT' + slower + 'ster', email= supper + 'inkyOTester' + slower + '@yahoo.com',  pidm__C = '123321' + i );
        contact2.recordtypeid = recid;
    
        myContacts.add(contact2);
        
        }
        
     //   System.debug(myContacts);
        
        insert myContacts;
         

         
        List<Account> myAccounts =  [Select id, pidm__C from Account];
         
        List<Opportunity> myCares1 = new List<Opportunity>();

        Test.startTest();
        for (Integer i =0; i < 6; i++)
        {
               Opportunity care2 = new Opportunity(AccountId=myAccounts[i].Id, StudentContact__c = myContacts[i].id,  
                                                   Name= myContacts[i].firstName + ' ' + myContacts[i].lastName , 
                                                   CloseDate=date.today(), StageName='Intake', 
                                                  RecordTypeId  = rec2id);
               care2.LeadGrade__c = 'B';
               
           insert care2;
                CAREforceUtility.createExternalLeads(care2);
           
        }
       


       
        
       Test.stopTest();
        
        List<Opportunity> myOtests = [SELECT Id, Name, 
                                    ExternalLeadContactControl__c , 
                                    ExternalLeadContactControl__r.id,
                                    ExternalLeadContactControl__r.name  FROM Opportunity];
                                    
        Integer j = 0;       
        
           
        for (Opportunity o: myOtests)
        {
 //           System.debug(o);
 //           System.debug(o.ExternalLeadContactControl__r.name);
            if (j < 3)
            {
                      System.assert(o.ExternalLeadContactControl__c == notwguELCC.id);
                
            }
            else if (j < 6)
            {
                System.assert(o.ExternalLeadContactControl__c == thirdNotELCC.id);
      
                
            }

            else
            {
                  System.assert(o.ExternalLeadContactControl__r.id == wguELCC.id); 
            }   
            j++;                        
        }
     
        
    
    }
    
    
     @IsTest
    public static void testCreateExternalLeadsPostToLeadQual (){ 
    
    Runtime__c rtc = new RunTime__C(    Value__c = 'http://requestb.in/wvdlwmwv', name = 'LeadQual');
    insert rtc;
    List<ExternalLeadContactControl__c> elist = new List<ExternalLeadContactControl__c>();
    
    String letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
      ExternalLeadContactControl__c wguELCC= new ExternalLeadContactControl__c();
        wguELCC.Name= 'WGU';
        wguELCC.Active__C = true;
        wguELCC.MonthlyLimit__c = 1000;
        wguELCC.StartHour__c = 0;
        wguELCC.StopHour__c = 24;
        wguELCC.PercentOfLeadsToAssignPicklist__c = '10';
        
        
        elist.add(wguELCC);
        
        
        ExternalLeadContactControl__c notwguELCC= new ExternalLeadContactControl__c();
        notwguELCC.Name= 'LeadQual';
        notwguELCC.Active__C = true;
        notwguELCC.MonthlyLimit__c = 1000;
        notwguELCC.StartHour__c = 0;
        notwguELCC.StopHour__c = 24;
        
        notwguELCC.PercentOfLeadsToAssignPicklist__c = '90';
    
        elist.add(notwguELCC);
        
   

        insert elist;
        
        List<Contact> myContacts = new List<Contact>();
        
        
        Id recid = [select id from recordtype where name = 'ProspectRecord' and sobjecttype = 'Contact' limit 1].id;
        Id rec2id = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id; 
        
        for (Integer i =0; i < 2; i++)
        {
              

        
            String supper = letters.substring(i+1, i+ 2);
            String slower = supper.toLowerCase();
            Contact contact2 = new Contact(firstName=supper + 'inky', lastName = 'OT' + slower + 'ster', 
                                            email= supper + 'inkyOTester' + slower + '@yahoo.com',  
                                            pidm__C = '123321' + i, phone = '1234567890', 
                                            homephone ='', mailingstate = 'UT', mailingpostalcode = '84111'
                                             );
            contact2.recordtypeid = recid;
        
            myContacts.add(contact2);
        
        }
        
        System.debug(myContacts);
        
        insert myContacts;
         

         
        List<Account> myAccounts =  [Select id, pidm__C from Account];
         
        List<Opportunity> myCares1 = new List<Opportunity>();
        
     

        Test.startTest();
        for (Integer i =0; i < 2; i++)
        {
               Opportunity care2 = new Opportunity(AccountId=myAccounts[i].Id, StudentContact__c = myContacts[i].id,  
                                                   Name= myContacts[i].firstName + ' ' + myContacts[i].lastName , 
                                                   CloseDate=date.today(), StageName='Intake', LeadGrade__c = 'B',
                                                   RecordTypeId  = rec2id, MarketingProgram__c = getProgram(i+1));
                                                   
             
               
               insert care2;
               System.debug(care2);
               CAREforceUtility.createExternalLeads(care2);
             
           
        }
       
       



       
        
       Test.stopTest();
        
        List<Opportunity> myOtests = [SELECT Id, Name, 
                                    ExternalLeadContactControl__c , 
                                    ExternalLeadContactControl__r.id,
                                    ExternalLeadContactControl__r.name  FROM Opportunity];
                                    
        Integer j = 0;       
        
           
        for (Opportunity o: myOtests)
        {
 //           System.debug(o);
 //           System.debug(o.ExternalLeadContactControl__r.name);
            if (j < 3)
            {
              //        System.assert(o.ExternalLeadContactControl__c == notwguELCC.id);
                
            }
            else if (j < 6)
            {
              //  System.assert(o.ExternalLeadContactControl__c == thirdNotELCC.id);
      
                
            }

            else
            {
           //       System.assert(o.ExternalLeadContactControl__r.id == wguELCC.id); 
            }   
            j++;                        
        }
     
        
    
    }
    
       @IsTest
  public static void testStatusUpdateToLeadQual() {      
  
      Runtime__c rtc = new RunTime__C(    Value__c = 'http://requestb.in/wvdlwmwv', name = 'LeadQual');
    insert rtc;
    List<ExternalLeadContactControl__c> elist = new List<ExternalLeadContactControl__c>();
    
    String letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
      ExternalLeadContactControl__c wguELCC= new ExternalLeadContactControl__c();
        wguELCC.Name= 'WGU';
        wguELCC.Active__C = true;
        wguELCC.MonthlyLimit__c = 1000;
        wguELCC.StartHour__c = 0;
        wguELCC.StopHour__c = 24;
        wguELCC.PercentOfLeadsToAssignPicklist__c = '0';
        
        
        elist.add(wguELCC);
        
        
        ExternalLeadContactControl__c notwguELCC= new ExternalLeadContactControl__c();
        notwguELCC.Name= 'LeadQual';
        notwguELCC.Active__C = true;
        notwguELCC.MonthlyLimit__c = 1000;
        notwguELCC.StartHour__c = 0;
        notwguELCC.StopHour__c = 24;
        
        notwguELCC.PercentOfLeadsToAssignPicklist__c = '100';
    
        elist.add(notwguELCC);  
        
        insert elist;
    
    Contact student = TestStudentUser.getTestStudentContact();
    
    Opportunity care = new Opportunity(AccountId=student.AccountId, Name='Dudley Schults', ExternalLeadContactControl__C = notwguELCC.id,
     CloseDate=date.today(), StageName='Intake', 
     RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
    insert care;
    update care;
    System.debug('CARET: ' + care);
    care = [select id, AccountId, LastCallDisposition__c, ExternalLeadContactControl__C from Opportunity where id = :care.id];
        System.debug('CAREA: ' + care);
    Id careTaskId = [Select id from RecordType where Name='CAREforce Task' and sObjectType = 'Task'].id;    
        
    Test.StartTest();

        List<Task> newTasksList = new List<Task>();
        newTasksList.add( new Task(Subject='Call', CallDisposition__c='Phone Attempt 1', RecordTypeId=careTaskId, whoid=student.Id, whatid=care.id, NoteType__c='Other') );
        insert newTasksList;
            
    Test.StopTest();
        
   
    //grabbing code coverage
    CAREforceUtility.sendStatusUpdateToLeadQualDecode( JSON.serialize(newTasksList) );

  }
    
    
        public static String getProgram(Integer sequence) {
        WGUDegreeProgram__c degreeProgram = null;
        CareProgramMiddleEarth__c earth = null;
        
        if (sequence == 1 || sequence == null) {

            // Create WGU Degree Program
            degreeProgram = new WGUDegreeProgram__c(Name='BAECE', Title__c='Bachelor of Arts, Early Childhood Education', active__c=true, PAMSID__c=15);
            insert degreeProgram;
            
            // Create Marketing Program
            earth = new CareProgramMiddleEarth__c(Name='BA Early Childhood Education', active__c=true, BannerProgramCode__c=degreeProgram.id, InquiryProgram__c=true, ProgramGroups__c='Nursing');
            insert earth;
        }
        else {
            // Create WGU Degree Program
            degreeProgram = new WGUDegreeProgram__c(Name='BAMA9', Title__c='Bachelor of Arts, Mathematics (5-9)', active__c=true, PAMSID__c=300000);
            insert degreeProgram;
            
            // Create Marketing Program
            earth = new CareProgramMiddleEarth__c(Name='BA Mathematics 5-9', active__c=true, BannerProgramCode__c=degreeProgram.id, InquiryProgram__c=true, ProgramGroups__c='Education (initial teaching licensure programs)');
            insert earth;
        }

        // Return Marketing Program Id
        return earth.id;
    }
    
    
}