src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>District</fullName>
        <active>true</active>
        <description>School District</description>
        <label>District</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>District with which the contact is associated</description>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District Contacts</relationshipLabel>
        <relationshipName>DistrictContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School with which the contact is associated</description>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>School Contacts</relationshipLabel>
        <relationshipName>SchoolContacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/FieldExperience__c.object
<CustomObject>
    <description>This object represents the field experiences application. Students have access to the this object in the customer portal. There are multiple record types including PCE/DT, BSHI, MSSP, etc.</description>
    <fields>
        <fullName>ClinicalSupervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person observing the student during DT.</description>
        <label>Clinical Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experiences (Clinical Supervisor)</relationshipLabel>
        <relationshipName>FEClinicalSupervisor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The mentor working with the student that is applying for PCE and DT.</description>
        <label>Mentor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FieldExperiences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <inlineHelpText>State of Licensure</inlineHelpText>
        <label>Licensure State</label>
        <picklist>
            <picklistValues>
                <fullName>AA - Armed Forces America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE - Armed Forces Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP - Armed Forces Pacific</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federated States of Micronesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marshall Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utah</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experiences</relationshipLabel>
        <relationshipName>FieldExperiences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieldExperienceProcess__c.object
<CustomObject>
    <description>The object that represents field experience-related processes such as placements, observations, appeals, etc.</description>
    <fields>
        <fullName>AbsenceDescription__c</fullName>
        <description>This is where the student can describe the reason for their absence in great detail.</description>
        <inlineHelpText>Describe the reason for you absence.</inlineHelpText>
        <label>Absence Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AbsenceReason__c</fullName>
        <description>The reason a student might be absent from their field experience.</description>
        <inlineHelpText>Select the reason for your absence.</inlineHelpText>
        <label>Absence Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Emergency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inclement Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ClinicalSupervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experience Processes (Clinical Supervisor)</relationshipLabel>
        <relationshipName>FieldExperienceProcesses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Field Experience Processes (District)</relationshipLabel>
        <relationshipName>Districts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldExperience__c</fullName>
        <label>Field Experience</label>
        <referenceTo>FieldExperience__c</referenceTo>
        <relationshipLabel>Field Experience Processes</relationshipLabel>
        <relationshipName>FieldExperiencesProcesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstDayAbsent__c</fullName>
        <description>The first day the student will be absent from their field experience/</description>
        <inlineHelpText>Please enter the first day of you absence.</inlineHelpText>
        <label>First Day Absent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HostTeacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The teacher hosting our student for demonstration teaching</description>
        <label>Host Teacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>FE Host Teacher</relationshipLabel>
        <relationshipName>Field_Experience_Processes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastDayAbsent__c</fullName>
        <description>The last day of a students absence from their field experience.</description>
        <inlineHelpText>Please enter the last day of your absence.</inlineHelpText>
        <label>Last Day Absent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NumberofDaysAbsent__c</fullName>
        <label>Number of Days Absent</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PlacementOutcome__c</fullName>
        <inlineHelpText>Check the appropriate response when nothing further needs to be done with this Placement Attempt, i.e., Confirmed = school, district, HT, grade, subject, length and payment info.</inlineHelpText>
        <label>Placement Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Withdrawn</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SchoolName__c</fullName>
        <formula>School__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Field Experience Processes (School)</relationshipLabel>
        <relationshipName>Schools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experience Processes</relationshipLabel>
        <relationshipName>Field_Experience_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Experience Process</label>
    <nameField>
        <label>Field Experiences Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experience Processes</pluralLabel>
    <recordTypes>
        <fullName>Absence</fullName>
        <active>true</active>
        <label>Absence</label>
    </recordTypes>
    <recordTypes>
        <fullName>Audit</fullName>
        <active>true</active>
        <label>Audit</label>
    </recordTypes>
    <recordTypes>
        <fullName>CSRequest</fullName>
        <active>true</active>
        <label>CS Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>PlacementAttempt</fullName>
        <active>true</active>
        <label>Placement Attempt</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The mentor pidm so we can use external id&apos;s</description>
        <externalId>true</externalId>
        <inlineHelpText>The WGU PIDM assigned to this mentor.</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/States__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>State Attributes</description>
    <fields>
        <fullName>EducatorBasicSkillsCodes__c</fullName>
        <description>Assessment code(s) for passing the Teachers&apos; Basic Skills Assessment for the given state.</description>
        <inlineHelpText>If multiple assessments are required, separate each with a comma. If any of a list is acceptable, separate each with a space. E.g. &apos;MI01,MI02,MI03&apos; = &apos;MI01 AND MI02 AND MI03&apos;, &apos;ACBC AWBT PXST&apos; = &apos;ACBC OR AWBT OR PXST&apos;</inlineHelpText>
        <label>Educator Basic Skills Codes</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateFullName__c</fullName>
        <description>Full name of State</description>
        <externalId>true</externalId>
        <label>State FullName</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>States</label>
</CustomObject>

src/classes/MyFieldExperienceController.cls
/*
 * Author Paul Coleman
 * Western Governors University 
 *
 * Date January 28, 2013 @ 1746 hrs
 * Revised: Person Account Refactor 
 * 
 * Revised Oct 30 2012 @ 1130 hrs
 * Revised: (security audit compliance: with sharing) 
 * 
 * Manages processes for Student-facing Visual Force Page: MyFieldExperience.page
 *
 */
 public with sharing class MyFieldExperienceController {
    
    public String getLt(){
        return '<';
    }
    public String getGt(){
        return '>';
    }

    public MyFieldExperienceController() {
      this.personalInfoURL = getStudentFieldExperience().getVerifyPersonalInfoURL();
    }

    public static StudentFieldExperience getStudentFieldExperience() { 
    
        ID userId = UserInfo.getUserId();
        try {
          transient StudentFieldExperience  sfe = (UserInfo.getProfileId() != [SELECT Id from Profile where Name='Student Profile'].id)? new StudentFieldExperience( [SELECT Id FROM Contact where Name = 'Khadijah_test Abdullah_test' and PIDM__c LIKE 'pctest%' LIMIT 1].id ): new StudentFieldExperience(userId);
          return sfe;
        } catch ( QueryException  e ) {
            ApexPages.addMessages(e);
            return null;
        }
    }

    public PageReference attachFile() {
       if ( this.fileAttachment != null && this.fileContentType != null && this.fileAttachmentName != null ){
         this.fieldExperienceId = this.fieldExperienceId == null? getFE().Id: this.fieldExperienceId;
         this.uploadSuccess = saveFileAttachment( this.fieldExperienceId, this.fileAttachment, this.fileContentType, this.fileAttachmentName );
       } else {
         ApexPages.addMessages(new FieldExperienceException('NULL VALUE ERROR: fileAttachment, fileContentType and fileAttachmentName are required parameters for the attachFile() method.'));
       }     
       this.fileAttachment = null;
       this.fileAttachmentName = null;
       this.fileContenttype = null;
       return Page.MyFieldExperience;              
    }

    public PageReference attachGeneralFile() {
       if ( this.fileAttachment != null && this.fileContentType != null && this.fileAttachmentName != null ){
         this.fieldExperienceId = this.fieldExperienceId == null? getFE().Id: this.fieldExperienceId;
         this.uploadSuccess = saveFileAttachment( this.fieldExperienceId, this.fileAttachment, this.fileContentType, this.fileAttachmentName );
       } else {
         ApexPages.addMessages(new FieldExperienceException('NULL VALUE ERROR: fileAttachment, fileContentType and fileAttachmentName are required parameters for the attachFile() method.'));
       }   
       this.fileAttachment = null;
       this.fileAttachmentName = null;
       this.fileContenttype = null;
       this.toDoIndex = null;
       return Page.MyFieldExperience;              
    }

    public static Boolean saveFileAttachment( ID thisFieldExperienceId, Blob thisfileAttachment, String thisfileContentType, String thisfileAttachmentName ) {
            Attachment attach = new Attachment();
            attach.Body = thisfileAttachment;
            attach.Name = thisfileAttachmentName;
            attach.Description = thisfileAttachmentName;
            attach.ContentType = thisfileContentType;
            attach.ParentID = thisFieldExperienceId;
            attach.isPrivate = false;
            try {
                  insert attach;
                  return true;
            } catch(System.DMLException dml) {
               ApexPages.addMessages(dml);
               System.debug(LoggingLevel.ERROR, dml);
               return false;
            }
    }
    
    @RemoteAction
    public static String getAllToDosAsJSON() { 
        try {
          return getStudentFieldExperience().getStudentFETasksExtJSON();
        } catch(FieldExperienceException e) {
          ApexPages.addMessages(e);
          return '';
        }
    }

    @RemoteAction
    public static String getAllToDoTemplates() {
        try {
          return getStudentFieldExperience().getAllFEToDoTemplatesExtJSON();
        } catch(FieldExperienceException e) {
          ApexPages.addMessages(e);
          return '';
        }
    }
           
    @RemoteAction
    public static boolean setToDoComplete( Id taskId ) {    
          try {
          return getStudentFieldExperience().setFEToDoComplete( taskId );
        } catch(FieldExperienceException e) {
          ApexPages.addMessages(e);
          return false;
        }
    }
    
    @RemoteAction
    public static boolean setDTPhaseStatus() {    
        return getStudentFieldExperience().setDTPhaseStatus('DT Submitted');
    }
    
    @RemoteAction
    public static String findDistrict( String districtName, String state ) {
        return getStudentFieldExperience().findDistrictExtJSON(districtName, state);
    }
    
    @RemoteAction
    public static String findSchool( String schoolName, String state ) {
        return getStudentFieldExperience().findSchoolExtJSON(schoolName, state);
    }
    
    @RemoteAction
    public static boolean isAssessmentComplete( String assessmentCode ) {
        return getStudentFieldExperience().isAssessmentComplete(assessmentCode);
    }

    @RemoteAction
    public static boolean isBasicSkillsAssessmentComplete() {
        Boolean result = false;
        String licenseState = Test.isRunningTest()? 'Utah': getStudentFieldExperience().getActiveFieldExperience().State__c;
         if ( licenseState != null ) {
           String stateAbbr = [SELECT NAME from States__c where StateFullName__c = :licenseState LIMIT 1].Name;
           String skillCodes = States__c.getValues(stateAbbr)!=null? States__c.getValues(stateAbbr).EducatorBasicSkillsCodes__c: null;
           result = skillCodes != null? isAssessmentComplete( skillCodes ) : false;
         } else {
           result = false;
         }
        return result;
    }

    
    @RemoteAction
    public static String addFEPlacementAttempt( String school, String district ) {
          try {
            String defaultRecordType = 'PlacementAttempt';
            return getStudentFieldExperience().addFEProcess( defaultRecordType, school, district );
          } catch (FieldExperienceException e) {
          ApexPages.addMessages(e);
          return '';
          }
    }
    
    @RemoteAction
    public static String addFEPlacementAttemptCustom( String address, String contact, Boolean isDistrict ) {
        try {
            String defaultRecordType = 'PlacementAttempt';
            return getStudentFieldExperience().addFEProcess( defaultRecordType, address, contact, isDistrict );
        } catch (FieldExperienceException e) {
          ApexPages.addMessages(e);
          return '';
        }
    }
    
    @RemoteAction
    public static String getAllFEProcesses() {
        return getStudentFieldExperience().getAllFEProcessesExtJSON();
    }
    
    @RemoteAction
    public static String getSchoolNamesFromFEProcessDistricts() {
        return getStudentFieldExperience().getSchoolNamesFromFEProcessDistrictsExtJSON();
    }
    
    

    @RemoteAction
    public static String getStateLicensesJSON( String state ) {
        return getStudentFieldExperience().getFEStateLicensesExtJSON( state );
    }

    @RemoteAction
    public static boolean setLicenseState( String state ) {
        return getStudentFieldExperience().setFELicenseState( state );
    }

    @RemoteAction
    public static boolean setCohort( ID cohort ) {
        return getStudentFieldExperience().setFECohort( cohort );
    }

    @RemoteAction
    public static boolean setLicenseGoal( Id licenseId ) {
        return getStudentFieldExperience().setFELicenseGoal( licenseId );
    }

    public String getVerifyPersonalInfoURL() {
        if ( this.personalInfoURL == null || Test.isRunningTest() ) {
          this.personalInfoURL = getStudentFieldExperience().getVerifyPersonalInfoURL();
        }
        return this.personalInfoUrl;
    }

    @RemoteAction
    public static String getFEExtJSON() {
        return getStudentFieldExperience().getActiveFieldExperienceExtJSON();
    }
    
    @RemoteAction
    public static boolean updateFieldExperience( String feJSON ) {
        try {
        return getStudentFieldExperience().updateFieldExperience(feJSON);
        } catch ( StudentFieldExperienceException  spe ) {
            ApexPages.addMessages(spe);
            return false;
        }
    }
    
    @RemoteAction
    public static List<FieldExperienceProcess__c> getFEPlacements( String feId ) {
        List<FieldExperienceProcess__c> placements = [SELECT Id,SchoolName__c,District__r.Name,HostTeacher__c FROM FieldExperienceProcess__c WHERE RecordType.DeveloperName = 'PlacementAttempt' AND FieldExperience__c = :String.escapeSingleQuotes(feId) AND PlacementOutcome__c = 'Accepted' AND (district__c != null OR school__c != null)];
        return placements;
    }
    
    @RemoteAction
    public static String addFEPAbsence( String fepJSON ) {
    	Map<String,String> fepFields = (Map<String,String>)JSON.deserialize(fepJSON, MAP<String,String>.class);
    	FieldExperienceProcess__c fep = new FieldExperienceProcess__c(); 
  		fep.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Absence' AND SObjectType = 'FieldExperienceProcess__c' LIMIT 1].Id;
  		fep.Student__c = fepFields.get('Student__c');
  		fep.Name = fepFields.get('Name');
  		fep.ClinicalSupervisor__c = fepFields.get('ClinicalSupervisor__c');
  		String hostTeacher = fepFields.get('HostTeacher__c');
  		fep.HostTeacher__c = hostTeacher==''? null : hostTeacher;
  		fep.AbsenceDescription__c = fepFields.get('AbsenceDescription__c');
  		fep.AbsenceReason__c = fepFields.get('AbsenceReason__c');
  		fep.FieldExperience__c = fepFields.get('FieldExperience__c');
  		fep.FirstDayAbsent__c = Date.parse(fepFields.get('FirstDayAbsent__c'));
  		fep.LastDayAbsent__c = Date.parse(fepFields.get('LastDayAbsent__c'));
  		fep.NumberofDaysAbsent__c = Double.valueOf(fepFields.get('NumberofDaysAbsent__c')); 
  		fep.Mentor__c = fepFields.get('Mentor__c'); 
	    insert fep;
        return fep.Id;
    }
    
    @RemoteAction
    public static String getRecordedAbsences( String feId ) {
        List<FieldExperienceProcess__c> absences = [SELECT Id,Name,RecordTypeId,RecordType.Name,AbsenceReason__c,AbsenceDescription__c,FirstDayAbsent__c,LastDayAbsent__c,NumberofDaysAbsent__c FROM FieldExperienceProcess__c WHERE RecordType.DeveloperName = 'Absence' AND FieldExperience__c = :String.escapeSingleQuotes(feId) ORDER BY FirstDayAbsent__c DESC];
        return JSON.serialize(absences);
    }
    
    @RemoteAction
    public static Id getCSRequestClinicalSupervisor( String feId ) {
        Id ClinicalSupervisor = [SELECT count() FROM FieldExperienceProcess__c WHERE CSRequest__c = 'Confirmed' AND RecordType.DeveloperName = 'CSRequest' AND FieldExperience__c = :String.escapeSingleQuotes(feId)] > 0? [SELECT ClinicalSupervisor__c FROM FieldExperienceProcess__c WHERE CSRequest__c = 'Confirmed' AND RecordType.DeveloperName = 'CSRequest' AND FieldExperience__c = :String.escapeSingleQuotes(feId) ORDER BY CreatedDate DESC LIMIT 1].ClinicalSupervisor__c: null;
        return ClinicalSupervisor;
    }
    
    private static FieldExperience__c getFE() {
        FieldExperience__c result;
        try {
          result = getStudentFieldExperience().getActiveFieldExperience();
          return result;
        } catch (FieldExperienceException fee) {
            ApexPages.addMessages(fee);
            result = new FieldExperience__c(Name='No valid field experience record for this student.');
            result.DTPhaseStatus__c = 'NOT FOUND';
            result.PCEPhaseStatus__c = 'NOT FOUND';
        } 
        return result;
    }
        
    public String getAvailableCohortsExtJSON() {
      List<Cohort__c> cohorts = [SELECT Id, Name from Cohort__c where AvailableForStudents__c = true];
      String jsonString ='[';
        boolean isFirst = true;
        for ( Cohort__c entry: cohorts ) {
                if ( isFirst ) {
                    isFirst = false;
                    jsonString += '{\"value\":\"'+entry.id+'\", \"name\":\"'+entry.Name+'\"}';
                } else {
                    jsonString += ',{\"value\":\"'+entry.id+'\", \"name\":\"'+entry.Name+'\"}';
                }
        }
        jsonString += ']';
        return jsonString;
    }
    
    public String getStatesExtJSON() {
      List<States__c> states = [SELECT Id, Name, StateFullName__c from States__c];
      String jsonString ='[';
        boolean isFirst = true;
        for ( States__c state: states ) {
                if ( isFirst ) {
                    isFirst = false;
                    jsonString += '{\"abbr\":\"'+state.Name+'\", \"name\":\"'+state.StateFullName__c+'\"}';
                } else {
                    jsonString += ',{\"abbr\":\"'+state.Name+'\", \"name\":\"'+state.StateFullName__c+'\"}';
                }
        }
        jsonString += ']';
        return jsonString;
    }
    
    public String getClassroomExperienceExtJSON() {
        Schema.DescribeFieldResult f = Schema.sObjectType.FieldExperience__c.fields.ClassroomExperience__c;
        f = f.getSObjectField().getDescribe();
        List<Schema.PicklistEntry> ple = f.getPicklistValues();
        String jsonString ='[';
        boolean isFirst = true;
        for ( Schema.PicklistEntry entry: ple ) {
                if ( isFirst ) {
                    isFirst = false;
                    jsonString += '{\"value\":\"'+entry.getValue()+'\", \"name\":\"'+entry.getLabel()+'\"}';
                } else {
                    jsonString += ',{\"value\":\"'+entry.getValue()+'\", \"name\":\"'+entry.getLabel()+'\"}';
                }
        }
        jsonString += ']';
        return jsonString;
    }
               
    public String getAbsenceReasonExtJSON() {
        Schema.DescribeFieldResult f = Schema.sObjectType.FieldExperienceProcess__c.fields.AbsenceReason__c;
        f = f.getSObjectField().getDescribe();
        List<Schema.PicklistEntry> ple = f.getPicklistValues();
        String jsonString ='[';
        boolean isFirst = true;
        for ( Schema.PicklistEntry entry: ple ) {
                if ( isFirst ) {
                    isFirst = false;
                    jsonString += '{\"value\":\"'+entry.getValue()+'\", \"name\":\"'+entry.getLabel()+'\"}';
                } else {
                    jsonString += ',{\"value\":\"'+entry.getValue()+'\", \"name\":\"'+entry.getLabel()+'\"}';
                }
        }
        jsonString += ']';
        return jsonString;
    }
               
    public blob fileAttachment { get; set; }
    public Id fieldExperienceId { get {
       this.FE = this.FE==null? getFE(): this.FE; 
       return this.FE.id;
    } set; }
    public String fieldExperienceName { get {
       this.FE = this.FE==null? getFE(): this.FE; 
       return this.FE.Name;
    } set; }
    public String fieldExperienceStatus { get {
       this.FE = this.FE==null? getFE(): this.FE; 
       return this.FE.PCEPhaseStatus__c;
    } set; }
    public String fileAttachmentName { get; set; }
    public String fileContentType { get; set; }
    public Integer toDoIndex { get; set; }
    public Boolean uploadSuccess { get; set; }
    private String personalInfoURL;
    private transient FieldExperience__c FE;
}