src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BannerStatus__c</fullName>
        <description>Student status as reported by SunGard Banner SIS, e.g., AS</description>
        <label>Banner Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrentTerm__c</fullName>
        <description>Current Term for the student, this is wgu foramtted</description>
        <label>Current Term</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateOfBirth__c</fullName>
        <description>Self disclosed from the application form</description>
        <label>Date of Birth</label>
        <length>10</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>InternationalPhone__c</fullName>
        <label>International Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>My_WGU_Email__c</fullName>
        <description>This is the my.wgu.edu email address used for students.</description>
        <inlineHelpText>This is the my.wgu.edu email address used for students.</inlineHelpText>
        <label>My WGU Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>OtherEmail__c</fullName>
        <description>Alternate email address for contact</description>
        <label>Other Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PhoneExtension__c</fullName>
        <label>Phone Extension</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>Student Identification number, also known as Banner ID.</description>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suffix__c</fullName>
        <label>Suffix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <description>This holds the student timezone. The source of data for this is in Banner and this should be updated each data in the Student Upload process</description>
        <inlineHelpText>Student Timezone</inlineHelpText>
        <label>Timezone</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>The username for the student that is assigned once the application fee has been paid.</description>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUEmail__c</fullName>
        <description>The student&apos;s @wgu.edu email address.</description>
        <label>WGU Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>middleInitial__c</fullName>
        <label>Middle Initial</label>
        <length>4</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TestCreateUserFromContactWebservice.cls
@IsTest
public class TestCreateUserFromContactWebservice{
    
    @IsTest public static void testUserCreation() {    
        String pidm = '0';
        createContactForTest(pidm);
        
      	User testUser = TestStudentUser.getSAdminUser();
    	System.RunAs( testUser ) {   
            Test.startTest();
                
            CreateUserFromContactWebservice cufcw = new CreateUserFromContactWebservice();
            String returnPidm = cufcw.createUserFromContact(pidm);
                            
            Test.stopTest(); 
            
         	List<User> result = [SELECT Id FROM User WHERE PIDM__c = :pidm];
            System.assertEquals(1, result.size());
        }
    }  
    
    @IsTest(SeeAllData=true) public static void userAlreadyExistsTest() {    
        User user = [SELECT id, pidm__c FROM User WHERE IsActive = true AND Profile.name = 'Student Profile' LIMIT 1];
        
      	User testUser = TestStudentUser.getSAdminUser();
    	System.RunAs( testUser ) {   
            Test.startTest();
                
            CreateUserFromContactWebservice cufcw = new CreateUserFromContactWebservice();
            String returnPidm = cufcw.createUserFromContact(user.pidm__c);
                            
            Test.stopTest();
            System.assertEquals('Exists', returnPidm);
        }
    }  
    
    private static void createContactForTest(String pidm) {
        Account acc = new Account();
        acc.name = 'Test Account';
        insert acc;
        
        Contact student = new Contact();
        student.accountId = acc.id;
        student.LastName='test1';
        student.FirstName='test1';
        student.Salutation='test1';
        student.MailingStreet='test1'; 
        student.MailingCity='test1';
        student.MailingState='test1';  
        student.MailingPostalCode='11111';  
        student.MailingCountry = 'UD';
        student.Phone='test1';  
        student.Fax='test1';  
        student.MobilePhone='test1'; 
        student.HomePhone='test1'; 
        student.OtherPhone='test1';  
        student.Email='test1@kf.com'; 
        student.Title='test1'; 
        student.BannerStatus__c='AS';  
        student.CurrentTerm__c='test1';  
        student.Gender__c='test1';
        student.PIDM__c=pidm;  
        student.Status__c='test1'; 
        student.StudentID__c = '21457';
        Student.OtherEmail__c='test1@tesky.com'; 
        student.My_WGU_Email__c='test1@bnleh.com';
        student.DateOfBirth__c ='1111';
        student.InternationalPhone__c='test1'; 
        student.PhoneExtension__c='test1'; 
        student.Suffix__c='test1'; 
        student.middleInitial__c='t'; 
        student.WGUEmail__c='test1@wgu.edu'; 
        student.timezone__c='GMT'; 
        student.Username__c = 'test1';  
        insert student;
    }
    
}