src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to the actual Contact record for dereferencing the complete set of Contact fields in formulas and validations</description>
        <inlineHelpText>The student contact field is set automatically when the account record is created or updated</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Contact</relationshipLabel>
        <relationshipName>StudentContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ProspectRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Prospects</description>
        <label>ProspectRecord</label>
    </recordTypes>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CAREStage__c</fullName>
        <label>CARE Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applicant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dis-Positioned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DateOfBirth__c</fullName>
        <description>Self disclosed from the application form</description>
        <label>Date of Birth</label>
        <length>10</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>Student Identification number, also known as Banner ID.</description>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUEmail__c</fullName>
        <description>The student&apos;s @wgu.edu email address.</description>
        <label>WGU Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>ProspectRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Prospects</description>
        <label>ProspectRecord</label>
    </recordTypes>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CAREStatusListView__c</fullName>
        <formula>LEFT(TEXT(CareStatus__c), 4)</formula>
        <label>CARE Status List View</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CareStatus__c</fullName>
        <label>CARE Status</label>
        <picklist>
            <picklistValues>
                <fullName>PROS – Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PRAP – Prospect Applied Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APNN – Application Incomplete PRAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APIN – Application Incomplete APCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APCO – Application Complete, Unpaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC – Application Complete, Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REDI - Admission Decision Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEND - Additional Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAMT - Auto Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMT – Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTV – Fit and EWB Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLRD - Cleared to Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENRL – Enrolled and Assigned a Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEVR – Never completed EWOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DROP – Dropped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAMT - Not Admitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAYT - Not Admitted Yet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MATR – Matriculated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRAD – Ready for Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALUMNI - Graduated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>StudentContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CARE Profile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <formula>Account.StudentContact__r.StudentID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestCAREforceScheduledStatusUpdate.cls
@IsTest
public class TestCAREforceScheduledStatusUpdate {
    @IsTest
    public static void testScheduling() {
        Test.startTest();
        CAREforceScheduledStatusUpdate.schedule();
        Test.stopTest();
    }

    @IsTest
    public static void testRun() {
        List<Contact> contacts = new List<Contact>();
        String prospectId = [SELECT Id FROM RecordType WHERE sObjectType = 'Contact' AND Name = 'ProspectRecord'][0].Id;
        String studentId = [SELECT Id FROM RecordType WHERE sObjectType = 'Contact' AND Name = 'StudentRecord'][0].Id;
    
        contacts.add(new Contact(FirstName = 'Unit', LastName = 'Test', Email = 'utest@test.fake', RecordTypeId = studentId,
                                      HomePhone = '(801) 555-5555', Phone = '(801) 555-5555',
                                       CAREStage__c = 'Prospect', DateOfBirth__c = '07/01/1980',
                                      Status__c = 'AS', WGUEmail__c = 'utest@my.wgu.edu', StudentID__c = '000123456'));
                                      
        contacts.add(new Contact(FirstName = 'Grad', LastName = 'Test', Email = 'utest@test.fake', RecordTypeId = studentId,
                                      HomePhone = '(801) 555-5555', Phone = '(801) 555-5555',
                                       CAREStage__c = 'Prospect', DateOfBirth__c = '07/01/1980',
                                      Status__c = 'IG', WGUEmail__c = 'gtest@my.wgu.edu', StudentID__c = '000123457'));   
                                      
        contacts.add(new Contact(FirstName = 'Drop', LastName = 'Test', Email = 'utest@test.fake', RecordTypeId = studentId,
                                      HomePhone = '(801) 555-5555', Phone = '(801) 555-5555',
                                       CAREStage__c = 'Prospect', DateOfBirth__c = '07/01/1980',
                                      Status__c = 'DR', WGUEmail__c = 'dtest@my.wgu.edu', StudentID__c = '000123458'));                                                                          
        insert contacts;
        
        List<Account> accounts = [SELECT id, Name, StudentContact__c From Account];
        
        Map<Id, Id> accountMap = new Map<Id, Id>();
        
        for (Account acc : accounts) {
            for (Contact con : contacts) {
                if (acc.StudentContact__c == con.Id) {
                    accountMap.put(con.Id, acc.Id);
                    break;
                }
            }
        }
        
        List<Opportunity> opportunities = new List<Opportunity>();
        
        // Contact 1, Opportunity 1 - CLRD -> ENRL
        Date today = Date.today();
        opportunities.add(new Opportunity(name = 'Unit Test', CAREStatus__c = 'CLRD - Cleared to Start', 
                                         StudentContact__c = contacts[0].Id, closeDate = Date.newInstance(today.year(), today.month(), 1),
                                         AccountId = accountMap.get(contacts[0].Id), StageName = 'Dis-positioned'));
        
        // Contact 1, Opportunity 2 - ENRL -> MATR
        opportunities.add(new Opportunity(name = 'Unit Test 2', CAREStatus__c = 'ENRL – Enrolled and Assigned a Mentor', 
                                         StudentContact__c = contacts[0].Id, closeDate = Date.newInstance(today.year(), today.month(), 1).addMonths(-1),
                                         AccountId = accountMap.get(contacts[0].Id), StageName = 'Dis-positioned'));
        
        // Contact 2, Opportunity 3 - MATR -> GRAD
        opportunities.add(new Opportunity(name = 'Grad Test', CAREStatus__c = 'MATR – Matriculated', 
                                         StudentContact__c = contacts[1].Id, closeDate = Date.newInstance(today.year(), today.month(), 1).addMonths(-18),
                                         AccountId = accountMap.get(contacts[1].Id), StageName = 'Dis-positioned'));
                                         
        // Contact 3, Opportunity 3 - MATR -> DROP
        opportunities.add(new Opportunity(name = 'Drop Test', CAREStatus__c = 'MATR – Matriculated', 
                                         StudentContact__c = contacts[2].Id, closeDate = Date.newInstance(today.year(), today.month(), 1).addMonths(-18),
                                         AccountId = accountMap.get(contacts[2].Id), StageName = 'Dis-positioned'));                                    
        
        insert opportunities;        
        
        Test.startTest();
        
        CAREforceScheduledStatusUpdate sched = new CAREforceScheduledStatusUpdate();
        sched.execute(null);
        
        Test.stopTest();
        
        opportunities = [SELECT Name, CAREStatusListView__c, CloseDate FROM Opportunity];
        
        for (Opportunity opp : opportunities) {
            if (opp.Name == 'Unit Test') {
                System.assert(opp.CAREStatusListView__c == 'ENRL');
            }
            
            if (opp.Name == 'Unit Test 2') {
                System.assert(opp.CAREStatusListView__c == 'MATR');
            }        
            
            if (opp.Name == 'Grad Test') {
                System.assert(opp.CAREStatusListView__c == 'GRAD');
            }                
            
            if (opp.Name == 'Drop Test') {
                System.assert(opp.CAREStatusListView__c == 'DROP');
            }            
        }
    }
}