src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to the actual Contact record for dereferencing the complete set of Contact fields in formulas and validations</description>
        <inlineHelpText>The student contact field is set automatically when the account record is created or updated</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Contact</relationshipLabel>
        <relationshipName>StudentContact</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>StudentContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CARE Profile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TranscriptStatus__c</fullName>
        <description>Check for appealed and unreceived transcripts to give an overall status</description>
        <formula>IF( LegacyCARETransferEval__c = true, &quot;Transcripts Logged in Legacy CARE&quot; ,
IF( TranscriptsNeeded__c = 0, &quot;No Transcripts Needed&quot;,
IF( RNValidationRequired__c = true,&quot;RN Validation Required&quot;,
IF( Appealed_Transcript_Count__c &gt; 0, &quot;Waiting for Appeal&quot;,
IF( OutstandingTranscriptsOnBase__c &gt;0, &quot;Waiting for Documents&quot;,
IF( OR(BEGINS(TEXT(CareStatus__c),&apos;PROS&apos;), BEGINS(TEXT(CareStatus__c),&apos;PRAP&apos;), BEGINS(TEXT(CareStatus__c),&apos;APNN&apos;), BEGINS(TEXT(CareStatus__c),&apos;APIN&apos;), BEGINS(TEXT(CareStatus__c),&apos;APCO&apos;)), &quot;Waiting for Banner ID&quot;, 
IF( AND(OutstandingTranscripts__c &gt;0, OutstandingTransferEvaluations__c = 0, CompletedTransferEvaluations__c = 0), &quot;Pending Automated Index&quot;, &quot;All Transcripts Received&quot;)))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The overall status of the transcript request process.  Valid values include Waiting for Transcripts, All Transcripts Received and Waiting for Appeal</inlineHelpText>
        <label>Transcript Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StudentTranscript__c.object
<CustomObject>
    <description>Object to manage the transcripts that must be collected through in-take and viewed by Mentors</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact of the student</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Transfer Institution</relationshipLabel>
        <relationshipName>StudentTransferInstitution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DegreeType__c</fullName>
        <label>Degree Type</label>
        <picklist>
            <picklistValues>
                <fullName>Associates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctorate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EndMonthYear__c</fullName>
        <formula>EndMonth__c &amp;&quot; - &quot; &amp;EndYear__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EndMonthYear</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InstitutionCity__c</fullName>
        <label>Institution City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InstitutionState__c</fullName>
        <label>Institution State</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartMonthYear__c</fullName>
        <formula>StartMonth__c  &amp;&quot; - &quot; &amp; StartYear__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>StartMonthYear</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TranscriptInstitution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transcript Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Transfer Institution (Transcript Institution)</relationshipLabel>
        <relationshipName>SchoolTranscripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TranscriptStatus__c</fullName>
        <description>Indicates the status of the transcripts associated with this school. The default is Expected. The status should be set to received when the scans are attached to the object record.</description>
        <inlineHelpText>When a transcript is expected, set the status to Expected and change the status to Received when it is attached. If a transcript is appealed, it will result in an approved or denied appeal.</inlineHelpText>
        <label>Transcript Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Expected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid - Unofficial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid - Non Accredited School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid - No Degree Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appealed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excluded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal Denied – Transfer Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal Denied – Military</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student Transfer Institution</label>
    <nameField>
        <displayFormat>Institution-{0000}</displayFormat>
        <label>Student Transfer Institution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transfer Institution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IntakeInterviewFlowController.cls
/*****************************************************************************************
* Name: IntakeInterviewFlowController
* Author: Will Slade
* Purpose: Controller for IntakeInterviewFlow
* Revisions: 
*    - 6/1/12 Created Class
*    - 1/23/13 Changed Account.PersonContactId to Account.StudentContact__c per refactor
******************************************************************************************/

public class IntakeInterviewFlowController
{
    private final Opportunity opp;
    private List<StudentTranscript__c> myTranscripts = new List<StudentTranscript__c>();
    private Opportunity testOpp;   

    public IntakeInterviewFlowController(ApexPages.StandardController stdController) 
    {
        opp = (Opportunity)stdController.getRecord();
        List<Opportunity> opp1 = [SELECT Id, Account.StudentContact__c FROM Opportunity WHERE Id = :opp.Id LIMIT 1];
        if (Opp1.size() != 0)
        {     
            myTranscripts = [SELECT Id, Name, TranscriptInstitution__r.name, StartMonthYear__c, EndMonthYear__c, InstitutionCity__c, 
                             InstitutionState__c, DegreeType__c, TranscriptStatus__c, Contact__c 
                             FROM StudentTranscript__c 
                             WHERE Contact__c = :opp1[0].Account.StudentContact__c];
            testOpp = opp1[0];
        }               
    }
    
    public List<StudentTranscript__c> getMyTranscripts()
    {    
        return myTranscripts;                                                                                                                                        
    }
    
    public Opportunity getTestOpp()
    {
        return testOpp;
    }         
}