src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>Student Identification number, also known as Banner ID.</description>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StudentCase__c.object
<CustomObject>
    <description>Object that will be visible/editable to students via some pages/interfaces.  Creation and manipulation of this object will trigger creation and manipulation of corresponding cases.  The existence of this object allows students to create and modify Salesforce cases without having visibility on them.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Student Cases</relationshipLabel>
        <relationshipName>StudentCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Cases</relationshipLabel>
        <relationshipName>StudentCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Case</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Student Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TestStudentCaseUtility.cls
/*****************************************************************************************
* Name: TestStudentCaseUtility
* Author: Will Slade
* Purpose: Test class for StudentCaseUtility
* Revisions: 
*    - 12/1/12 Created Class
*    - 1/24/13 Updated class for person account refactor
*    - 10/8/2013 PBC commented out User record creation, replaced with active User lookup for test runs
******************************************************************************************/

@isTest
private class TestStudentCaseUtility
{
    static testMethod void buildTestData()
    {
        User testUser = [SELECT id FROM User where isActive=TRUE and Profile.Name = 'System Administrator' LIMIT 1]; //new User();
        /*List<Profile> profiles = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        
        testUser.Firstname = 'TestStCaEm';
        testUser.Lastname = 'UserStCaEm';
        testUser.Pidm__c = 'QA9505QA';
        testUser.Username = 'testuserStuCaEm@testuser.testuser';
        testUser.Email = 'testuserStCaEm@testuser.testuser.my.wgu.edu';
        testUser.Alias = 'testStCa';
        testUser.CommunityNickname = 'testua6123se';
        testUser.TimeZoneSidKey = 'America/Denver';
        testUser.LocaleSidKey = 'en_US';
        testUser.EmailEncodingKey = 'ISO-8859-1';
        testUser.ProfileId = profiles[0].Id;
        testUser.LanguageLocaleKey = 'en_US';
        
        insert testUser;       
        */
    
        Contact testContact1 = new Contact();
        testContact1.FirstName = 'Willtest';
        testContact1.Lastname = 'Slayedtest';
        testContact1.Email = 'wslayed@my.wgu.edu';
        testContact1.PIDM__c = 'EMQAPIDM1';
        testContact1.StudentID__c = 'QA125ID';
        
        insert testContact1;
        
        test.startTest();
        System.RunAs(testUser)
        {
            StudentCase__c stuCase = new StudentCase__c(Comments__c = 'Hello these are comments', Contact__c = testContact1.Id);
            
            insert stuCase;                  
            
            Attachment attach = new Attachment();  
            attach.Body = Blob.valueOf('Attachment Body');  
            attach.Name = 'TestAttachFileWS.txt';
            //attach.ContentType = contentType;
            attach.ParentID = stuCase.Id;
            
            insert attach;
            
            stuCase.Comments__c += ' and here are more comments';
            
            update stuCase;
        
            test.stopTest();
            
            List<StudentCase__c> stuCases = [SELECT Id, Comments__c, Contact__c, Case__c FROM StudentCase__c WHERE Id = :stuCase.Id LIMIT 1];        
            List<Case> newCases = [SELECT Id FROM Case LIMIT 1];
            
            System.assert(stuCases.size() > 0);
            System.assert(newCases.size() > 0);
            //System.assertEquals(stuCase.Case__c, newCases[0].Id);
        }                
    }
}