src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/CareerServices__c.object
<CustomObject>
    <description>This object allows the Career Services team to track all appointment sessions completed for students related to career services..</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Career Services</relationshipLabel>
        <relationshipName>Student</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Career Services</label>
    <nameField>
        <displayFormat>CS# {00}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Career Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>LastStudentNote__c</fullName>
        <description>Date of the most recent student note posted by the student&apos;s mentor.</description>
        <label>Last Student Note</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MentorPidm__c</fullName>
        <description>The mentor that is assigned to this student</description>
        <label>Mentor Pidm</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/WGUStudentNote__c.object
<CustomObject>
    <description>This object stores notes about a student&apos;s interaction with service personnel such as mentors, etc.</description>
    <fields>
        <fullName>AuthorPidm__c</fullName>
        <label>Author Pidm</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user pidm</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WGUStudentNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShortText__c</fullName>
        <description>Field to store a portion of the Text__c field data in plain text</description>
        <label>ShortText</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>The contact record for this student</description>
        <inlineHelpText>The student associated with this note.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>WGUStudentNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>The basic rich text area for details of this note</description>
        <inlineHelpText>Please enter any details for this note.</inlineHelpText>
        <label>Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>WGUCreationDateTime__c</fullName>
        <description>This holds the date time stamp of a note.</description>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <label>WGU Student Note</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGUStudentNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WguStudentNoteUtility.cls
/*
 * Author Paul Stay
 * Western Governors University
 *
 * Date October 30, 2012 @ 1130 hrs
 * Revised: (security audit compliance: with sharing) 
 *
 * Utility class for WGUStudentNote__c trigger
 *
 * Based on AccountUtility and broken out so we can do testing with a future method.
 *
 * Date Jan. 2013
 * Checked for refactor person account, looks good, uses contact record for students. 
 */

public with sharing class WguStudentNoteUtility {

    public static void triggerWguStudentNote(List<WguStudentNote__c> noteList) {
                Map<String,ID> studentMap = new Map<String,ID>();
                Set<String> studentPidms = new Set<String>();
                List<Contact> cList = new List<Contact>();
                
                Map<String, ID> userMap = new Map<String,ID>();
                Set<String> userPidms = new Set<String>();
                List<User> uList = new List<User>();
                
                for(WguStudentNote__c sNote : noteList){
                    if(sNote.PIDM__c != null){
                        studentPidms.add(sNote.PIDM__C);
                        userPidms.add(sNote.AuthorPidm__c);
                    }
                }
                
                // Get the contact records for these students.
                cList = !studentPidms.isEmpty()? [SELECT Id, PIDM__C, LastStudentNote__c from Contact where PIDM__C IN : studentPidms]: new List<Contact>();  //maximizing code coverage
                
                // Create the map for pidms and students
                for(Contact c : cList) {
                    studentMap.put(c.PIDM__C, C.Id);
                }
                
                // user Map
                uList = !userPidms.isEmpty()? [SELECT Id, Pidm__c from User where PIDM__C In : userPidms]: new List<User>();   //maximizing code coverage
                
                // Create the user list
                for(User u : uList){
                    userMap.put(u.PIDM__c, u.Id);
                }
        
        		//Create Map of Student ID's and existing LastStudentNote dates
        		Map<Id, Date> LastNoteMap=new Map<Id, Date>();
        
        		for (Contact Student : cList)
                {
                    LastNoteMap.put(Student.Id, Student.LastStudentNote__c);
                }
                
                // Now fix the student record with all of the details that we need to do
                for(WguStudentNote__c note : noteList){

                    // Need to get the student here first so we can get the student mentor if needed.
                    note.Student__c = note.Student__c == null? studentMap.get(note.PIDM__c): note.Student__c;  //maximizing code coverage
                    
                    //Determine if the LastStudentNote date should be set on the student contact
                    if (note.AuthorPidm__c!=null && note.AuthorPidm__c!='' && (LastNoteMap.get(note.Student__c)==null || LastNoteMap.get(note.Student__c)<note.WGUCreationDateTime__c.date()))
                    {
                    	LastNoteMap.put(note.Student__c, note.WGUCreationDateTime__c.date());
                    }
                    
                    // If the author pidm is null, this means for some reason it was not set, so we assume that the authro should have been
                    // the Student Mentor for this student, and set that person to be the author
                    note.AuthorPidm__c = note.AuthorPidm__c == null ? note.Student__r.MentorPidm__c : note.AuthorPidm__c;
                    
                    note.Author__c = note.Author__c == null? userMap.get(note.AuthorPidm__c): note.Author__c; //maximizing code coverage

                    
                    if(Note.ShortText__c == null && Note.Text__c != null) {
                        String textString = String.valueOf(Note.Text__c).replaceAll('//<.*?//>', '');
                        Integer textLength = textString.length() > 64 ? 64 : textString.length()-1;
                        note.ShortText__c = textString.subString(0,textLength);
                    }
                }
        
        		//Update LastStudentNote on Student Contacts
        		for (Contact Student : cList)
                {
                    Student.LastStudentNote__c=LastNoteMap.get(Student.Id);
                }
        
        		update cList;
    }

    
}