src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The mentor pidm so we can use external id&apos;s</description>
        <externalId>true</externalId>
        <inlineHelpText>The WGU PIDM assigned to this mentor.</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The User with a mentor role for this record</description>
        <inlineHelpText>The user that has these attributes</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Student_Mentors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/MentorUtility.cls
/*
* Author Katarina Melki
* Western Governors University
*
* Created 01/28/2013
*
* Utility class for Mentor objects
*/
public class MentorUtility
{
    /* 
    * We want to auotmatically update the StudentMentor Account with the user from the pidm
    * So get the Account associated with the pidm and insert this into the lookup for the student
    * mentor object.
    */
    public static void mapUserPidm(List<Mentor__c> triggernew)
    {
        Map<String,ID> pidmMap = new Map<String,Id>();
    
        Set<String> mentorPidmList = new Set<String>();
        
        for(Mentor__c sm : triggernew)
        {
            mentorPidmList.add(sm.pidm__c);
        }
        
        if(!mentorPidmList.isEmpty())
        {
            List<User> uList = [SELECT Id, pidm__c from User where pidm__c in :mentorPidmList];
            
            for( User u : uList){
                pidmMap.put(u.pidm__c, u.id);
            }
        }

        for(Mentor__c m : triggernew)
        {
            m.User__c = pidmMap.get(m.pidm__c);
        }
    }
}