src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WGUPlacesStudents__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean value that determines if WGU should place students for Practical Clinical Experience (PCE) for all schools in this district.</description>
        <inlineHelpText>Should WGU place PCE students for all schools in this district (vs. self serve)?</inlineHelpText>
        <label>WGU Places Students</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>District</fullName>
        <active>true</active>
        <description>School District</description>
        <label>District</label>
    </recordTypes>
    <recordTypes>
        <fullName>SchoolK12</fullName>
        <active>true</active>
        <description>A K-12 School</description>
        <label>School (K-12)</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>District with which the contact is associated</description>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>District Contacts</relationshipLabel>
        <relationshipName>DistrictContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>School with which the contact is associated</description>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>School Contacts</relationshipLabel>
        <relationshipName>SchoolContacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/FieldExperience__c.object
<CustomObject>
    <description>This object represents the field experiences application. Students have access to the this object in the customer portal. There are multiple record types including PCE/DT, BSHI, MSSP, etc.</description>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The mentor working with the student that is applying for PCE and DT.</description>
        <label>Mentor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FieldExperiences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experiences</relationshipLabel>
        <relationshipName>FieldExperiences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieldExperienceProcess__c.object
<CustomObject>
    <description>The object that represents field experience-related processes such as placements, observations, appeals, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Field Experience Processes (District)</relationshipLabel>
        <relationshipName>Districts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldExperience__c</fullName>
        <label>Field Experience</label>
        <referenceTo>FieldExperience__c</referenceTo>
        <relationshipLabel>Field Experience Processes</relationshipLabel>
        <relationshipName>FieldExperiencesProcesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Mentor Contact for CC to mentor on workflow emails</description>
        <label>Mentor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FieldExperienceProcesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Field Experience Processes (School)</relationshipLabel>
        <relationshipName>Schools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experience Processes</relationshipLabel>
        <relationshipName>Field_Experience_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Experience Process</label>
    <nameField>
        <label>Field Experiences Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experience Processes</pluralLabel>
    <recordTypes>
        <fullName>PlacementAttempt</fullName>
        <active>true</active>
        <label>Placement Attempt</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The mentor pidm so we can use external id&apos;s</description>
        <externalId>true</externalId>
        <inlineHelpText>The WGU PIDM assigned to this mentor.</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IsEmployee__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this user is an employee please check this</description>
        <inlineHelpText>Checked if this user is an employee</inlineHelpText>
        <label>IsEmployee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TestFieldExperienceProcessUtility.cls
/*
 * This is the test class for FEPlacementAttempt
 * Author-Bhavadeep raavi
 *
 * Date February 12, 2013 @ 1014 hrs
 * Revised: PersonAccount Refactor, try/catch correction for future calls - Paul Coleman 
 *
 *
*/
@isTest
private class TestFieldExperienceProcessUtility{
    
    private static testmethod void testFieldExperienceProcessCreateWGUPlacementCase(){
 
             TestStudentFieldExperience.setupTestFEData();
             Contact testStudent = TestStudentUser.getTestStudentContact();
             //ID mentorProfileID = [SELECT id from Profile where name = 'Mentor'].id;
             //User testUser = new User(LastName='Mentor', FirstName='Standard', pidm__c='m1942_test', Username='a_test_mentor@wgu.edu', email='a_test_mentor@wgu.edu', Alias='a_test_m', CommunityNickname='a_test_mentor', TimeZoneSidKey='GMT', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=mentorProfileId, LanguageLocaleKey='en_US', isEmployee__c=true);
         User testMentor = [SELECT Id from User WHERE UserRole.Name ='Mentor' AND isActive = true LIMIT 1]; 
        
         ID DistrictId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName ='District' Limit 1].Id;
         ID SchoolK12Id = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName ='SchoolK12' Limit 1].Id;
         ID PlacementAttemptId = [SELECT Id FROM RecordType WHERE SobjectType = 'FieldExperienceProcess__c' AND DeveloperName ='PlacementAttempt' Limit 1].Id;
         Account DistrictAccount = new Account();
         DistrictAccount.recordtypeid = DistrictId;
         DistrictAccount.Name = 'Test District';
         DistrictAccount.WGUPlacesStudents__c = true;
         insert DistrictAccount;
         
         Account SchoolAccount = new Account();
         SchoolAccount.recordtypeid = SchoolK12Id;
         SchoolAccount.Name = 'Test School';
         SchoolAccount.WGUPlacesStudents__c = true;
         insert SchoolAccount;
         
         FieldExperience__c fe = new FieldExperience__c();
         fe.Name ='Test Fe';
         fe.Student__c = testStudent.Id;
         insert fe;
         
         fe.Mentor__c = testMentor.Id;
         update fe;
         
          
         Test.startTest();
         
              FieldExperienceProcess__c fep= new  FieldExperienceProcess__c();
                  fep.Name ='Test Fep';
                  fep.District__c = DistrictAccount.Id;
                  fep.School__c = SchoolAccount.Id;
                  fep.FieldExperience__c = fe.Id;
                  fep.recordtypeid = PlacementAttemptId;
                  insert fep;
         
                  FieldExperienceProcess__c fepAfterInsert = [SELECT id,Name,Student__c FROM FieldExperienceProcess__c WHERE id = :fep.Id LIMIT 1];
                  System.assert( fepAfterInsert.Student__c == testStudent.Id, 'FEP TRIGGER ERROR, FieldExperience__c.Student__c does NOT equal FieldExperienceProcess__c.Student__c AFTER INSERT');
                  
         Test.stopTest();
                             
              //future method assertions
              System.assert( [select count() from Case where contactId = :testStudent.Id LIMIT 1] == 1, 'FEP TRIGGER FUTURE METHOD ERROR, Case not created.' );
              Case studentCase = [select id,Description, contactid, Status from Case where contactId = :testStudent.Id LIMIT 1];
              System.assert( studentCase.Description.equals(DistrictAccount.Name) || studentCase.Description.equals(SchoolAccount.Name), 'FEP TRIGGER FUTURE METHOD ERROR, Case description does not match either of the referenced Accounts (District__c or School__c)');
              System.assert( studentCase.ContactId == fe.Student__c, 'FEP TRIGGER FUTURE METHOD ERROR, Case created from Trigger, FieldExperience.Student__c');
           
           //grab extra code coverage for future method Exception Handler
           List<FieldExperienceProcess__c> newFEPList = new List<FieldExperienceProcess__c>();
           newFEPList.add(fep);
           String TriggerNew = JSON.serialize( newFEPList );   
           createCaseFutureCall( TriggerNew ); 
    } 


    @future
    private static void createCaseFutureCall( String TriggerNew ) {
        
          //grabbing code coverage into future call exception handling blocks
          try { FieldExperienceProcessUtility.createWGUPlacesStudentCase( TriggerNew ); } catch (Exception e) {}
          
    }

    private static testmethod void testFieldExperienceProcessNoStudentIdFound(){
 
         FieldExperience__c fe = new FieldExperience__c();
         fe.Name ='Test Fe';
         fe.Student__c = null;  //SHOULD THROW AN EXCPEPTION ON FEP CREATION
         insert fe;
          
         Test.startTest();
         
              FieldExperienceProcess__c fep= new  FieldExperienceProcess__c();
              fep.Name ='Test Fep';
              fep.FieldExperience__c = fe.Id;
              fep.recordtypeid = [SELECT Id FROM RecordType WHERE SobjectType = 'FieldExperienceProcess__c' AND DeveloperName ='PlacementAttempt' Limit 1].Id;
              
              try {
                  insert fep;
              } catch (DmlException dml) {
                System.Assert( dml.getMessage().contains('CANNOT SAVE FEP RECORD WITHOUT A VALID STUDENT'), 'DML Exception did not contain "CANNOT SAVE FEP RECORD WITHOUT A VALID STUDENT": ' + dml.getMessage() );
              } 
                       
         Test.stopTest();
                             
    } 

}