src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to the actual Contact record for dereferencing the complete set of Contact fields in formulas and validations</description>
        <inlineHelpText>The student contact field is set automatically when the account record is created or updated</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Contact</relationshipLabel>
        <relationshipName>StudentContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/CAREProgram__c.object
<CustomObject>
    <description>The object to handle all of the CARE Programs and their codes</description>
    <label>CARE Program</label>
    <nameField>
        <label>CARE Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CareProgramMiddleEarth__c.object
<CustomObject>
    <description>Used to bring together the CARE Program code and the PAMS program code together.</description>
    <fields>
        <fullName>BannerProgramCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banner Program Code</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>CARE Programs Middle Earth</relationshipLabel>
        <relationshipName>CAREProgramsMiddleEarth</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CAREProgramCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CARE Program Code</label>
        <referenceTo>CAREProgram__c</referenceTo>
        <relationshipLabel>CARE Programs Middle Earth</relationshipLabel>
        <relationshipName>CAREProgramsMiddleEarth</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CARE Program Middle Earth</label>
    <nameField>
        <label>Program Middle Earth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs Middle Earth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for wguProgram</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MarketingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Program</label>
        <referenceTo>CareProgramMiddleEarth__c</referenceTo>
        <relationshipLabel>CAREProfile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>StudentContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CARE Profile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/StudentCase__c.object
<CustomObject>
    <description>Object that will be visible/editable to students via some pages/interfaces.  Creation and manipulation of this object will trigger creation and manipulation of corresponding cases.  The existence of this object allows students to create and modify Salesforce cases without having visibility on them.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Student Cases</relationshipLabel>
        <relationshipName>StudentCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Cases</relationshipLabel>
        <relationshipName>StudentCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentURL__c</fullName>
        <description>URL of the parent object</description>
        <label>Parent URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>StudentCaseReason__c</fullName>
        <label>Student Case Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Appeal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revision Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TransferEvaluation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer Evaluation</label>
        <referenceTo>TransferEvaluation__c</referenceTo>
        <relationshipLabel>Student Cases</relationshipLabel>
        <relationshipName>StudentCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Case</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Student Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentTranscript__c.object
<CustomObject>
    <description>Object to manage the transcripts that must be collected through in-take and viewed by Mentors</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact of the student</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Transfer Institution</relationshipLabel>
        <relationshipName>StudentTransferInstitution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Student Transfer Institution</relationshipLabel>
        <relationshipName>opportunityTransferInstitution</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <formula>Opportunity__r.Account.PIDM__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PIDM</label>
        <type>Text</type>
    </fields>
    <label>Student Transfer Institution</label>
    <nameField>
        <displayFormat>Institution-{0000}</displayFormat>
        <label>Student Transfer Institution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transfer Institution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TransferEvaluation__c.object
<CustomObject>
    <description>A Transfer evaluation is the parent object of the equivalent courses that will given to the student from their transfer work. It controls the overall status and assignment of the evaluation.</description>
    <fields>
        <fullName>EvaluationStatus__c</fullName>
        <label>Evaluation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready for Evaluation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appealed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The Link Between opportunities and transfer evaluations</description>
        <label>CARE Profile Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transfer Evaluations</relationshipLabel>
        <relationshipName>TransferEvaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The program that the student was eThe program that the student was evaluated for valuated for</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Transfer Evaluations</relationshipLabel>
        <relationshipName>TransferEvaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transfer Evaluation</label>
    <nameField>
        <label>Transfer Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfer Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <description>The ID that represents the program in PAMS.</description>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestStudentCaseTrigger.cls
/*****************************************************************************************
* Name: TestStudentCaseTrigger
* Author: Will Slade
* Purpose: Test class for StudentCaseTrigger
* Revisions: 
*    - 12/1/12 Created Class
*    - 1/24/13 Updated for person account refactor
******************************************************************************************/

@isTest
global class TestStudentCaseTrigger
{
    static testMethod void TestStudentCaseTrigger()
    {
        CAREProgram__c testCAREProgram = new CAREProgram__c(Name = 'TestCAREProgram124');
        insert testCAREProgram;
        
        WGUDegreeProgram__c testWGUDegreeProgram = new WGUDegreeProgram__c(Name = 'TestWGUDegreeProgram124', PAMSID__c = 124124124);
        insert testWGUDegreeProgram;       
        
        CAREProgramMiddleEarth__c testCAREProgramMiddleEarth = new CAREProgramMiddleEarth__c(CareProgramCode__c = testCAREProgram.Id, BannerProgramCode__c = testWGUDegreeProgram.Id);
        insert testCAREProgramMiddleEarth;
        
        RecordType RTA = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Account' AND Name = 'Institution of Higher Ed'];             

        Contact newContact = new Contact(Status__c='AS', Pidm__c='QA002233', FirstName='Dudley', LastName='FEEmailTest',
                                         RecordTypeId = [Select Id from RecordType where Name = 'StudentRecord' and SObjectType = 'Contact'].id);
        insert newContact;
        
        newContact = [SELECT Id, Status__c, Pidm__c, FirstName, LastName, Account.Id FROM Contact WHERE Id = :newContact.Id LIMIT 1];
        Account acct = [SELECT Id, Pidm__c, StudentContact__c FROM Account WHERE Id = :newContact.Account.Id];              
        
        System.assert( newContact.AccountId != null && newContact.AccountId == acct.Id );        
        System.assert( acct.id != null );
        System.assert( newContact != null && newContact.id != null );
        System.assert( newContact.pidm__c == acct.pidm__c );                    
        
        System.assertEquals(acct.StudentContact__c, newContact.Id);
        
        Account acct2 = new Account(Name = 'TestWeber1', RecordTypeId = RTA.Id);        
        insert acct2;
        
        Contact testContact = new Contact(FirstName = 'Willtest1', Lastname = 'Slayedtest1', Email = 'wslayed@my.wgu.edu', Account = acct);        
        insert testContact;        
        
        Opportunity testOpportunity = new Opportunity(Name = 'testEvalCourseTriggerOpp', CloseDate = Date.Today(), StageName = 'Applicant', 
                                                      Account = acct, MarketingProgram__c = testCAREProgramMiddleEarth.Id);
        insert testOpportunity;
 
        TransferEvaluation__c testTransferEvaluation = new TransferEvaluation__c(Name = 'testTransferEval124', Opportunity__c = testOpportunity.Id, EvaluationStatus__c = 'Pending');
        insert testTransferEvaluation;        
        
        StudentTranscript__c testInstitution = new StudentTranscript__c(Opportunity__c = testOpportunity.Id);
        insert testInstitution;
        
        StudentCase__c testStudentCase = new StudentCase__c(Contact__c = testContact.Id, TransferEvaluation__c = testTransferEvaluation.Id, StudentCaseReason__c = 'Appeal', 
                                                            ParentURL__c = 'http://www.espn.com');
        Test.startTest();
        insert testStudentCase;
        Test.stopTest();
        String scId = testStudentCase.Id;
        testStudentCase = [SELECT Id, Contact__c, TransferEvaluation__c, StudentCaseReason__c, Case__c FROM StudentCase__c WHERE Id = :scId];        
        
        List<Case> cases = [SELECT Id, Reason, TransferEvaluation__c FROM Case WHERE TransferEvaluation__c = :testStudentCase.TransferEvaluation__c LIMIT 1];
        System.assert(cases.size() > 0);
        System.assertEquals(testStudentCase.Case__c, cases[0].Id);
    }
}