src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BalanceDue__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This just shows if a balance is due from the student.</description>
        <inlineHelpText>Student has a balance due.</inlineHelpText>
        <label>Balance Due</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CumulativeSAP__c</fullName>
        <description>Cumulative SAP Percentage
Includes courses that received TR or RS</description>
        <formula>if(TotalAttemptedCUs__c &gt;0, TotalCompletedCUs__c / TotalAttemptedCUs__c , 0.00)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Cumulative SAP Percentage
Includes courses that received TR or RS</inlineHelpText>
        <label>Cumulative SAP %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MentorName__c</fullName>
        <description>Mentor name to get around permissions issue.</description>
        <formula>Mentor__r.FirstName &amp; &apos; &apos; &amp; Mentor__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mentor Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PlannedGraduationDate__c</fullName>
        <label>Planned Graduation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>Student Identification number, also known as Banner ID.</description>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The mentor pidm so we can use external id&apos;s</description>
        <externalId>true</externalId>
        <inlineHelpText>The WGU PIDM assigned to this mentor.</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentProcess__c.object
<CustomObject>
    <description>Custom object to manage student processes by record type.</description>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Student_Processes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>The stage of the student process.</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assign Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Student Reply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student spoke with Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student spoke with other personnel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student was submitted too early</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correction Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counsel Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Degree Plan Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diploma and Transcripts Mailed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diploma and Transcripts Mailed - Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midterm Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOU Accepted by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOU Needed - Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the student process.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated/Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Response Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Response Needed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>A formula field that pulls in the student ID number.</description>
        <formula>Student__r.StudentID__c</formula>
        <label>Student ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup field to the contact of the student process object.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>StudentProcesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TBGradAppSubmitted__c</fullName>
        <description>Have you or do you plan to submit a Graduation Application?</description>
        <inlineHelpText>Have you or do you plan to submit a Graduation Application?</inlineHelpText>
        <label>TB Grad App Submitted</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TBRequestedMonths__c</fullName>
        <description>Term Breaks are 1-3 months. Statistics show that one month term breaks are best for student progress and graduating. How much time will you be requesting?</description>
        <inlineHelpText>Term Breaks are 1-3 months. Statistics show that one month term breaks are best for student progress and graduating. How much time will you be requesting?</inlineHelpText>
        <label>TB Requested Months</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Student Process</label>
    <nameField>
        <label>Student Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Processes</pluralLabel>
    <recordTypes>
        <fullName>Graduation</fullName>
        <active>true</active>
        <description>The record type used to manage the graduation process for student records.</description>
        <label>Graduation</label>
    </recordTypes>
    <recordTypes>
        <fullName>TermBreak</fullName>
        <active>true</active>
        <description>The record type used to manage the term break process for student records.</description>
        <label>Term Break</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TermBreakRequestController.cls
/*
This Controller is for TermBreakRequest VF page used by Students.
Author- Bhavadeep Raavi

Revised: 12/02/2013 Comment out work submitted after term and graduation application submitted questions - Kristin Hasna
3/10/2014: Fixed a bug where the students contact was being looked up with unnecessary criteria such as last name - Austin Poulter
*/

public with sharing class TermBreakRequestController{
    public Boolean disFlag{get;set;}
    public Boolean msgFlag{get;set;}
    public Boolean stdIdFlag{get;set;}
    public string  stdId{get;set;}

    
    public Contact studentInfo{get;set;}
    public List<Contact> studentInfoList{get;set;}
    public StudentProcess__c sp{get{
        if(sp==null){
            sp=new StudentProcess__c();
            return sp;
        }else{
            return sp;
        }
    }set;}
    public List<selectoption> TBRequestedMonths{get;set;}
    public String selReqMonths{get;set;}
    
    public TermBreakRequestController(){
        TBRequestedMonths = new List<selectoption>();
        TBRequestedMonths.add(new selectoption('','--None--'));
        TBRequestedMonths.add(new selectoption('1','1 month'));
        TBRequestedMonths.add(new selectoption('2','2 months'));
        TBRequestedMonths.add(new selectoption('3','3 months'));
        
        User u = [select pidm__c, Profile.Name from User where id=:UserInfo.getUserId()];
        string userPidm = u.pidm__c; 
        String usrProfileName = u.Profile.Name;
        
        if(usrProfileName =='Student Profile'){
            //studentInfoList=[select Id,Name,firstname,Lastname,BalanceDue__c,CumulativeSAP__c,PlannedGraduationDate__c,studentID__c,Mentor__c,MentorName__c,Mentor__r.Email,MailingState,MailingCity,Phone from Contact where firstName=:UserInfo.getFirstName() and lastName=:UserInfo.getLastName()  and PIDM__c =:userPidm  limit 1]; 
            studentInfoList=[select Id,Name,firstname,Lastname,BalanceDue__c,CumulativeSAP__c,PlannedGraduationDate__c,studentID__c,Mentor__c,MentorName__c,Mentor__r.Email,MailingState,MailingCity,Phone from Contact where PIDM__c =:userPidm  limit 1]; 
        }else if(stdId == null || stdId =='' ){
            disflag = true;
            stdIdFlag = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You are not a Student.Please enter the student Id below'));
        }
        if(studentInfoList!=null && studentInfoList.size()>0){
            studentInfo=studentInfoList.get(0);
        }
    }
    public PageReference saveTermBreak(){
         try{    
         
           /*Set<String> monthSet = new Set<String>{'1','2','3'};
           String trMonths = String.valueOf(sp.TBRequestedMonths__c).trim();
           if(trMonths!=null && !monthSet.contains(trMonths)){
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please enter 1 or 2 or 3'));
               //msgFlag = false;
               return null;
                 
            }*/
            system.debug('raavimonth =========='+selReqMonths);
            if(selReqMonths  == '' || selReqMonths == null){
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please enter number of months value'));
               return null;
                 
            }
            msgFlag = true;
            if(studentInfo.BalanceDue__c !=null && studentInfo.BalanceDue__c ==true ){ 
              ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Your student account currently shows a balance.  Please check the payment link on your student portal Resources tab, and with questions, contact the Bursar (877-435-7948 ext. 3105).  When the balance is paid, we can discuss your Term Break request.')); 
              msgFlag = false;
              stdIdFlag = false;
            }
            /*if(studentInfo.CumulativeSAP__c !=null && studentInfo.CumulativeSAP__c <50){
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Request Denied - Academic Eligibility'));
               msgFlag = false;  
            }*/
            /*if(sp.TBGradAppSubmitted__c !=null && sp.TBGradAppSubmitted__c  == 'Yes'){
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Congratulations as you prepare to graduate!  Contact your mentor to discuss final requirements.  A Term Break will only delay your graduation.'));
               msgFlag = false;
               stdIdFlag = false;     
            }*/
            
            sp.student__c=studentInfo.Id;
            sp.Name=studentInfo.lastname+','+studentInfo.firstname+' '+'Term Break';
            sp.recordTypeId =  [Select ID from RecordType where DeveloperName='TermBreak' and sObjectType = 'StudentProcess__c' ].id;
            sp.stage__c = 'New';
            sp.Status__c = 'New'; 
            sp.TBRequestedMonths__c=Integer.ValueOf(selReqMonths);
            insert sp;
            
           
            if(msgFlag == true){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Thank you for completing the Term Break Request form. A counselor will contact you within 24 to 48 hours through your WGU email to setup a scheduled counsel call. Please make sure to check your email and respond back quickly so we can better serve you.'));
                stdIdFlag = false;
            
            }
             disFlag=true;
             
            }catch(exception e){
              ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You got some Error'));   
            }
    return null;
    }
    public PageReference cancel(){
         PageReference pf = new PageReference('https://my.wgu.edu'); 
         pf.setRedirect(true); 
         return pf;   
    }
    public PageReference getStudentRecord(){
          if(stdId != null){
                system.debug('raavi2 ==========='+stdId);
                
                studentInfoList=[select Id,Name,firstname,Lastname,BalanceDue__c,CumulativeSAP__c,PlannedGraduationDate__c,studentID__c,Mentor__c,MentorName__c,Mentor__r.Email,MailingState,MailingCity,Phone from Contact where StudentID__c =:stdId]; 
            
            if(studentInfoList == null || studentInfoList.size()==0){
                Integer len=stdId.length();               
                for(integer i=0;i<9-len;i++ ){
                   stdId='0'+stdId;                        
                } 
                system.debug('raavi3 ==========='+stdId);
                studentInfoList=[select Id,Name,firstname,Lastname,BalanceDue__c,CumulativeSAP__c,PlannedGraduationDate__c,studentID__c,Mentor__c,MentorName__c,Mentor__r.Email,MailingState,MailingCity,Phone from Contact where StudentID__c =:stdId]; 
            
            }
            }
            if(studentInfoList == null || studentInfoList.isEmpty()== true){
                stdIdFlag = true;
                
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please enter a valid student Id')); 
                return null;
            }
            if(studentInfoList!=null && studentInfoList.size()>0){
                studentInfo=studentInfoList.get(0);
                disflag = false;
                stdIdFlag = false;
            }
            
         PageReference pf = new PageReference('/apex/TermBreakrequest'); 
         pf.setRedirect(false); 
         return pf;   
    }
    //public void initialize(
    
}