src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/QualityAssurance__c.object
<CustomObject>
    <description>Custom object used for the Registrar Office Quality Assurance processes and reporting.</description>
    <fields>
        <fullName>DateOfAudit__c</fullName>
        <description>Date field that allows a user to select the date in which the audit took place.</description>
        <label>Date of Audit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to a WGU employee</description>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QualityAssurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentProcess__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the student process object</description>
        <label>Student Process</label>
        <referenceTo>StudentProcess__c</referenceTo>
        <relationshipLabel>Quality Assurance</relationshipLabel>
        <relationshipName>QualityAssurance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransferEvaluation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the transfer evaluation object</description>
        <label>Transfer Evaluation</label>
        <referenceTo>TransferEvaluation__c</referenceTo>
        <relationshipLabel>Quality Assurance</relationshipLabel>
        <relationshipName>QualityAssurance2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quality Assurance</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Quality Assurance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Assurance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/StudentProcess__c.object
<CustomObject>
    <description>Custom object to manage student processes by record type.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>Student_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QualityAssurance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quality Assurance</label>
        <referenceTo>QualityAssurance__c</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>Student_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Process</label>
    <nameField>
        <label>Student Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Processes</pluralLabel>
    <recordTypes>
        <fullName>Withdrawal</fullName>
        <active>true</active>
        <description>The record type used to manage the withdrawal process for student records.</description>
        <label>Withdrawal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TransferEvaluation__c.object
<CustomObject>
    <description>A Transfer evaluation is the parent object of the equivalent courses that will given to the student from their transfer work. It controls the overall status and assignment of the evaluation.</description>
    <fields>
        <fullName>AssignedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Transfer_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EvaluationStatus__c</fullName>
        <label>Evaluation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready for Evaluation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appealed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EvaluationType__c</fullName>
        <label>Evaluation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Transfer Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Degree Verification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The Link Between opportunities and transfer evaluations</description>
        <label>CARE Profile Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transfer Evaluations</relationshipLabel>
        <relationshipName>TransferEvaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QualityAssurance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quality Assurance</label>
        <referenceTo>QualityAssurance__c</referenceTo>
        <relationshipLabel>Transfer Evaluations</relationshipLabel>
        <relationshipName>TransferEvaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transfer Evaluation</label>
    <nameField>
        <label>Transfer Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfer Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestQualityAssuranceUtility.cls
@isTest
private with sharing class TestQualityAssuranceUtility{
    
    //Test SearchForSP method
    //Created by Kristin Hasna 2013.12.10
    //Updated by Dave Manwaring 2014.04.15 to fix Kristin's test user.  Changed from "Kristin Hasna" to Profile.Name='System Administrator'
    private static testmethod void testSearchForSP () {
        
        ID spRecordID = [Select Id From RecordType Where SobjectType = 'StudentProcess__c' and Name = 'Withdrawal'].Id;
        ID rTypeId = [Select Id From RecordType Where SobjectType = 'Contact' and Name = 'StudentRecord'].Id;
        
        Contact a = new Contact(LastName='TestName');
        a.RecordTypeId = rTypeId;
        insert a;
        
        System.assert(a.AccountId == null, 'Account creation trigger not working.');
        
        Opportunity o = new Opportunity();
        o.Name = 'Run1';
        o.AccountID = a.Account.id;
        o.StageName = 'Prospect';
        o.CloseDate = Date.today();
        insert o;
        
        Date d = Date.today();
        Integer i;
        List<StudentProcess__c> spinsert = new List<StudentProcess__c>();
        User u = [SELECT ID FROM User WHERE Profile.name='System Administrator' and IsActive=TRUE LIMIT 1];
        for (i = 0; i < 5; i++) {
            StudentProcess__c sp = new StudentProcess__c();
            sp.Account__c=a.AccountId;
            sp.Name='TestMe'+i;
            sp.OwnerId=u.id;
            spinsert.add(sp);
        }
        
        insert spinsert;
        spinsert.clear();
        
        
        QualityAssurance__c qa = new QualityAssurance__c(Employee__c=u.id,DateOfAudit__c=d);
        insert qa;
        
        List<StudentProcess__c> updatedSP = new List<StudentProcess__c>();
        
        System.RunAs(u){
               Test.startTest(); 
        QualityAssuranceUtility.SearchForSP(qa.Employee__c,qa.DateOfAudit__c,qa.id);
        
        updatedSP=[SELECT ID, QualityAssurance__c FROM StudentProcess__c WHERE QualityAssurance__c=:qa.id];
        for(StudentProcess__c sp1: updatedSP) {
            System.assert(sp1.QualityAssurance__c != null, 'Null value found');
        }
        updatedSP.clear();
            
        }
        
        
        for (i = 0; i < 25; i++) {
            StudentProcess__c sp = new StudentProcess__c();
            sp.Account__c=a.AccountId;
            sp.Name='TestAgain'+i;
            sp.OwnerId=u.id;
            spinsert.add(sp);
        }
        
        insert spinsert;
        
        System.RunAs(u) {
        
        QualityAssuranceUtility.SearchForSP(qa.Employee__c,qa.DateOfAudit__c,qa.id);
        
        updatedSP=[SELECT ID, QualityAssurance__c FROM StudentProcess__c WHERE QualityAssurance__c=:qa.id];
        for(StudentProcess__c sp1: updatedSP) {
            System.assert(sp1.QualityAssurance__c != null, 'Null value found');
        }
            Test.stopTest();
        }
    }
    
    //Test SearchForTR method
    private static testmethod void testSearchForTR () {
        
        ID rTypeId = [Select Id From RecordType Where SobjectType = 'Contact' and Name = 'StudentRecord'].Id;
        
        Contact a = new Contact(LastName='TestName');
        a.RecordTypeId = rTypeId;
        insert a;
        
        System.assert(a.AccountId == null, 'Account creation trigger not working.');
        
        Opportunity o = new Opportunity(Name='Run1', AccountID=a.AccountId, StageName='Prospect',CloseDate=Date.today());
        insert o;
        
        Date d = Date.today();
        Integer i;
        List<TransferEvaluation__c> trinsert = new List<TransferEvaluation__c>();
        User u = [SELECT ID FROM User WHERE Profile.name='System Administrator' AND IsActive=TRUE LIMIT 1];
        for (i = 0; i < 5; i++) {
            TransferEvaluation__c tr = new TransferEvaluation__c();
            tr.Opportunity__c=o.id;
            tr.EvaluationType__c='Transfer Evaluation';
            tr.EvaluationStatus__c='Ready for Evaluation';
            tr.Name='TestMe'+i;
            tr.AssignedTo__c=u.id;
            trinsert.add(tr);
        }
        
        insert trinsert;
        trinsert.clear();
        
        
        QualityAssurance__c qa = new QualityAssurance__c(Employee__c=u.id,DateOfAudit__c=d);
        insert qa;
        List<TransferEvaluation__c> updatedTR = new List<TransferEvaluation__c>();
        
        System.RunAs(u) {
            Test.startTest();
        QualityAssuranceUtility.SearchForTR(qa.Employee__c,qa.DateOfAudit__c,qa.id);
        
        updatedTR=[SELECT ID, QualityAssurance__c FROM TransferEvaluation__c WHERE QualityAssurance__c=:qa.id];
        for(TransferEvaluation__c tr1: updatedTR) {
            System.assert(tr1.QualityAssurance__c != null, 'Null value found');
        }
        
            updatedTR.clear();
            
        }
        
        for (i = 0; i < 25; i++) {
            TransferEvaluation__c tr = new TransferEvaluation__c();
            tr.Opportunity__c=o.id;
            tr.EvaluationType__c='Transfer Evaluation';
            tr.EvaluationStatus__c='Ready for Evaluation';
            tr.Name='TestMe'+i;
            tr.AssignedTo__c=u.id;
            trinsert.add(tr);
        }
        
        insert trinsert;
        
        System.RunAs(u) {
            
        QualityAssuranceUtility.SearchForTR(qa.Employee__c,qa.DateOfAudit__c,qa.id);
        
        updatedTR=[SELECT ID, QualityAssurance__c FROM TransferEvaluation__c WHERE QualityAssurance__c=:qa.id];
        for(TransferEvaluation__c tr1: updatedTR) {
            System.assert(tr1.QualityAssurance__c != null, 'Null value found');
        }
            Test.stopTest();
        }
    }
    
    //Test for SearchForCase method
    private static testmethod void testSearchForCase () {
        
        ID CRecordID = [Select Id From RecordType Where SobjectType = 'Case' and Name = 'Withdrawal'].Id;
        ID rTypeId = [Select Id From RecordType Where SobjectType = 'Contact' and Name = 'StudentRecord'].Id;
        
        Contact a = new Contact(LastName='TestName');
        a.RecordTypeId = rTypeId;
        insert a;
        
        System.assert(a.AccountId == null, 'Account creation trigger not working.');
        
        Opportunity o = new Opportunity(Name='Run1', AccountID=a.AccountId, StageName='Prospect',CloseDate=Date.today());
        insert o;
        
        Date d = Date.today();
        Integer i;
        List<Case> cainsert = new List<Case>();
        User u = [SELECT ID FROM User WHERE Profile.Name='System Administrator' AND IsActive=TRUE LIMIT 1];
        for (i = 0; i < 3; i++) {
            Case ca = new Case();
            ca.RecordTypeId=CRecordID;
            ca.Status='New';
            ca.Subject='TestMe'+i;
            ca.OwnerId=u.id;
            cainsert.add(ca);
        }
        for (i = 0; i < 5; i++) {
            Case ca = new Case();
            ca.RecordTypeId=CRecordID;
            ca.Status='Resolved';
            ca.Subject='TestMe'+i;
            ca.OwnerId=u.id;
            cainsert.add(ca);
        }
        
        insert cainsert;
        cainsert.clear();
        
        
        QualityAssurance__c qa = new QualityAssurance__c(Employee__c=u.id,DateOfAudit__c=d);
        insert qa;
        List<Case> updatedCA = new List<Case>();
        
        System.RunAs(u){
            Test.startTest();        
            
        QualityAssuranceUtility.SearchForCase(qa.Employee__c,qa.DateOfAudit__c,qa.id);
        
        updatedCA=[SELECT ID, QualityAssurance__c FROM Case WHERE QualityAssurance__c=:qa.id];
        for(Case ca1: updatedCA) {
            System.assert(ca1.QualityAssurance__c != null, 'Null value found');
        }
        updatedCA.clear();
            
        }
        
        for (i = 0; i < 25; i++) {
            Case ca = new Case();
            ca.RecordTypeId=CRecordID;
            ca.Status='New';
            ca.Subject='TestMe1'+i;
            ca.OwnerId=u.id;
            cainsert.add(ca);
        }
        
        insert cainsert;
        
        System.RunAs(u) {
            
        
        QualityAssuranceUtility.SearchForCase(qa.Employee__c,qa.DateOfAudit__c,qa.id);
        
        updatedCA=[SELECT ID, QualityAssurance__c FROM Case WHERE QualityAssurance__c=:qa.id];
        for(Case ca1: updatedCA) {
            System.assert(ca1.QualityAssurance__c != null, 'Null value found');
        }
            Test.stopTest();
    }
    }
}