src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to the actual Contact record for dereferencing the complete set of Contact fields in formulas and validations</description>
        <inlineHelpText>The student contact field is set automatically when the account record is created or updated</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Contact</relationshipLabel>
        <relationshipName>StudentContact</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CareStatus__c</fullName>
        <label>CARE Status</label>
        <picklist>
            <picklistValues>
                <fullName>PROS – Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PRAP – Prospect Applied Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APNN – Application Incomplete PRAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APIN – Application Incomplete APCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APCO – Application Complete, Unpaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC – Application Complete, Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REDI - Admission Decision Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEND - Additional Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAMT - Auto Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMT – Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTV – Fit and EWB Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLRD - Cleared to Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENRL – Enrolled and Assigned a Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEVR – Never completed EWOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DROP – Dropped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAMT - Not Admitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAYT - Not Admitted Yet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MATR – Matriculated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRAD – Ready for Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALUMNI - Graduated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the CARE Profile Inactive</description>
        <inlineHelpText>This CARE Profile is Inactive.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StopAllContact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Opts the student out of all contact.</description>
        <label>Stop All Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StopEmails__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Opts the student out of emails.</description>
        <label>Stop Emails</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StopPhoneCalls__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Opts the student out of phone calls</description>
        <label>Stop Dialer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>StudentContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CARE Profile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/CAREforceScheduledStatusUpdate.cls
global class CAREforceScheduledStatusUpdate implements Schedulable {
    private static String CRON_EXP = '0 0 5 * * ?'; // Run every day at 5 AM.

    global static void schedule() {
        System.schedule('CARE Status Update', CRON_EXP, new CAREforceScheduledStatusUpdate());
    }


    global void execute(SchedulableContext sc) {
        List<Opportunity> opps = [SELECT Id, CAREStatus__c, Account.StudentContact__r.Status__c, Inactive__c, StopEmails__c, StopAllContact__c, StopPhoneCalls__c 
                                     FROM Opportunity WHERE 
                                        (CAREStatus__c LIKE 'CLRD%' AND CloseDate = THIS_MONTH AND Account.StudentContact__r.Status__c = 'AS') OR 
                                        (CAREStatus__c LIKE 'ENRL%' AND CloseDate = LAST_MONTH AND Account.StudentContact__r.Status__c = 'AS') OR
                                        (CAREStatus__c LIKE 'MATR%' AND Account.StudentContact__r.Status__c IN ('WI', 'DD', 'DR', 'IG'))
                                     LIMIT 10000];
        
        for (Opportunity opp : opps) {
            if (opp.CAREStatus__c.startsWith('CLRD')) {
                opp.CAREStatus__C = 'ENRL – Enrolled and Assigned a Mentor';
                continue;
            }
            
            if (opp.CAREStatus__c.startsWith('ENRL')) {
                opp.CAREStatus__C = 'MATR – Matriculated';
                continue;
            }
            
            if (opp.CAREStatus__c.startsWith('MATR') && opp.Account.StudentContact__r.Status__c == 'IG') {
                opp.CAREStatus__C = 'GRAD – Ready for Graduation';         
                continue;     
            }
            
            if (opp.CAREStatus__c.startsWith('MATR') && 
                (opp.Account.StudentContact__r.Status__c == 'WI' || opp.Account.StudentContact__r.Status__c == 'DD' || opp.Account.StudentContact__r.Status__c == 'DR')) {
                opp.CAREStatus__C = 'DROP – Dropped';  
                opp.Inactive__c = true;
                opp.StopEmails__c = true;
                opp.StopAllContact__c = true;
                opp.StopPhoneCalls__c = true;
                continue;            
            }                      
        }
        
        update opps;        
    }
}