src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to the actual Contact record for dereferencing the complete set of Contact fields in formulas and validations</description>
        <inlineHelpText>The student contact field is set automatically when the account record is created or updated</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Contact</relationshipLabel>
        <relationshipName>StudentContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>StudentContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CARE Profile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>IntakeInterviewReady</fullName>
        <active>true</active>
        <businessProcess>Intake</businessProcess>
        <label>IntakeInterviewReady</label>
    </recordTypes>
</CustomObject>

src/objects/StudentTranscript__c.object
<CustomObject>
    <description>Object to manage the transcripts that must be collected through in-take and viewed by Mentors</description>
    <fields>
        <fullName>CollegeEndDate__c</fullName>
        <description>Date you stopped attending class</description>
        <label>College End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CollegeStartDate__c</fullName>
        <description>Date you started attending class</description>
        <label>College Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact of the student</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Transfer Institution</relationshipLabel>
        <relationshipName>StudentTransferInstitution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Student Transfer Institution</relationshipLabel>
        <relationshipName>opportunityTransferInstitution</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <formula>Opportunity__r.Account.PIDM__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PIDM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TranscriptInstitution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transcript Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Student Transfer Institution (Transcript Institution)</relationshipLabel>
        <relationshipName>SchoolTranscripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Transfer Institution</label>
    <nameField>
        <displayFormat>Institution-{0000}</displayFormat>
        <label>Student Transfer Institution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transfer Institution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestIntakeInterviewFlowController.cls
/*****************************************************************************************
* Name: IntakeInterviewFlowController
* Author: Will Slade
* Purpose: Test IntakeInterviewFlowController
* Revisions: 
*    - 6/1/12 Created Class
*    - 1/24/13 Updated for person account refactor
******************************************************************************************/

@isTest
Public class TestIntakeInterviewFlowController 
{
    @IsTest
    public static void testIntakeInterviewFlowController() 
    { 
             
        /*Account student = new Account( Status__pc='AS', pidm__c='QA002233', pidm__pc='QA002233', firstName='Dudley', personEmail='FEEmailTest@test.com', personMailingState='UT', LastName='StudleyIntake', RecordTypeId = [Select Id from RecordType where Name = 'Student Account' and SObjectType = 'Account'].id );
        insert student;
        student = [Select Id, MentorPidm__pc, Mentor__pc, StudentMentor__pc, FirstName, LastName, PersonEmail, PersonContactId, RecordTypeId, Pidm__c, StudentContact__c, isPersonAccount, PersonMailingState, Status__pc from Account where ID = :student.Id LIMIT 1].get(0);
        */
        Contact newContact = new Contact(Status__c='AS', Pidm__c='QA002233', FirstName='Dudley', LastName='FEEmailTest',
                                         RecordTypeId = [Select Id from RecordType where Name = 'StudentRecord' and SObjectType = 'Contact'].id);
        insert newContact;
        
        newContact = [SELECT Id, Status__c, Pidm__c, FirstName, LastName, Account.Id FROM Contact WHERE Id = :newContact.Id LIMIT 1];
        Account newAccount = [SELECT Id, Pidm__c, StudentContact__c FROM Account WHERE Id = :newContact.Account.Id];              
        
        System.assert( newContact.AccountId != null && newContact.AccountId == newAccount.Id );
        
        System.assert( newAccount.id != null );
        System.assert( newContact != null && newContact.id != null );
        System.assert( newContact.pidm__c == newAccount.pidm__c );                    
        
        System.assertEquals(newAccount.StudentContact__c, newContact.Id);
        
        Account Institution = new Account (Name='DCS University', RecordTypeId = [Select Id from RecordType where Name = 'Institution of Higher Ed' and SObjectType = 'Account'].id);
        insert Institution;
        Institution = [Select Id, Name from Account where ID = :Institution.Id LIMIT 1].get(0);
        
        Opportunity care = new Opportunity(AccountId=newAccount.Id, Name='Dudley Schults', CloseDate=date.today(), StageName='Intake', RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
        insert care;
        care = [select id, AccountId from Opportunity where id = :care.id];
        
        StudentTranscript__c transcript = new StudentTranscript__c (Opportunity__c=care.id, CollegeEndDate__c=date.today(), CollegeStartDate__c=date.today(), Contact__c=newAccount.StudentContact__c, TranscriptInstitution__c=Institution.Id);
        insert transcript;
        
        System.assert(transcript.Opportunity__c != null);
        System.assertEquals(transcript.Opportunity__c, care.Id);
               
        PageReference pageTest0 = Page.IntakeInterview;
        pageTest0.getParameters().put('Id',null);
        Test.setCurrentPage(pageTest0);
        ApexPages.Standardcontroller stdcon0 = new ApexPages.Standardcontroller(care);
        IntakeInterviewFlowController con = new IntakeInterviewFlowController(stdcon0);

        PageReference pageTest1 = Page.IntakeInterview;
        pageTest1.getParameters().put('Id',care.id);
        Test.setCurrentPage(pageTest1);
        
        List<StudentTranscript__c> transcripts = con.getMyTranscripts();
        Opportunity testOpp = con.getTestOpp();
        
        System.assert(testOpp.Id != null);
        System.assertEquals(testOpp.Id, care.Id);
        //System.assert(transcripts.size() == 1);
        //System.assert(transcripts.get(0).Contact__c == newAccount.StudentContact__c);
    }
}