src/objects/ADAFile__c.object
<CustomObject>
    <description>Contains information about student ADA self-disclosure and requests. This object contains sensitive student information and should only be available to the ADA coordinator and Director of Student Services.</description>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ADAFiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Student Feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed Pending Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Appeal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ADA File</label>
    <nameField>
        <label>ADA File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADA Files</pluralLabel>
    <recordTypes>
        <fullName>Referral</fullName>
        <active>true</active>
        <description>Record type used for internal staff ADA referrals.</description>
        <label>Referral</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/ADAFormController.cls
public with sharing class ADAFormController {
    public ADAFile__c studentInfo {get;set;}
    //public String 
    public String confirm {get;set;}
    public Boolean flag {get;set;}
    
    public ADAFormController(ApexPages.StandardController acon){
        studentInfo = new ADAFile__c();
        flag= true;
    }
    public PageReference submit(){
        List<RecordType> rType = [SELECT ID FROM RecordType WHERE SobjectType='ADAFile__c' AND name = 'Referral' LIMIT 1];
        ID rTypeID = rType[0].ID;
        try{
            studentInfo.Status__c = 'Requested';
            studentInfo.RecordTypeId = rTypeID;
            studentInfo.Referrer__c = UserInfo.getUserId();
            studentInfo.Name = studentInfo.LastName__c+ ' , '+studentInfo.FirstName__c;
            insert studentInfo;
            //confirm = 'yes';
            flag= false;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Your ADA Referral Form has been submitted.'));      
            
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You got an error.Please contact your Administrator.'));      
        }
    return null;
    }
    public PageReference cancel(){
            PageReference pf = new PageReference('/home/home.jsp'); 
            pf.setRedirect(true); 
            return pf;
    }
    public PageReference homepage(){
            PageReference pf = new PageReference('https://my.wgu.edu'); 
            pf.setRedirect(true); 
            return pf;
    }
    
}