src/objects/ArticleCourseVersionLink__c.object
<CustomObject>
    <description>Each record in this object links a knowledge article version id to a course version id</description>
    <fields>
        <fullName>ArticleType__c</fullName>
        <label>Article Type</label>
        <picklist>
            <picklistValues>
                <fullName>Welcome Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Getting Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course At-a-Glance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CourseOfStudyId__c</fullName>
        <formula>WGUCourseVersion__r.CourseOfStudyId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course of Study ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Article CourseVersion Links</relationshipLabel>
        <relationshipName>Article_CourseVersion_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Article CourseVersion Link</label>
    <nameField>
        <displayFormat>ACV-{000000}</displayFormat>
        <label>ACV Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article CourseVersion Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CourseArticle__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>ArticleType__c</fullName>
        <label>Article Type</label>
        <picklist>
            <picklistValues>
                <fullName>Welcome Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Getting Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Resource Navigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course At-a-Glance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RichTextArea__c</fullName>
        <label>Rich Text Area</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Course Article</label>
    <pluralLabel>Course Articles</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IsEmployee__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this user is an employee please check this</description>
        <inlineHelpText>Checked if this user is an employee</inlineHelpText>
        <label>IsEmployee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsInMentorPilot__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this person is a member of the mentor pilot.</description>
        <label>Is In Mentor Pilot</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>MajorVersion__c</fullName>
        <label>Major Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PAMSID__c</fullName>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <fields>
        <fullName>CourseOfStudyId__c</fullName>
        <description>The ID for the course of study associated with this WGUCourseVersion.  Relationship is 1 to 1 WGUCourseVersion to Course Of Study</description>
        <label>Course Of Study ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MajorVersion__c</fullName>
        <description>The major version of the course</description>
        <label>Major Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The course that this course version belongs to</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>WGU Course Versions</relationshipLabel>
        <relationshipName>WGUCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>title__c</fullName>
        <label>title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCourseArticleUtility.cls
@isTest
public class TestCourseArticleUtility {
	public static testMethod void testValidatePublishArticle() {
		User mentorUser = TestCourseArticleHelper.getTestUser('testmentor', 'Mentor', true);
		System.runAs(mentorUser) {
			List<CourseArticle__kav> courseArticleNoLink = TestCourseArticleHelper.createCourseArticle(1);
			//missing type, summary, rich text 
			system.assert(!CourseArticleUtility.validatePublishArticle(courseArticleNoLink[0], 'courseVersionIds', null));
			
			//Testing messages, all errors
			String[] validationMsgs = new String[] {};
			system.assert(!CourseArticleUtility.validatePublishArticle(courseArticleNoLink[0], null, validationMsgs));
			system.assertEquals(4, validationMsgs.size());
			
			CourseArticle__kav courseArticle = TestCourseArticleHelper.createCourseArticleFull('Test Article', 
					Schema.SObjectType.CourseArticle__kav.fields.ArticleType__c.getPickListValues()[0].getValue(),
					Schema.SObjectType.CourseArticle__kav.fields.FileUpload__ContentType__s.getPickListValues()[0].getValue(), 'Test Course');
					
			//Pass Validation
			courseArticle.articleType__c = 'Unit Test Type';
			courseArticle.Summary = 'Unit Test Summary';
			courseArticle.RichTextArea__c = 'Unit Test Rich Text';
			system.assert(CourseArticleUtility.validatePublishArticle(courseArticle));
		}
	}
	
    public static User init() {
        User testUser;
        Profile systemProfileId = [SELECT Id FROM Profile WHERE Name Like 'System Administrator' LIMIT 1];
        list<User> user1 = [SELECT Id FROM User WHERE ProfileId=:systemProfileId.id AND IsActive=true LIMIT 1]; 
        if (user1.size() > 0){
            System.runAs(user1[0]){ 
    
                // Get Mentor Profile Id
                Profile p = [SELECT Id FROM Profile WHERE Name='Mentor']; 
                // Get Course Mentor Role Id
                UserRole r = [SELECT Id FROM UserRole WHERE Name='Course Mentor'];+
                // Create Test User
                testUser = new User(Alias = 'testUser', Email='testuser@wgu.edu', 
                    EmailEncodingKey='UTF-8', UserRoleId = r.Id, LastName='Testing', LanguageLocaleKey='en_US', 
                    LocaleSidKey='en_US', ProfileId = p.Id, PIDM__c = 'a1b2c3', IsEmployee__c = true, IsInMentorPilot__c = true,
                    TimeZoneSidKey='America/Denver', UserName='testuser@wgu.edu', IsActive=true,
                    UserPermissionsKnowledgeUser=true, UserPermissionsSFContentUser=true, UserPermissionsMobileUser=true);
                insert testUser;
                // Get Permission Set Id
                PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'KnowledgeBaseUsers'];
                // Assign Test User to Permission Set
                PermissionSetAssignment psa = new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps.Id);
                insert psa;
            }
        }
        return testUser;
    }
    
    //--------------------------------------------------------------------------
    // Helper methods for creating objects
    //--------------------------------------------------------------------------
    public static WGUCourse__c newCourse(String name, Decimal pamsid) {
        return new WGUCourse__c(Name = name, PAMSID__c = pamsid);
    }

    public static WGUCourseVersion__c newCourseVersion(String name, Id courseId, Decimal courseofstudyid, Decimal majorversion, string title) {
        return new WGUCourseVersion__c(Name = name, CourseOfStudyId__c = courseofstudyid, MajorVersion__c = majorversion, Title__c = title);
    }
    public static CourseArticle__kav newCourseArticle(String title, String summary, String articletype, String richtextfield, String urlname) {
        return new CourseArticle__kav(Title = title, Summary = summary, ArticleType__c = articletype, RichTextArea__c = richtextfield, UrlName = urlname);
    }
    public static ArticleCourseVersionLink__c newArticleCVL(Id courseversion, Id articleversionid) {
        return new ArticleCourseVersionLink__c(WGUCourseVersion__c = courseversion, KnowledgeArticleVersionId__c = articleversionid);
    }

}