src/objects/ArticleCourseVersionLink__c.object
<CustomObject>
    <description>Each record in this object links a knowledge article version id to a course version id</description>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Article CourseVersion Links</relationshipLabel>
        <relationshipName>Article_CourseVersion_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Article CourseVersion Link</label>
    <nameField>
        <displayFormat>ACV-{000000}</displayFormat>
        <label>ACV Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article CourseVersion Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KnowledgeBaseReporting__c.object
<CustomObject>
    <description>This object is used to report on KB.</description>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Article version id&apos;s from knowledge base (kav objects)</description>
        <externalId>true</externalId>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Knowledge Base Reporting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>KB Reporting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Base Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KnowledgeBaseWguCourseVersionLink__c.object
<CustomObject>
    <description>Junction object between a Knowledge Article Reporting (Knowledge Article) and Course Versions</description>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <externalId>true</externalId>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KnowledgeBaseReporting__c</fullName>
        <label>Knowledge Base Reporting</label>
        <referenceTo>KnowledgeBaseReporting__c</referenceTo>
        <relationshipLabel>WGU Course Version</relationshipLabel>
        <relationshipName>Knowledge_Article_Course_Version_Link</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Knowledge Base Reporting</relationshipLabel>
        <relationshipName>Knowledge_Article_Course_Version_Link</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Knowledge Base WGU Course Version Link</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Knowledge Base WGU Course Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Base WGU Course Version Link</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KnowledgeBaseCourseVersionBatchUtility.cls
/*
*Author John Chan
*Slalom
Migrate from old ArticleCourseVersionLink__c to new junction object.  This should only be need to ran once or twice to migrate the data over.
*/
global with sharing class KnowledgeBaseCourseVersionBatchUtility implements Database.Batchable<sObject>{
	private final String query = 'SELECT KnowledgeArticleVersionId__c, WGUCourseVersion__c FROM ArticleCourseVersionLink__c';
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope){
		Map<String, Id> knowledgeBaseReportMap = new Map<String, Id>();
		for (KnowledgeBaseReporting__c kbReport : [SELECT Id, KnowledgeArticleVersionId__c FROM KnowledgeBaseReporting__c]) {
			knowledgeBaseReportMap.put(kbReport.KnowledgeArticleVersionId__c, kbReport.Id);
		}
		
		Set<String> knoweldgeBaseCourseVersionLinkIds = new Set<String>();
		for (KnowledgeBaseWguCourseVersionLink__c kbCourseVersionLink : [SELECT KnowledgeArticleVersionId__c, WGUCourseVersion__c FROM KnowledgeBaseWguCourseVersionLink__c]) {
			knoweldgeBaseCourseVersionLinkIds.add(kbCourseVersionLink.KnowledgeArticleVersionId__c + kbCourseVersionLink.WGUCourseVersion__c);
		}
		
		List<KnowledgeBaseWguCourseVersionLink__c> knowledgeBaseCourseVersionLinkUpdates = new List<KnowledgeBaseWguCourseVersionLink__c>();
		for (ArticleCourseVersionLink__c articleCourseLink : ((List<ArticleCourseVersionLink__c>)scope)) {
			//Check to make sure neither Id's are empty and that it does not exist already in the new junction object
			if ((string.isNotEmpty(articleCourseLink.KnowledgeArticleVersionId__c) && articleCourseLink.WGUCourseVersion__c != null) && (knoweldgeBaseCourseVersionLinkIds.size() == 0 
					|| !knoweldgeBaseCourseVersionLinkIds.contains(articleCourseLink.KnowledgeArticleVersionId__c + articleCourseLink.WGUCourseVersion__c))) {
				if (knowledgeBaseReportMap.get(articleCourseLink.KnowledgeArticleVersionId__c) != null) {
					KnowledgeBaseWguCourseVersionLink__c knowledgeBaseCourseVersion = new KnowledgeBaseWguCourseVersionLink__c();
					knowledgeBaseCourseVersion.KnowledgeArticleVersionId__c = articleCourseLink.KnowledgeArticleVersionId__c;
					knowledgeBaseCourseVersion.WGUCourseVersion__c = articleCourseLink.WGUCourseVersion__c;
					knowledgeBaseCourseVersion.KnowledgeBaseReporting__c = knowledgeBaseReportMap.get(articleCourseLink.KnowledgeArticleVersionId__c);
					knowledgeBaseCourseVersionLinkUpdates.add(knowledgeBaseCourseVersion);
				} else {
					system.debug('cannot find knoweldgeArticleVersionId in reporting table for Id: ' + articleCourseLink.KnowledgeArticleVersionId__c);
				}
			}
		}
		
		insert knowledgeBaseCourseVersionLinkUpdates;
	}

	global void finish(Database.BatchableContext BC){
   	}
}