src/objects/ArticleCourseVersionLink__c.object
<CustomObject>
    <description>Each record in this object links a knowledge article version id to a course version id</description>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Article CourseVersion Links</relationshipLabel>
        <relationshipName>Article_CourseVersion_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Article CourseVersion Link</label>
    <nameField>
        <displayFormat>ACV-{000000}</displayFormat>
        <label>ACV Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article CourseVersion Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CourseArticle__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Course Article</label>
    <pluralLabel>Course Articles</pluralLabel>
</CustomObject>

src/objects/KnowledgeBaseReporting__c.object
<CustomObject>
    <description>This object is used to report on KB.</description>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Article version id&apos;s from knowledge base (kav objects)</description>
        <externalId>true</externalId>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Knowledge Base Reporting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>KB Reporting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Base Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KnowledgeBaseWguCourseVersionLink__c.object
<CustomObject>
    <description>Junction object between a Knowledge Article Reporting (Knowledge Article) and Course Versions</description>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <externalId>true</externalId>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KnowledgeBaseReporting__c</fullName>
        <label>Knowledge Base Reporting</label>
        <referenceTo>KnowledgeBaseReporting__c</referenceTo>
        <relationshipLabel>WGU Course Version</relationshipLabel>
        <relationshipName>Knowledge_Article_Course_Version_Link</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Knowledge Base Reporting</relationshipLabel>
        <relationshipName>Knowledge_Article_Course_Version_Link</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Knowledge Base WGU Course Version Link</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Knowledge Base WGU Course Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Base WGU Course Version Link</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestKnowledgeBaseCourseVersionBatchUtil.cls
/*
*Author John Chan
*Slalom
*/
@isTest
private with sharing class TestKnowledgeBaseCourseVersionBatchUtil {
	public static testMethod void test() {
		List<KnowledgeBaseReporting__c> kbReports = TestCourseArticleHelper.createKnowledgeBaseReporting(3);
		List<CourseArticle__kav> courseArticles = TestCourseArticleHelper.createCourseArticleLink(kbReports);
		List<WGUCourseVersion__c> courseVersions = TestCourseArticleHelper.createCourseVersions(3, 'TestCourse');
		List<ArticleCourseVersionLink__c> articleCourseVersionLinks = new List<ArticleCourseVersionLink__c>();
		for (integer i = 0; i < 2; i++) {
			ArticleCourseVersionLink__c link = new ArticleCourseVersionLink__c();
			link.WGUCourseVersion__c = courseVersions.get(i).Id;
			link.KnowledgeArticleVersionId__c = courseArticles.get(i).Id;
			articleCourseVersionLinks.add(link);
		}
		upsert articleCourseVersionLinks;
		
		List<KnowledgeBaseWguCourseVersionLink__c> kbCourseVersionLinks = [SELECT Id FROM KnowledgeBaseWguCourseVersionLink__c];
		System.assertEquals(0, kbCourseVersionLinks.size());
		
		Test.startTest();
		KnowledgeBaseCourseVersionBatchUtility kbBatch = new KnowledgeBaseCourseVersionBatchUtility();
		Database.executeBatch(kbBatch);
		Test.stopTest();
		
		kbCourseVersionLinks = [SELECT Id FROM KnowledgeBaseWguCourseVersionLink__c];
		System.assertEquals(articleCourseVersionLinks.size(), kbCourseVersionLinks.size());
	}
}