src/objects/AtRiskStudent__c.object
<CustomObject>
    <description>Contains Student At Risk data.</description>
    <fields>
        <fullName>ActivityConcerns__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Concerns</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastTotalRiskCount__c</fullName>
        <label>Last Total Risk Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LastTrendUpdated__c</fullName>
        <label>Last Trend Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ObjectiveFailCount__c</fullName>
        <label>Objective Assessment Fail Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PastEndDateCount__c</fullName>
        <label>Past End Date Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PerformanceFailCount__c</fullName>
        <label>Performance Assessment Fail Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RiskTrend__c</fullName>
        <label>Risk Trend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StudentDisplayName__c</fullName>
        <label>Student Display Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentName__c</fullName>
        <label>Student Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>At Risk Students</relationshipLabel>
        <relationshipName>At_Risk_Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalRiskCount__c</fullName>
        <label>Total Risk Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>At Risk Student</label>
    <nameField>
        <label>At Risk Student PIDM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>At Risk Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CurrentTermEnrolledCUs__c</fullName>
        <label>Current Term Enrolled CUs</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrentTerm__c</fullName>
        <description>Current Term for the student, this is wgu foramtted</description>
        <label>Current Term</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>Student Identification number, also known as Banner ID.</description>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TermCode__c</fullName>
        <description>The current TERM Code year + month</description>
        <formula>TEXT(YEAR(TermStartDate__c))  &amp; 
IF(MONTH(TermStartDate__c) &lt; 10, &apos;0&apos;, NULL) &amp;
TEXT(Month( TermStartDate__c ))</formula>
        <inlineHelpText>Term Code</inlineHelpText>
        <label>Term Code</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The mentor pidm so we can use external id&apos;s</description>
        <externalId>true</externalId>
        <inlineHelpText>The WGU PIDM assigned to this mentor.</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentCompletionTask__c.object
<CustomObject>
    <description>Custom object to manage student assessments, requirements, and zero CU tasks by recordtype.</description>
    <fields>
        <fullName>LastFailedAssessmentAttemptDate__c</fullName>
        <description>The date of the most recent failed objective assessment attempt.</description>
        <label>Last Failed Assessment Attempt Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NumberFailedAssessmentAttempts__c</fullName>
        <description>Contains a count of the number of times a student has failedthe objective assessment for the course.</description>
        <label>Number of Failed Assessment Attempts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequirementComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requirement Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>StudentAssessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TermCode__c</fullName>
        <label>Term Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Student Completion Task</label>
    <nameField>
        <label>Student Task Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Completion Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentCourseRegistration__c.object
<CustomObject>
    <description>This is an object for pulling current term registration  information from WGUFDP. No FDP user should have direct access to this Object,</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The student associated with this registration. (used to speed up queries on this table)</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>StudentCourseRegistrations</relationshipLabel>
        <relationshipName>StudentCourseRegistrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Termcode__c</fullName>
        <label>Termcode</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>enddate__c</fullName>
        <label>enddate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pidm__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for referential integrity</description>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>pidm</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student Course Registration</label>
    <nameField>
        <label>StudentCourseRegistration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Course Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentCourseVersion__c.object
<CustomObject>
    <description>The version of a course that the student is set to take (or has taken).</description>
    <fields>
        <fullName>EnrollTermCode__c</fullName>
        <description>The term code that the course was enrolled in.</description>
        <label>Enroll Term Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentCourseRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Course Registration</label>
        <referenceTo>StudentCourseRegistration__c</referenceTo>
        <relationshipLabel>Student Course Versions</relationshipLabel>
        <relationshipName>StudentCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Course Version</relationshipLabel>
        <relationshipName>StudentCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Course Version</label>
    <nameField>
        <label>Studentid+&apos;-&apos;+Wgucourseid</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TaskStreamAssessment__c.object
<CustomObject>
    <description>Data for a Task Stream Assessment that a student is enrolled</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Task_Stream_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Taskstream Assessment</label>
    <nameField>
        <label>Task Stream Assessment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taskstream Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TaskStreamTaskFailure__c.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Task Stream Task Failures</relationshipLabel>
        <relationshipName>TaskStreamTaskFailures</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Stream Task Failure</label>
    <nameField>
        <label>Task Stream Assessment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Stream Task Failures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/WGUStudentNote__c.object
<CustomObject>
    <description>This object stores notes about a student&apos;s interaction with service personnel such as mentors, etc.</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>The contact record for this student</description>
        <inlineHelpText>The student associated with this note.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>WGUStudentNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>WGU Student Note</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGUStudentNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WGUStudentPerformanceSurvey__c.object
<CustomObject>
    <description>Answers to student performance survey questions, completed by student mentors via the student notes UI. NOTE: The Labels are different than the Object Name to match verbiage of the Notes.</description>
    <fields>
        <fullName>GoalPerformanceSinceLastCall__c</fullName>
        <inlineHelpText>How has student performed against academic goals set in the last call?</inlineHelpText>
        <label>Goal Performance Since Last Call</label>
        <picklist>
            <picklistValues>
                <fullName>Yes - 100%</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No - 0%</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Student (Contact) whose WGUStudentNote__c record is associated with this Performance Survey Record (1:1)</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>WGUStudentPerformanceSurveys</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUStudentNote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WGUStudentNote</label>
        <referenceTo>WGUStudentNote__c</referenceTo>
        <relationshipName>WGUStudentPerformanceSurveys</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Student Performance Question</label>
    <nameField>
        <label>Note Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Performance Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestStudentsAtRiskContoller.cls
/*
Author Katarina Melki 
Western Governer University
8/9/2013

Test class for StudentsAtRiskController class.
*/
@IsTest
private class TestStudentsAtRiskContoller
{
    //Function to create student test data
    static private Set<Id> setupTestStudents()
    {
        List<Contact> contacts=Test.loadData(Contact.sObjectType, 'ContactTestData');
        String testTerm=String.valueOf(Date.today().year());
        
        if (Date.today().month()<10)
        {
            testTerm=testTerm+'0'+String.valueOf(Date.today().month());
        }
        else
        {
            testTerm=testTerm+String.valueOf(Date.today().month());
        }
        
        contacts[0].CurrentTerm__c=testTerm;
        contacts[1].CurrentTerm__c=testTerm;
        contacts[0].CurrentTermEnrolledCUs__c=4;
        contacts[1].CurrentTermEnrolledCUs__c=4;
        update contacts;
        
        List<WGUStudentNote__c> Notes=new List<WGUStudentNote__c>();
        Notes.add(new WGUStudentNote__c(Student__c=contacts[0].Id));
        Notes.add(new WGUStudentNote__c(Student__c=contacts[1].Id));
        insert Notes;
        
        //Setup test data for student 1
        AtRiskStudent__c ExistingAtRisk=new AtRiskStudent__c(Name=contacts[0].PIDM__c, ActivityConcerns__c=true, LastTotalRiskCount__c=2, LastTrendUpdated__c=Date.today().addDays(-3), ObjectiveFailCount__c=1, PastEndDateCount__c=1, PerformanceFailCount__c=1, RiskTrend__c=0, Student__c=contacts[0].Id, StudentDisplayName__c=contacts[0].LastName+', '+contacts[0].FirstName, StudentName__c=contacts[0].FirstName+' '+contacts[0].LastName, StudentID__c='0001111', TotalRiskCount__c=4);
        List<WGUStudentPerformanceSurvey__c> PerformanceSurveys=new List<WGUStudentPerformanceSurvey__c>();
        PerformanceSurveys.add(new WGUStudentPerformanceSurvey__c(Student__c=contacts[0].Id, WGUStudentNote__c=[select Id from WGUStudentNote__c where Student__c=:contacts[0].Id Limit 1].Id, GoalPerformanceSinceLastCall__c='Yes - 100%'));
        PerformanceSurveys.add(new WGUStudentPerformanceSurvey__c(Student__c=contacts[0].Id, WGUStudentNote__c=[select Id from WGUStudentNote__c where Student__c=:contacts[0].Id Limit 1].Id, GoalPerformanceSinceLastCall__c='Partially Met'));
        PerformanceSurveys.add(new WGUStudentPerformanceSurvey__c(Student__c=contacts[0].Id, WGUStudentNote__c=[select Id from WGUStudentNote__c where Student__c=:contacts[0].Id Limit 1].Id, GoalPerformanceSinceLastCall__c='No - 0%'));
        PerformanceSurveys.add(new WGUStudentPerformanceSurvey__c(Student__c=contacts[0].Id, WGUStudentNote__c=[select Id from WGUStudentNote__c where Student__c=:contacts[0].Id Limit 1].Id, GoalPerformanceSinceLastCall__c='No - 0%'));
        PerformanceSurveys.add(new WGUStudentPerformanceSurvey__c(Student__c=contacts[0].Id, WGUStudentNote__c=[select Id from WGUStudentNote__c where Student__c=:contacts[0].Id Limit 1].Id, GoalPerformanceSinceLastCall__c='No - 0%'));
        
        //Setup test data for student 2
        PerformanceSurveys.add(new WGUStudentPerformanceSurvey__c(Student__c=contacts[1].Id, WGUStudentNote__c=[select Id from WGUStudentNote__c where Student__c=:contacts[1].Id Limit 1].Id, GoalPerformanceSinceLastCall__c='Yes - 100%'));
        StudentCourseRegistration__c tempReg=new StudentCourseRegistration__c(pidm__c=contacts[1].PIDM__c, enddate__c=Date.today().addDays(-10), Student__c=contacts[1].Id, Termcode__c='test123');
        insert tempReg;
        
        StudentCourseVersion__c StudentCourse=new StudentCourseVersion__c(Student__c=contacts[1].Id, StudentCourseRegistration__c=[select Id from StudentCourseRegistration__c where Termcode__c='test123' Limit 1].Id, EnrollTermCode__c=testTerm);
        StudentCompletionTask__c CompletionTask=new StudentCompletionTask__c(Student__c=contacts[1].Id, LastFailedAssessmentAttemptDate__c=Date.today(), NumberFailedAssessmentAttempts__c=4, RequirementComplete__c=false, TermCode__c=testTerm);
        TaskStreamAssessment__c tempTask=new TaskStreamAssessment__c(AssessmentCode__c='Test1', AssessmentIDKey__c=123456, OverallStatus__c='IP', pidm__c=contacts[1].PIDM__c, Student__c=contacts[1].Id);
        insert tempTask;
        
        TaskStreamTaskFailure__c TaskStreamFailure=new TaskStreamTaskFailure__c(AssessmentIDKey__c=123456, TaskFailureKey__c=123456, pidm__c=contacts[1].PIDM__c, Student__c=contacts[1].Id, LastFailedAttempt__c=Date.today(), NumberFailedAttempts__c=4, TaskTitle__c='Test stuff', TaskStreamAssessment__c=[select Id from TaskStreamAssessment__c where AssessmentIDKey__c=123456 and AssessmentCode__c='Test1'].Id, TaskStartDate__c=Date.today());
        
        //Insert test data for both students
        insert ExistingAtRisk;
        insert PerformanceSurveys;
        insert StudentCourse;
        insert CompletionTask;
        insert TaskStreamFailure;
        
        Set<Id> students=new Set<Id>();
        students.add(contacts[0].Id);
        students.add(contacts[1].Id);
        
        return students;
    }
    
    //Tests StudentsAtRiskController.generateAtRisk
	static testmethod void testAtRiskCreation()
    {
        String environment = TestStudentUser.getEnvironment();
        
        Set<Id> students=setupTestStudents();
        
        Test.startTest();
        	StudentsAtRiskController.generateAtRisk(students);
        Test.stopTest();
        
        System.assert([select id from AtRiskStudent__c where Student__c in :students].size()==2);
    }
    
    //StudentsAtRiskController.getAtRiskRecords
    static testmethod void testAtRiskRetrieval()
    {
        String environment = TestStudentUser.getEnvironment();
        
        //Setup mentor
        Profile prof = [SELECT id from profile where name = 'Lockdown'];
        Profile mentorProfile = [select ID from Profile where Name='Mentor'];
        UserRole mentorRole = [select ID from UserRole where Name='Mentor'];
        
        User testUser=new User(LastName='Mentor', FirstName='Standard', pidm__c='123123', Username='a@wgu.edu', Email='a@wgu.edu', Alias='a', CommunityNickname='a', TimeZoneSidKey='GMT', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', ProfileId=prof.ID, LanguageLocaleKey='en_US');
        insert testUser;
        
        Id MentorId=[select Id from User where pidm__c='123123' and Username='a@wgu.edu' Limit 1].Id;
        
        //Setup students
        Set<Id> students=setupTestStudents();
        
        List<Contact> studentContacts=[select Id from Contact where Id in :students];
        for (Contact studentContact :studentContacts)
        {
            studentContact.Mentor__c=MentorId;
        }
        update studentContacts;
        
        String AtRisk;
        
        Test.startTest();
        	AtRisk=StudentsAtRiskController.getAtRiskRecords(MentorId);
        Test.stopTest();
        
        //List<AtRiskStudent__c> AtRiskList=JSON.deserialize(AtRisk);
        
        system.assert(AtRisk!=null);
        
    }
}