src/objects/Campus__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Represents a mapping from various systems to the campus code used by Banner.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The value that will go into the Contact.Campus__c field.</description>
        <inlineHelpText>The value that will go into the Contact.Campus__c field.</inlineHelpText>
        <label>Contact</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAttributes__c</fullName>
        <description>The value that will go into the StudentAttributes__c.Affiliation__c field.</description>
        <inlineHelpText>The value that will go into the StudentAttributes__c.Affiliation__c field.</inlineHelpText>
        <label>Student Attributes</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Campus</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BannerReady__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator to be updated from a Opportunity/CAREProfile when the correct status has been reached to begin updating Banner from Contact. Should be automated and never set by hand.</description>
        <label>Banner Ready</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CampusCode__c</fullName>
        <description>This is the state campus code if there is one, otherwise it is considered the Main campus.</description>
        <inlineHelpText>Campus Code for WGU State Universities</inlineHelpText>
        <label>Campus Code</label>
        <picklist>
            <picklistValues>
                <fullName>WGU Main</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU Washington</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU Tennessee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU Texas</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LastDateOfAAV__c</fullName>
        <label>Last Date of AAV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LastPortalLogin__c</fullName>
        <description>This field should be used to display the last time a student logged into the portal We use this to feed Students at risk.</description>
        <inlineHelpText>Last student portal login date by a Student.</inlineHelpText>
        <label>Last Portal Login</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/ContactToBanner__c.object
<CustomObject>
    <description>Control object for synchronization of Contact with Information in Banner.</description>
    <fields>
        <fullName>BannerEventDateIN__c</fullName>
        <description>The date/time of the last event captured in Banner. An event may be any change made to a record that triggers a change notification to occur.</description>
        <label>Banner Event Date (IN)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CampusCodeIN__c</fullName>
        <description>The Banner campus code that will be converted to the Salesforce version by the trigger to Contact.</description>
        <label>Campus Code (IN)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The Contact that should be synchronized two ways to Banner.</description>
        <inlineHelpText>The Contact that should be synchronized two ways to Banner.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts To Banner</relationshipLabel>
        <relationshipName>ContactsToBanner</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CurrentTermCompletedCUsIN__c</fullName>
        <label>Current Term Completed CUs (IN)</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrentTermEnrolledCUsIN__c</fullName>
        <label>Current Term Enrolled CUs (IN)</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FirstNameIN__c</fullName>
        <label>First Name (IN)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HistoricallyAttemptedCUsIN__c</fullName>
        <label>Historically Attempted CUs (IN)</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HistoricallyCompletedCUsIN__c</fullName>
        <label>Historically Completed CUs (IN)</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LastAAVDateIN__c</fullName>
        <label>Last AAV Date (IN)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LastLoginIN__c</fullName>
        <label>Last Login (IN)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LastNameIN__c</fullName>
        <label>Last Name (IN)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastSynchronizedFromBanner__c</fullName>
        <label>Last Synchronized From Banner</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MyWGUEmailIN__c</fullName>
        <label>My WGU Email (IN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OtherEmailIN__c</fullName>
        <description>The personal email address for the student that is their primary address.</description>
        <label>Other Email (IN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResynchronizeToSalesforce__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Request that the current synchronization record be repushed into Salesforce.</description>
        <label>Resynchronize to Salesforce</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StatusIN__c</fullName>
        <description>The current Banner term status such as AS or TB.</description>
        <label>Status (IN)</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SynchronizationError__c</fullName>
        <description>Any error that occurs while trying to process data between Salesforce and Banner.</description>
        <label>Synchronization Error</label>
        <type>TextArea</type>
    </fields>
    <label>Contact To Banner</label>
    <nameField>
        <displayFormat>CTB-{0}</displayFormat>
        <label>Contact To Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts To Banner</pluralLabel>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>First time investigation and application into the university.</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>Returning</fullName>
        <active>true</active>
        <description>Prospects that were once student but are now attempting to return to the university.</description>
        <label>Returning</label>
    </recordTypes>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Active students or students on temporary leave.</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Campus__c</fullName>
        <formula>TEXT(StudentAttributes__r.Affiliation__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>University Affiliation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CareStatus__c</fullName>
        <label>CARE Status</label>
        <picklist>
            <picklistValues>
                <fullName>PROS – Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PRAP – Prospect Applied Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APNN – Application Incomplete PRAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APIN – Application Incomplete APCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APCO – Application Complete, Unpaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC – Application Complete, Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REDI - Admission Decision Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEND - Additional Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAMT - Auto Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMT – Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTV – Fit and EWB Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLRD - Cleared to Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENRL – Enrolled and Assigned a Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEVR – Never completed EWOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DROP – Dropped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAMT - Not Admitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAYT - Not Admitted Yet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MATR – Matriculated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRAD – Ready for Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALUMNI - Graduated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAttributes__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Convenience lookup for Informatica to grab all information about a Paid Applicant in one shot instead of splitting into multiple jobs.</description>
        <label>Student Attributes</label>
        <referenceTo>StudentAttributes__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>StudentContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CARE Profile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Runtime__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Store sandbox related values for runtime context</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Runtime</label>
</CustomObject>

src/classes/TestContactToBannerUtilities.cls
@IsTest
public class TestContactToBannerUtilities{
    @IsTest
    public static void updateLastLoginDate() {
        Runtime__c environment = new Runtime__c(name='environment', value__c = 'test');
        insert environment;
        
        Campus__c campus = new Campus__c(name='M', Contact__c = 'WGU Main', StudentAttributes__c = 'WGU');
        insert campus;
        
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();

        Contact baggins = [SELECT Id, PIDM__C, FirstName, LastName FROM Contact WHERE LastName = 'Baggins'];
        
        ContactToBanner__c record = new ContactToBanner__c(Contact__c = baggins.Id, FirstNameIN__c = baggins.FirstName,
                                                           LastNameIN__c = baggins.LastName, StatusIN__c = 'IN', HistoricallyAttemptedCUsIN__c = 0,
                                                           CurrentTermEnrolledCUsIN__c = 0, HistoricallyCompletedCUsIN__c = 0, 
                                                           CurrentTermCompletedCUsIN__c = 0, MyWGUEmailIN__c = 'me@my.wgu.edu',
                                                           OtherEmailIN__c = 'other@unit.test', LastSynchronizedFromBanner__c = Datetime.now(),
                                                           LastLoginIn__c = DateTime.newInstance(2013, 1, 1),
                                                           CampusCodeIN__c = 'M'
                                                          );
        
        insert record;         
        
        Test.startTest();   
            
            // Check only update to Last Login Date
            DateTime testTime = DateTime.now();
            record.LastLoginIn__c = testTime;
            record.FirstNameIN__c = 'Changed';
            update record;        
        
        Test.stopTest();
        
        // Verify only last login changes but name stays the same.
        Contact confirmContact = [SELECT LastPortalLogin__c, FirstName, CampusCode__c FROM Contact WHERE Id = :record.Contact__c];
        
        System.assert(confirmContact.LastPortalLogin__c.isSameDay(testTime));         
        System.assert(confirmContact.FirstName == baggins.FirstName);
        System.assert(confirmContact.CampusCode__c == 'WGU Main');
    }
    
    @IsTest
    public static void updateCheckIN() {
        Runtime__c environment = new Runtime__c(name='environment', value__c = 'test');
        insert environment;
        
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();

        Contact baggins = [SELECT Id, PIDM__C, FirstName, LastName FROM Contact WHERE LastName = 'Baggins'];      
        
        Test.startTest();   
            
            ContactToBanner__c record = new ContactToBanner__c(Contact__c = baggins.Id, FirstNameIN__c = baggins.FirstName,
                                                               LastNameIN__c = baggins.LastName, StatusIN__c = 'IN', HistoricallyAttemptedCUsIN__c = 0,
                                                               CurrentTermEnrolledCUsIN__c = 0, HistoricallyCompletedCUsIN__c = 0, 
                                                               CurrentTermCompletedCUsIN__c = 0, MyWGUEmailIN__c = 'me@my.wgu.edu',
                                                               OtherEmailIN__c = 'other@unit.test', LastSynchronizedFromBanner__c = Datetime.now(),
                                                               LastLoginIn__c = DateTime.newInstance(2013, 1, 1)
                                                              );
            
            insert record;    
        
        Test.stopTest();
        
        // Check IN settings.
        ContactToBanner__c confirm = [SELECT Id, RecordType.Name, SynchronizationError__c FROM ContactToBanner__c WHERE Contact__c = :baggins.Id];
        System.debug(confirm);
        System.assert(confirm.RecordType.Name == 'Prospect');
        
        baggins = [SELECT Id, Status__c FROM Contact WHERE LastName = 'Baggins'];
        System.assert(baggins.Status__c == 'IN');  
    }
    
    @IsTest
    public static void updateCheckAS() {
        Runtime__c environment = new Runtime__c(name='environment', value__c = 'test');
        insert environment;
        
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();

        Contact baggins = [SELECT Id, PIDM__C, FirstName, LastName FROM Contact WHERE LastName = 'Baggins'];
        
        ContactToBanner__c record = new ContactToBanner__c(Contact__c = baggins.Id, FirstNameIN__c = baggins.FirstName,
                                                           LastNameIN__c = baggins.LastName, StatusIN__c = 'IN', HistoricallyAttemptedCUsIN__c = 0,
                                                           CurrentTermEnrolledCUsIN__c = 0, HistoricallyCompletedCUsIN__c = 0, 
                                                           CurrentTermCompletedCUsIN__c = 0, MyWGUEmailIN__c = 'me@my.wgu.edu',
                                                           OtherEmailIN__c = 'other@unit.test', LastSynchronizedFromBanner__c = Datetime.now(),
                                                           LastLoginIn__c = DateTime.newInstance(2013, 1, 1)
                                                          );
        
        insert record;         
        
        Test.startTest();   
            
            record.StatusIN__c = 'AS';
            update record;    
        
        Test.stopTest();
        
        ContactToBanner__c confirm = [SELECT Id, RecordType.Name, SynchronizationError__c FROM ContactToBanner__c WHERE Contact__c = :baggins.Id];
        System.assert(confirm.RecordType.Name == 'Student');
        
        baggins = [SELECT Id, Status__c FROM Contact WHERE LastName = 'Baggins'];
        System.assert(baggins.Status__c == 'AS');    
    }    
    
    @IsTest
    public static void updateCheckGR() {
        Runtime__c environment = new Runtime__c(name='environment', value__c = 'test');
        insert environment;
        
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();

        Contact baggins = [SELECT Id, PIDM__C, FirstName, LastName FROM Contact WHERE LastName = 'Baggins'];
        
        ContactToBanner__c record = new ContactToBanner__c(Contact__c = baggins.Id, FirstNameIN__c = baggins.FirstName,
                                                           LastNameIN__c = baggins.LastName, StatusIN__c = 'IN', HistoricallyAttemptedCUsIN__c = 0,
                                                           CurrentTermEnrolledCUsIN__c = 0, HistoricallyCompletedCUsIN__c = 0, 
                                                           CurrentTermCompletedCUsIN__c = 0, MyWGUEmailIN__c = 'me@my.wgu.edu',
                                                           OtherEmailIN__c = 'other@unit.test', LastSynchronizedFromBanner__c = Datetime.now(),
                                                           LastLoginIn__c = DateTime.newInstance(2013, 1, 1)
                                                          );
        
        insert record;         
        
        Test.startTest();   
            
            record.StatusIN__c = 'GR';
            update record;    
        
        Test.stopTest();
        
        ContactToBanner__c confirm = [SELECT Id, RecordType.Name, SynchronizationError__c FROM ContactToBanner__c WHERE Contact__c = :baggins.Id];
        System.assert(confirm.RecordType.Name == 'Returning');
        
        baggins = [SELECT Id, Status__c FROM Contact WHERE LastName = 'Baggins'];
        System.assert(baggins.Status__c == 'GR');    
    }      
    
    @IsTest
    public static void updateCheckInvalidEmailField() {
        Runtime__c environment = new Runtime__c(name='environment', value__c = 'test');
        insert environment;
        
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();

        Contact baggins = [SELECT Id, PIDM__C, FirstName, LastName FROM Contact WHERE LastName = 'Baggins'];
        
        ContactToBanner__c record = new ContactToBanner__c(Contact__c = baggins.Id, FirstNameIN__c = baggins.FirstName,
                                                           LastNameIN__c = baggins.LastName, StatusIN__c = 'IN', HistoricallyAttemptedCUsIN__c = 0,
                                                           CurrentTermEnrolledCUsIN__c = 0, HistoricallyCompletedCUsIN__c = 0, 
                                                           CurrentTermCompletedCUsIN__c = 0, MyWGUEmailIN__c = 'me@my.wgu.edu',
                                                           OtherEmailIN__c = 'other@unit.test', LastSynchronizedFromBanner__c = Datetime.now(),
                                                           LastLoginIn__c = DateTime.newInstance(2013, 1, 1)
                                                          );
        
        insert record;         
        
        Test.startTest();   
            
            record.MyWGUEmailIN__c = 'someeo;jfkldjs@fjkdfos.fds.';
            update record;    
        
        Test.stopTest();
        
        ContactToBanner__c confirm = [SELECT Id, RecordType.Name, SynchronizationError__c FROM ContactToBanner__c WHERE Contact__c = :baggins.Id];
        System.assert(confirm.SynchronizationError__c.indexOf('Email') > 0);   
    }    
    
    @IsTest
    public static void updateCheckErrorDoesNotSync() {
        Runtime__c environment = new Runtime__c(name='environment', value__c = 'test');
        insert environment;
        
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();

        Contact baggins = [SELECT Id, PIDM__C, FirstName, LastName FROM Contact WHERE LastName = 'Baggins'];
        
        ContactToBanner__c record = new ContactToBanner__c(Contact__c = baggins.Id, FirstNameIN__c = baggins.FirstName,
                                                           LastNameIN__c = baggins.LastName, StatusIN__c = 'IN', HistoricallyAttemptedCUsIN__c = 0,
                                                           CurrentTermEnrolledCUsIN__c = 0, HistoricallyCompletedCUsIN__c = 0, 
                                                           CurrentTermCompletedCUsIN__c = 0, MyWGUEmailIN__c = 'someeo;jfkldjs@fjkdfos.fds.',
                                                           OtherEmailIN__c = 'other@unit.test', LastSynchronizedFromBanner__c = Datetime.now(),
                                                           LastLoginIn__c = DateTime.newInstance(2013, 1, 1)
                                                          );
        
        insert record;         
        
        Test.startTest();   
            
            record.MyWGUEmailIN__c = 'me@my.wgu.edu';
            update record;    
        
        Test.stopTest();
        
        ContactToBanner__c confirm = [SELECT Id, RecordType.Name, SynchronizationError__c FROM ContactToBanner__c WHERE Contact__c = :baggins.Id];
        System.assert(confirm.SynchronizationError__c.indexOf('Email') > 0); // System error from previous update.  
    } 

    @IsTest
    public static void updateCheckResynchronize() {
        Runtime__c environment = new Runtime__c(name='environment', value__c = 'test');
        insert environment;
        
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();

        Contact baggins = [SELECT Id, PIDM__C, FirstName, LastName FROM Contact WHERE LastName = 'Baggins'];
        
        ContactToBanner__c record = new ContactToBanner__c(Contact__c = baggins.Id, FirstNameIN__c = baggins.FirstName,
                                                           LastNameIN__c = baggins.LastName, StatusIN__c = 'IN', HistoricallyAttemptedCUsIN__c = 0,
                                                           CurrentTermEnrolledCUsIN__c = 0, HistoricallyCompletedCUsIN__c = 0, 
                                                           CurrentTermCompletedCUsIN__c = 0, MyWGUEmailIN__c = 'me@my.wgu.edu',
                                                           OtherEmailIN__c = 'other@unit.test', LastSynchronizedFromBanner__c = Datetime.now(),
                                                           LastLoginIn__c = DateTime.newInstance(2013, 1, 1)
                                                          );
        
        insert record;         
        
        Test.startTest();   
            
            record.SynchronizationError__c = 'Existing Error.';
            record.ResynchronizeToSalesforce__c = true;
            record.BannerEventDateIN__c = DateTime.now();
            update record;    
        
        Test.stopTest();
        
        ContactToBanner__c confirm = [SELECT Id, ResynchronizeToSalesforce__c, SynchronizationError__c FROM ContactToBanner__c WHERE Contact__c = :baggins.Id];
        System.assert(confirm.SynchronizationError__c == null);      
        System.assert(!confirm.ResynchronizeToSalesforce__c);
    }    
   
    @IsTest
    public static void updateCheckLastAAVDate() {
        Runtime__c environment = new Runtime__c(name='environment', value__c = 'test');
        insert environment;
        
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();

        Contact baggins = [SELECT Id, PIDM__C, FirstName, LastName FROM Contact WHERE LastName = 'Baggins'];
        
        ContactToBanner__c record = new ContactToBanner__c(Contact__c = baggins.Id, FirstNameIN__c = baggins.FirstName,
                                                           LastNameIN__c = baggins.LastName, StatusIN__c = 'IN', HistoricallyAttemptedCUsIN__c = 0,
                                                           CurrentTermEnrolledCUsIN__c = 0, HistoricallyCompletedCUsIN__c = 0, 
                                                           CurrentTermCompletedCUsIN__c = 0, MyWGUEmailIN__c = 'me@my.wgu.edu',
                                                           OtherEmailIN__c = 'other@unit.test', LastSynchronizedFromBanner__c = Datetime.now(),
                                                           LastLoginIn__c = DateTime.newInstance(2013, 1, 1)
                                                          );
        
        insert record;         
        
        Test.startTest();   
            
            record.LastAAVDateIN__c = DateTime.now();
            update record;  
        
        Test.stopTest();
        
        baggins = [SELECT Id, LastDateOfAAV__c FROM Contact WHERE LastName = 'Baggins'];
        System.assert(baggins.LastDateOfAAV__c != null); 
    }
    
    @IsTest
    public static void checkUpdateReadyForBanner() {
        Runtime__c environment = new Runtime__c(name='environment', value__c = 'test');
        insert environment;
        
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();

        Contact baggins = [SELECT Id, PIDM__C, FirstName, LastName, AccountId, BannerReady__c FROM Contact WHERE LastName = 'Baggins'];
        
        System.assertEquals(false, baggins.BannerReady__c);
        
        Opportunity testOpp = new Opportunity(Name = 'FrodoTest BagginsTest', CareStatus__c = 'APIN – Application Incomplete APCO', AccountId = baggins.AccountId,
                                              CloseDate = Date.today(), StageName = 'Applicant', StudentContact__c = baggins.Id);
        insert testOpp;
        
        testOpp.CareStatus__c = 'APAC – Application Complete, Paid';
                        
        Test.startTest(); 
            update testOpp; 
        Test.stopTest();
        
        baggins = [SELECT Id, PIDM__C, FirstName, LastName, AccountId, BannerReady__c FROM Contact WHERE LastName = 'Baggins'];  
        
        System.assertEquals(true, baggins.BannerReady__c);
    }
    
    @isTest
    public static void testUpdateContactBannerData()
    {
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();

        Contact baggins = [SELECT Id, PIDM__C, FirstName, LastName FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        baggins.Pidm__c = null;
        baggins.WGUEmail__c = null;
        baggins.Username__c = null;
        baggins.StudentId__c = null;
        update baggins;
         
        ContactToBanner__c record = new ContactToBanner__c(Contact__c = baggins.Id, FirstNameIN__c = baggins.FirstName,
                                                           LastNameIN__c = baggins.LastName, StatusIN__c = 'IN', HistoricallyAttemptedCUsIN__c = 0,
                                                           CurrentTermEnrolledCUsIN__c = 0, HistoricallyCompletedCUsIN__c = 0, 
                                                           CurrentTermCompletedCUsIN__c = 0, MyWGUEmailIN__c = 'me@my.wgu.edu',
                                                           OtherEmailIN__c = 'other@unit.test', LastSynchronizedFromBanner__c = Datetime.now(),
                                                           LastLoginIn__c = DateTime.newInstance(2013, 1, 1),
                                                           PIDMFromBannerIN__c = '1967325',
                                                           UsernameFromBannerIN__c = baggins.Firstname,
                                                           WGUEmailFromBannerIN__c = 'testupdateZhang@wgu.edu',
                                                           BannerIDFromBannerIN__c = '201308275' );
        insert record;
        
        List<ContactToBanner__c> ctbList = new List<ContactToBanner__c>();
        ctbList.add(record);        
        
        Test.startTest();                
            ContactToBannerUtilities.updateContactBannerData(ctbList);                                    
        Test.stopTest();               
        
        List<Contact> updateResult = [select Id, PIDM__c, FirstName, LastName, Username__c, WGUEmail__c, StudentID__c
                                      from Contact where Id = :baggins.Id LIMIT 1];
        
        System.assert(updateResult[0].PIDM__c != null);
        System.assert(updateResult[0].Firstname != null);
        System.assert(updateResult[0].WGUEmail__c != null);
        System.assert(updateResult[0].StudentId__c != null);
        System.assertEquals(updateResult[0].PIDM__c, record.PIDMFromBannerIN__c);
        System.assertEquals(updateResult[0].Firstname, record.UsernameFromBannerIN__c);
        //System.assertEquals(updateResult[0].WGUEmail__c.toLowerCase(), record.WGUEmailFromBannerIN__c.toLowerCase());
        System.assertEquals(updateResult[0].StudentId__c, record.BannerIDFromBannerIN__c);
        
    }  
}