src/objects/CareProgramMiddleEarth__c.object
<CustomObject>
    <description>Used to bring together the CARE Program code and the PAMS program code together.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProgramGroups__c</fullName>
        <label>Program Groups</label>
        <picklist>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education (initial teaching licensure programs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education (programs for current teachers and others)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CARE Program Middle Earth</label>
    <nameField>
        <label>Program Middle Earth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs Middle Earth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>StudentAttributes__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Convenience lookup for Informatica to grab all information about a Paid Applicant in one shot instead of splitting into multiple jobs.</description>
        <label>Student Attributes</label>
        <referenceTo>StudentAttributes__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/States__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>State Attributes</description>
    <fields>
        <fullName>StateFullName__c</fullName>
        <description>Full name of State</description>
        <externalId>true</externalId>
        <label>State FullName</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>States</label>
</CustomObject>

src/objects/StudentAttributes__c.object
<CustomObject>
    <description>Custom object to manage student attributes via portal and sites, with update triggers to Contact/Account</description>
    <fields>
        <fullName>Affiliation__c</fullName>
        <description>WGU affiliate the student belongs to</description>
        <inlineHelpText>Set the student&apos;s WGU affiliation.</inlineHelpText>
        <label>University Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>WGU</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <label>Nickname</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Student Attributes</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CAREProfileController.cls
public class CAREProfileController {
    
    Contact contact;
    Opportunity careprofile;
    public String marketingProgram {get; set;}
    public String fieldRep {get; set;}
    StudentAttributes__c attributes;
    // public String firstname {get; set;}
    public CAREProfileController(){
    }
    public List<SelectOption> getPrograms(){
        List<CareProgramMiddleEarth__c> programs = [SELECT Id,Name FROM CareProgramMiddleEarth__c WHERE Active__c = True ORDER BY ProgramGroups__c, Name];
        List<SelectOption> options = new List<SelectOption>();
        if (!programs.isEmpty()){
            for (CareProgramMiddleEarth__c program : programs){
                options.add(new SelectOption(program.Id, program.Name));
            }    
        }
        return options; 
    }
    
    public List<SelectOption> getStatesSelectList(){
        List<SelectOption> states = new List<SelectOption>();
        states.add(new SelectOption('', '--Select a State--'));
        Map<String, States__c> stateNames = States__c.getAll(); // new Map<ID, States__c>( [select id, name, value__c from States__c order by name ASC] ); 
        List <String> statesShortName = new List<String>();
        statesShortName.addAll(stateNames.keySet());
        statesShortName.sort();
        for (String stateShortName : statesShortName) {
            States__c state = stateNames.get(stateShortName);
            states.add(new SelectOption(stateShortName, state.StateFullName__c));
        }
        return states;
    }
    
    public void setContact(Contact contact){
        this.contact = contact;
    }
    public void setOpportunity(Opportunity careprofile){
        this.careprofile = careprofile;
    }
    public void setAttributes(StudentAttributes__c attributes){
        this.attributes = attributes;
    }
    
    public Contact getContact(){
        if(contact == null) contact= new Contact(); 
        return contact;
    } 
    
    public Opportunity getOpportunity() {
        if(careprofile == null) careprofile = new Opportunity();
        return careprofile;
    }
    
    public StudentAttributes__c getAttributes(){
        if(attributes == null) attributes = new StudentAttributes__c();
        return attributes;
    }
    
    public void save() {
        Map<String, String> fields = new Map<String, String>();
        fields.put('firstname', contact.firstName);
        fields.put('lastname', contact.lastName);
        fields.put('street', contact.mailingStreet);
        fields.put('city', contact.mailingCity);
        fields.put('state', contact.mailingState);
        fields.put('postalcode', contact.mailingPostalCode);
        fields.put('country', 'US');
        fields.put('email', contact.Email);
        fields.put('campus', attributes.Affiliation__c);
        fields.put('fieldrep', fieldRep);
        fields.put('nickname', attributes.Nickname__c);
        fields.put('phone', contact.phone);
        fields.put('alternatephone', contact.OtherPhone);
        fields.put('program', marketingProgram);
        fields.put('referid', '1721');
        
        CAREforceInquiryRESTServices.inquiry(null, fields, null, null, false);
        
        contact = null;
        careprofile = null;
        attributes = null; 
    
    }
    
}