src/objects/CareerServices__c.object
<CustomObject>
    <description>This object allows the Career Services team to track all appointment sessions completed for students related to career services..</description>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Career Services</relationshipLabel>
        <relationshipName>Student</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Career Decision Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Services Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interviewing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Search Strategies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Networking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume/Cover Letter (Reviewed/Development)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Career Services</label>
    <nameField>
        <displayFormat>CS# {00}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Career Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CatalogYear__c</fullName>
        <label>Catalog Year</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MentorName__c</fullName>
        <description>Mentor name to get around permissions issue.</description>
        <formula>Mentor__r.FirstName &amp; &apos; &apos; &amp; Mentor__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mentor Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <label>Program Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StudentProcess__c.object
<CustomObject>
    <description>Custom object to manage student processes by record type.</description>
    <fields>
        <fullName>ApplicationVerification__c</fullName>
        <description>Open text field used for various records online forms for student verification.</description>
        <label>Application Verification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CatalogYear__c</fullName>
        <description>A formula field that pulls in the student&apos;s program catalog term.</description>
        <formula>Student__r.ProgramCatalogTerm__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Catalog Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>A formula field that pulls in the student&apos;s first name.</description>
        <formula>Student__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>A formula field that pulls in the student&apos;s last name.</description>
        <formula>Student__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewCatalogTerm__c</fullName>
        <description>Text field that allows the user to enter in the new catalog term for Banner processing.</description>
        <label>New Catalog Term</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to reference WGU Degree Program for program code and catalog version used to request a program change.</description>
        <inlineHelpText>When selecting the correct Program, please also select the correct Catalog Version.</inlineHelpText>
        <label>New Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>Student_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewProgramCode__c</fullName>
        <description>Text field for users to enter the new program code for Banner processing.</description>
        <label>New Program Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <description>A formula field that pulls in the student&apos;s program code.</description>
        <formula>Student__r.ProgramCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>The stage of the student process.</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assign Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Student Reply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student spoke with Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student spoke with other personnel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student was submitted too early</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correction Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counsel Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Degree Plan Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diploma and Transcripts Mailed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diploma and Transcripts Mailed - Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midterm Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOU Accepted by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOU Needed - Custom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentProcessAutoNumber__c</fullName>
        <description>Auto number for the student process object used for student facing forms.</description>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Student Process Auto Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup field to the contact of the student process object.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>StudentProcesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>A picklist indicating the type of the student process.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>2nd Degree Acceleration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAV Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Expulsion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Standards Committee Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Suspension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Drop Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal to Registrar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Articulation Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessment Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board of Registered Nursing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bursar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campus Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change in Mentor Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change in Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Required Completion Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clear Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Copy of Degree Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crosswalk Applied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crosswalk Request (RM/RS/TR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date of Birth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferment Form</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student Process</label>
    <nameField>
        <label>Student Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Processes</pluralLabel>
    <recordTypes>
        <fullName>ProgramChange</fullName>
        <active>true</active>
        <description>The record type used to manage the program change process for student records.</description>
        <label>Program Change</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/ProgramChangeController.cls
/*
This Controller is for ProgramChange VF page used by Students.
Author- Bhavadeep Raavi
*/

public with sharing class ProgramChangeController{
    public StudentProcess__c stdProcess{get;set;}
    public String q1{get;set;}
    public String q2{get;set;}
    public String q3{get;set;}
    public String q4{get;set;}
    public String q5{get;set;}
    private String stdProcessAutoNum;
    public String Fname;
    public String Lname;
    public Boolean disFlag{get;set;} 
    public Boolean pceandnonpce{get;set;} 
    public ProgramChangeController(ApexPages.StandardController controller) {
            stdProcessAutoNum=Apexpages.currentpage().getParameters().get('StudentProcessAutoNumber__c');
            System.debug('stdProcessAutoNum '+stdProcessAutoNum); 
            string userPidm = [select pidm__c from User where id=:UserInfo.getUserId()].pidm__c; 
            
            stdProcess=test.isRunningTest()?[select Id,FirstName__c,LastName__c,Stage__c,ApplicationVerification__c,CatalogYear__c,NewCatalogTerm__c,NewProgramCode__c,NewDegreeProgram__r.Name,Type__c,Student__r.pidm__c, Student__r.MentorName__c,MentorEmail__c,StudentID__c,ProgramCode__c from StudentProcess__c LIMIT 1]:[select Id,FirstName__c,LastName__c,Stage__c,ApplicationVerification__c,CatalogYear__c,NewCatalogTerm__c,NewProgramCode__c,NewDegreeProgram__r.Name,Type__c,Student__r.pidm__c, Student__r.MentorName__c,MentorEmail__c,StudentID__c,ProgramCode__c from StudentProcess__c where StudentProcessAutoNumber__c=:stdProcessAutoNum LIMIT 1];
            /*if (test.isRunningTest())
            {          
            stdProcess=[select Id,FirstName__c,LastName__c,Stage__c,ApplicationVerification__c,CatalogYear__c,NewCatalogTerm__c,NewProgramCode__c,Type__c,Student__r.pidm__c, Student__r.MentorName__c,MentorEmail__c,StudentID__c,ProgramCode__c from StudentProcess__c LIMIT 1];
            }else{
            stdProcess=[select Id,FirstName__c,LastName__c,Stage__c,ApplicationVerification__c,CatalogYear__c,NewCatalogTerm__c,NewProgramCode__c,Type__c,Student__r.pidm__c, Student__r.MentorName__c,MentorEmail__c,StudentID__c,ProgramCode__c from StudentProcess__c where StudentProcessAutoNumber__c=:stdProcessAutoNum LIMIT 1];
            }*/
            
            Fname = stdProcess.FirstName__c;
            Lname = stdProcess.LastName__c;
            if(stdProcess.Student__r!=null &&  stdProcess.Student__r.pidm__c!=userPidm){
                 disFlag=true;
                 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You do not have the required permission to access this record.   If you believe this message is in error, please contact the Student Records Department at 877-435-7948 x 3146 or by email at records@wgu.edu .'));  
            }
            if(stdProcess!=null && stdProcess.Stage__c!=null && stdProcess.Stage__c=='MOU Accepted by Student'){
                 disFlag=true;
                 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Your Memorandum of Understanding for your requested program change has already been submitted and is currently being reviewed.  If you have questions concerning your program change request please contact Student Records at 877-435-7948 x 3146 or by email at records@wgu.edu .'));  
            }
            
            
    }
    public PageReference approveNonPCE(){
        String sDesc='';
        Boolean flag=false;
               
        if(q1==null){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'ERROR: Please answer all the questions below'));                   
            flag=true;
        }
        if(q2==null){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'ERROR: Please answer all the questions below'));                   
            flag=true;
        }
        if(q3==null){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'ERROR: Please answer all the questions below'));                   
            flag=true;
        }
        if(q4==null){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'ERROR: Please answer all the questions below'));                   
            flag=true;
        }
        if(q5==null){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'ERROR: Please answer all the questions below'));                   
            flag=true;
        }
        
        if(flag==true){
            return null;
        }
        String strNonPCE='';
        if(q1=='No' || q2=='No' || q3=='No' || q4=='No' || q5=='No'){
            strNonPCE='Your Memorandum of Understanding has been submitted to your Mentor. You answered no to one or more questions indicating that you do not fully understand the ramifications of your requested program change.   Your mentor will review your MOU and communicate directly with you to discuss your program change request further. Thank you!';            
        }else{
           strNonPCE='Your Memorandum of Understanding has been submitted to your Mentor. Once your mentor has reviewed your MOU, a Program Change Request will be submitted on your behalf.If any additional information is required, your Mentor will communicate that need directly to you. Thank you! ';             
        }
        try{
        stdProcess.ApplicationVerification__c='Q1- '+q1+','+'Q2- '+q2+','+'Q3- '+q3+','+'Q4- '+q4+','+'Q5- '+q5+' '+Fname+' '+Lname+' '+'Approved on'+'  '+datetime.now();
        stdProcess.Stage__c='MOU Accepted by Student';
        update stdProcess;
        disFlag = true;
        }catch(Exception e){
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'ERROR: There is problem in updating'));
        return null;
        }
         ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,strNonPCE));
         return null;
    }
    public PageReference approvePCE(){
        
         
        try{
            stdProcess.ApplicationVerification__c='Verified'+' '+datetime.now();
            stdProcess.Stage__c='MOU Accepted by Student';
            update stdProcess;
            disFlag = true;
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'ERROR: There is problem in updating'));                   
            return null;
        }
         ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Thank you for completing the Memorandum of Understanding for your requested program change. Your mentor has been notified and will be in contact with you if any further information is needed.'));
         return null;
    }
    public PageReference cancel(){
            PageReference pf = new PageReference('https://my.wgu.edu'); 
            pf.setRedirect(true); 
            return pf;
    }
}