src/objects/CareProgramMiddleEarth__c.object
<CustomObject>
    <description>Used to bring together the CARE Program code and the PAMS program code together.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>CARE Program Middle Earth</label>
    <nameField>
        <label>Program Middle Earth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs Middle Earth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ContactLastName__c</fullName>
        <formula>StudentContact__r.LastName</formula>
        <label>Contact Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Program</label>
        <referenceTo>CareProgramMiddleEarth__c</referenceTo>
        <relationshipLabel>CAREProfile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NameAndPhone__c</fullName>
        <formula>StudentContact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonalPageIdentifier__c</fullName>
        <description>This is for the personal page to store the ID to support the public personal page.</description>
        <label>Personal Page Identifier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAttributes__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Convenience lookup for Informatica to grab all information about a Paid Applicant in one shot instead of splitting into multiple jobs.</description>
        <label>Student Attributes</label>
        <referenceTo>StudentAttributes__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Personal_Pages_Link__c.object
<CustomObject>
    <description>Personal Pages Links is for the creation and maintenance of links on the personal pages.</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>affiliation__c</fullName>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>WGU-SLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TEX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TEN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>image__c</fullName>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>link__c</fullName>
        <label>Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sort_order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Personal Pages Link</label>
    <nameField>
        <label>Personal Pages Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Pages Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/StudentAttributes__c.object
<CustomObject>
    <description>Custom object to manage student attributes via portal and sites, with update triggers to Contact/Account</description>
    <fields>
        <fullName>Affiliation__c</fullName>
        <description>WGU affiliate the student belongs to</description>
        <inlineHelpText>Set the student&apos;s WGU affiliation.</inlineHelpText>
        <label>University Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>WGU</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student Attributes</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PersonalPages.cls
public class PersonalPages{
 
public static void generateIdentifier(Id profileId, String contactId) {

    //SOQL for contact name
    Contact contact = [SELECT FirstName, LastName FROM Contact WHERE Id =:contactId];
    
    String name = contact.FirstName + '' + contact.LastName; 
    name = name.toLowerCase();
    name = name.replaceAll('[^a-z]+', '');
    
    System.debug(contactId);
    System.debug(contactId.length());
    String lastFour = (contactId.length() >= 7)? contactId.substring(contactId.length() - 7, contactId.length()-3): contactId ;
    String identifier = name + lastFour ;
    
    
     //Replaced by above as we have chosen a diffrent unique id string. 
    /*  // Get current Date
    Date currentDate = date.today();
    
    
    
    // Check contact for null
    
    String identifier = generateIdentifierWithDate(profileId, contact.FirstName, contact.LastName, currentDate);
    
    */
    
    
    
    // Set Identifier for the Opportunity
    Opportunity profile = New Opportunity(id = profileId, PersonalPageIdentifier__c = identifier);
    
    // Save change
    update profile;
}


/*  Replaced by above as we have chosen a diffrent unique id string.  

private static String generateIdentifierWithDate(String profileId, String firstName, String lastName, Datetime createdDate) {
List<String> dateParts = String.valueOf(createdDate).split('-', 0);

String identifierStub = firstName.toLowerCase() + lastName.toLowerCase() + '-' + dateParts[1] + dateParts[0].right(2) + '-'; 
String queryLikeStub = identifierStub + '%';

// Get list of records
List<Opportunity> records = [SELECT PersonalPageIdentifier__c 
                 FROM Opportunity 
                 WHERE PersonalPageIdentifier__c LIKE :queryLikeStub];

// Get the next sequence number (default to 1)
Integer sequenceNumber = 1;

// Search for correct sequence number
for (Opportunity record : records) {
// Determine sequence number of record
Integer recordSequenceNumber = Integer.valueOf(record.PersonalPageIdentifier__c.substring(record.PersonalPageIdentifier__c.lastIndexOf('-') + 1));

// Does this record have a sequence number larger or equal to 
// the one we are trying to apply to the new record 
if (recordSequenceNumber >= sequenceNumber) {
// Set sequence number to be next number in sequence
sequenceNumber = recordSequenceNumber + 1;
}
}

return identifierStub + String.valueOf(sequenceNumber);
}
*/
/*

    @RemoteAction
    public static String identifierDataGather(String identifierURL)
    {
        
        if (identifierURL == null)
        {
            return null;
        }
        String errorMessage = 'none';
        Map<String,Object>  returnMap  = new Map<String,Object>();
        
        String identifier = identifierURL.substringAfterLast('/');
        if (identifier  == null || identifier.length() < 1)
        {
            return null;
        }
        
        List<Opportunity> profiles = [Select id, NameAndPhone__c,
                               ContactLastName__c,
                               MarketingProgram__r.Name,
                               Owner.name, StudentAttributes__r.Affiliation__c
                               from Opportunity 
                               where PersonalPageIdentifier__c = :identifier];
                               
        if (profiles.size() < 1)
        {
            errorMessage = 'Student Not Found';
            returnMap.put('errorMessage',errorMessage);   
            return  Json.serialize(returnMap);                 
        }
        
        
        Opportunity profile = profiles.get(0);
        
        System.debug('Profile: ' + profile);
        System.debug('Afil: ' + profile.StudentAttributes__r.Affiliation__c);
        String ecName = profile.Owner.name;
        String programName = profile.MarketingProgram__r.name;
        String affiliation = profile.StudentAttributes__r.Affiliation__c;
        
        List<Personal_Pages_Link__c> pplc = [Select id, affiliation__c, active__c,
                                             sort_order__c, image__c, link__c,
                                             Program__c
                                             from Personal_Pages_Link__c
                                             where active__C = true
                                             and affiliation__c = :affiliation
                                             order by sort_order__c];                                       
        System.debug('HERE0' + pplc);
        
   
        
        List<Personal_Pages_Link__c> personalPagesLinks = new List<Personal_Pages_Link__c>();
            
            
        
        for (Personal_Pages_Link__c pagelink : pplc )
        {
            System.debug('HERE1' + pagelink );
            if (pagelink.Program__c != null)
            {
                 List<String> programsLinks = pagelink.Program__c.split(';'); 
                 
                 for (String program : programsLinks )
                 {
                     if (program.equalsIgnoreCase(programName))
                     {
                        personalPagesLinks.add(pagelink);
                        break;
                     } 
                 }
            }

                  
       }
       

        
        returnMap.put('firstName', profile.NameAndPhone__c);
        returnMap.put('lastName', profile.ContactLastName__c);
        returnMap.put('ecName', ecName);
        returnMap.put('programName', programName);
        returnMap.put('personalPagesLinks', personalPagesLinks);
        returnMap.put('identifier', identifier);
        returnMap.put('errorMessage',errorMessage);
        
       // System.debug(returnMap);
        
        String jsonReturnMap = Json.serialize(returnMap);
        
      //  System.debug(jsonReturnMap);
        return jsonReturnMap;
        
        
    }

*/
    
}