src/objects/CareerServices__c.object
<CustomObject>
    <description>This object allows the Career Services team to track all appointment sessions completed for students related to career services..</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Career Services</relationshipLabel>
        <relationshipName>Student</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Career Services</label>
    <nameField>
        <displayFormat>CS# {00}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Career Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OLD_Id__c</fullName>
        <description>A temporary holding field for the SF ID of this Contact record, to be used for data migration from a person account org to a non-person account org. Declared as External Id for Upsert operations via the SOAP, REST, or BULK APIs.</description>
        <externalId>true</externalId>
        <label>OLD_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/FDPMigrationStudent__c.object
<CustomObject>
    <description>Contains pidms for students that will be converted/migrated to Java FDP.</description>
    <fields>
        <fullName>processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>processed</label>
        <type>Checkbox</type>
    </fields>
    <label>FDPMigrationStudent</label>
    <nameField>
        <label>PIDM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FDPMigrationStudents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentDegreePlans__c.object
<CustomObject>
    <description>Student instance of a WGU degree plan, provisioned from the WGUDegreeProgram__c object.</description>
    <fields>
        <fullName>IsApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Degree plan is approved</description>
        <label>Is Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OLD_Id__c</fullName>
        <description>A temporary holding field for the SF ID of this record, to be used for data migration from a person account org to a non-person account org. Declared as External Id for Upsert operations via the SOAP, REST, or BULK APIs.</description>
        <externalId>true</externalId>
        <label>OLD_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Degree Plans</relationshipLabel>
        <relationshipName>StudentDegreePlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Degree Plan</label>
    <nameField>
        <label>Student Degree Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Degree Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchMigrate.cls
global class BatchMigrate implements Database.Batchable<sObject> {
   global final String query;

   global BatchMigrate() {
     query = 'select id,Name,processed__c from FDPMigrationStudent__C where processed__c = false';
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

   global void execute(Database.BatchableContext BC, List<sObject> scope){
      List<String> pidms = new List<String>();
    for(sObject ms :scope){
    FDPMigrationStudent__C mstudent=(FDPMigrationStudent__C)ms;
        pidms.add(mstudent.Name);
        mstudent.processed__c = true;
    }

    list<StudentDegreeplans__C> plans = [select id,old_id__C from studentdegreeplans__C where isapproved__C=true and student__r.pidm__C IN :pidms];
    for(StudentDegreeplans__C plan: plans) {
        plan.old_id__C='N';
    }

    update plans;
    update scope;

      
   }

   global void finish(Database.BatchableContext BC){}

}