src/objects/CAREProgram__c.object
<CustomObject>
    <description>The object to handle all of the CARE Programs and their codes</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>CARE Program</label>
    <nameField>
        <label>CARE Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CareProgramMiddleEarth__c.object
<CustomObject>
    <description>Used to bring together the CARE Program code and the PAMS program code together.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BannerProgramCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banner Program Code</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>CARE Programs Middle Earth</relationshipLabel>
        <relationshipName>CAREProgramsMiddleEarth</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CAREProgramCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CARE Program Code</label>
        <referenceTo>CAREProgram__c</referenceTo>
        <relationshipLabel>CARE Programs Middle Earth</relationshipLabel>
        <relationshipName>CAREProgramsMiddleEarth</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CARE Program Middle Earth</label>
    <nameField>
        <label>Program Middle Earth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs Middle Earth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KeyValue__c.object
<CustomObject>
    <description>Represents the Key Value pairs with record types.</description>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NumericValue__c</fullName>
        <description>The numeric value of the key value used for value based rules and sorting</description>
        <inlineHelpText>The numeric value of the key value used for value based rules and sorting</inlineHelpText>
        <label>Numeric Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>The external reference code for the title in the group.</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Key Value</label>
    <nameField>
        <label>Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Values</pluralLabel>
    <recordTypes>
        <fullName>TransferDegree</fullName>
        <active>true</active>
        <description>Degrees that may transfer to WGU.</description>
        <label>Transfer Degree</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MarketingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Program</label>
        <referenceTo>CareProgramMiddleEarth__c</referenceTo>
        <relationshipLabel>CAREProfile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MarketingReferID__c</fullName>
        <description>The refer id field that is used by marketing as the original refer id for a lead</description>
        <label>Marketing Refer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StudentEquivalentCourse__c.object
<CustomObject>
    <description>WGU&apos;s courses and the link between transfered course for which a student may receive credit.</description>
    <fields>
        <fullName>TransferEvaluation__c</fullName>
        <description>Related Transfer Evaluation</description>
        <label>Transfer Evaluation</label>
        <referenceTo>TransferEvaluation__c</referenceTo>
        <relationshipLabel>Student Equivalent Courses</relationshipLabel>
        <relationshipName>StudentEquivalentCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WGUCourseInProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Course In Program</label>
        <referenceTo>WGUCourseInProgram__c</referenceTo>
        <relationshipLabel>Student Equivalent Courses</relationshipLabel>
        <relationshipName>Student_Equivalent_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <formula>WGUCourseInProgram__r.Course__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>WGU Course</label>
        <type>Text</type>
    </fields>
    <label>Student Equivalent Course</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Student Equivalent Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Equivalent Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentTranscript__c.object
<CustomObject>
    <description>Object to manage the transcripts that must be collected through in-take and viewed by Mentors</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Student Transfer Institution</relationshipLabel>
        <relationshipName>opportunityTransferInstitution</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <formula>Opportunity__r.Account.PIDM__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PIDM</label>
        <type>Text</type>
    </fields>
    <label>Student Transfer Institution</label>
    <nameField>
        <displayFormat>Institution-{0000}</displayFormat>
        <label>Student Transfer Institution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transfer Institution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentTransferredCourse__c.object
<CustomObject>
    <description>Shows courses that were transferred to WGU. Child object of Student Transfer Instituition.</description>
    <fields>
        <fullName>Course__c</fullName>
        <description>The course being transferred in to WGU</description>
        <inlineHelpText>The course being transferred in to WGU</inlineHelpText>
        <label>Course</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Student Transferred Course</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transferred Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TranscriptToBanner__c.object
<CustomObject>
    <description>Sync object to house Transcripts being pushed to Banner</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>PIDM of the related Opportunity</description>
        <label>PIDM</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Transcript to Banner</label>
    <nameField>
        <displayFormat>T2B-{0000000}</displayFormat>
        <label>Transcript to Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcripts to Banner</pluralLabel>
    <recordTypes>
        <fullName>StudentEquivalentCourse</fullName>
        <active>true</active>
        <label>StudentEquivalentCourse</label>
    </recordTypes>
    <recordTypes>
        <fullName>StudentTransferredCourse</fullName>
        <active>true</active>
        <label>StudentTransferredCourse</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TransferEvaluation__c.object
<CustomObject>
    <description>A Transfer evaluation is the parent object of the equivalent courses that will given to the student from their transfer work. It controls the overall status and assignment of the evaluation.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether or not this is the current active evaluation</description>
        <inlineHelpText>Whether or not this is the current active evaluation</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EligibilityStatus__c</fullName>
        <description>The status of the student&apos;s eligibility based on the transfer evaluation</description>
        <inlineHelpText>The status of the student&apos;s eligibility based on the transfer evaluation</inlineHelpText>
        <label>Eligibility Status</label>
        <picklist>
            <picklistValues>
                <fullName>Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Eligible</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The Link Between opportunities and transfer evaluations</description>
        <label>CARE Profile Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transfer Evaluations</relationshipLabel>
        <relationshipName>TransferEvaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The program that the student was eThe program that the student was evaluated for valuated for</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Transfer Evaluations</relationshipLabel>
        <relationshipName>TransferEvaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transfer Evaluation</label>
    <nameField>
        <label>Transfer Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfer Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this course is active.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PAMSID__c</fullName>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseInProgram__c.object
<CustomObject>
    <description>A many to many mapping that assigns which course are required to accomplish any degree program.</description>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipName>PAMS_Course_In_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>WGU Course In Programs</relationshipLabel>
        <relationshipName>WGUCourseInPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transferable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>checkbox field to indicate whether or not the course is transferable</description>
        <inlineHelpText>Is this course transferable?</inlineHelpText>
        <label>Transferable</label>
        <type>Checkbox</type>
    </fields>
    <label>WGU Course In Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WGU Course In Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Degree Program is active and can be used.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CatalogTerm__c</fullName>
        <description>The catalog Term this program was built. This is the Major Version in the PAMS database.</description>
        <label>Catalog Term</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PAMSID__c</fullName>
        <description>The ID that represents the program in PAMS.</description>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestTransferEvaluationUtility.cls
/***************************************************************************************
 * Author: Will Slade
 * Western Governors University 
 *
 * Purpose: Test TransferEvaluationUtility
 *
 * Revisions:
 *     4-16-2013 - Created Class 
 *     10/8/2013 - PBC commented out User record creation, replaced with active User lookup for test runs
 *
 ***************************************************************************************/

@isTest
private with sharing class TestTransferEvaluationUtility
{
    private static testMethod void testInsert()
    {
        //Id profileId = [SELECT Id FROM Profile WHERE Name = 'Mentor' LIMIT 1].Id;
        
        User testUser = [SELECT id FROM User WHERE isActive=true AND Profile.Name = 'Mentor' LIMIT 1]; //new User();
        /*
        testUser.Firstname = 'TestFEPlEm';
        testUser.Lastname = 'UserFEPlEm';
        testUser.Pidm__c = 'QA95050QA';
        testUser.Username = 'testuserFEPlEm@testuser.testuser';
        testUser.Email = 'testuserFEPlEm@testuser.testuser.wgu.edu';
        testUser.Alias = 'testFEPl';
        testUser.CommunityNickname = 'testua6123se';
        testUser.TimeZoneSidKey = 'America/Denver';
        testUser.LocaleSidKey = 'en_US';
        testUser.EmailEncodingKey = 'ISO-8859-1';
        testUser.ProfileId = profileId;
        testUser.LanguageLocaleKey = 'en_US';     
        insert testUser;
        */
        
        RecordType trDegRT = [SELECT Id FROM RecordType WHERE SObjectType = 'KeyValue__c' AND DeveloperName = 'TransferDegree' LIMIT 1];
        
        KeyValue__c noDegree = new KeyValue__c(RecordTypeId = trDegRT.Id, ExternalID__c = 'ND', Value__c = 'ND', NumericValue__c = 0);
        insert noDegree;        
            
        CAREProgram__c testCAREProgram = new CAREProgram__c(Name = 'TestCAREProgram124');
        insert testCAREProgram;
        
        WGUDegreeProgram__c testWGUDegreeProgram = new WGUDegreeProgram__c(Name = 'TestWGUDegreeProgram124', PAMSID__c = 124124124, Active__c = true, CatalogTerm__c = '201106');
        WGUDegreeProgram__c testWGUDegreeProgram1 = new WGUDegreeProgram__c(Name = 'TestWGUDegreeProgram124', PAMSID__c = 124124125, Active__c = true, CatalogTerm__c = '201206');
        WGUDegreeProgram__c testWGUDegreeProgram2 = new WGUDegreeProgram__c(Name = 'TestWGUDegreeProgram124', PAMSID__c = 124124126, Active__c = false, CatalogTerm__c = '201306');
        insert testWGUDegreeProgram;
        insert testWGUDegreeProgram1;
        insert testWGUDegreeProgram2;
        
        WGUCourse__c testWGUCourse1 = new WGUCourse__c(Name = 'TestWGUCourse1', PAMSID__c = 1241241241);
        WGUCourse__c testWGUCourse2 = new WGUCourse__c(Name = 'TestWGUCourse2', PAMSID__c = 1241241242);        
        insert testWGUCourse1;
        insert testWGUCourse2;
        
        testWGUCourse1 = [SELECT Id, Name FROM WGUCourse__c WHERE Name = 'TestWGUCourse1' LIMIT 1];
        testWGUCourse2 = [SELECT Id, Name FROM WGUCourse__c WHERE Name = 'TestWGUCourse2' LIMIT 1];
        
        WGUCourseInProgram__c testWGUCourseInProgram1 = new WGUCourseInProgram__c(Course__c = testWGUCourse1.Id, Program__c = testWGUDegreeProgram1.Id, Transferable__c = true);
        WGUCourseInProgram__c testWGUCourseInProgram2 = new WGUCourseInProgram__c(Course__c = testWGUCourse2.Id, Program__c = testWGUDegreeProgram1.Id, Transferable__c = true);        
        insert testWGUCourseInProgram1; 
        insert testWGUCourseInProgram2;
        
        CAREProgramMiddleEarth__c testCAREProgramMiddleEarth = new CAREProgramMiddleEarth__c(CareProgramCode__c = testCAREProgram.Id, BannerProgramCode__c = testWGUDegreeProgram.Id);
        insert testCAREProgramMiddleEarth;
        
        Opportunity testOpportunity = new Opportunity(Name = 'testEvalCourseTriggerOpp', CloseDate = Date.Today(), StageName = 'Applicant', 
                                                      MarketingReferID__c = '549519sdfa8', MarketingProgram__c = testCAREProgramMiddleEarth.Id);
        insert testOpportunity;                
        
        TransferEvaluation__c testTransferEvaluation = new TransferEvaluation__c(Name = 'testTransferEval124', Opportunity__c = testOpportunity.Id, 
                                                                                 EligibilityStatus__c = 'Eligible', EvaluationStatus__c = 'Pending');
        testTransferEvaluation.assignedTo__c = testUser.Id;                                                                                
        insert testTransferEvaluation;
        //Trigger just created 2 equivalent courses 
        
        List<StudentEquivalentCourse__c> eqCrss = [SELECT Id, Name, TransferEvaluation__c FROM StudentEquivalentCourse__c LIMIT 20];
        
        for (StudentEquivalentCourse__c eqCrs : eqCrss)
        {
            System.debug('=====> ' + eqCrs + ' ' + testTransferEvaluation.Id);
        }               
        
        testTransferEvaluation = [SELECT Name, Opportunity__c, EvaluationStatus__c, WGUDegreeProgram__c FROM TransferEvaluation__c WHERE Id = :testTransferEvaluation.Id LIMIT 1];
        
        StudentTranscript__c testTranscript = new studentTranscript__c(Opportunity__c = testOpportunity.Id);
        insert testTranscript;                
        
        StudentTransferredCourse__c transCourse1 = new studentTransferredCourse__c(StudentTransferInstitution__c = testTranscript.Id);
        StudentTransferredCourse__c transCourse2 = new studentTransferredCourse__c(StudentTransferInstitution__c = testTranscript.Id); 
        insert transCourse1;
        insert transCourse2;                    
        
        StudentEquivalentCourse__c equivCourse1 = new studentEquivalentCourse__c(TransferEvaluation__c = testTransferEvaluation.Id, 
                                                                                 TransferredCourse__c = transCourse1.Id,
                                                                                 RequirementSatisfied__c = true);
        StudentEquivalentCourse__c equivCourse2 = new studentEquivalentCourse__c(TransferEvaluation__c = testTransferEvaluation.Id, 
                                                                                 TransferredCourse__c = transCourse2.Id,
                                                                                 RequirementSatisfied__c = true);
        insert equivCourse1;    
        insert equivCourse2;
        
        Id eqCrsRT = [SELECT Id FROM RecordType WHERE SObjectType = 'TranscriptToBanner__c' AND Name = 'StudentEquivalentCourse' LIMIT 1].Id;
        Id trCrsRT = [SELECT Id FROM RecordType WHERE SObjectType = 'TranscriptToBanner__c' AND Name = 'StudentTransferredCourse' LIMIT 1].Id;
        
        TranscriptToBanner__c trToBan1 = new TranscriptToBanner__c(StudentEquivalentCourse__c = equivCourse1.Id, RecordTypeId = eqCrsRT);
        TranscriptToBanner__c trToBan2 = new TranscriptToBanner__c(StudentTransferredCourse__c = transCourse1.Id, RecordTypeId = trCrsRT);
        insert trToBan1;
        insert trToBan2;                
        
        testTransferEvaluation.evaluationStatus__c = 'Sent';
        
        Test.startTest(); 
        
            update testTransferEvaluation; 
        
        Test.stopTest();
        
        List<TranscriptToBanner__c> testTransToBanList = [SELECT Id, StudentEquivalentCourse__c, StudentTransferredCourse__c, RecordType.Name FROM TranscriptToBanner__c LIMIT 20];
        
        System.debug('====> control size ' + testTransToBanList.size());
        
        Integer foundEq1 = 0;
        Integer foundEq2 = 0;
        Integer foundTrgEq = 0;
        Integer foundTr1 = 0;
        Integer foundTr2 = 0;                
        
        for (TranscriptToBanner__c testTransToBan : testTransToBanList)
        {
            System.debug('========> EquivCourse: ' + testTransToBan.StudentEquivalentCourse__c);
            System.debug('========> TransCourse: ' + testTransToBan.StudentTransferredCourse__c);
            System.debug('========> RecordType: ' + testTransToBan.RecordType.Name);
            System.debug('========> TestValues: ' + equivCourse1.Id + ' ' + equivCourse2.Id + ' ' + transCourse1.Id + ' ' + transCourse2.Id);
            if (testTransToBan.StudentEquivalentCourse__c == equivCourse1.Id)
            {
                foundEq1 += 1;
            }
            else if (testTransToBan.StudentEquivalentCourse__c == equivCourse2.Id)
            {
                foundEq2 += 1;
            }
            else if (testTransToBan.StudentTransferredCourse__c == transCourse1.Id)
            {
                foundTr1 += 1;
            }
            else if (testTransToBan.StudentTransferredCourse__c == transCourse2.Id)
            {
                foundTr2 += 1;
            }  
            else if (testTransToBan.StudentEquivalentCourse__c != null && testTransToBan.StudentTransferredCourse__c == null)
            {
                foundTrgEq += 1;
            }       
        }
        
        System.assertEquals(foundEq1, 1);
        System.assertEquals(foundEq2, 1);
        System.assertEquals(foundTr1, 1);
        System.assertEquals(foundTr2, 1); 
        //System.assertEquals(foundTrgEq, 2);                                                                  
    }
}