src/objects/CareerServices__c.object
<CustomObject>
    <description>This object allows the Career Services team to track all appointment sessions completed for students related to career services..</description>
    <fields>
        <fullName>StudentID__c</fullName>
        <formula>Student__r.StudentID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Career Services</relationshipLabel>
        <relationshipName>Student</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Career Services</label>
    <nameField>
        <displayFormat>CS# {00}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Career Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>Student Identification number, also known as Banner ID.</description>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The mentor pidm so we can use external id&apos;s</description>
        <externalId>true</externalId>
        <inlineHelpText>The WGU PIDM assigned to this mentor.</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentCourse__c.object
<CustomObject>
    <description>Represents a course that a student may take at WGU. Multiple Assessments or Tasks may be required to complete the course.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the course (Completed,Enrolled,Planned).</description>
        <inlineHelpText>The status of the course (Completed,Enrolled,Planned).</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InProgress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentTerm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term this course instance is scheduled</description>
        <label>Student Term</label>
        <referenceTo>StudentTerm__c</referenceTo>
        <relationshipLabel>Student Course</relationshipLabel>
        <relationshipName>StudentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Course</relationshipLabel>
        <relationshipName>StudentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Course</label>
    <nameField>
        <label>Student Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentTerm__c.object
<CustomObject>
    <description>Instance of a student period of time, using recordtype to designate between academic terms, term breaks, withdraw/drops, etc.</description>
    <fields>
        <fullName>ApprovalDateTime__c</fullName>
        <description>The date and time in which the term was approved.</description>
        <label>Approval Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Approval status of the term in relation to dates on courses.</description>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The date that the term ends.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The starting date of the term. WGU Terms are normally 6 months but it is possible that one may be smaller because it is a term break.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Terms</relationshipLabel>
        <relationshipName>myTerms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Term</label>
    <nameField>
        <label>Student Term Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/FDPListController.cls
public with sharing class FDPListController {
    public Map<Id,StudentObj> StudentsMap {get;set;}
    public List<StudentObj> StudentsList {get;set;}
    public List<MentorObj> MentorsList {get;set;}
    public Id MentorUserId;

    public with sharing class MentorObj {
      public Id MentorUserId {get;set;}
      public String MentorPIDM {get;set;}
      public String MentorName {get;set;}
      public Boolean IsCurrentUser {get;set;}
    }

    public with sharing class StudentObj {
      public Map<String,TermCode> TermCodesMap {get;set;}
      public List<TermCode> TermCodesList {get;set;}
      public String Name {get;set;}
      public String PIDM {get;set;}
      public String StudentId {get;set;}
      public Id Id {get;set;}
      public Boolean RequiresApproval {get;set;}
      public DateTime LastApprovedDate {get;set;}
      public DateTime LastModifiedDate {get;set;}
      public Integer DueIn {get;set;}
      public Date RollDate {get;set;}
      public String Status {get;set;}
      public Boolean IsRendered {get;set;}
      public StudentObj() {
        TermCodesMap = new Map<String,TermCode>();
        TermCodesList = new List<TermCode>();
        LastApprovedDate = DateTime.newInstance(1901,1,1);
        LastModifiedDate = DateTime.newInstance(1901,1,1);
        RequiresApproval = false;
        IsRendered = false;
      }
    }

    public with sharing class TermCode {
    	public List<StudentTerm__c> terms {get;set;}
    	public String TermCode {get;set;}
    	public DateTime LastApprovedDate {get;set;}
    	public DateTime LastModifiedDate {get;set;}
        public Date StartDate {get;set;}
        public Boolean RequiresApproval {get;set;}
        public Integer UnenrolledCourses {get;set;}
    	public TermCode() {
    		terms = new List<StudentTerm__c>();
    		LastApprovedDate = DateTime.newInstance(1901,1,1);
    		LastModifiedDate = DateTime.newInstance(1901,1,1);
    	}
    	public TermCode(String pTermCode) {
    		this();
    		TermCode = pTermCode;
    	}
    }

	public FDPListController() {}
        public with sharing class FDPListException extends Exception{}

        public PageReference changeMentor() {
          this.MentorUserId = (Id)ApexPages.currentPage().getParameters().get('MentorId');
          loadStudents();
          return null;
        }

        public void loadStudents() {
          StudentsMap = new Map<Id,StudentObj>();
          StudentsList = new List<StudentObj>();
	  List<StudentTerm__c> results = [
	    select Student__r.Id,
	    Student__r.Name,
	    Student__r.PIDM__c,
	    Student__r.StudentId__c,
	    LastModifiedDate,
	    ApprovalDateTime__c,
	    Approved__c,
            StartDate__c,
	    Name,
          (
            select Name,
            Status__c
            from StudentCourses__r
            where Status__c != 'Enrolled'
            and Status__c != 'Submitted'
            and Status__c != 'Completed'
            and Status__c != 'Failed'
          )
		  from StudentTerm__c
          where ((
              StartDate__c <= NEXT_MONTH
              and EndDate__c >= NEXT_MONTH
            ) or (
              StartDate__c <= Today
              and EndDate__c >= Today
            )) and Student__r.Mentor__c = :MentorUserId
		];
		for(StudentTerm__c res:results) {
			StudentObj student;
			if(!StudentsMap.containsKey(res.Student__c)) {
				student = new StudentObj();
				StudentsMap.put(res.Student__c,student);
			} else {
				student = StudentsMap.get(res.Student__c);
			}
			TermCode tc;
			if(!student.TermCodesMap.containsKey(res.Name)) {
				tc = new TermCode(res.Name);
                tc.StartDate = res.StartDate__c;
				student.TermCodesMap.put(res.Name,tc);
				student.TermCodesList.add(tc);
			} else {
				tc = student.TermCodesMap.get(res.Name);
			}
			tc.terms.add(res);
			student.Name = res.Student__r.Name;
			student.Id = res.Student__c;
			student.StudentId = res.Student__r.StudentId__c;
			student.PIDM = res.Student__r.PIDM__c;
		}
		for(Id key: StudentsMap.keySet()) {
			StudentObj student = StudentsMap.get(key);
			for(String code : student.TermCodesMap.keySet()) {
				TermCode tc = student.TermCodesMap.get(code);
				for(StudentTerm__c term : tc.terms) {
					if(term.LastModifiedDate > tc.LastModifiedDate) {
					    tc.LastModifiedDate = term.LastModifiedDate;
					}
                }
                for(StudentTerm__c term : tc.terms) {
                    DateTime approvalDT = null;
                    if(term.ApprovalDateTime__c != null)
                        approvalDT = term.ApprovalDateTime__c.addMinutes(2);
					if(term.Approved__c && approvalDT > tc.LastApprovedDate) {
						tc.LastApprovedDate = approvalDT;
                    }
                    if(tc.UnEnrolledCourses == null || tc.UnenrolledCourses < term.StudentCourses__r.size()) {
                        tc.UnenrolledCourses = term.StudentCourses__r.size();
                    }
				}
				if(tc.LastModifiedDate > tc.LastApprovedDate) {
                    tc.RequiresApproval = true;
					student.RequiresApproval = true;
                    student.IsRendered = true;
                    if(tc.StartDate < student.RollDate || student.RollDate == null) {
                      student.DueIn = Date.Today().daysBetween(tc.StartDate);
                      student.RollDate = tc.StartDate;
                    }
				} else if(tc.UnenrolledCourses > 0) {
                    student.Status = 'Approved';
                    student.IsRendered = true;
                    if(tc.StartDate < student.RollDate || student.RollDate == null) {
                      student.DueIn = Date.Today().daysBetween(tc.StartDate);
                      student.RollDate = tc.StartDate;
                    }
                }
			}
			StudentsList.add(student);
		}

        }

	public void initialize() {
          User u = [select
            ContactId,
            UserType,
            Name,
            PIDM__c
            from User
            where id = :UserInfo.getUserID()];
          if(u.UserType != 'Standard') {
            throw new FDPListException('You do not have access to this page.');
          }
          MentorUserId = u.Id;
          MentorsList = new List<MentorObj>();
          List<AggregateResult> mList = [select
            Mentor__r.Name mname,
            Mentor__r.PIDM__c mpidm,
            Mentor__r.Id mid
            from Contact
            where Mentor__r.Name != null
            and Mentor__c != :u.Id
            group by Mentor__r.Name,
            Mentor__r.PIDM__c,
            Mentor__r.Id];
          MentorObj currentM = new MentorObj();
          currentM.MentorUserId = u.Id;
          currentM.MentorName = 'Current User (' + u.Name + ')';
          currentM.MentorPIDM = u.PIDM__c;
          currentM.IsCurrentUser = true;
          MentorsList.add(currentM);
          for(AggregateResult r : mList) {
            MentorObj mo = new MentorObj();
            mo.MentorUserId = (Id)r.get('mid');
            mo.MentorName = (String)r.get('mname');
            mo.MentorPIDM = (String)r.get('mpidm');
            mo.IsCurrentUser = false;
            MentorsList.add(mo);
          }
          loadStudents();
    }
}