src/objects/CareerServices__c.object
<CustomObject>
    <description>This object allows the Career Services team to track all appointment sessions completed for students related to career services..</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <formula>Student__r.StudentID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Career Services</relationshipLabel>
        <relationshipName>Student</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Career Services</relationshipLabel>
        <relationshipName>Career_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Career Services</label>
    <nameField>
        <displayFormat>CS# {00}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Career Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>College__c</fullName>
        <label>College</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>Student Identification number, also known as Banner ID.</description>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for wguProgram</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CareerServicesApptRequestController.cls
/*
This Controller is for Career Services Appointment Request VF page used by Students.
Author- Bhavadeep Raavi
*/
public with sharing class CareerServicesApptRequestController{
    public Contact studentInfo{get;set;}
    public Boolean disFlag{get;set;}
    public string fileName{get;set;} 
    public Blob fileBody{get;set;}  

    public Attachment attachment {
      get {
      if (attachment == null)
        attachment = new Attachment();
      return attachment;
    }
      set;
    }
    public CareerServices__c cs{get{
        if(cs==null){
            cs=new CareerServices__c();
            return cs;
        }else{
            return cs;
        }
    }set;}
    public CareerServicesApptRequestController(){
        try{
            
            string userPidm = [select pidm__c from User where id=:UserInfo.getUserId()].pidm__c; 
            studentInfo=[select Id,Name,firstname,Lastname,studentID__c,Status__c,WGUDegreeProgram__r.Name,College__c,Phone,Email from Contact where firstName=:UserInfo.getFirstName() and lastName=:UserInfo.getLastName() and PIDM__c =:userPidm  limit 1];    
            
        }catch(Exception e){
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You will need to log in to the WGU Portal to access this form. If you have forgotten your username or password for the WGU portal, please contact Student Services at 1-866-903-0110 or studentservices@wgu.edu. They are available 6am-Midnight (MT) Mon-Fri and 10am-7pm (MT) Sat-Sun'));      
        }
    }
    public PageReference submit(){
         try{
            cs.student__c= studentInfo.Id;
            cs.FirstName__c = studentInfo.FirstName;
            cs.LastName__c = studentInfo.LastName;
            cs.Email__c = studentInfo.Email;
            cs.Phone__c = studentInfo.Phone;
            insert cs;
            
            disFlag=true;     
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Thank you for your request.')); 
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You got an error.Please contact your Administrator.'));      
        }
        try{
          //Attachment myAttachment  = new Attachment();  
          attachment.ParentId = cs.Id;
          insert attachment;  
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Error in attaching your file.'));      
        }
    return null;
    }
    public PageReference cancel(){
            PageReference pf = new PageReference('https://my.wgu.edu'); 
            pf.setRedirect(true); 
            return pf;
    }
    
}