src/objects/CareerServices__c.object
<CustomObject>
    <description>This object allows the Career Services team to track all appointment sessions completed for students related to career services..</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Career Services</relationshipLabel>
        <relationshipName>Student</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Career Services</label>
    <nameField>
        <displayFormat>CS# {00}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Career Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ProgramCode__c</fullName>
        <label>Program Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <label>Program Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StudentSearchHash__c.object
<CustomObject>
    <description>Lookup Object for Student Accounts by SSN Hash so that SSN need not be exposed in unencrypted fields.</description>
    <fields>
        <fullName>BirthDateHash__c</fullName>
        <description>Hash value for searching</description>
        <externalId>true</externalId>
        <label>BirthDateHash</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSNHash__c</fullName>
        <description>Hash value for searching</description>
        <externalId>true</externalId>
        <label>SSNHash</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSNLastFour__c</fullName>
        <description>Last four digits of SSN for searching</description>
        <externalId>true</externalId>
        <label>SSNLastFour</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Student Contact related field</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Search Hashes</relationshipLabel>
        <relationshipName>StudentSearchHashes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Search Hash</label>
    <nameField>
        <label>Student Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Search Hashes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FindStudentController.cls
/*
 * Author Paul Coleman
 * Western Governors University
 *
 * Date February 13, 2013 @ 1420hrs
 * Revised: Person Account Refactor - Paul Coleman 
 * 
 * Date October 30, 2012 @ 1130 hrs
 * Revised: (security audit compliance: with sharing) 
 * 
 */
public with sharing class FindStudentController {

    @RemoteAction
    public static String searchSSN( String ssn, Boolean isLast4 ) {
    
        List<StudentSearchHash__c> students = new List<StudentSearchHash__c>();
        if ( isLast4 ) {
          students = [SELECT count() FROM StudentSearchHash__c WHERE SSNLastFour__c = :Integer.ValueOf(ssn)]>0? [SELECT Id, Name, Student__c, Student__r.Name, Student__r.FirstName,Student__r.LastName, Student__r.ProgramCode__c, Student__r.ProgramName__c, Student__r.MailingCity, Student__r.MailingState,Student__r.RecordType.Name FROM StudentSearchHash__c WHERE SSNLastFour__c = :Integer.ValueOf(ssn)  LIMIT 200]: new List<StudentSearchHash__c>();
        } else { 
          String ssnHash = EncodingUtil.base64Encode( Crypto.generateDigest( 'SHA1', Blob.valueOf( ssn ) ) );
          students = [SELECT count() FROM StudentSearchHash__c WHERE SSNHash__c = :ssnHash]>0? [SELECT Id, Name, Student__c, Student__r.Name,Student__r.FirstName,Student__r.LastName, Student__r.ProgramCode__c, Student__r.ProgramName__c, Student__r.MailingCity, Student__r.MailingState,Student__r.RecordType.Name FROM StudentSearchHash__c WHERE SSNHash__c = :ssnHash  LIMIT 200]: new List<StudentSearchHash__c>();
        }
        for( StudentSearchHash__c hash: students ){
            hash.Name = hash.Student__r.LastName + ', ' +hash.Student__r.FirstName; 
        }
        return  JSONUtil.getJSON(students);
    }
    
    @RemoteAction
    public static String searchBirthDate( String birthdate ) {
        
        List<StudentSearchHash__c> students = new List<StudentSearchHash__c>();
        Date bDate = Date.parse(birthdate);
        String bdateHash = EncodingUtil.base64Encode( Crypto.generateDigest( 'SHA1', Blob.valueOf( bDate.format() ) ) );
        students = [SELECT count() FROM StudentSearchHash__c WHERE BirthDateHash__c = :bdateHash ]>0? [SELECT Id, Name, Student__c, Student__r.Name, Student__r.FirstName, Student__r.LastName, Student__r.ProgramCode__c, Student__r.ProgramName__c, Student__r.MailingCity, Student__r.MailingState,Student__r.RecordType.Name FROM StudentSearchHash__c WHERE BirthDateHash__c = :bdateHash  LIMIT 500]: new List<StudentSearchHash__c>();
        for( StudentSearchHash__c hash: students ){
          hash.Name = hash.Student__r.LastName + ', ' +hash.Student__r.FirstName; 
        }
        
        return JSONUtil.getJSON(students);
    }
    
}