src/objects/CareProgramMiddleEarth__c.object
<CustomObject>
    <description>Used to bring together the CARE Program code and the PAMS program code together.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CAREProgramTitle__c</fullName>
        <formula>CAREProgramCode__r.ProgramLabel__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CARE Program Title</label>
        <type>Text</type>
    </fields>
    <label>CARE Program Middle Earth</label>
    <nameField>
        <label>Program Middle Earth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs Middle Earth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CAREStatusListView__c</fullName>
        <formula>LEFT(TEXT(CareStatus__c), 4)</formula>
        <label>CARE Status List View</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactEmail__c</fullName>
        <formula>Account.StudentContact__r.Email</formula>
        <label>Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactLastName__c</fullName>
        <formula>StudentContact__r.LastName</formula>
        <label>Contact Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Program</label>
        <referenceTo>CareProgramMiddleEarth__c</referenceTo>
        <relationshipLabel>CAREProfile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NameAndPhone__c</fullName>
        <formula>StudentContact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonalPageIdentifier__c</fullName>
        <description>This is for the personal page to store the ID to support the public personal page.</description>
        <label>Personal Page Identifier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAttributes__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Convenience lookup for Informatica to grab all information about a Paid Applicant in one shot instead of splitting into multiple jobs.</description>
        <label>Student Attributes</label>
        <referenceTo>StudentAttributes__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Personal_Pages_Link__c.object
<CustomObject>
    <description>Personal Pages Links is for the creation and maintenance of links on the personal pages.</description>
    <fields>
        <fullName>LinkCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Pages Link Category</label>
        <referenceTo>PersonalPagesLinkCategory__c</referenceTo>
        <relationshipLabel>Personal Pages Links</relationshipLabel>
        <relationshipName>Personal_Pages_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LinkGroup__c</fullName>
        <label>Link Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkType__c</fullName>
        <label>Link Type</label>
        <picklist>
            <picklistValues>
                <fullName>Web Page</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TilePosition__c</fullName>
        <label>Tile Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>affiliation__c</fullName>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>WGU-SLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TEX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TEN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>image__c</fullName>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>label__c</fullName>
        <description>The display name for the link.</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>last_updated__c</fullName>
        <label>Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>link__c</fullName>
        <label>Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sort_order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Personal Pages Link</label>
    <nameField>
        <label>Personal Pages Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Pages Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PersonalPagesLinkCategory__c.object
<CustomObject>
    <fields>
        <fullName>ProgramSpecific__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Program Specific</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Personal Pages Link Category</label>
    <nameField>
        <label>Personal Pages Link Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Pages Link Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PersonalPagesTextArea__c.object
<CustomObject>
    <fields>
        <fullName>TextArea__c</fullName>
        <label>Text Area</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Personal Pages Text Area</label>
    <nameField>
        <label>Personal Pages Text Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Pages Text Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentAttributes__c.object
<CustomObject>
    <description>Custom object to manage student attributes via portal and sites, with update triggers to Contact/Account</description>
    <fields>
        <fullName>Affiliation__c</fullName>
        <description>WGU affiliate the student belongs to</description>
        <inlineHelpText>Set the student&apos;s WGU affiliation.</inlineHelpText>
        <label>University Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>WGU</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student Attributes</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserAttributes__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Extension__c</fullName>
        <label>Extension</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JsonConfigData__c</fullName>
        <description>A JSON Configuration String for Visualforce/Javascript purposes, the context and semantics of which should be dictated by RecordTypeId</description>
        <inlineHelpText>This field is typically not designed for manual editing</inlineHelpText>
        <label>JsonConfigData</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Personal800Number__c</fullName>
        <label>Personal 800 Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PreferredFirstName__c</fullName>
        <label>Preferred First Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredLastName__c</fullName>
        <label>Preferred Last Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>University800Number__c</fullName>
        <defaultValue>&quot;(866) 225-5948&quot;</defaultValue>
        <label>University 800 number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>UserEmail__c</fullName>
        <description>Pulls the email down from user.</description>
        <formula>User__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UserEmail</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserAttributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Attributes</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserAttributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PersonalPageController.cls
public class PersonalPageController {
    
    public String firstName { get; set; }
    public Integer step { get; set; }
    public String lastName { get; set; }
    public String ecName { get; set; }
    public String ecEmail { get; set; }
    public String ecPhone { get; set; }
    public String ecPhoto { get; set; }
    public String programName { get; set; }
    public String personalPagesLinksJson { get; set; }
 //   public List<PageLink> tileLinks { get; set; }
    public Map<Integer,PageLink> tileLinks { get; set; }
    public List<LinkCategory> pageLinks { get; set; }
    public String errorMessage { get; set; }
    public String studentEmail{get; set; }
    public Map<String, String> textAreaMap { get; set; }
    public String studentComments {get; set; }
    public String studentPhone {get; set; }
    public String fullName { get; set; }
    public String careProgramTitle { get; set; }

    
    public PageReference initCheck()
    {
        String pid = Apexpages.currentPage().getParameters().get('pid');
        if(pid == null) {
            PageReference pag = new PageReference('/apex/PersonalPagesErrorPage');
            pag.setRedirect(true);
            return pag;
       }
       
        List<Opportunity> profiles = [Select id, NameAndPhone__c,
                                      CAREStatusListView__c,
                                      ContactLastName__c,
                                      MarketingProgram__r.Name, OwnerId,
                                      StudentAttributes__r.Affiliation__c,
                                      ContactEmail__c
                                      from Opportunity 
                                      where PersonalPageIdentifier__c = :pid];
        
        if (profiles.size() < 1)
        {

            PageReference pag = new PageReference('/apex/PersonalPagesErrorPage');
            pag.setRedirect(true);
            return pag;
        }
       // PageReference pag = new PageReference('http://devfull-wgu.cs16.force.com/personalpage/' + pid);
        return null;
    }
    
    public PersonalPageController() {
        String pid = Apexpages.currentPage().getParameters().get('pid');
        if(pid == null) {
            

             return;
        }
        
        String errorMessage = 'none';
       List<Opportunity> profiles = [Select id, NameAndPhone__c,
                                      CAREStatusListView__c,
                                      ContactLastName__c,
                                     MarketingProgram__r.CAREProgramTitle__c,
                                      MarketingProgram__r.Name, OwnerId,
                                      StudentAttributes__r.Affiliation__c,
                                      ContactEmail__c
                                      from Opportunity 
                                      where PersonalPageIdentifier__c = :pid];
        
        if (profiles.size() < 1)
        {

             return;
        }
        
        Opportunity profile = profiles.get(0);
        firstName = profile.NameAndPhone__c;
        studentEmail = profile.ContactEmail__c;
        fullName = profile.NameAndPhone__c + ' ' + profile.ContactLastName__c;
        
        if (profile.CAREStatusListView__c == 'PROS')
        {
            step = 1;
        }
        else if (profile.CAREStatusListView__c == 'APIN' || 
                 profile.CAREStatusListView__c == 'APNN' ||
                 profile.CAREStatusListView__c == 'PRAP' ||
                 profile.CAREStatusListView__c == 'APCO' )
        {
            step = 2;
        }
        else if (profile.CAREStatusListView__c == 'APAC')
        {
            step = 3;
        }
                 
        else {
            step = 4;
        }

        
        List<UserAttributes__c> owners = [SELECT Id, OwnerId, IsDeleted, Name, RecordTypeId,
                                          
                                          Extension__c, Personal800Number__c, 
                                          PreferredFirstName__c, PreferredLastName__c, UserEmail__c,
                                          University800Number__c, User__c,  JsonConfigData__c FROM UserAttributes__c
                                          where  User__c = :profile.OwnerId];
        

        ecName = owners.get(0).PreferredFirstName__c + ' ' +  owners.get(0).PreferredLastName__c;
        ecEmail = owners.get(0).UserEmail__c;
        ecPhone = owners.get(0).University800Number__c + ' x' + owners.get(0).Extension__c; 
        
        
        //ConnectApi.UserDetail ecUserDetail = ConnectApi.ChatterUsers.getUser(null, owners.get(0).OwnerId);
        //String ecPhoto = ecUserDetail.photo.smallPhotoUrl;
        careProgramTitle  = profile.MarketingProgram__r.CAREProgramTitle__c;   
     
        programName = profile.MarketingProgram__r.name;
        String affiliation = profile.StudentAttributes__r.Affiliation__c;
        //System.debug('programName: ' + programName);
        
        List<Personal_Pages_Link__c> personalPagesLinks = 
            [SELECT Id,  IsDeleted,
             Name, 
             Program__c,
             active__c,
             image__c, 
             label__c,
             last_updated__c,
             link__c, 
             sort_order__c, 
             TilePosition__c, 
             LinkCategory__r.name, 
             LinkCategory__r.sortorder__c, 
             LinkType__c, 
             LinkCategory__r.isdeleted, 
             LinkCategory__r.programspecific__c, 
             LinkGroup__c
             FROM Personal_Pages_Link__c 
             where IsDeleted = false and LinkCategory__r.isdeleted = false
             and active__c = true and 
             (program__C = :programName or (program__C = null and link__C != null))
             order by LinkCategory__r.sortorder__c asc, sort_order__c asc
            ];
      //  System.debug(personalPagesLinks);
        LinkCategory currentCategory;
        pageLinks = new List<LinkCategory>();
      //  tileLinks = new PageLink[12];
      tileLinks  = new Map<Integer,PageLink>();
        
        for(Personal_Pages_Link__c link : personalPagesLinks) {
     //       System.debug(link);
            String nameLink = link.LinkCategory__r.name;
                        
            if(currentCategory == null ||   currentCategory.name != nameLink  ) {
                
                currentCategory = new LinkCategory(nameLink);
                
                pageLinks.add(currentCategory);
            }
            
            String linkType = link.LinkType__c;
            if (linktype == 'PDF') {
                linktype = 'pdf';
            } else if (linktype == 'Web Page') {
                linktype = 'link';
                
            } else if (linktype == 'Video') {
                linktype = 'video';
            }
            else if (linktype == 'Image'){
                 linktype = 'video';
            } 
                
            PageLink pageLink = new PageLink(linkType,
                                             link.link__c,
                                             link.label__c,
                                             link.TilePosition__c
                                             );
             currentCategory.linkList.add(pageLink);
           // System.debug('PageLink: ' + pageLink);
            if(link.TilePosition__c != null && link.TilePosition__c >= 0 && link.TilePosition__c < 12) {
           //    tileLinks[(Integer)link.TilePosition__c] = pageLink;
            //    System.debug('link.TilePosition__c' + link.TilePosition__c);
               tileLinks.put((Integer)link.TilePosition__c, pageLink);
          //      for (Integer i =0; i < 12; i++)
          //      {
         //           System.debug('tileLink ' + i + ' : ' + tileLinks[i]);
         //           }
             //   System.debug('tileLinks' + tileLinks[(Integer)link.TilePosition__c]);
                
            }
            // System.debug(tileLinks);
        }
        
        for (LinkCategory lc: pageLinks)        
        {
            Boolean includeProgram = false;
            for (PageLink pl : lc.linkList)
            {
                if (pl.tilePos  == 0)
                {
                    includeProgram =true;
                    break;
                }
            }
            if (includeProgram )
            {
                lc.name += ': ' + careProgramTitle;
                break;
            }
        }
        
        personalPagesLinksJson = JSON.serialize(personalPagesLinks);
        
        List<PersonalPagesTextArea__c> textAreaList = [SELECT Name,TextArea__c FROM PersonalPagesTextArea__c];
        
        textAreaMap = new Map<String, String>();
        for(PersonalPagesTextArea__c textArea : textAreaList) {
            textAreaMap.put(textArea.name, textArea.textArea__c);
        }
        
        fillInBlankTileItems();
    }
    
    private void fillInBlankTileItems() {
       for(integer i = 0; i < 12; i++) {
       if (tileLinks.get(i) == null)
       {
           tileLinks.put(i,new PageLink('none', '', 'none', (Decimal) i));
         //    System.debug('Null Link' + i);
       }

       //       System.debug(tileLinks[i]);
      //      if(tileLinks[i] == null) {
      //          tileLinks[i] = new PageLink();
      //          System.debug('Null Link' + i);
      //     }
        }
    }
    
    public class PageLink {
        
        public String type { get; set; }
        public String address { get; set; }
        public String label { get; set; }
        public Decimal tilePos{ get; set; }
       public Boolean isNotBlank;
         public Boolean isBlank;
        
        public Boolean getIsBlank()
        {
            if ((address == null) || address.length() < 1)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
                public Boolean getIsNotBlank()
        {
           
                return !getIsBlank();
     
        }
        
        
        public PageLink() {}
        
        public PageLink(String type, String address, String label, Decimal tilePos) {
            this.type = type;
            this.address = address;
            this.label = label;
            this.tilePos = tilePos;
            this.isNotBlank= isNotBlank;
            this.isBlank= isBlank;
        }
        
    }
    
    public class LinkCategory {
        
        public String name { get; set; }
        public List<PageLink> linkList { get; set; }
        
        public LinkCategory(String name) {
            this.name = name;
            linkList = new List<PageLink>();
        }
        
    }
    
    public void actionSend() {
        List<String> listofst =  new List<String>();
        if (!(studentComments == null))
        {
            listofst = studentComments.split('\n');
        }
        //studentComments.replaceAll('(\r\n|\n)', '<br />');
     //   system.debug(studentComments);
        String[] recipients = new String[]{ecEmail};
            Messaging.reserveSingleEmailCapacity(recipients.size());
        Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
        msg.setSenderDisplayName(fullName);
        msg.setReplyTo(studentEmail);
        msg.setToAddresses(recipients);
        msg.setSubject('Personal Page Message from ' + fullName );
        String htmlBody = 'Student Name: ' + fullName + '<br/>';
        htmlBody += 'Student Email Address: ' + studentEmail + '<br/>';
        htmlBody += 'Student Phone: ' + studentPhone + '<br/>';
        htmlBody += 'Student Comments: <br/>';
        for (String s: listofst)
        {
            htmlBody += s + '<br/>';
        }
        msg.setHtmlBody(htmlBody );
        //  msg.setPlainTextBody('Student Name: ' + fullName + '\nStudent Email Address: ' + studentEmail + '\nStudent Phone: ' + studentPhone + '\nStudent Comments: ' +   studentComments);
        msg.setSaveAsActivity(false);
        msg.setUseSignature(false);
        
        if (Test.isRunningTest())
        {
        }
        else
        {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {msg}, false);
            
            
            
        }
        
        studentComments = null;
       
        // PageReference pageRef = new PageReference(ApexPages.currentPage().getUrl());
        //pageRef.setRedirect(true);
        // return pageRef;
        
    }
    
}