src/objects/CareProgramMiddleEarth__c.object
<CustomObject>
    <description>Used to bring together the CARE Program code and the PAMS program code together.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>CARE Program Middle Earth</label>
    <nameField>
        <label>Program Middle Earth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs Middle Earth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CAREStatusListView__c</fullName>
        <formula>LEFT(TEXT(CareStatus__c), 4)</formula>
        <label>CARE Status List View</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CareStatus__c</fullName>
        <label>CARE Status</label>
        <picklist>
            <picklistValues>
                <fullName>PROS – Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PRAP – Prospect Applied Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APNN – Application Incomplete PRAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APIN – Application Incomplete APCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APCO – Application Complete, Unpaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC – Application Complete, Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REDI - Admission Decision Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEND - Additional Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAMT - Auto Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMT – Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTV – Fit and EWB Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLRD - Cleared to Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENRL – Enrolled and Assigned a Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEVR – Never completed EWOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DROP – Dropped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAMT - Not Admitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAYT - Not Admitted Yet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MATR – Matriculated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRAD – Ready for Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALUMNI - Graduated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ContactEmail__c</fullName>
        <formula>Account.StudentContact__r.Email</formula>
        <label>Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactLastName__c</fullName>
        <formula>StudentContact__r.LastName</formula>
        <label>Contact Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Program</label>
        <referenceTo>CareProgramMiddleEarth__c</referenceTo>
        <relationshipLabel>CAREProfile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NameAndPhone__c</fullName>
        <formula>StudentContact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonalPageIdentifier__c</fullName>
        <description>This is for the personal page to store the ID to support the public personal page.</description>
        <label>Personal Page Identifier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAttributes__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Convenience lookup for Informatica to grab all information about a Paid Applicant in one shot instead of splitting into multiple jobs.</description>
        <label>Student Attributes</label>
        <referenceTo>StudentAttributes__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>StudentContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CARE Profile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>IntakeInterviewReady</fullName>
        <active>true</active>
        <businessProcess>Intake</businessProcess>
        <label>IntakeInterviewReady</label>
    </recordTypes>
</CustomObject>

src/objects/Personal_Pages_Link__c.object
<CustomObject>
    <description>Personal Pages Links is for the creation and maintenance of links on the personal pages.</description>
    <fields>
        <fullName>LinkCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Pages Link Category</label>
        <referenceTo>PersonalPagesLinkCategory__c</referenceTo>
        <relationshipLabel>Personal Pages Links</relationshipLabel>
        <relationshipName>Personal_Pages_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LinkGroup__c</fullName>
        <label>Link Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkType__c</fullName>
        <label>Link Type</label>
        <picklist>
            <picklistValues>
                <fullName>Web Page</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TilePosition__c</fullName>
        <label>Tile Position</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>affiliation__c</fullName>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>WGU-SLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TEX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TEN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>image__c</fullName>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>label__c</fullName>
        <description>The display name for the link.</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>last_updated__c</fullName>
        <label>Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>link__c</fullName>
        <label>Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sort_order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Personal Pages Link</label>
    <nameField>
        <label>Personal Pages Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Pages Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PersonalPagesLinkCategory__c.object
<CustomObject>
    <fields>
        <fullName>ProgramSpecific__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Program Specific</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Personal Pages Link Category</label>
    <nameField>
        <label>Personal Pages Link Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Pages Link Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentAttributes__c.object
<CustomObject>
    <description>Custom object to manage student attributes via portal and sites, with update triggers to Contact/Account</description>
    <fields>
        <fullName>Affiliation__c</fullName>
        <description>WGU affiliate the student belongs to</description>
        <inlineHelpText>Set the student&apos;s WGU affiliation.</inlineHelpText>
        <label>University Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>WGU</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related contact record for this student&apos;s attributes</description>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students Attributes</relationshipLabel>
        <relationshipName>Students_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Attributes</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WGUPostalCode__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/UserAttributes__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Extension__c</fullName>
        <label>Extension</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredFirstName__c</fullName>
        <label>Preferred First Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredLastName__c</fullName>
        <label>Preferred Last Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>University800Number__c</fullName>
        <defaultValue>&quot;(866) 225-5948&quot;</defaultValue>
        <label>University 800 number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserAttributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Attributes</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserAttributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestPersonalPageController.cls
@IsTest
public class TestPersonalPageController{
    
    
    @IsTest
        public static void helloWorld(){
            
            System.assert(true);
            
        }
    
    @IsTest
        public static void TestContoller()
    {
        ID LockDownID = [SELECT id from Profile where name = 'LockDown'].id;
        
        //Create the EC User
        
        User u =  new User(LastName='Baggins',FirstName='Frodo',pidm__c='a1111111', Username='ec@wgu.edu', Email='Baggins1@test.wgu.edu', Alias='MyEC', CommunityNickname='a', TimeZoneSidKey='GMT'
                           , LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=LockDownID, LanguageLocaleKey='en_US',WGUPostalCode__c='20776');
        insert u;
        
        //Create the EC UserAttributes__c
        UserAttributes__c uac = new UserAttributes__c();
        uac.Extension__c = '1212';
        uac.University800Number__c = '801888222';
        uac.PreferredFirstName__c = 'Frodo';
        uac.PreferredLastName__c = 'Baggins';  
        uac.User__c = u.id;   
        
        insert uac;   
        
        //Create MarketingProgram Program
        CareProgramMiddleEarth__c mark = new CareProgramMiddleEarth__c();
        mark.name = 'BBBB';
        insert mark;
        /*    

//Create student Contact record
Contact sc = new Contact();
sc.LastName = 'Baggins';
sc.FirstName = 'Bilbo';
sc.Email = 'BBBBaggins@test.wgu.edu';
insert sc;

Select id, NameAndPhone__c,
CAREStatusListView__c,
ContactLastName__c,
MarketingProgram__r.Name, OwnerId,
StudentAttributes__r.Affiliation__c,
ContactEmail__c
from Opportunity 
where PersonalPageIdentifier__c = :pid

*/
        //Create Student Care Profile (Opportunity)
        
        Contact student = TestStudentUser.getTestStudentContact();
        
        System.debug(student);
        
        Opportunity care = new Opportunity(AccountId=student.AccountId, 
                                           
                                           Name='Dudley Schults', 
                                           CloseDate=date.today(), 
                                           StageName='Intake', 
                                           RecordTypeId = [SELECT Id from RecordType where Name = 'IntakeInterviewReady' and SObjectType = 'Opportunity'].id);
        
        
        
        care.CAREStatus__c = 'PROS – Prospect';
        care.PersonalPageIdentifier__c = 'dudleyschultsAAAA';
        care.MarketingProgram__c = mark.id;
        care.OwnerId = u.id;
        care.StudentContact__c = student.id;
        
        insert care;
        
        
        //Create Student StudentAttributes__c
        
        StudentAttributes__c sac = new StudentAttributes__c();
        sac.Affiliation__c = 'WGU';
        
        insert sac;
        
        /*
[SELECT Id,  IsDeleted,
Name, 
Program__c,
active__c,
image__c, 
label__c,
last_updated__c,
link__c, 
sort_order__c, 
TilePosition__c, 
LinkCategory__r.name, 
LinkCategory__r.sortorder__c, 
LinkType__c, 
LinkCategory__r.isdeleted, 
LinkCategory__r.programspecific__c, 
LinkGroup__c
FROM Personal_Pages_Link__c 
where IsDeleted = false and LinkCategory__r.isdeleted = false
and active__c = true and 
(program__C = :programName or (program__C = null and link__C != null))
order by LinkCategory__r.sortorder__c asc, sort_order__c asc
];

*/
        PersonalPagesLinkCategory__c lc1 = new PersonalPagesLinkCategory__c(name='CAT1',sortorder__c=0,programspecific__c=false);
        PersonalPagesLinkCategory__c  lc2 = new PersonalPagesLinkCategory__c(name='CAT2',sortorder__c=1,programspecific__c=true);
        insert lc1;
        insert lc2;
        
        List<Personal_Pages_Link__c> pinks = new List<Personal_Pages_Link__c>();
        
        Personal_Pages_Link__c plink0 = new Personal_Pages_Link__c(active__c = true,
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page1.html',
                                                                   LinkCategory__c = lc1.id,
                                                                   LinkType__c = 'PDF',
                                             
                                                                   sort_order__c = -1);
        pinks.add(plink0);
        
        Personal_Pages_Link__c plink11 = new Personal_Pages_Link__c(active__c = true,
                                                                    image__c = 'My Image URL 1',
                                                                    label__c = 'Alt Label Text',
                                                                    link__c= 'http://link.to.me/page111.html',
                                                                    LinkCategory__c = lc2.id,
                                                                    LinkType__c = 'PDF',
                                                                    Program__c = 'BBBB',
                                                                    sort_order__c = 0);
        pinks.add(plink11);
        Personal_Pages_Link__c plink2 = new Personal_Pages_Link__c(active__c = true,
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page2.html',
                                                                   LinkCategory__c = lc2.id,
                                                                   LinkType__c = 'PDF',
                                                                   Program__c = 'BBBB',
                                                                   sort_order__c = 1);
        pinks.add(plink2);
        Personal_Pages_Link__c plink3 = new Personal_Pages_Link__c(active__c = true,
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page3.html',
                                                                   LinkCategory__c = lc2.id,
                                                                   LinkType__c = 'Web Page',
                                                                   Program__c = 'BBBB',
                                                                   sort_order__c = 2);
        pinks.add(plink3);
        Personal_Pages_Link__c plink4 = new Personal_Pages_Link__c(active__c = true,
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page4.html',
                                                                   LinkType__c = 'Web Page',
                                                                   LinkCategory__c = lc2.id,
                                                                   Program__c = 'BBBB',
                                                                   sort_order__c = 3);
        pinks.add(plink4);
        Personal_Pages_Link__c plink5 = new Personal_Pages_Link__c(active__c = true,
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page5.html',
                                                                   LinkType__c = 'Web Page',
                                                                   LinkCategory__c = lc1.id,
                                                             
                                                                   sort_order__c = 4);
        pinks.add(plink5);
        Personal_Pages_Link__c plink6 = new Personal_Pages_Link__c(active__c = true,
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page6.html',
                                                                   LinkType__c = 'Web Page',
                                                                   LinkCategory__c = lc1.id,
                                                              
                                                                   sort_order__c = 5);
        pinks.add(plink6);
        Personal_Pages_Link__c plink7 = new Personal_Pages_Link__c(active__c = true,
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page7.html',
                                                                   LinkType__c = 'Video',
                                                                   LinkCategory__c = lc1.id,
                                                            
                                                                   sort_order__c = 6);
        pinks.add(plink7);
        Personal_Pages_Link__c plink8 = new Personal_Pages_Link__c(active__c = true,
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page8.html',
                                                                   LinkCategory__c = lc1.id,
                                                                   LinkType__c = 'Video',
                                                       
                                                                   sort_order__c = 7);
        pinks.add(plink8);
        Personal_Pages_Link__c plink9 = new Personal_Pages_Link__c(active__c = true,
                                                                   image__c = 'My Image URL 1',
                                                                   label__c = 'Alt Label Text',
                                                                   link__c= 'http://link.to.me/page9.html',
                                                                   LinkCategory__c = lc1.id,
                                                                   LinkType__c = 'Video',
                                                                   Program__c = 'BBBB',
                                                                   sort_order__c = 8);
        pinks.add(plink9);
        Personal_Pages_Link__c plink10 = new Personal_Pages_Link__c(active__c = true,
                                                                    image__c = 'My Image URL 1',
                                                                    label__c = 'Alt Label Text',
                                                                    link__c= 'http://link.to.me/page10.html',
                                                                    LinkCategory__c = lc1.id,
                                                                    LinkType__c = 'Video',
                                                                    Program__c = 'BBBB',
                                                                    sort_order__c = 9);
        pinks.add(plink10);
        
        insert pinks;
        
        
        Test.startTest();
        
        PageReference pageRef = Page.PersonalPagesUAT;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('pid', 'dudleyschultsAAAA');
        PersonalPageController controller = new PersonalPageController();
        
        System.debug(controller.firstName + 'Khadijah_test' );
        System.debug(controller.fullName + 'Khadijah_test Abdullah_test' );
        System.debug(controller.ecName +'Frodo Baggins' );
         
        //  Admittedly mostly for code coverage
        // Check null comments
        controller.actionSend();
        controller.studentComments = 'This is my comment';
            controller.actionSend();
        
        Test.stopTest();
    }   
    
}