src/objects/CAREProgram__c.object
<CustomObject>
    <description>The object to handle all of the CARE Programs and their codes</description>
    <label>CARE Program</label>
    <nameField>
        <label>CARE Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CareProgramMiddleEarth__c.object
<CustomObject>
    <description>Used to bring together the CARE Program code and the PAMS program code together.</description>
    <fields>
        <fullName>BannerProgramCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banner Program Code</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>CARE Programs Middle Earth</relationshipLabel>
        <relationshipName>CAREProgramsMiddleEarth</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CAREProgramCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CARE Program Code</label>
        <referenceTo>CAREProgram__c</referenceTo>
        <relationshipLabel>CARE Programs Middle Earth</relationshipLabel>
        <relationshipName>CAREProgramsMiddleEarth</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CARE Program Middle Earth</label>
    <nameField>
        <label>Program Middle Earth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE Programs Middle Earth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KeyValue__c.object
<CustomObject>
    <description>Represents the Key Value pairs with record types.</description>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NumericValue__c</fullName>
        <description>The numeric value of the key value used for value based rules and sorting</description>
        <inlineHelpText>The numeric value of the key value used for value based rules and sorting</inlineHelpText>
        <label>Numeric Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UsageNotes__c</fullName>
        <description>Optional notes on how this key value pair might be used</description>
        <inlineHelpText>Enter optional usage notes on how this key value pair might be used in this cloud instance/sandbox.</inlineHelpText>
        <label>Usage Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>The external reference code for the title in the group.</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Key Value</label>
    <nameField>
        <label>Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Values</pluralLabel>
    <recordTypes>
        <fullName>Degree</fullName>
        <active>true</active>
        <description>The type of degree this record represents.</description>
        <label>Degree</label>
    </recordTypes>
    <recordTypes>
        <fullName>TransferDegree</fullName>
        <active>true</active>
        <description>Degrees that may transfer to WGU.</description>
        <label>Transfer Degree</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MarketingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Program</label>
        <referenceTo>CareProgramMiddleEarth__c</referenceTo>
        <relationshipLabel>CAREProfile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/StudentEquivalentCourse__c.object
<CustomObject>
    <description>WGU&apos;s courses and the link between transfered course for which a student may receive credit.</description>
    <fields>
        <fullName>TransferAttendance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Transfer Attendance</description>
        <label>Transfer Attendance</label>
        <referenceTo>TransferAttendance__c</referenceTo>
        <relationshipLabel>Student Equivalent Courses</relationshipLabel>
        <relationshipName>Student_Equivalent_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransferEvaluation__c</fullName>
        <description>Related Transfer Evaluation</description>
        <label>Transfer Evaluation</label>
        <referenceTo>TransferEvaluation__c</referenceTo>
        <relationshipLabel>Student Equivalent Courses</relationshipLabel>
        <relationshipName>StudentEquivalentCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WGUCourseInProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Course In Program</label>
        <referenceTo>WGUCourseInProgram__c</referenceTo>
        <relationshipLabel>Student Equivalent Courses</relationshipLabel>
        <relationshipName>Student_Equivalent_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Equivalent Course</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Student Equivalent Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Equivalent Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentTranscript__c.object
<CustomObject>
    <description>Object to manage the transcripts that must be collected through in-take and viewed by Mentors</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Student Transfer Institution</relationshipLabel>
        <relationshipName>opportunityTransferInstitution</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Student Transfer Institution</label>
    <nameField>
        <displayFormat>Institution-{0000}</displayFormat>
        <label>Student Transfer Institution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transfer Institution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentTransferredCourse__c.object
<CustomObject>
    <description>Shows courses that were transferred to WGU. Child object of Student Transfer Instituition.</description>
    <fields>
        <fullName>StudentTransferInstitution__c</fullName>
        <label>Student Transfer Institution</label>
        <referenceTo>StudentTranscript__c</referenceTo>
        <relationshipName>TransferCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TransferAttendance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer Attendance</label>
        <referenceTo>TransferAttendance__c</referenceTo>
        <relationshipLabel>Student Transferred Courses</relationshipLabel>
        <relationshipName>StudentTransferredCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Transferred Course</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transferred Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TransferAttendance__c.object
<CustomObject>
    <description>This is a record of attendance at other institutions including any degrees awarded, program, GPA, and dates of attendance.</description>
    <fields>
        <fullName>DegreeAwarded__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the degree awarded at a prior institution.</description>
        <label>Degree Awarded</label>
        <referenceTo>KeyValue__c</referenceTo>
        <relationshipLabel>Transfer Attendance</relationshipLabel>
        <relationshipName>TransferAttendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DegreeRelatesToWGUProgram__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the transcript degree is related to the WGU enrolled program for transfer credit purposes</description>
        <inlineHelpText>Is this degree related to the WGU enrolled program</inlineHelpText>
        <label>Degree Relates to WGU Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StudentTransferInstitution__c</fullName>
        <label>Student Transfer Institution</label>
        <referenceTo>StudentTranscript__c</referenceTo>
        <relationshipLabel>Transfer Attendance</relationshipLabel>
        <relationshipName>TransferAttendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transfer Attendance</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Transfer Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transfer Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TransferEvaluation__c.object
<CustomObject>
    <description>A Transfer evaluation is the parent object of the equivalent courses that will given to the student from their transfer work. It controls the overall status and assignment of the evaluation.</description>
    <fields>
        <fullName>EvaluationStatus__c</fullName>
        <label>Evaluation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready for Evaluation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appealed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The Link Between opportunities and transfer evaluations</description>
        <label>CARE Profile Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transfer Evaluations</relationshipLabel>
        <relationshipName>TransferEvaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The program that the student was eThe program that the student was evaluated for valuated for</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Transfer Evaluations</relationshipLabel>
        <relationshipName>TransferEvaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transfer Evaluation</label>
    <nameField>
        <label>Transfer Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfer Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WGUCourseInProgram__c.object
<CustomObject>
    <description>A many to many mapping that assigns which course are required to accomplish any degree program.</description>
    <fields>
        <fullName>TransferDegree__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>What Specific Degree or certification will satisfy this course during the transfer evaluation</description>
        <label>Transfer Degree</label>
        <referenceTo>KeyValue__c</referenceTo>
        <relationshipLabel>WGU Course In Programs (Transfer Degree)</relationshipLabel>
        <relationshipName>WGUCourseI_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransferMinimumDegree__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The minimum degree nessesary to be able to have this course satisfied in this program</description>
        <inlineHelpText>The minimum degree nessesary to be able to have this course satisfied in this program</inlineHelpText>
        <label>Transfer Minimum Degree</label>
        <referenceTo>KeyValue__c</referenceTo>
        <relationshipLabel>WGU Course In Programs</relationshipLabel>
        <relationshipName>WGUCourseInPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransferRelatedProgram__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field specifies whether or not the Degree and or the Minimum degree will only satisfy the requirement if it&apos;s a related field</description>
        <inlineHelpText>This field specifies whether or not the Degree and or the Minimum degree will only satisfy the requirement if it&apos;s a related field</inlineHelpText>
        <label>Transfer Related Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transferable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>checkbox field to indicate whether or not the course is transferable</description>
        <inlineHelpText>Is this course transferable?</inlineHelpText>
        <label>Transferable</label>
        <type>Checkbox</type>
    </fields>
    <label>WGU Course In Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WGU Course In Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <description>The ID that represents the program in PAMS.</description>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestEvalOppController.cls
@isTest
global class TestEvalOppController
{
    static testMethod void textEvalOppExt()
    {
        RecordType trDegRT = [SELECT Id FROM RecordType WHERE SObjectType = 'KeyValue__c' AND DeveloperName = 'TransferDegree' LIMIT 1];
        
        KeyValue__c noDegree = new KeyValue__c(RecordTypeId = trDegRT.Id, ExternalID__c = 'ND', Value__c = 'ND', NumericValue__c = 0);
        insert noDegree; 
            
        CAREProgram__c testCAREProgram = new CAREProgram__c(Name = 'TestCAREProgram124');
        insert testCAREProgram;
        
        WGUDegreeProgram__c testWGUDegreeProgram = new WGUDegreeProgram__c(Name = 'TestWGUDegP124', PAMSID__c = 124124124);
        insert testWGUDegreeProgram;

        CAREProgramMiddleEarth__c testCAREProgramMiddleEarth = new CAREProgramMiddleEarth__c(CareProgramCode__c = testCAREProgram.Id, BannerProgramCode__c = testWGUDegreeProgram.Id);
        insert testCAREProgramMiddleEarth;
        
        Opportunity testOpportunity = new Opportunity(Name = 'testEvalCourseTriggerOpp', CloseDate = Date.Today(), StageName = 'Applicant', MarketingProgram__c = testCAREProgramMiddleEarth.Id);
        insert testOpportunity;

        TransferEvaluation__c testTransferEvaluation = new TransferEvaluation__c(Name = 'testTransferEval124', Opportunity__c = testOpportunity.Id, EvaluationStatus__c = 'Pending');
        insert testTransferEvaluation;

        StudentTranscript__c testInstitution = new StudentTranscript__c(Opportunity__c = testOpportunity.Id);
        insert testInstitution;

        RecordType transDegreeRT = [SELECT Id FROM RecordType WHERE Name = 'Transfer Degree' AND SobjectType = 'KeyValue__c' LIMIT 1];
        
        KeyValue__c testBS = new KeyValue__c(RecordTypeId = transDegreeRT.Id, Name = 'testBS421', Value__c = '3', UsageNotes__c = 'Test421 Bachelor of Science');
        KeyValue__c testAS = new KeyValue__c(RecordTypeId = transDegreeRT.Id, Name = 'testAS421', Value__c = '2', UsageNotes__c = 'Test421 Associate of Science');
        insert testBS;
        insert testAS;       
        
        TransferAttendance__c testAttendance = new TransferAttendance__c(StudentTransferInstitution__c = testInstitution.Id, DegreeAwarded__c = testBS.Id, DegreeRelatesToWGUProgram__c = True);
        insert testAttendance;
        
        WGUCourseInProgram__c crsInProg1 = new WGUCourseInProgram__c(Transferable__c = True, TransferMinimumDegree__c = testAS.Id);
        WGUCourseInProgram__c crsInProg2 = new WGUCourseInProgram__c(Transferable__c = True, TransferDegree__c = testBS.Id, TransferRelatedProgram__c = True);  
        insert crsInProg1;
        insert crsInProg2;      
        
        StudentTransferredCourse__c transCourse1 = new StudentTransferredCourse__c(StudentTransferInstitution__c = testInstitution.Id);  
        StudentTransferredCourse__c transCourse2 = new StudentTransferredCourse__c(StudentTransferInstitution__c = testInstitution.Id); 
        insert transCourse1;
        insert transCourse2;
        
        StudentEquivalentCourse__c equivCourse1 = new StudentEquivalentCourse__c(TransferEvaluation__c = testTransferEvaluation.Id, WGUCourseInProgram__c = crsInProg1.Id);
        StudentEquivalentCourse__c equivCourse2 = new StudentEquivalentCourse__c(TransferEvaluation__c = testTransferEvaluation.Id, WGUCourseInProgram__c = crsInProg2.Id);
        insert equivCourse1;
        insert equivCourse2;         
        
        ApexPages.StandardController stdCont = new ApexPages.standardController(testOpportunity);
               
        OppTranscriptController testController = new OppTranscriptController(stdCont);
        
        testController.getInstCourses(); 
        testController.NewSubject = 'TestSubject1';
        testController.NewCrseName = 'TestCrseName1';
        testController.CurrentInstId = testInstitution.Id;         
        testController.add();
        testController.save();      
    }
}