src/objects/CaseUpdateHistory__c.object
<CustomObject>
    <description>This object stores a snapshot of case information created by trigger when a case status changes. This object is intended for analytic use only. It is a child to case in a master detail relationship.</description>
    <fields>
        <fullName>AppealStatus__c</fullName>
        <label>Appeal Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial Pend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Pend</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Update Histories</relationshipLabel>
        <relationshipName>CaseUpdateHistories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Escalated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Event</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <description>Owner of the case at the time that the case is edited</description>
        <label>Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ParentCaseCreatedDate__c</fullName>
        <label>Parent Case Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PreviousStatusChangeTime__c</fullName>
        <label>Previous Status Change Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PreviousStatusValue__c</fullName>
        <label>Previous Status Value</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer/Student Response Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Response Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <picklistValues>
                <fullName>1098-T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2nd Term Exmpt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3P (Third Party)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4th Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Absences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access Code Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anthem Singers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attention Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorizations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAES/MAES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefit Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bursar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capstone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Receipts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cert Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Personal Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citations</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <label>Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>ADA Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alumni</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alumni Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AppSupport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessment Scheduling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bursar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bursar-Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAREforce Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EWB Adds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excessive Attempts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Placement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITHelpDesk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Military Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Readmission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scholarship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scores</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StatusChangeTime__c</fullName>
        <label>Status Change Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StatusValue__c</fullName>
        <label>Status Value</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open: Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open: WGU Response Needed / In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open: Student Response Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Positive Feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative Feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Question/Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Failure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suggestion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Failure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breakdown of Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Lapse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FYI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Update History</label>
    <nameField>
        <displayFormat>CaseUpdateHistory-{0000}</displayFormat>
        <label>Case Update History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Update Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>EmployeeTask</fullName>
        <active>true</active>
        <description>WGU Employee Task</description>
        <label>Employee Task</label>
    </recordTypes>
</CustomObject>

src/classes/CaseUtility.cls
/*
 * Author Paul Coleman
 * Western Governors University 
 *
 * Date Feb 13 2013 @ 0858  hrs
 * Revised: Added Before INSERT | UPDATE block for Student  Contactid=AccountId  Syncrhonization - Paul Coleman
 * Revised: Person Account refactor, asynchronous try catch removed - Paul Coleman
 * 
 * Date Nov 03 2012 @ 1312  hrs
 * Revised: (security audit compliance: with sharing and SeeAllData=false) 
 * 
 *
 */  
public with sharing class CaseUtility {


//////////////////////////////// START SECTION: TRANSFER SYSADMIN TASKS TO CASE OWNER //////////////////////////////////
   public static void transferOpenSysAdminTasks( String ListNewJSON, String ListOldMapJSON ) {
     if ( Limits.getFutureCalls() > 5 || System.isFuture() || System.isBatch() || System.isScheduled() ) {
       processTransferOpenSysAdminTasks( ListNewJSON, ListOldMapJSON );
     } else {
       try { asyncTransferOpenSysAdminTasks( ListNewJSON, ListOldMapJSON );} catch (Exception e) { processTransferOpenSysAdminTasks( ListNewJSON, ListOldMapJSON ); }
     }
   }
   
   @future
   private static void asyncTransferOpenSysAdminTasks( String ListNewJSON, String ListOldMapJSON ) {
     processTransferOpenSysAdminTasks( ListNewJSON, ListOldMapJSON );
   }
   
   //Case: after Update, look for OwnerId changes, to change corresponding Tasks on the Case
   private static void processTransferOpenSysAdminTasks( String ListNewJSON, String ListOldMapJSON ) {
      List<Case> TriggerNew = (List<Case>)JSON.deserialize( ListNewJSON, List<Case>.class );
      Map<ID,Case> TriggerOldMap = (Map<ID,Case>)JSON.deserialize( ListOldMapJSON, Map<ID,Case>.class );
      
      if ( TriggerNew.size() > 0 && TriggerOldMap.size() > 0  ) {
      
        Map<Id,Group> queues = new Map<ID,Group>([SELECT id FROM Group where Type='Queue' LIMIT 50000]);
        ID sysAdminId = [SELECT Id from User where alias = 'sadmi' LIMIT 1].id;
        
          //get all cases with non-queue and non-sadmin ownership
          List<Case> casesOfInterest = [SELECT id, OwnerId from Case where OwnerId NOT in :queues.keySet() AND OwnerId != :sysAdminId AND id IN :TriggerNew LIMIT 50000];
          
          //get all Tasks for the cases of Interest, if any
          List<Task> tasks = [SELECT id, OwnerId, WhatId from Task where WhatId IN :casesOfInterest and isClosed = false and isDeleted = false AND RecordType.DeveloperName='EmployeeTask' LIMIT 50000];
          List<Task> taskForUpdate = new List<Task>();      
          
          for ( Case thisCase : casesOfInterest ) {
              if ( TriggerOldMap.containsKey(thisCase.id) && thisCase.OwnerId != TriggerOldMap.get(thisCase.id).OwnerID ) {  //newly changed owner
                for ( Task taskRec: tasks ) {
                  //Change all Tasks owned by System Admin account to new owner id
                  if ( taskRec.whatId == thisCase.id && taskRec.Ownerid == sysAdminId ) {
                    taskForUpdate.add( new Task(id=taskRec.id,OwnerId=thisCase.OwnerId) );
                  }
                }
              }
          
          }
       
          if ( !taskForUpdate.isEmpty() ) {
            update taskForUpdate;
          }
                
      }
   }
///////////////////////////////// END SECTION: TRANSFER SYSADMIN TASKS TO CASE OWNER /////////////////////////////////// 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    //////////////////////////////// START SECTION: CASE HISTORY TO SUPPORT TRIGGER //////////////////////////////////

    public static void updateCaseHistory(String ListNewJSON, String ListOldMapJSON) {  
 
        List<Case> TriggerNew = (List<Case>)JSON.deserialize( ListNewJSON, List<Case>.class );
        Map<ID,Case> TriggerOldMap = (Map<ID,Case>)JSON.deserialize( ListOldMapJSON, Map<ID,Case>.class );
        for ( Case newCase : TriggerNew ) {
            //system.debug('~~~~~~~~~~~~~~~ TriggerNew.Status ~~~~~~~~~~~~~ ' + newCase.Status);   
        }
        for ( Case oldCase : TriggerOldMap.values()) {
          //  system.debug('~~~~~~~~~~~~~~~ TriggerOldMap.Status ~~~~~~~~~~~~~ ' + oldCase.Status);   
        }
        insertCaseUpdateHistory(ListNewJSON, ListOldMapJSON);
    }
    
    private static void insertCaseUpdateHistory (String ListNewJSON, String ListOldMapJSON){
        Integer iRows;
        Id oCase;
        Id nCase;
        String sOwnerName;
       RecordType pCase;
        CaseUpdateHistory__c cuh = new CaseUpdateHistory__c();
        List<Case> TriggerNew = (List<Case>)JSON.deserialize( ListNewJSON, List<Case>.class );
        Map<ID,Case> TriggerOldMap = (Map<ID,Case>)JSON.deserialize( ListOldMapJSON, Map<ID,Case>.class );
        
        for ( Case newCase : TriggerNew ) {
            cuh.AppealStatus__c = newCase.AppealStatus__c;
            cuh.Case__c = newCase.Id;
            nCase = newCase.Id;
            cuh.StatusValue__c = newCase.Status;  
            cuh.Escalated__c = newCase.isEscalated;
            cuh.Origin__c = newCase.Origin;
            cuh.ParentCaseCreatedDate__c = newCase.CreatedDate;
            cuh.Priority__c = newCase.Priority;
            cuh.Reason__c = newCase.Reason;
            cuh.StatusChangeTime__c = system.now();
            cuh.Type__c = newCase.Type__c;        
        }
        iRows = checkCUHRows(nCase);
        for ( Case oldCase : TriggerOldMap.values()) {
          //  system.debug('~~~~~~~~~~~~~~~ insertCase TriggerOldMap.OwnerID ~~~~~~~~~~~~~ ' + oldCase.ownerId);
            
            if (iRows != 0){ cuh.PreviousStatusValue__c = oldCase.Status; }   
         //   system.debug('~~~~~~~~~~~~~~~ insertCase Trigger oldCase.ownerId ~~~~~~~~~~~~~ ' + oldCase.ownerId);
           // sOwnerName = getOwnerName(oldCase.ownerId); // Don't know who put this in a for loop / 1-22-14 Dave
            oCase = oldCase.Id;
        }

       // system.debug('~~~~~~~~~~~~~~~ insertCase before insert ~~~~~~~~~~~~~ ');
        //system.debug('~~~~~~~~~~~~~~~ insertCaseUpdateHistory cuh.StatusValue__c ~~~~~~~~~~~~~ ' + cuh.StatusValue__c);
            // if status is open: update
            // get average time
       // system.debug('~~~~~~~~~~~~~~~ insertCaseUpdateHistory cuh.StatusValue__c ~~~~~~~~~~~~~ ' + cuh.StatusValue__c);
        
        //cuh.owner__c = sOwnerName;
        if ( cuh.PreviousStatusValue__c != cuh.StatusValue__c ){
            cuh.RecordTypeId = getRecordTypeId ('Case Status Update'); //012e00000008gHtAAI
            if (iRows != 0){ cuh.PreviousStatusChangeTime__c = previousDate(oCase); }
            /* TEMP
            pCase = getPreviousCaseRecordTypeName(oCase);
            cuh.RecordType__c = pCase.name;
            insert cuh;
            END TEMP */
        }
        system.debug('~~~~~~~~~~~~~~~ insertCase after insert ~~~~~~~~~~~~~ ');        
    }
    
    private static DateTime previousDate (Id caseId){
        List<CaseUpdateHistory__c> rDate;
        DateTime lDate;
        Integer size;
        rDate = [SELECT CreatedDate FROM CaseUpdateHistory__c WHERE Case__c =: caseId ORDER BY CreatedDate DESC]; 
        size = rDate.size();
        If ( size > 0) {
          // system.debug('~~~~~~~~~~~~~~~~~~~~~~~~~ rDate[0] ~~~~~~~~~~~~~~~~~~~ ' + rDate[0].CreatedDate);
        }
        //system.debug('~~~~~~~~~~~~~~~~~~~~~~~~~ Last Date ~~~~~~~~~~~~~~~~~~~ ' + rDate.CreatedDate);
       lDate = rDate[0].CreatedDate;
     //  system.debug('~~~~~~~~~~~~~~~~~~~~~~~~~ getTime() ~~~~~~~~~~~~~~~~~~~ ' + lDate.getTime());
       return lDate; 
    }
    
    private static String getOwnerName (Id oId) {
        Integer iCount;
        Group gName;
        User uName;
        String sName;
        if ( [SELECT count() FROM Group WHERE Id =: oId] > 0 ) { 
            gName = [SELECT Name FROM Group WHERE Id =: oId]; 
            sName = gName.name;
        } else {
           if ( [SELECT count() FROM User WHERE Id =: oId] > 0 ) {  
            uName = [SELECT Name FROM User WHERE Id =: oId]; 
            sName = uName.name;  
           }
        }
        return sName;
    }
    private static Integer checkCUHRows (Id sId){
        return [SELECT count() FROM CaseUpdateHistory__c WHERE Case__c = :sId];
    }
    
    private static Id getRecordTypeId (String sRT){
        RecordType rId;
        rId = [SELECT Id FROM RecordType WHERE Name =: sRT];
        return rId.Id;
    }
    
     private static RecordType getPreviousCaseRecordTypeName (Id id){
        return [SELECT Name FROM RecordType WHERE Id IN (SELECT RecordTypeId FROM Case WHERE ID =: id)];
    }
    
///////////////////////////////// END SECTION: CASE HISTORY TO SUPPORT TRIGGER /////////////////////////////////// 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


}