src/objects/Cohort__c.object
<CustomObject>
    <description>This object houses information about cohorts for field experiences (PCE, DT, Nursing, etc).</description>
    <fields>
        <fullName>AvailableForStudents__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The field that drives whether or not a student is able to select the cohort in their task page on the field experience portal.</description>
        <inlineHelpText>If checked true, the students will be able to select the cohort in the portal.</inlineHelpText>
        <label>Available For Students</label>
        <type>Checkbox</type>
    </fields>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieldExperience__c.object
<CustomObject>
    <description>This object represents the field experiences application. Students have access to the this object in the customer portal. There are multiple record types including PCE/DT, BSHI, MSSP, etc.</description>
    <fields>
        <fullName>Cohort__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Field Experiences</relationshipLabel>
        <relationshipName>FieldExperiences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experiences</relationshipLabel>
        <relationshipName>FieldExperiences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieldExperienceProcess__c.object
<CustomObject>
    <description>The object that represents field experience-related processes such as placements, observations, appeals, etc.</description>
    <fields>
        <fullName>Cohort__c</fullName>
        <description>Return the name of the cohort related to the parent field experience.</description>
        <formula>FieldExperience__r.Cohort__r.Name</formula>
        <label>Cohort</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldExperience__c</fullName>
        <label>Field Experience</label>
        <referenceTo>FieldExperience__c</referenceTo>
        <relationshipLabel>Field Experience Processes</relationshipLabel>
        <relationshipName>FieldExperiencesProcesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experience Processes</relationshipLabel>
        <relationshipName>Field_Experience_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Experience Process</label>
    <nameField>
        <label>Field Experiences Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experience Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestFEAppealsController.cls
/*
 * Test class  for code coverage of FEAppealsController
 * Author- Bhavadeep Raavi
 *
 * Date January 31, 2013 @ 1447 hrs
 * Revised: Person Account Refactor - Paul Coleman 
 * 
 *
*/

@isTest(SeeAllData=false)
private with sharing class TestFEAppealsController {

static testmethod void FEAppealsControllerTestMethod(){
    TestStudentFieldExperience.setupTestFEData();
    Contact studentContact = TestStudentUser.getTestStudentContact();
    
    FieldExperience__c fe=new FieldExperience__c();
    fe.Name='Test FE';
    fe.Student__c = studentContact.Id;
    fe.Cohort__c = [SELECT id FROM Cohort__c WHERE AvailableForStudents__c=true LIMIT 1].Id;
    insert fe;
    
    FieldExperienceProcess__c fep=new FieldExperienceProcess__c();
    fep.Name='Test FEP';
    fep.FieldExperience__c=fe.Id;
    insert fep;
    
    List<SelectOption> test_options = new List<SelectOption>();
    test_options.add(new SelectOption('Yes', 'Yes'));
    test_options.add(new SelectOption('No', 'No'));
    
    List<SelectOption> test_options1 = new List<SelectOption>();
    test_options1.add(new SelectOption('Failed', 'Failed'));
    test_options1.add(new SelectOption('Not Taken', 'Not Taken'));
    
    FEAppealsController ac=new FEAppealsController();
    
    ac.getAppealTypeValues();
    List<SelectOption> q1Options=ac.getQOne();
    System.assertEquals(test_options.size(),q1Options.size());    
    List<SelectOption> q3aOptions=ac.getQ3a();
    System.assertEquals(test_options.size(),q3aOptions.size()); 
    List<SelectOption> q3bOptions=ac.getQ3b();
    System.assertEquals(test_options.size(),q3bOptions.size()); 
    List<SelectOption> q3cOptions=ac.getQ3c();
    System.assertEquals(test_options.size(),q3cOptions.size()); 
    List<SelectOption> q3dOptions=ac.getQ3d();
    System.assertEquals(test_options.size(),q3dOptions.size()); 
    List<SelectOption> q3eOptions=ac.getQ3e();
    System.assertEquals(test_options.size(),q3eOptions.size()); 
    List<SelectOption> q3fOptions=ac.getQ3f();
    System.assertEquals(test_options.size(),q3fOptions.size()); 
    List<SelectOption> q3gOptions=ac.getQ3g();
    System.assertEquals(test_options.size(),q3gOptions.size()); 
    List<SelectOption> q11Options=ac.getQ11();
    System.assertEquals(test_options1.size(),q11Options.size()); 

    User testUser = [SELECT id FROM User WHERE Profile.Name = 'Field Experiences User' AND isActive = true LIMIT 1];
    System.RunAs( testUser ) {

    
  Test.startTest();
  
    ApexPages.currentPage().getParameters().put('fe',fe.Id);
    ac.q1AnsrSel='Yes';  
    System.assertEquals('Yes',ac.q1AnsrSel);  
    PageReference pf=ac.save();
    String str=pf.getUrl();
    System.assertEquals('/'+fe.Id,str);
    PageReference pf1=ac.cancel();
    
    System.assert('/'+fe.Id==pf1.getUrl(), 'APPEALS TEST FAILURE, resulting URL does not equal /' + fe.id);
    
    Test.stopTest();
    }
} 

}