src/objects/CommunityAccessControl__c.object
<CustomObject>
    <description>Object used by WGU Commons to manage the access level that students have to a community, a group, and custom groups.</description>
    <fields>
        <fullName>AdministrationType__c</fullName>
        <label>Administration Type</label>
        <picklist>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quick Tip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AnnouncementRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement Record</label>
        <referenceTo>CommunityAccessControl__c</referenceTo>
        <relationshipLabel>Community Access Controls</relationshipLabel>
        <relationshipName>StudentAnnouncements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CommunityStatus__c</fullName>
        <description>Status level of the student in the learning community</description>
        <label>Community Status</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Super Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DateAnnouncementExpires__c</fullName>
        <label>Date Announcement Expires</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <description>Id of the group that the student is assigned to.</description>
        <label>Group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewedByStudent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Viewed by Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WGUCourseInProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The course that is in the program that the student is assigned to.</description>
        <label>WGU Course In Program</label>
        <referenceTo>WGUCourseInProgram__c</referenceTo>
        <relationshipLabel>Learning Communities</relationshipLabel>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>Community Access Controls</relationshipLabel>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Access Control</label>
    <nameField>
        <label>Access For</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Access Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for wguProgram</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseInProgram__c.object
<CustomObject>
    <description>A many to many mapping that assigns which course are required to accomplish any degree program.</description>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipName>PAMS_Course_In_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>WGU Course In Programs</relationshipLabel>
        <relationshipName>WGUCourseInPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course In Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WGU Course In Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <description>The ID that represents the program in PAMS.</description>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseCommunitiesDegreeChangeUtilTest.cls
@IsTest
public class CourseCommunitiesDegreeChangeUtilTest {
    
    @IsTest(SeeAllData=true) static void changeDegreeNoCommonCourses() {
        User u = [SELECT Id, ContactId FROM User WHERE ContactId != null AND Contact.WGUDegreeProgram__c != null AND IsActive = true AND Profile.Name = 'Student Profile' LIMIT 1];
        Contact c = [SELECT WGUDegreeProgram__c FROM Contact WHERE Id = :u.ContactId];
        
        String newtworkId = [SELECT Id FROM Network WHERE Name = 'WGU Commons'].id;
        
        CollaborationGroup newGroup = new CollaborationGroup();
        newGroup.Name = 'AAAA';
        newGroup.CollaborationType = 'Public';
        newGroup.NetworkId = newtworkId;
        insert newGroup;
        
        WGUCourse__c newCourse = new WGUCourse__c();
        newCourse.name = 'AAAA';
        newCourse.PAMSID__c = -1;
        insert newCourse;
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.WGUCourse__c = newCourse.id;
        cac.GroupId__c = newGroup.id;
        cac.RecordTypeId = [SELECT id FROM RecordType WHERE name = 'Group Assignment' AND sObjectType = 'CommunityAccessControl__c'].id;
        insert cac;
        
        WGUDegreeProgram__c newDegree = new WGUDegreeProgram__c();
        newDegree.name = 'B.S. Unit Testing';
        newDegree.PAMSID__c = -3;
        insert newDegree;
        
        WGUCourseInProgram__c newCip = new WGUCourseInProgram__c();
        newCip.Course__c = newCourse.id;
        newCip.Program__c = newDegree.id;
        insert newCip;
        
        CollaborationGroup oldGroup = new CollaborationGroup();
        oldGroup.Name = 'BBBB';
        oldGroup.CollaborationType = 'Public';
        oldGroup.NetworkId = newtworkId;
        insert oldGroup;
        
        WGUCourse__c oldCourse = new WGUCourse__c();
        oldCourse.name = 'BBBB';
        oldCourse.PAMSID__c = -2;
        insert oldCourse;
        
        CommunityAccessControl__c oldCac = new CommunityAccessControl__c();
        oldCac.WGUCourse__c = oldCourse.id;
        oldCac.GroupId__c = oldGroup.id;
        oldCac.CommunityStatus__c = 'Contributor';
        oldCac.StudentUser__c = u.id;
        oldCac.RecordTypeId = [SELECT id FROM RecordType WHERE name = 'Group Access' AND sObjectType = 'CommunityAccessControl__c'].id;
        insert oldCac;
        
        WGUCourseInProgram__c oldCip = new WGUCourseInProgram__c();
        oldCip.Course__c = oldCourse.id;
        oldCip.Program__c = c.WGUDegreeProgram__c;
        insert oldCip;
        
        CollaborationGroupMember oldCgm = new CollaborationGroupMember();
        oldCgm.MemberId = u.id;
        oldCgm.CollaborationGroupId = oldGroup.id;
        oldCgm.NotificationFrequency = 'W';
        oldCgm.CollaborationRole = 'Standard';
        insert oldCgm;

        CommunityAccessControl__c announcement = new CommunityAccessControl__c();
        announcement.GroupId__c = newGroup.id;
        announcement.AdministrationType__c = 'Announcement';
        announcement.DateAnnouncementExpires__c = System.today().addDays(5);
        announcement.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Community Administration' AND sObjectType = 'CommunityAccessControl__c'].id;
        insert announcement;
        
        Test.startTest();
        c.WGUDegreeProgram__c = newDegree.id;
        update c;
        Test.stopTest();
        
        List<CollaborationGroupMember> oldCgmList = [SELECT id FROM CollaborationGroupMember WHERE id = :oldCgm.id];
        System.assertEquals(0, oldCgmList.size());
        
        List<CommunityAccessControl__c> oldCacList = [SELECT id, CommunityStatus__c FROM CommunityAccessControl__c WHERE id = :oldCac.id];
        System.assertEquals('Removed', oldCacList.get(0).CommunityStatus__c);
        
        List<CollaborationGroupMember> newCgmList = [SELECT id FROM CollaborationGroupMember WHERE MemberId = :u.id AND CollaborationGroupId = :newGroup.id];
        System.assertEquals(1, newCgmList.size());
        
        List<CommunityAccessControl__c> newCacList = [SELECT id, CommunityStatus__c FROM CommunityAccessControl__c WHERE StudentUser__c = :u.id AND GroupId__c = :newGroup.id];
        System.assertEquals('Viewer', newCacList.get(0).CommunityStatus__c);

        List<CommunityAccessControl__c> studentAnnouncementRecords = [SELECT Id 
                                                                        FROM CommunityAccessControl__c 
                                                                       WHERE StudentUser__c = :u.id 
                                                                         AND RecordType.Name = 'Course Announcement'
                                                                         AND AnnouncementRecord__c = :announcement.id
                                                                         AND ViewedByStudent__c = false];
        System.assertEquals(1, studentAnnouncementRecords.size());
    }
    
    @IsTest(SeeAllData=true) static void changeDegreeCommonCourses() {
        User u = [SELECT Id, ContactId FROM User WHERE ContactId != null AND Contact.WGUDegreeProgram__c != null AND IsActive = true AND Profile.Name = 'Student Profile' LIMIT 1];
        Contact c = [SELECT WGUDegreeProgram__c FROM Contact WHERE Id = :u.ContactId];
        
        String newtworkId = [SELECT Id FROM Network WHERE Name = 'WGU Commons'].id;
        
        CollaborationGroup newGroup = new CollaborationGroup();
        newGroup.Name = 'AAAA';
        newGroup.CollaborationType = 'Public';
        newGroup.NetworkId = newtworkId;
        insert newGroup;
        
        WGUCourse__c newCourse = new WGUCourse__c();
        newCourse.name = 'AAAA';
        newCourse.PAMSID__c = -1;
        insert newCourse;
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.WGUCourse__c = newCourse.id;
        cac.GroupId__c = newGroup.id;
        cac.RecordTypeId = [SELECT id FROM RecordType WHERE name = 'Group Assignment' AND sObjectType = 'CommunityAccessControl__c'].id;
        insert cac;
        
        WGUDegreeProgram__c newDegree = new WGUDegreeProgram__c();
        newDegree.name = 'B.S. Unit Testing';
        newDegree.PAMSID__c = -3;
        insert newDegree;
        
        WGUCourseInProgram__c newCip = new WGUCourseInProgram__c();
        newCip.Course__c = newCourse.id;
        newCip.Program__c = newDegree.id;
        insert newCip;
        
        CommunityAccessControl__c oldCac = new CommunityAccessControl__c();
        oldCac.WGUCourse__c = newCourse.id;
        oldCac.GroupId__c = newGroup.id;
        oldCac.CommunityStatus__c = 'Contributor';
        oldCac.StudentUser__c = u.id;
        oldCac.RecordTypeId = [SELECT id FROM RecordType WHERE name = 'Group Access' AND sObjectType = 'CommunityAccessControl__c'].id;
        insert oldCac;
        
        WGUCourseInProgram__c oldCip = new WGUCourseInProgram__c();
        oldCip.Course__c = newCourse.id;
        oldCip.Program__c = c.WGUDegreeProgram__c;
        insert oldCip;
        
        CollaborationGroupMember oldCgm = new CollaborationGroupMember();
        oldCgm.MemberId = u.id;
        oldCgm.CollaborationGroupId = newGroup.id;
        oldCgm.NotificationFrequency = 'W';
        oldCgm.CollaborationRole = 'Standard';
        insert oldCgm;
        
        Test.startTest();
        c.WGUDegreeProgram__c = newDegree.id;
        update c;
        Test.stopTest();
        
        List<CollaborationGroupMember> oldCgmList = [SELECT id FROM CollaborationGroupMember WHERE id = :oldCgm.id];
        System.assertEquals(1, oldCgmList.size());
        
        List<CommunityAccessControl__c> oldCacList = [SELECT id, CommunityStatus__c FROM CommunityAccessControl__c WHERE id = :oldCac.id];
        System.assertEquals('Contributor', oldCacList.get(0).CommunityStatus__c);
    }

}