src/objects/CommunityAccessControl__c.object
<CustomObject>
    <description>Object used by WGU Commons to manage the access level that students have to a community, a group, and custom groups.</description>
    <fields>
        <fullName>AdministrationType__c</fullName>
        <label>Administration Type</label>
        <picklist>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quick Tip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AnnouncementRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement Record</label>
        <referenceTo>CommunityAccessControl__c</referenceTo>
        <relationshipLabel>Community Access Controls</relationshipLabel>
        <relationshipName>StudentAnnouncements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AnnouncementStatus__c</fullName>
        <formula>IF(OR(DateAnnouncementExpires__c = NULL, DateAnnouncementExpires__c &gt;=  TODAY()) , &apos;Active&apos;, &apos;Archived&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Announcement Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <description>Id of the group that the student is assigned to.</description>
        <label>Group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewedByStudent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Viewed by Student</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Access Control</label>
    <nameField>
        <label>Access For</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Access Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseCommunitiesGroupAnnouncementsUtil.cls
public class CourseCommunitiesGroupAnnouncementsUtil {
	
	public static Map<String, List<CommunityAccessControl__c>> getGroupAnnouncementsMap(Set<String> groupIdSet) {
        List<CommunityAccessControl__c> cacList = [SELECT Id, GroupId__c 
                                                     FROM CommunityAccessControl__c 
                                                    WHERE GroupId__c IN :groupIdSet 
                                                      AND AdministrationType__c = 'Announcement'
                                                      AND RecordType.Name = 'Community Administration'
                                                      AND AnnouncementStatus__c = 'Active'
                                                    ORDER BY GroupId__c];
        Map<String, List<CommunityAccessControl__c>> announcementMap = new Map<String, List<CommunityAccessControl__c>>();
        String currentGroupId = null;
        for(CommunityAccessControl__c cac : cacList) {
            if(currentGroupId == null || currentGroupId != cac.GroupId__c) {
                announcementMap.put(cac.GroupId__c, new List<CommunityAccessControl__c>());
            }
            announcementMap.get(cac.GroupId__c).add(cac);
        }
        return announcementMap;
    }

    public static void addAnnouncementsForUser(String userId, String courseAnnouncementRecordTypeId,
        List<CommunityAccessControl__c> announcementList, List<CommunityAccessControl__c> insertCacList) 
    {
        for(CommunityAccessControl__c announcement : announcementList) {
            insertCacList.add(createAnnouncementViewRecord(userId, courseAnnouncementRecordTypeId, announcement.id));
        }
    }

    public static void addAnnouncementsForNewUsersGroups(List<CommunityAccessControl__c> groupPermissionCacList) {
        Set<String> groupIdSet = new Set<String>();
        for(CommunityAccessControl__c cac : groupPermissionCacList) {
            groupIdSet.add(cac.GroupId__c);
        }

        String courseAnnoucementRecordTypeId = [SELECT Id FROM RecordType WHERE sObjectType = 'CommunityAccessControl__c' AND Name = 'Course Announcement'].id;
        Map<String, List<CommunityAccessControl__c>> groupAnnoucementsMap = getGroupAnnouncementsMap(groupIdSet);
        List<CommunityAccessControl__c> recordsToAdd = new List<CommunityAccessControl__c>();
        for(CommunityAccessControl__c cac : groupPermissionCacList) {
            if(!groupAnnoucementsMap.containsKey(cac.GroupId__c)) {
                continue;
            }
            recordsToAdd.addAll(createAnnouncementViewRecords(cac.StudentUser__c, 
                    courseAnnoucementRecordTypeId, groupAnnoucementsMap.get(cac.GroupId__c)));
        }
        groupPermissionCacList.addAll(recordsToAdd);
    }

    private static List<CommunityAccessControl__c> createAnnouncementViewRecords(String userId, String courseAnnoucementRecordTypeId,
        List<CommunityAccessControl__c> annoucementList) 
    {
    	List<CommunityAccessControl__c> resultList = new List<CommunityAccessControl__c>();
        for(CommunityAccessControl__c annoucement : annoucementList) {
            resultList.add(createAnnouncementViewRecord(userId, courseAnnoucementRecordTypeId, annoucement.id));
        }
        return resultList;
    }

    public static CommunityAccessControl__c createAnnouncementViewRecord(String userId, String courseAnnoucementRecordTypeId, String annoucementId) {
    	CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.StudentUser__c = userId;
        cac.ViewedByStudent__c = false;
        cac.RecordTypeId = courseAnnoucementRecordTypeId;
        cac.AnnouncementRecord__c = annoucementId;
        return cac;
    }

}