src/objects/CommunityAccessControl__c.object
<CustomObject>
    <description>Object used by WGU Commons to manage the access level that students have to a community, a group, and custom groups.</description>
    <fields>
        <fullName>AdministrationType__c</fullName>
        <label>Administration Type</label>
        <picklist>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quick Tip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AnnouncementRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement Record</label>
        <referenceTo>CommunityAccessControl__c</referenceTo>
        <relationshipLabel>Community Access Controls</relationshipLabel>
        <relationshipName>StudentAnnouncements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateAnnouncementExpires__c</fullName>
        <label>Date Announcement Expires</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <description>Id of the group that the student is assigned to.</description>
        <label>Group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MyResponse__c</fullName>
        <description>Response that was made by the course mentor</description>
        <inlineHelpText>The response from the Course Mentor.</inlineHelpText>
        <label>My Response</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OriginalPostId__c</fullName>
        <description>The Id of the original post that they student made.</description>
        <label>Original Post Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostStatus__c</fullName>
        <description>The current status of the post.</description>
        <label>Post Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Clarification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor Satisfied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q/A Resolved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewedByStudent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Viewed by Student</label>
        <type>Checkbox</type>
    </fields>
    <label>Community Access Control</label>
    <nameField>
        <label>Access For</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Access Controls</pluralLabel>
    <recordTypes>
        <fullName>Post</fullName>
        <active>true</active>
        <description>Record type for the post that is made to a chatter group.</description>
        <label>Post</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommonsChatterManagementControlTest.cls
@IsTest
public class CommonsChatterManagementControlTest{

    @IsTest static void getGroupOptionsTest() {
        Map<String, String> groupMap = new Map<String, String>();
        groupMap.put('1', 'AAAA');
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupMap = groupMap;
        Test.startTest();
        List<SelectOption> resultList = control.getGroupOptions();
        Test.stopTest();
        
        System.assertEquals(1, resultList.size());
        System.assertEquals('1', resultList.get(0).getValue());
        System.assertEquals('AAAA', resultList.get(0).getLabel());
    }
    
    @IsTest static void getSelectedGroupNameTest_Null() {
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        Test.startTest();
        String result = control.getSelectedGroupName();
        Test.stopTest();
        
        System.assertEquals(null, result);
    }
    
    @IsTest static void getSelectedGroupNameTest() {
        Map<String, String> groupMap = new Map<String, String>();
        groupMap.put('1', 'AAAA');        
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupMap = groupMap;
        control.groupId = '1';
        Test.startTest();
        String result = control.getSelectedGroupName();
        Test.stopTest();
        
        System.assertEquals('AAAA', result);
    }
    
    @IsTest static void getUnansweredQuestionCountTest_Null() {
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        Test.startTest();
        Integer result = control.getUnansweredQuestionCount();
        Test.stopTest();
        
        System.assertEquals(null, result);
    }
    
    @IsTest static void getUnansweredQuestionCountTest() {
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.groupId__c = '1';
        cac.PostStatus__c = 'Unanswered';
        cac.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Post' AND SobjectType = 'CommunityAccessControl__c'].id;
        insert cac;
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = '1';
        Test.startTest();
        Integer result = control.getUnansweredQuestionCount();
        Test.stopTest();
        
        System.assertEquals(1, result);
    }
    
    @IsTest static void getCourseCommunityAnnouncementsTest() {
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.groupId__c = '1';
        cac.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Community Administration' AND SobjectType = 'CommunityAccessControl__c'].id;
        cac.MyResponse__c = 'This is an announcement';
        cac.AdministrationType__c = 'Announcement';
        cac.DateAnnouncementExpires__c = System.today().addDays(5);
        insert cac;
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = '1';
        Test.startTest();
        List<CommonsChatterManagementControl.CourseCommunitiesAnnouncementOrTip> resultList = control.getCourseCommunityAnnouncements();
        Test.stopTest();
        
        System.assertEquals(1, resultList.size());
        System.assertEquals('This is an announcement', resultList.get(0).announcementOrTip.MyResponse__c);
    }
    
    @IsTest static void getCourseCommunityQuickTipsTest() {
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.groupId__c = '1';
        cac.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Community Administration' AND SobjectType = 'CommunityAccessControl__c'].id;
        cac.MyResponse__c = 'This is a tip';
        cac.AdministrationType__c = 'Quick Tip';
        cac.DateAnnouncementExpires__c = System.today().addDays(5);
        insert cac;
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = '1';
        Test.startTest();
        List<CommonsChatterManagementControl.CourseCommunitiesAnnouncementOrTip> resultList = control.getCourseCommunityQuickTips();
        Test.stopTest();
        
        System.assertEquals(1, resultList.size());
        System.assertEquals('This is a tip', resultList.get(0).announcementOrTip.MyResponse__c);
    }
    
    @IsTest static void editAdminCommunityAccessControlTest() {
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.groupId__c = '1';
        cac.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Community Administration' AND SobjectType = 'CommunityAccessControl__c'].id;
        cac.MyResponse__c = 'This is a tip';
        cac.AdministrationType__c = 'Quick Tip';
        insert cac;
        
        ApexPages.currentPage().getParameters().put('itemId', String.valueOf(cac.id));
        ApexPages.currentPage().getParameters().put('updatedMessage', 'This is an updated tip');
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = '1';
        Test.startTest();
        control.editAdminCommunityAccessControl();
        Test.stopTest();
        
        List<CommunityAccessControl__c> resultList = [SELECT MyResponse__c 
                                                        FROM CommunityAccessControl__c 
                                                       WHERE GroupId__c = '1' 
                                                         AND RecordType.Name = 'Community Administration' 
                                                         AND AdministrationType__c = 'Quick Tip'];
        
        System.assertEquals(1, resultList.size());
        System.assertEquals('This is an updated tip', resultList.get(0).MyResponse__c);
    }
    
    @IsTest static void createAdminCommunityAccessControlTest() {
        ApexPages.currentPage().getParameters().put('message', 'This is a tip');
        ApexPages.currentPage().getParameters().put('adminType', 'Quick Tip');
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = '1';
        Test.startTest();
        control.createAdminCommunityAccessControl();
        Test.stopTest();
        
        List<CommunityAccessControl__c> resultList = [SELECT MyResponse__c 
                                                        FROM CommunityAccessControl__c 
                                                       WHERE GroupId__c = '1' 
                                                         AND RecordType.Name = 'Community Administration' 
                                                         AND AdministrationType__c = 'Quick Tip'];
        
        System.assertEquals(1, resultList.size());
        System.assertEquals('This is a tip', resultList.get(0).MyResponse__c);
    }

    @IsTest static void createAnnouncementTest() {
        String networkId = [SELECT Id FROM Network WHERE Name = 'WGU Commons'].Id;
        CollaborationGroup testGroup = new CollaborationGroup();
        testGroup.name = 'Test group asdf';
        testGroup.CollaborationType = 'Private';
        testGroup.NetworkId = networkId;
        insert testGroup;

        ApexPages.currentPage().getParameters().put('message', 'This is an announcement');
        ApexPages.currentPage().getParameters().put('adminType', 'Announcement');
        ApexPages.currentPage().getParameters().put('numberOfDaysToExpiration', '5');
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = testGroup.id;
        Test.startTest();
        control.createAdminCommunityAccessControl();
        Test.stopTest();
        
        List<CommunityAccessControl__c> resultList = [SELECT Id, MyResponse__c, DateAnnouncementExpires__c
                                                        FROM CommunityAccessControl__c 
                                                       WHERE GroupId__c = :testGroup.id 
                                                         AND RecordType.Name = 'Community Administration' 
                                                         AND AdministrationType__c = 'Announcement'];
        
        System.assertEquals(1, resultList.size());

        CommunityAccessControl__c result = resultList.get(0);

        System.assertEquals('This is an announcement', result.MyResponse__c);
        System.assertEquals(System.today().addDays(5), result.DateAnnouncementExpires__c);

        //By default the user running the test is the only member of the group
        List<CommunityAccessControl__c> studentAnnouncementRecords = [SELECT Id 
                                                                        FROM CommunityAccessControl__c 
                                                                       WHERE StudentUser__c = :UserInfo.getUserId()
                                                                         AND RecordType.Name = 'Course Announcement'
                                                                         AND AnnouncementRecord__c = :result.id
                                                                         AND ViewedByStudent__c = false];
        System.assertEquals(1, studentAnnouncementRecords.size());
    }
    
    @IsTest(SeeAllData=true) static void getCommunityAccessControlListUnansweredTest_FeedItemIsAQuestion() {
        String networkId = [SELECT Id FROM Network WHERE Name = 'WGU Commons'].Id;
        CollaborationGroup testGroup = new CollaborationGroup();
        testGroup.name = 'Test group asdf';
        testGroup.CollaborationType = 'Private';
        testGroup.NetworkId = networkId;
        insert testGroup;
        
        ConnectApi.FeedItem feedItem = ConnectApi.ChatterFeeds.postFeedItem(networkId, ConnectApi.FeedType.Record, testGroup.id, 'This is a test post');
        ConnectApi.Comment comment = ConnectApi.ChatterFeeds.postComment(networkId, feedItem.id, 'This is a test comment');
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.OriginalPostId__c = feeditem.id;
        cac.PostStatus__c = 'Unanswered';
        cac.RecordTypeId = [SELECT id FROM RecordType WHERE Name = 'Post' AND sObjectType = 'CommunityAccessControl__c'].id;
        cac.GroupId__c = testGroup.id;
        insert cac;
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = testGroup.id;
        Test.startTest();
        List<CommonsCommunityManagementControlResult> resultList = control.getCommunityAccessControlListUnanswered();
        Test.stopTest();
        
        System.assertEquals(1, resultList.size());
        System.assertEquals('This is a test post', resultList.get(0).feedItem.feedItem.body.text);
        System.assertEquals('This is a test comment', resultList.get(0).feedItem.commentList.get(0).comment.body.text);
    }
    
    @IsTest(SeeAllData=true) static void getCommunityAccessControlListUnansweredTest_FeedCommentIsAQuestion() {
        String networkId = [SELECT Id FROM Network WHERE Name = 'WGU Commons'].Id;
        CollaborationGroup testGroup = new CollaborationGroup();
        testGroup.name = 'Test group asdf';
        testGroup.CollaborationType = 'Private';
        testGroup.NetworkId = networkId;
        insert testGroup;
        
        ConnectApi.FeedItem feedItem = ConnectApi.ChatterFeeds.postFeedItem(networkId, ConnectApi.FeedType.Record, testGroup.id, 'This is a test post');
        ConnectApi.Comment comment = ConnectApi.ChatterFeeds.postComment(networkId, feedItem.id, 'This is a test comment');
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.OriginalPostId__c = comment.id;
        cac.PostStatus__c = 'Unanswered';
        cac.RecordTypeId = [SELECT id FROM RecordType WHERE Name = 'Post' AND sObjectType = 'CommunityAccessControl__c'].id;
        cac.GroupId__c = testGroup.id;
        insert cac;
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = testGroup.id;
        Test.startTest();
        List<CommonsCommunityManagementControlResult> resultList = control.getCommunityAccessControlListUnanswered();
        Test.stopTest();
        
        System.assertEquals(1, resultList.size());
        System.assertEquals('This is a test post', resultList.get(0).feedItem.feedItem.body.text);
        System.assertEquals('This is a test comment', resultList.get(0).feedItem.commentList.get(0).comment.body.text);
    }
    
    @IsTest(SeeAllData=true) static void getCommunityAccessControlListUnansweredTest_FeedItemAndCommentIsAQuestion() {
        String networkId = [SELECT Id FROM Network WHERE Name = 'WGU Commons'].Id;
        CollaborationGroup testGroup = new CollaborationGroup();
        testGroup.name = 'Test group asdf';
        testGroup.CollaborationType = 'Private';
        testGroup.NetworkId = networkId;
        insert testGroup;
        
        ConnectApi.FeedItem feedItem = ConnectApi.ChatterFeeds.postFeedItem(networkId, ConnectApi.FeedType.Record, testGroup.id, 'This is a test post');
        ConnectApi.Comment comment = ConnectApi.ChatterFeeds.postComment(networkId, feedItem.id, 'This is a test comment');
        
        CommunityAccessControl__c cac2 = new CommunityAccessControl__c();
        cac2.OriginalPostId__c = feedItem.id;
        cac2.PostStatus__c = 'Unanswered';
        cac2.RecordTypeId = [SELECT id FROM RecordType WHERE Name = 'Post' AND sObjectType = 'CommunityAccessControl__c'].id;
        cac2.GroupId__c = testGroup.id;
        insert cac2;
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.OriginalPostId__c = comment.id;
        cac.PostStatus__c = 'Unanswered';
        cac.RecordTypeId = [SELECT id FROM RecordType WHERE Name = 'Post' AND sObjectType = 'CommunityAccessControl__c'].id;
        cac.GroupId__c = testGroup.id;
        insert cac;
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = testGroup.id;
        Test.startTest();
        List<CommonsCommunityManagementControlResult> resultList = control.getCommunityAccessControlListUnanswered();
        Test.stopTest();
        
        System.assertEquals(1, resultList.size());
        System.assertEquals('This is a test post', resultList.get(0).feedItem.feedItem.body.text);
        System.assertEquals('This is a test comment', resultList.get(0).feedItem.commentList.get(0).comment.body.text);
    }
    
    @IsTest static void getFilesForGroupTest() {
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.RecordTypeId = [SELECT id FROM RecordType WHERE Name = 'Community Administration' AND sObjectType = 'CommunityAccessControl__c'].id;
        cac.GroupId__c = '1';
        cac.AdministrationType__c = 'Document';
        insert cac;
        
		Attachment att = new Attachment();
        att.name = 'Test attachment';
        att.parentId = cac.id;
        att.body = Blob.valueOf('Test file content');
        insert att;
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = '1';
        
        Test.startTest();
        List<CommunityAccessControl__c> resultList = control.getFilesForGroup();
        Test.stopTest();
        
        System.assertEquals(1, resultList.size());
        System.assertEquals('Test attachment', resultList.get(0).attachments.get(0).name);
    }
    
    @IsTest(SeeAllData=true) static void postFileToChatterTest() {
        String networkId = [SELECT Id FROM Network WHERE Name = 'WGU Commons'].id;
        
        CollaborationGroup testGroup = new CollaborationGroup();
        testGroup.name = 'Test group asdf';
        testGroup.CollaborationType = 'Private';
        testGroup.NetworkId = networkId;
        insert testGroup;
        
        ConnectApi.FeedItem feedItem = ConnectApi.ChatterFeeds.postFeedItem(networkId, ConnectApi.FeedType.Record, testGroup.id, 'This is a post.');
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.PostStatus__c = 'Unanswered';
        cac.GroupId__c = testGroup.id;
        cac.OriginalPostId__c = feedItem.id;
        cac.RecordTypeId = [SELECT id FROM RecordType WHERE Name = 'Post' AND sObjectType = 'CommunityAccessControl__c'].id;
        insert cac;
        
        CommonsChatterManagementControl controller = new CommonsChatterManagementControl();
        controller.groupId = testGroup.Id;
        
        controller.fileBlob = Blob.valueOf('This is some text for the blob');
        controller.fileName = 'Test.txt';
        controller.fileType = 'text/plain';
        controller.fileSize = 30;
        controller.fileMessage = 'This is a test message.';
    	controller.fileFeedItemId = feedItem.id;
        controller.postStatus = 'Mentor Satisfied';
        
        Test.startTest();
        controller.postFileToChatter();
        Test.stopTest();
        
        List<FeedItem> feedItemList = [SELECT Id, (SELECT CommentBody, RelatedRecordId FROM FeedComments) FROM FeedItem WHERE ParentId = :testGroup.Id];
        System.assertEquals(1, feedItemList.size());
        System.assertEquals(1, feedItemList.get(0).FeedComments.size());
        System.assertEquals('This is a test message.', feedItemList.get(0).FeedComments.get(0).CommentBody);
        
        String relatedRecordId = feedItemList.get(0).FeedComments.get(0).RelatedRecordId;
        ContentVersion content = [SELECT Title FROM ContentVersion WHERE Id = :relatedRecordId];
        System.assertEquals('Test.txt', content.Title);
        
        List<CommunityAccessControl__c> cacList = [SELECT PostStatus__c FROM CommunityAccessControl__c WHERE id = :cac.id];
        System.assertEquals(1, cacList.size());
        System.assertEquals('Mentor Satisfied', cacList.get(0).PostStatus__c);
    }
    
    @IsTest(SeeAllData=true) static void postMessageToChatterTest() {
        String networkId = [SELECT Id FROM Network WHERE Name = 'WGU Commons'].id;
        CollaborationGroup testGroup = new CollaborationGroup();
        testGroup.name = 'Test group asdf';
        testGroup.CollaborationType = 'Private';
        testGroup.NetworkId = networkId;
        insert testGroup;
        
        ConnectApi.FeedItem feedItem = ConnectApi.ChatterFeeds.postFeedItem(networkId, ConnectApi.FeedType.Record, testGroup.id, 'This is a post.');
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.PostStatus__c = 'Unanswered';
        cac.GroupId__c = testGroup.id;
        cac.OriginalPostId__c = feedItem.id;
        cac.RecordTypeId = [SELECT id FROM RecordType WHERE Name = 'Post' AND sObjectType = 'CommunityAccessControl__c'].id;
        insert cac;
        
        ApexPages.currentPage().getParameters().put('message', 'This is a test message.');
        ApexPages.currentPage().getParameters().put('question', 'false');
        ApexPages.currentPage().getParameters().put('feedItemId', feedItem.id);
        ApexPages.currentPage().getParameters().put('postStatus', 'Mentor Satisfied');
        
        CommonsChatterManagementControl controller = new CommonsChatterManagementControl();
        controller.groupId = testGroup.Id;
        
        Test.startTest();
        controller.postMessageToChatter();
        Test.stopTest();
        
        List<FeedItem> feedItemList = [SELECT Id, (SELECT CommentBody FROM FeedComments) FROM FeedItem WHERE ParentId = :testGroup.Id];
        System.assertEquals(1, feedItemList.size());
        System.assertEquals(1, feedItemList.get(0).FeedComments.size());
        System.assertEquals('This is a test message.', feedItemList.get(0).FeedComments.get(0).CommentBody);
        
        List<CommunityAccessControl__c> cacList = [SELECT PostStatus__c FROM CommunityAccessControl__c WHERE id = :cac.id];
        System.assertEquals(1, cacList.size());
        System.assertEquals('Mentor Satisfied', cacList.get(0).PostStatus__c);
    }
    
    @IsTest static void deleteCommunityAccessControlTest() {
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.RecordTypeId = [SELECT id FROM RecordType WHERE Name = 'Community Administration' AND sObjectType = 'CommunityAccessControl__c'].id;
        cac.GroupId__c = '1';
        cac.AdministrationType__c = 'Document';
        insert cac;
        
		Attachment att = new Attachment();
        att.name = 'Test attachment';
        att.parentId = cac.id;
        att.body = Blob.valueOf('Test file content');
        insert att;
        
        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = '1';
        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', String.valueOf(cac.id));
        control.deleteCommunityAccessControl();
        Test.stopTest();
        
        List<CommunityAccessControl__c> cacList = [SELECT id FROM CommunityAccessControl__c WHERE id = :cac.id];
        System.assertEquals(0, cacList.size());
    }

    @IsTest static void renewCourseTipTest() {
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.RecordTypeId = [SELECT id FROM RecordType WHERE Name = 'Community Administration' AND sObjectType = 'CommunityAccessControl__c'].id;
        cac.GroupId__c = '1';
        cac.AdministrationType__c = 'Quick Tip';
        cac.DateAnnouncementExpires__c = System.today().addDays(3);
        insert cac;

        CommonsChatterManagementControl control = new CommonsChatterManagementControl();
        control.groupId = '1';

        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', String.valueOf(cac.id));
        control.renewCourseTip();
        Test.stopTest();

        List<CommunityAccessControl__c> tip1List = [SELECT Id, DateAnnouncementExpires__c
                                                      FROM CommunityAccessControl__c 
                                                     WHERE id = :cac.id];
        System.assertEquals(System.today().addDays(-1), tip1List.get(0).DateAnnouncementExpires__c);

        List<CommunityAccessControl__c> tip2List = [SELECT Id, DateAnnouncementExpires__c
                                                      FROM CommunityAccessControl__c 
                                                     WHERE id != :cac.id];
        System.assertEquals(1, tip2List.size());
    }

    @IsTest static void validateHelperMethodsOnCourseCommunitiesAnnouncementOrTip() {
        CommunityAccessControl__c tipCac = new CommunityAccessControl__c();
        tipCac.DateAnnouncementExpires__c = System.today().addDays(6);
        tipCac.AdministrationType__c = 'Quick Tip';

        CommonsChatterManagementControl.CourseCommunitiesAnnouncementOrTip tip = new CommonsChatterManagementControl.CourseCommunitiesAnnouncementOrTip(tipCac);
        System.assertEquals(6, tip.getDaysToExpiration());
        System.assertEquals(1, tip.getDaysToRenewalEligibility());
        System.assertEquals(false, tip.getEligibleForRenewal());
        System.assertEquals(datetime.newInstance(System.today().addDays(6), time.newInstance(0,0,0,0)).format('MM/dd/yyyy'),
            tip.getMMDDYYYYFormattedExpirationDate());
        System.assertEquals(datetime.newInstance(System.today().addDays(6), time.newInstance(0,0,0,0)).format('yyyy-MM-dd'),
            tip.getYYYYMMDDFormattedExpirationDate());

        tipCac.DateAnnouncementExpires__c = System.today().addDays(1);
        System.assertEquals(true, tip.getEligibleForRenewal());

        //Also checking for null DateAnnouncementExpires__c
        CommunityAccessControl__c announcementCac = new CommunityAccessControl__c();
        announcementCac.AdministrationType__c = 'Announcement';

        CommonsChatterManagementControl.CourseCommunitiesAnnouncementOrTip announcement = new CommonsChatterManagementControl.CourseCommunitiesAnnouncementOrTip(announcementCac);
        System.assertEquals(false, announcement.getEligibleForRenewal());
        System.assertEquals(null, announcement.getDaysToExpiration());
        System.assertEquals(null, announcement.getDaysToRenewalEligibility());
        System.assertEquals(null, announcement.getMMDDYYYYFormattedExpirationDate());
        System.assertEquals(null, announcement.getYYYYMMDDFormattedExpirationDate());
    }
    
}