src/objects/CommunityAccessControl__c.object
<CustomObject>
    <description>Object used by WGU Commons to manage the access level that students have to a community, a group, and custom groups.</description>
    <fields>
        <fullName>CaseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id of the case that was created by the question posted,</description>
        <label>Case Id</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Learning Community</relationshipLabel>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <description>Id of the group that the student is assigned to.</description>
        <label>Group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostStatus__c</fullName>
        <description>The current status of the post.</description>
        <label>Post Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Responded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Clarification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor Satisfied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q/A Resolved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Original question text that was asked by the student.</description>
        <inlineHelpText>Original question that was asked by the student.</inlineHelpText>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>Community Access Controls</relationshipLabel>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Access Control</label>
    <nameField>
        <label>Access For</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Access Controls</pluralLabel>
    <recordTypes>
        <fullName>Post</fullName>
        <active>true</active>
        <description>Record type for the post that is made to a chatter group.</description>
        <label>Post</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommonsExpandedSearchControllerTest.cls
@IsTest
public class CommonsExpandedSearchControllerTest {
    
    @IsTest static void constructorTest() {
        ApexPages.currentPage().getParameters().put('groupId', '1');
        ApexPages.currentPage().getParameters().put('searchTerm', 'Test');
        ApexPages.currentPage().getParameters().put('refineSearchTerm', 'Refine test');
        ApexPages.currentPage().getParameters().put('courseCode', 'AAAA');
        
        WGUCourse__c course = new WGUCourse__c();
        course.name = 'AAAA';
        course.title__c = 'Introduction to Underwater Basket Weaving';
        course.pamsid__c = 0;
        insert course;
        
        User u = ([SELECT Id, AccountId FROM User WHERE IsActive = true AND Profile.Name = 'Student Profile' LIMIT 1]);
        
        System.runAs(u) {
            Test.startTest();
            CommonsExpandedSearchController controller = new CommonsExpandedSearchController();
            Test.stopTest();
            
            System.assertEquals('1', controller.groupId);
            System.assertEquals('Test', controller.searchTerm);
            System.assertEquals('Refine test', controller.refineSearchTerm);
            System.assertEquals('AAAA', controller.courseCode);
            System.assertEquals('Introduction to Underwater Basket W...', controller.courseTitle);
            System.assert(controller.paginator != null);
        }
    }
    
    @IsTest static void redoSearchTest() {
        CommonsExpandedSearchController controller = new CommonsExpandedSearchController();
        ApexPages.currentPage().getParameters().put('redoSearchTerm', 'Test');
        controller.redoSearch();
        System.assertEquals('Test', controller.searchTerm);
        System.assert(controller.paginator != null);
    }
    
    @IsTest static void refineSearchTest() {
        CommonsExpandedSearchController controller = new CommonsExpandedSearchController();
        ApexPages.currentPage().getParameters().put('refineSearchTerm', 'Refine test');
        controller.refineSearch();
        System.assertEquals('Refine test', controller.refineSearchTerm);
        System.assert(controller.paginator != null);
    }
    
    @IsTest(SeeAllData=true) static void postMessageToChatterTest() {
        CollaborationGroup testGroup = new CollaborationGroup();
        testGroup.name = 'Test group asdf';
        testGroup.CollaborationType = 'Private';
        testGroup.NetworkId = [SELECT Id FROM Network WHERE Name = 'WGU Commons'].Id;
        insert testGroup;
        
        ApexPages.currentPage().getParameters().put('groupId', String.valueOf(testGroup.id));
        CommonsExpandedSearchController controller = new CommonsExpandedSearchController();
        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('message', 'This is a test message.');
        ApexPages.currentPage().getParameters().put('question', 'false');
        ApexPages.currentPage().getParameters().put('feedItemId', 'null');
        controller.postMessageToChatter();
        Test.stopTest();
        
        List<FeedItem> feedItemList = [SELECT Id, Body FROM FeedItem WHERE ParentId = :testGroup.Id];
        System.assertEquals(1, feedItemList.size());
        System.assertEquals('This is a test message.', feedItemList.get(0).Body);
        
        List<CommunityAccessControl__c> cacList = [SELECT Id, PostStatus__c, CaseId__c, Question__c FROM CommunityAccessControl__c WHERE GroupId__c = :testGroup.Id AND RecordType.Name = 'Post'];
        System.assertEquals(1, cacList.size());
        System.assertEquals('Comment', cacList.get(0).PostStatus__c);
        System.assertEquals(null, cacList.get(0).Question__c);
        System.assertEquals(null, cacList.get(0).CaseId__c);
    }

}