src/objects/CommunityAccessControl__c.object
<CustomObject>
    <description>Object used by WGU Commons to manage the access level that students have to a community, a group, and custom groups.</description>
    <fields>
        <fullName>AdministrationType__c</fullName>
        <label>Administration Type</label>
        <picklist>
            <picklistValues>
                <fullName>Announcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quick Tip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AnnouncementRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Announcement Record</label>
        <referenceTo>CommunityAccessControl__c</referenceTo>
        <relationshipLabel>Community Access Controls</relationshipLabel>
        <relationshipName>StudentAnnouncements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CommunityId__c</fullName>
        <description>Id of the community that the student is assigned to.</description>
        <label>Community Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunityStatus__c</fullName>
        <description>Status level of the student in the learning community</description>
        <label>Community Status</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Super Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DateAnnouncementExpires__c</fullName>
        <label>Date Announcement Expires</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <description>Id of the group that the student is assigned to.</description>
        <label>Group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ViewedByStudent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Viewed by Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WGUCourseInProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The course that is in the program that the student is assigned to.</description>
        <label>WGU Course In Program</label>
        <referenceTo>WGUCourseInProgram__c</referenceTo>
        <relationshipLabel>Learning Communities</relationshipLabel>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>Community Access Controls</relationshipLabel>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Access Control</label>
    <nameField>
        <label>Access For</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Access Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for wguProgram</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseInProgram__c.object
<CustomObject>
    <description>A many to many mapping that assigns which course are required to accomplish any degree program.</description>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipName>PAMS_Course_In_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>WGU Course In Programs</relationshipLabel>
        <relationshipName>WGUCourseInPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course In Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WGU Course In Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <description>The ID that represents the program in PAMS.</description>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactStatusCourseCommunitySyncTest.cls
@IsTest
public class ContactStatusCourseCommunitySyncTest {

    @IsTest(SeeAllData=true) static void changeToASTest() {
        String networkId = ([SELECT Id FROM Network WHERE Name = 'WGU Commons']).id;
        CollaborationGroup newGroup = setupGroup(networkId);
        
        User u = [SELECT Id, ContactId FROM User WHERE ContactId != null AND Contact.Status__c != 'AS' AND Contact.WGUDegreeProgram__c != null AND IsActive = true AND Profile.Name = 'Student Profile' LIMIT 1];
        Contact con = [SELECT Id, Status__c, WGUDegreeProgram__c FROM Contact WHERE id = :u.contactId];
        
        WGUCourse__c c = new WGUCourse__c();
        c.Title__c = 'Introduction to Underwater Basket Weaving';
        c.Name = 'AAAA';
        c.PAMSID__c = 0;
        insert c;
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.GroupId__c = newGroup.id;
        cac.WGUCourse__c = c.id;
        cac.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Group Assignment'].id;
        insert cac;
        
        WGUCourseInProgram__c cip = new WGUCourseInProgram__c();
        cip.Course__c = c.id;
        cip.Program__c = con.WGUDegreeProgram__c;
        insert cip;

        CommunityAccessControl__c announcement = new CommunityAccessControl__c();
        announcement.GroupId__c = newGroup.id;
        announcement.AdministrationType__c = 'Announcement';
        announcement.DateAnnouncementExpires__c = System.today().addDays(5);
        announcement.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Community Administration' AND sObjectType = 'CommunityAccessControl__c'].id;
        insert announcement;
        
        Test.startTest();
        con.Status__c = 'AS';
        update con;
        Test.stopTest();
        
        List<CommunityAccessControl__c> cacList = [SELECT GroupId__c, CommunityStatus__c 
                                                     FROM CommunityAccessControl__c 
                                                    WHERE StudentUser__c = :u.id 
                                                      AND GroupId__c = :newGroup.id
                                                      AND RecordTypeId IN (SELECT Id FROM RecordType WHERE Name = 'Group Access')];

        System.assertEquals(1, cacList.size());
        System.assertEquals('Viewer', cacList.get(0).CommunityStatus__c);
        
        List<CollaborationGroupMember> cgmList = [SELECT NotificationFrequency FROM CollaborationGroupMember WHERE MemberId = :u.id AND CollaborationGroupId = :newGroup.id];
        System.assertEquals(1, cgmList.size());
        System.assertEquals('N', cgmList.get(0).NotificationFrequency);

        List<CommunityAccessControl__c> studentAnnouncementRecords = [SELECT Id 
                                                                        FROM CommunityAccessControl__c 
                                                                       WHERE StudentUser__c = :u.id 
                                                                         AND RecordType.Name = 'Course Announcement'
                                                                         AND AnnouncementRecord__c = :announcement.id
                                                                         AND ViewedByStudent__c = false];
        System.assertEquals(1, studentAnnouncementRecords.size());
    }
    
    @IsTest(SeeAllData=true) static void removeTest() {
        String networkId = ([SELECT Id FROM Network WHERE Name = 'WGU Commons']).id;
        CollaborationGroup newGroup = setupGroup(networkId);
        
        User u = [SELECT Id, ContactId FROM User WHERE ContactId != null AND Contact.Status__c != 'DR' AND Contact.WGUDegreeProgram__c != null AND IsActive = true AND Profile.Name = 'Student Profile' LIMIT 1];
        Contact con = [SELECT Id, Status__c, WGUDegreeProgram__c FROM Contact WHERE id = :u.contactId];
        
        CollaborationGroupMember groupMember = new CollaborationGroupMember();
        groupMember.CollaborationGroupId = newGroup.Id;
        groupMember.MemberId = u.Id;
        groupMember.CollaborationRole = 'Standard';
        groupMember.NotificationFrequency = 'N';
        insert groupMember;
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.CommunityStatus__c = 'Viewer';
        cac.StudentUser__c = u.Id;
        cac.GroupId__c = newGroup.Id;
        cac.CommunityId__c = networkId;
        cac.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Group Access'].id;
        insert cac;

        Test.startTest();
        con.Status__c = 'DR';
        update con;
        Test.stopTest();
        
        List<CommunityAccessControl__c> cacList = [SELECT GroupId__c, CommunityStatus__c 
                                                     FROM CommunityAccessControl__c 
                                                    WHERE StudentUser__c = :u.id 
                                                      AND GroupId__c = :newGroup.id
                                                      AND RecordTypeId IN (SELECT Id FROM RecordType WHERE Name = 'Group Access')];
        System.assertEquals(1, cacList.size());
        System.assertEquals('Removed', cacList.get(0).CommunityStatus__c);
        
        List<CollaborationGroupMember> cgmList = [SELECT NotificationFrequency FROM CollaborationGroupMember WHERE MemberId = :u.id AND CollaborationGroupId = :newGroup.id];
        System.assertEquals(0, cgmList.size());
    }
    
    @IsTest(SeeAllData=true) static void changeToAS_CGMAlreadyExistsNoUpdateTest() {
        String networkId = ([SELECT Id FROM Network WHERE Name = 'WGU Commons']).id;
        CollaborationGroup newGroup = setupGroup(networkId);
        
        User u = [SELECT Id, ContactId FROM User WHERE ContactId != null AND Contact.Status__c != 'AS' AND Contact.WGUDegreeProgram__c != null AND IsActive = true AND Profile.Name = 'Student Profile' LIMIT 1];
        Contact con = [SELECT Id, Status__c, WGUDegreeProgram__c FROM Contact WHERE id = :u.contactId];
        
        WGUCourse__c c = new WGUCourse__c();
        c.Title__c = 'Introduction to Underwater Basket Weaving';
        c.Name = 'AAAA';
        c.PAMSID__c = 0;
        insert c;
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.GroupId__c = newGroup.id;
        cac.WGUCourse__c = c.id;
        cac.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Group Assignment'].id;
        insert cac;
        
        WGUDegreeProgram__c dp = new WGUDegreeProgram__c();
        dp.Title__c = 'Bachelor of Science, Science!';
        dp.PAMSID__c = -1;
        insert dp;
        
        WGUCourseInProgram__c cip = new WGUCourseInProgram__c();
        cip.Course__c = c.id;
        cip.Program__c = con.WGUDegreeProgram__c;
        insert cip;
        
        CollaborationGroupMember cgm = new CollaborationGroupMember();
        cgm.CollaborationGroupId = newGroup.id;
        cgm.MemberId = u.id;
        cgm.CollaborationRole = 'Standard';
        cgm.NotificationFrequency = 'N';
        insert cgm;
        
        CommunityAccessControl__c permissionCac = new CommunityAccessControl__c();
        permissionCac.CommunityStatus__c = 'Viewer';
        permissionCac.StudentUser__c = u.id;
        permissionCac.GroupId__c = newGroup.id;
        permissionCac.CommunityId__c = networkId;
        permissionCac.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Group Access'].id;
        permissionCac.WGUCourse__c = c.id;
        insert permissionCac;
        
        Test.startTest();
        con.Status__c = 'AS';
        update con;
        Test.stopTest();
        
        List<CommunityAccessControl__c> cacList = [SELECT GroupId__c, CommunityStatus__c 
                                                     FROM CommunityAccessControl__c 
                                                    WHERE StudentUser__c = :u.id 
                                                      AND GroupId__c = :newGroup.id
                                                      AND RecordTypeId IN (SELECT Id FROM RecordType WHERE Name = 'Group Access')];
        System.assertEquals(1, cacList.size());
        System.assertEquals('Viewer', cacList.get(0).CommunityStatus__c);
        
        List<CollaborationGroupMember> cgmList = [SELECT NotificationFrequency FROM CollaborationGroupMember WHERE MemberId = :u.id AND CollaborationGroupId = :newGroup.id];
        System.assertEquals(1, cgmList.size());
        System.assertEquals('N', cgmList.get(0).NotificationFrequency);
    }
    
    @IsTest(SeeAllData=true) static void changeToAS_CGMAlreadyExistsUpdateTest() {
        String networkId = ([SELECT Id FROM Network WHERE Name = 'WGU Commons']).id;
        CollaborationGroup newGroup = setupGroup(networkId);
        
        User u = [SELECT Id, ContactId FROM User WHERE ContactId != null AND Contact.Status__c != 'AS' AND Contact.WGUDegreeProgram__c != null AND IsActive = true AND Profile.Name = 'Student Profile' LIMIT 1];
        Contact con = [SELECT Id, Status__c, WGUDegreeProgram__c FROM Contact WHERE id = :u.contactId];
        
        WGUCourse__c c = new WGUCourse__c();
        c.Title__c = 'Introduction to Underwater Basket Weaving';
        c.Name = 'AAAA';
        c.PAMSID__c = 0;
        insert c;
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.GroupId__c = newGroup.id;
        cac.WGUCourse__c = c.id;
        cac.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Group Assignment'].id;
        insert cac;
        
        WGUDegreeProgram__c dp = new WGUDegreeProgram__c();
        dp.Title__c = 'Bachelor of Science, Science!';
        dp.PAMSID__c = -1;
        insert dp;
        
        WGUCourseInProgram__c cip = new WGUCourseInProgram__c();
        cip.Course__c = c.id;
        cip.Program__c = con.WGUDegreeProgram__c;
        insert cip;
        
        CollaborationGroupMember cgm = new CollaborationGroupMember();
        cgm.CollaborationGroupId = newGroup.id;
        cgm.MemberId = u.id;
        cgm.CollaborationRole = 'Standard';
        cgm.NotificationFrequency = 'W';
        insert cgm;
        
        CommunityAccessControl__c permissionCac = new CommunityAccessControl__c();
        permissionCac.CommunityStatus__c = 'Removed';
        permissionCac.StudentUser__c = u.id;
        permissionCac.GroupId__c = newGroup.id;
        permissionCac.CommunityId__c = networkId;
        permissionCac.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Group Access'].id;
        permissionCac.WGUCourse__c = c.id;
        insert permissionCac;
        
        Test.startTest();
        con.Status__c = 'AS';
        update con;
        Test.stopTest();
        
        List<CommunityAccessControl__c> cacList = [SELECT GroupId__c, CommunityStatus__c 
                                                     FROM CommunityAccessControl__c 
                                                    WHERE StudentUser__c = :u.id 
                                                      AND GroupId__c = :newGroup.id
                                                      AND RecordTypeId IN (SELECT Id FROM RecordType WHERE Name = 'Group Access')];
        System.assertEquals(1, cacList.size());
        System.assertEquals('Viewer', cacList.get(0).CommunityStatus__c);
        
        List<CollaborationGroupMember> cgmList = [SELECT NotificationFrequency FROM CollaborationGroupMember WHERE MemberId = :u.id AND CollaborationGroupId = :newGroup.id];
        System.assertEquals(1, cgmList.size());
        System.assertEquals('N', cgmList.get(0).NotificationFrequency);
    }
        
    private static CollaborationGroup setupGroup(String networkId) {
        CollaborationGroup newGroup = new CollaborationGroup();
        newGroup.Name = 'AAAA';
        newGroup.CollaborationType = 'Public';
        newGroup.NetworkId = networkId;
        insert newGroup;
        return newGroup;
    }
    
}