src/objects/CommunityAccessControl__c.object
<CustomObject>
    <description>Object used by WGU Commons to manage the access level that students have to a community, a group, and custom groups.</description>
    <fields>
        <fullName>CommunityStatus__c</fullName>
        <description>Status level of the student in the learning community</description>
        <label>Community Status</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Super Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <description>Id of the group that the student is assigned to.</description>
        <label>Group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>Community Access Controls</relationshipLabel>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Access Control</label>
    <nameField>
        <label>Access For</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Access Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CurrentTerm__c</fullName>
        <description>Current Term for the student, this is wgu foramtted</description>
        <label>Current Term</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/StudentAcademicCourse__c.object
<CustomObject>
    <description>A representation of a course being taken at WGU wither in the past, current enrollment, or tentatively planned in the future. Includes credited courses such as transferred competency units or requirements met while working on  another degree.</description>
    <fields>
        <fullName>CourseCode__c</fullName>
        <description>The code the course is registered within Banner and PAMS.</description>
        <label>Course Code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the course in relation to the student&apos;s progress in it or credit to it.</description>
        <inlineHelpText>The status of the course in relation to the student&apos;s progress in it or credit to it.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements Met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <description>The student for which this course is entered.</description>
        <inlineHelpText>The student for which this course is entered.</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Academic Courses</relationshipLabel>
        <relationshipName>StudentAcademicCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>If course to enroll in the future then no term code may be specified but might be if Flexible Degree Plan was completed.</description>
        <inlineHelpText>If course to enroll in the future then no term code may be specified but might be if Flexible Degree Plan was completed.</inlineHelpText>
        <label>Term</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Student Academic Course</label>
    <nameField>
        <label>Course Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Academic Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Term__c.object
<CustomObject>
    <description>Term</description>
    <label>Term</label>
    <nameField>
        <label>Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Term</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseCommunitiesTermRollScheduledTest.cls
@IsTest
public class CourseCommunitiesTermRollScheduledTest {

    @IsTest(SeeAllData=true) static void testJob() {
        String currentTerm = DateTime.now().format('yyyyMM');
        
        User u = [SELECT Id, ContactId FROM User WHERE ContactId != null AND IsActive = true AND Profile.Name = 'Student Profile' LIMIT 1];
        Contact c = [SELECT CurrentTerm__c FROM Contact WHERE Id = :u.ContactId];
        c.CurrentTerm__c = currentTerm;
        update c;
        
        CollaborationGroup newGroup = new CollaborationGroup();
        newGroup.Name = 'AAAA';
        newGroup.CollaborationType = 'Public';
        newGroup.NetworkId = [SELECT Id FROM Network WHERE Name = 'WGU Commons'].id;
        insert newGroup;
        
        CollaborationGroupMember cgm = new CollaborationGroupMember();
        cgm.MemberId = u.id;
        cgm.CollaborationGroupId = newGroup.id;
        cgm.NotificationFrequency = 'W';
        cgm.CollaborationRole = 'Standard';
        insert cgm;
        
        WGUCourse__c course = new WGUCourse__c();
        course.Title__c = 'Introduction to Underwater Basket Weaving';
        course.Name = 'AAAA';
        course.PAMSID__c = 0;
        insert course;
        
        CommunityAccessControl__c cac = new CommunityAccessControl__c();
        cac.GroupId__c = newGroup.id;
        cac.WGUCourse__c = course.id;
        cac.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Group Assignment'].id;
        insert cac;
        
        CommunityAccessControl__c cac2 = new CommunityAccessControl__c();
        cac2.GroupId__c = newGroup.id;
        cac2.StudentUser__c = u.id;
        cac2.CommunityStatus__c = 'Viewer';
        cac2.WGUCourse__c = course.id;
        cac2.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Group Access'].id;
        insert cac2;
        
        StudentAcademicCourse__c sac = new StudentAcademicCourse__c();
        sac.CourseCode__c = 'AAAA';
        sac.Term__c = currentTerm;
        sac.Status__c = 'Registered';
        sac.StudentContact__c = u.ContactId;
        insert sac;
        
        Test.startTest();
        System.schedule('Test Course Communities Term Roll Scheduled Job', '0 0 0 3 9 ? 2022', new CourseCommunitiesTermRollScheduledJob(c.id));
        Test.stopTest();
        
        List<CommunityAccessControl__c> cacList = [SELECT CommunityStatus__c 
                                                     FROM CommunityAccessControl__c 
                                                    WHERE StudentUser__c = :u.id 
                                                      AND GroupId__c = :newGroup.id
                                                      AND RecordType.Name = 'Group Access'];
        System.assertEquals(1, cacList.size());
        System.assertEquals('Contributor', cacList.get(0).CommunityStatus__c);
    }
    
}