src/objects/CommunityAccessControl__c.object
<CustomObject>
    <description>Object used by WGU Commons to manage the access level that students have to a community, a group, and custom groups.</description>
    <fields>
        <fullName>CommunityStatus__c</fullName>
        <description>Status level of the student in the learning community</description>
        <label>Community Status</label>
        <picklist>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Super Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <description>Id of the group that the student is assigned to.</description>
        <label>Group Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourseInProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The course that is in the program that the student is assigned to.</description>
        <label>WGU Course In Program</label>
        <referenceTo>WGUCourseInProgram__c</referenceTo>
        <relationshipLabel>Learning Communities</relationshipLabel>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>Community Access Controls</relationshipLabel>
        <relationshipName>CommunityAccessControls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Access Control</label>
    <nameField>
        <label>Access For</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Access Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseInProgram__c.object
<CustomObject>
    <description>A many to many mapping that assigns which course are required to accomplish any degree program.</description>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipName>PAMS_Course_In_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>WGU Course In Programs</relationshipLabel>
        <relationshipName>WGUCourseInPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course In Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WGU Course In Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseCommunitySyncUtil.cls
public class CourseCommunitySyncUtil {
    
    public void populateCourseMapAndSet(Set<String> programIdSet, Map<String, List<String>> programCourseMap,
                                         Set<String> courseIdSet) 
    {
        List<WGUCourseInProgram__c> courseInProgramList = [SELECT Program__c, Course__c 
                                                             FROM WGUCourseInProgram__c 
                                                            WHERE Program__c IN :programIdSet
                                                            ORDER BY Program__c];
        
        String currentProgramId = null;
        for(WGUCourseInProgram__c courseInProgram : courseInProgramList) {
            if(currentProgramId == null || !currentProgramId.equals(courseInProgram.Program__c)) {
                currentProgramId = courseInProgram.Program__c;
                programCourseMap.put(courseInProgram.Program__c, new List<String>());
            }
            programCourseMap.get(courseInProgram.Program__c).add(courseInProgram.Course__c);
            courseIdSet.add(courseInProgram.Course__c);
        }
    }

    public Map<String, String> getGroupCourseMap(Set<String> courseIdSet) {
        List<CommunityAccessControl__c> cacList = [SELECT GroupId__c, WGUCourse__c 
                                                     FROM CommunityAccessControl__c 
                                                    WHERE WGUCourse__c IN :courseIdSet 
                                                      AND recordType.Name = 'Group Assignment'];

        Map<String, String> groupCourseMap = new Map<String, String>();
        for(CommunityAccessControl__c cac : cacList) {
            groupCourseMap.put(cac.WGUCourse__c, cac.GroupId__c);
        }
        return groupCourseMap;
    }
    
    public Map<String, Map<String, CommunityAccessControl__c>> getExistingPermissionMap(Set<String> userIdSet) {
        List<CommunityAccessControl__c> existingPermissionList = [SELECT GroupId__c, StudentUser__c, CommunityStatus__c
                                                                    FROM CommunityAccessControl__c 
                                                                   WHERE StudentUser__c IN :userIdSet 
                                                                     AND recordType.Name = 'Group Access'
                                                                   ORDER BY StudentUser__c];
        Map<String, Map<String, CommunityAccessControl__c>> existingPermissionMap = new Map<String, Map<String, CommunityAccessControl__c>>();
        String currentUserId = null;
        for(CommunityAccessControl__c cac : existingPermissionList) {
            if(currentUserId == null || !currentUserId.equals(cac.StudentUser__c)) {
                currentUserId = cac.StudentUser__c;
                existingPermissionMap.put(cac.StudentUser__c, new Map<String, CommunityAccessControl__c>());
            }
            existingPermissionMap.get(cac.StudentUser__c).put(cac.GroupId__c, cac);
        }
        return existingPermissionMap;
    }
    
    public Map<String, Map<String, CollaborationGroupMember>> getExistingGroupMap(Set<String> userIdSet) {
        List<CollaborationGroupMember> existingGroupList = [SELECT MemberId,
                                                                   CollaborationGroupId,
                                                                   NotificationFrequency
                                                              FROM CollaborationGroupMember
                                                             WHERE MemberId IN :userIdSet
                                                             ORDER BY MemberId];
        Map<String, Map<String, CollaborationGroupMember>> existingGroupMap = new Map<String, Map<String, CollaborationGroupMember>>();
        String currentMemberId = null;
        for(CollaborationGroupMember cgm : existingGroupList) {
            if(currentMemberId == null || !currentMemberId.equals(cgm.MemberId)) {
                currentMemberId = cgm.MemberId;
                existingGroupMap.put(cgm.MemberId, new Map<String, CollaborationGroupMember>());
            }
            existingGroupMap.get(cgm.MemberId).put(cgm.CollaborationGroupId, cgm);
        }
        return existingGroupMap;
    }
    
}