src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IDMRequiresUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by the IDM to detect if changes occurred on this contact record. Marked true by on update process handler, either workflow or trigger. Marked false when IDM completes processing the record.</description>
        <inlineHelpText>Used by the IDM to detect if changes occurred on this contact record. Marked true by on update process handler, either workflow or trigger. Marked false when IDM completes processing the record.</inlineHelpText>
        <label>IDM Requires Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>middleInitial__c</fullName>
        <label>Middle Initial</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>BusinessContact</fullName>
        <active>true</active>
        <description>A contact for an Account other than a StudentAccount, such as a School Administrator</description>
        <label>BusinessContact</label>
    </recordTypes>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/classes/TestContactTrigger.cls
@IsTest
public class TestContactTrigger{

    @IsTest static void IDMUpdateRequiredTest_true() {
        Contact c = new Contact();
        c.LastName = 'Test';
        c.MiddleInitial__c = 'A';
        c.recordTypeId = [SELECT Id FROM RecordType WHERE Name = 'StudentRecord' AND sObjectType = 'Contact'].id;
        c.pidm__c = '0';
        insert c;
        
        c.MiddleInitial__c = 'Z';
        Test.startTest();
        update c;
        Test.stopTest();
        
        Contact result = [SELECT IDMRequiresUpdate__c FROM Contact WHERE Id = :c.id];
        System.assertEquals(true, result.IDMRequiresUpdate__c);
    }
    
    @IsTest static void IDMUpdateRequiredTest_NullPIDM() {
        Contact c = new Contact();
        c.LastName = 'Test';
        c.MiddleInitial__c = 'A';
        c.recordTypeId = [SELECT Id FROM RecordType WHERE Name = 'StudentRecord' AND sObjectType = 'Contact'].id;
        insert c;
        
        c.MiddleInitial__c = 'Z';
        Test.startTest();
        update c;
        Test.stopTest();
        
        Contact result = [SELECT IDMRequiresUpdate__c FROM Contact WHERE Id = :c.id];
        System.assertEquals(false, result.IDMRequiresUpdate__c);
    }
    
    @IsTest static void IDMUpdateRequiredTest_NotAStudentRecordType() {
        Contact c = new Contact();
        c.LastName = 'Test';
        c.MiddleInitial__c = 'A';
        c.recordTypeId = [SELECT Id FROM RecordType WHERE Name = 'BusinessContact' AND sObjectType = 'Contact'].id;
        c.pidm__c = '0';
        insert c;
        
        c.MiddleInitial__c = 'Z';
        Test.startTest();
        update c;
        Test.stopTest();
        
        Contact result = [SELECT IDMRequiresUpdate__c FROM Contact WHERE Id = :c.id];
        System.assertEquals(false, result.IDMRequiresUpdate__c);
    }
    
}