src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/StudentAcademicCourse__c.object
<CustomObject>
    <description>A representation of a course being taken at WGU wither in the past, current enrollment, or tentatively planned in the future. Includes credited courses such as transferred competency units or requirements met while working on  another degree.</description>
    <fields>
        <fullName>CompetencyUnits__c</fullName>
        <description>The number of Competency Units this course is will put towards the student&apos;s degree program.</description>
        <label>Competency Units</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompositeKey__c</fullName>
        <externalId>true</externalId>
        <label>Composite Key</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CourseCode__c</fullName>
        <description>The code the course is registered within Banner and PAMS.</description>
        <label>Course Code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The last day of the term this course is enrolled. Will not be filled out on records with no term.</description>
        <inlineHelpText>The last day of the term this course is enrolled. Will not be filled out on records with no term.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The first day of the term this course is enrolled. Will not be filled out on records with no term.</description>
        <inlineHelpText>The first day of the term this course is enrolled. Will not be filled out on records with no term.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the course in relation to the student&apos;s progress in it or credit to it.</description>
        <inlineHelpText>The status of the course in relation to the student&apos;s progress in it or credit to it.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements Met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <description>The student for which this course is entered.</description>
        <inlineHelpText>The student for which this course is entered.</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Academic Courses</relationshipLabel>
        <relationshipName>StudentAcademicCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>If course to enroll in the future then no term code may be specified but might be if Flexible Degree Plan was completed.</description>
        <inlineHelpText>If course to enroll in the future then no term code may be specified but might be if Flexible Degree Plan was completed.</inlineHelpText>
        <label>Term</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Objective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student Academic Course</label>
    <nameField>
        <label>Course Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Academic Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentAcademicCourseFromBanner__c.object
<CustomObject>
    <description>Control object for receiving Student Academic Course records from Banner</description>
    <fields>
        <fullName>ActionNeeded__c</fullName>
        <label>Action Needed</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompetencyUnitsIN__c</fullName>
        <label>Competency Units (IN)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompositeKeyIN__c</fullName>
        <description>PIDM + Course Code + Term Code</description>
        <externalId>true</externalId>
        <label>Composite Key (IN)</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CourseCodeIN__c</fullName>
        <label>Course Code (IN)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CourseTitleIn__c</fullName>
        <label>Course Title (IN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDateIN__c</fullName>
        <label>End Date (IN)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDateIN__c</fullName>
        <label>Start Date (IN)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusIN__c</fullName>
        <description>Status of the assessment (passed, not passed, transferred, etc)</description>
        <label>Status (IN)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAcademicCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Academic Course</label>
        <referenceTo>StudentAcademicCourse__c</referenceTo>
        <relationshipLabel>Student Academic Courses From Banner</relationshipLabel>
        <relationshipName>StudentAcademicCoursesFromBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentPIDMIN__c</fullName>
        <label>Student PIDM (IN)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TermIN__c</fullName>
        <label>Term (IN)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeIN__c</fullName>
        <description>Obj/Prfm etc</description>
        <label>Type (IN)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Student Academic Course From Banner</label>
    <nameField>
        <displayFormat>SACFB-{0}</displayFormat>
        <label>Student Academic Course From Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Academic Courses From Banner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Term__c.object
<CustomObject>
    <description>Term</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End Date referenced the end date for the term.</description>
        <inlineHelpText>End Date referenced the end date for the term.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Start Date referenced the start date for the term.</description>
        <inlineHelpText>Start Date referenced the start date for the term.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Term</label>
    <nameField>
        <label>Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Term</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestStudentAcademicCourseUtility.cls
/*****************************************************************************************
* Name: TestStudentAcademicCourseUtility
* Author: Will Slade
* Purpose: Test StudentAcademicCourseUtility class and trigger
* Revisions: 
*    - 10/25/2013 Created Class
*
******************************************************************************************/

@isTest
public class TestStudentAcademicCourseUtility
{
    private static testmethod void testUpsertSourceObject()
    {
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        Contact baggins = [SELECT Id, PIDM__c, FirstName, LastName FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        StudentAcademicCourseFromBanner__c sacfb = new StudentAcademicCourseFromBanner__c(
                                                         ActionNeeded__c='UPSERT',CompetencyUnitsIN__c=2,
                                                         CompositeKeyIN__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         CourseCodeIN__c='CRSE',CourseTitleIN__c='test class course',
                                                         EndDateIN__c=date.valueOf('2013-10-25'),
                                                         startDateIN__c=date.valueOf('2013-10-01'),
                                                         StatusIN__c='PA',studentPIDMIN__c=baggins.PIDM__c,
                                                         termIN__c='201310',TypeIN__c='PRFA',StudentAcademicCourse__c=null);
        Test.startTest();
         insert sacfb;
        Test.stopTest();
       
        List<StudentAcademicCourse__c> sacList = [ select Id,name,competencyUnits__c,compositeKey__c,coursecode__c,enddate__c,startdate__c,
                                                  status__c,StudentContact__c,term__c,type__c
                                                 from StudentAcademicCourse__c
                                                 where compositeKey__c = :sacfb.CompositeKeyIN__c ];        
        System.assertEquals(sacList.size(), 1, 'Excess control records created - expected 1, found ' + sacList.size() ); 
        System.assertEquals(sacfb.CompetencyUnitsIN__c, sacList[0].competencyUnits__c, 'Incorrect comp-Units');
        System.assertEquals(sacfb.CompositeKeyIN__c, sacList[0].compositeKey__c, 'Incorrect comp-key');
        System.assertEquals(sacfb.CourseCodeIN__c, sacList[0].coursecode__c, 'Incorrect course code');
        System.assertEquals(sacfb.enddateIN__c, sacList[0].enddate__c, 'Incorrect End date');
        System.assertEquals(sacfb.startdateIN__c, sacList[0].startdate__c, 'Incorrect start date');
        System.assertEquals('Passed', sacList[0].status__c, 'Incorrect status');
        System.assertEquals(baggins.id, sacList[0].StudentContact__c, 'Incorrect contact id');
        System.assertEquals(sacfb.termIN__c, sacList[0].term__c, 'Incorrect Term');
        System.assertEquals('Performance', sacList[0].type__c, 'Incorrect Type');
        System.assertEquals(sacfb.CourseTitleIN__c, sacList[0].Name, 'Incorrect SAC name-title');
    }
    
    private static testmethod void testUpsertSourceObject2(){
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        Contact baggins = [SELECT Id, PIDM__c, FirstName, LastName FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        StudentAcademicCourseFromBanner__c sacfb = new StudentAcademicCourseFromBanner__c(
                                                         ActionNeeded__c='UPSERT',CompetencyUnitsIN__c=2,                                                        
                                                         CourseCodeIN__c='CRSE',CourseTitleIN__c='test class course',
                                                         studentPIDMIN__c=baggins.PIDM__c,
                                                         termIN__c='201310',TypeIN__c='Task');
        Test.startTest();
         insert sacfb;
        Test.stopTest();
        List<StudentAcademicCourse__c> sacList = [ select Id,name,competencyUnits__c,compositeKey__c,coursecode__c,enddate__c,startdate__c,
                                                  status__c,StudentContact__c,term__c,type__c
                                                 from StudentAcademicCourse__c
                                                 where compositeKey__c = :sacfb.CompositeKeyIN__c ];        
        System.assertEquals(sacList.size(), 0, 'Incorrect record size when wrong insertion.');
    }
    
    private static testmethod void testUpsertSourceObject3(){
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        Contact baggins = [SELECT Id, PIDM__c, FirstName, LastName FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        StudentAcademicCourseFromBanner__c sacfb = new StudentAcademicCourseFromBanner__c(
                                                         ActionNeeded__c='UPSERT',CompetencyUnitsIN__c=2,
                                                         CompositeKeyIN__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         CourseCodeIN__c='CRSE',CourseTitleIN__c='test class course',
                                                         EndDateIN__c=date.valueOf('2013-10-25'),
                                                         startDateIN__c=date.valueOf('2013-10-01'),
                                                         StatusIN__c='PA',studentPIDMIN__c=baggins.PIDM__c,
                                                         termIN__c='201310',TypeIN__c='EXTLR',StudentAcademicCourse__c=null);
        insert sacfb;
        sacfb.EndDateIN__c=date.valueOf('2013-10-31');
        sacfb.StatusIN__c = 'NP';
        Test.startTest();
         update sacfb;
         sacfb.StatusIN__c = 'TR';
         update sacfb;
         sacfb.StatusIN__c = 'test';
         update sacfb;
         sacfb.StatusIN__c = 'WV';
         update sacfb;
        Test.stopTest();
        List<StudentAcademicCourse__c> sacList = [ select Id,name,competencyUnits__c,compositeKey__c,coursecode__c,enddate__c,startdate__c,
                                                  status__c,StudentContact__c,term__c,type__c
                                                 from StudentAcademicCourse__c
                                                 where compositeKey__c = :sacfb.CompositeKeyIN__c ];        
        System.assertEquals(sacList.size(), 1, 'Excess control records created - expected 1, found ' + sacList.size() ); 
        System.assertEquals(sacfb.CompetencyUnitsIN__c, sacList[0].competencyUnits__c, 'Incorrect comp-Units');
        System.assertEquals(sacfb.CompositeKeyIN__c, sacList[0].compositeKey__c, 'Incorrect comp-key');
        System.assertEquals(sacfb.CourseCodeIN__c, sacList[0].coursecode__c, 'Incorrect course code');
        System.assertEquals(sacfb.enddateIN__c, sacList[0].enddate__c, 'Incorrect End date');
        System.assertEquals(sacfb.startdateIN__c, sacList[0].startdate__c, 'Incorrect start date');
        System.assertEquals('Waived', sacList[0].status__c, 'Incorrect status');
        System.assertEquals(baggins.id, sacList[0].StudentContact__c, 'Incorrect contact id');
        System.assertEquals(sacfb.termIN__c, sacList[0].term__c, 'Incorrect Term');
        System.assertEquals('Not Applicable', sacList[0].type__c, 'Incorrect Type');
        System.assertEquals(sacfb.CourseTitleIN__c, sacList[0].Name, 'Incorrect SAC name-title');
    }
    
    private static testmethod void testUpsertSourceObject4(){
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        Contact baggins = [SELECT Id, PIDM__c, FirstName, LastName FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        StudentAcademicCourseFromBanner__c sacfb = new StudentAcademicCourseFromBanner__c(
                                                         ActionNeeded__c='UPSERT',CompetencyUnitsIN__c=2,
                                                         CompositeKeyIN__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         CourseCodeIN__c='CRSE',CourseTitleIN__c='test class course',
                                                         EndDateIN__c=date.valueOf('2013-10-25'),
                                                         startDateIN__c=date.valueOf('2013-10-01'),
                                                         StatusIN__c='PA',studentPIDMIN__c=baggins.PIDM__c,
                                                         termIN__c='201310',TypeIN__c='OBJA',StudentAcademicCourse__c=null);
        insert sacfb;
        sacfb.EndDateIN__c=date.valueOf('2013-10-31');
        sacfb.StatusIN__c = 'RM';
        sacfb.ActionNeeded__c = 'DELETE';
        Test.startTest();
         update sacfb;
        Test.stopTest();
        List<StudentAcademicCourse__c> sacList = [ select Id,name,competencyUnits__c,compositeKey__c,coursecode__c,enddate__c,startdate__c,
                                                  status__c,StudentContact__c,term__c,type__c
                                                 from StudentAcademicCourse__c
                                                 where compositeKey__c = :sacfb.CompositeKeyIN__c ];        
        System.assertEquals(sacList.size(), 0, 'Incorrect record size after deletion.');
    }
}