src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StatusDate__c</fullName>
        <label>Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TermCode__c</fullName>
        <description>The current TERM Code year + month</description>
        <formula>TEXT(YEAR(TermStartDate__c))  &amp; 
IF(MONTH(TermStartDate__c) &lt; 10, &apos;0&apos;, NULL) &amp;
TEXT(Month( TermStartDate__c ))</formula>
        <inlineHelpText>Term Code</inlineHelpText>
        <label>Term Code</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StudentCompletionCourse__c.object
<CustomObject>
    <description>This stores the information for the results of the courses.</description>
    <fields>
        <fullName>BannerActivityDate__c</fullName>
        <description>Banner activity date</description>
        <label>Banner Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InPreviousProgram__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Value that indicates whether the course was completed in a previous program</description>
        <label>In Previous Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The internal identifier of the student.</description>
        <label>PIDM</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusDate__c</fullName>
        <description>The date when this occurred</description>
        <label>Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TermCode__c</fullName>
        <description>The term code when this course was completed (or failed)</description>
        <label>Term Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The WGUCourse Version for this completed course</description>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Student Completion Courses</relationshipLabel>
        <relationshipName>StudentCompletionCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>link to wgucourse</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>Student Completion Courses</relationshipLabel>
        <relationshipName>Student_Completion_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>Status of the course</description>
        <label>status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Student Completion Course</label>
    <nameField>
        <label>PAMS Course ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Completion Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentCompletionTask__c.object
<CustomObject>
    <description>Custom object to manage student assessments, requirements, and zero CU tasks by recordtype.</description>
    <fields>
        <fullName>AssessmentStatus__c</fullName>
        <label>Assessment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Attempted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Satisfied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdraw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Recheck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BannerActivityDate__c</fullName>
        <label>Banner Activity Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RequirementComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requirement Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StatusDate__c</fullName>
        <label>Status Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StudentPIDM__c</fullName>
        <label>Student PIDM</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TermCode__c</fullName>
        <label>Term Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUCourseCompletionTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Course Completion Task</label>
        <referenceTo>WGUCourseCompletionTask__c</referenceTo>
        <relationshipName>StudentCourseCompletionTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Completion Task</label>
    <nameField>
        <label>Student Task Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Completion Tasks</pluralLabel>
    <recordTypes>
        <fullName>Requirement</fullName>
        <active>false</active>
        <label>Requirement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentCourseRegistration__c.object
<CustomObject>
    <description>This is an object for pulling current term registration  information from WGUFDP. No FDP user should have direct access to this Object,</description>
    <fields>
        <fullName>Banneractivitydate__c</fullName>
        <description>last update or insert date on banner for this record</description>
        <label>Banner Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CourseCode__c</fullName>
        <description>Banner code for the course</description>
        <label>CourseCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Termcode__c</fullName>
        <label>Termcode</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookout for wgucourse.</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>Student Course Registrations</relationshipLabel>
        <relationshipName>StudentCourseRegistrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>enddate__c</fullName>
        <label>enddate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pidm__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for referential integrity</description>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>pidm</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>startdate__c</fullName>
        <label>startdate</label>
        <type>Date</type>
    </fields>
    <label>Student Course Registration</label>
    <nameField>
        <label>StudentCourseRegistration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Course Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentTermBreak__c.object
<CustomObject>
    <description>Imported term break information</description>
    <fields>
        <fullName>Code__c</fullName>
        <description>The leave code</description>
        <label>Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EffectiveTermCode__c</fullName>
        <description>The term code when this will be effective</description>
        <label>Effective Term Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The end date of the term break</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The student&apos;s PIDM</description>
        <label>PIDM</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The start date of the term break</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <description>Unique id for the record</description>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <label>Student Term Break</label>
    <nameField>
        <label>Student Term Break Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Term Breaks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>MajorVersion__c</fullName>
        <label>Major Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseCompletionTask__c.object
<CustomObject>
    <description>Custom object to manage template definitions for course assessments, requirements, or tasks. Student instances of assessments are managed via the StudentCourseCompletionTask__c object.</description>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>WGU Course Completion Task</relationshipLabel>
        <relationshipName>WGUCourseCompletionTask</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Course that this task is a requirement to complete.</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>WGU Course Completion Task</relationshipLabel>
        <relationshipName>WGUCourseCompletionTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course Completion Task</label>
    <nameField>
        <label>WGU Course Task Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Completion Task</pluralLabel>
    <recordTypes>
        <fullName>Requirement</fullName>
        <active>false</active>
        <label>Requirement</label>
    </recordTypes>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <fields>
        <fullName>MajorVersion__c</fullName>
        <description>The major version of the course</description>
        <label>Major Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The course that this course version belongs to</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>WGU Course Versions</relationshipLabel>
        <relationshipName>WGUCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FDPAccountTestingUtility.cls
public with sharing class FDPAccountTestingUtility {
  List<StudentCompletionTask__c> studentCompletionTasks;
  List<StudentCompletionCourse__c> studentCompletionCourseVersions;
  List<StudentCourseRegistration__c> studentCourseRegistrations;
  List<StudentTermBreak__c> studentTermBreaks;
  public Enum CourseCompletionType {Passed, Failed, Transfer, RequirementMet, RequirementSatisfied, Waived, PreviousProgram}
  public with sharing class CompletedCourse {
    public WGUCourse__c course;
    public WGUCourseVersion__c version;
    public CourseCompletionType cType;
    public Date completionDate;
  }
  Map<String,CompletedCourse> completedCourses;
  Set<Id> completedCourseIds;
  AccountTestingUtility atu;
  public AccountTestingUtility.TestingStudentInfo student1 {
    get {
      return atu.student1;
    }
  }
  public AccountTestingUtility.TestingMentorInfo mentor1 {
    get {
      return atu.mentor1;
    }
  }

  public AccountTestingUtility.TestingStudentInfo student2 {
    get {
      return atu.student2;
    }
  }

  public AccountTestingUtility.TestingMentorInfo mentor2 {
    get {
      return atu.mentor2;
    }
  }

  public List<AccountTestingUtility.TestingStudentInfo> students;
  public List<AccountTestingUtility.TestingMentorInfo> mentors;

  public FDPAccountTestingUtility(String pBoxName) {
    atu = new AccountTestingUtility(pBoxName);
    studentCompletionTasks = new List<StudentCompletionTask__c>();
    studentCourseRegistrations = new List<StudentCourseRegistration__c>();
    completedCourses = new Map<String,CompletedCourse>();
    completedCourseIds = new Set<Id>();
    studentCompletionCourseVersions = new List<StudentCompletionCourse__c>();
    students = new List<AccountTestingUtility.TestingStudentInfo>();
    students.add(atu.student1);
    students.add(atu.student2);
    mentors = new List<AccountTestingUtility.TestingMentorInfo>();
    mentors.add(atu.mentor1);
    mentors.add(atu.mentor2);
    studentTermBreaks = new List<StudentTermBreak__c>();
  }

  public void createTermBreakInfo() {
    for(AccountTestingUtility.TestingStudentInfo student : students) {
      StudentTermBreak__c tb = new StudentTermBreak__c();
      tb.PIDM__c = student.PIDM;
      tb.EffectiveTermCode__c = student.Contact.TermCode__c;
      tb.Code__c = 'A';
      tb.StartDate__c = Date.today().addMonths(6);
      tb.EndDate__c = Date.today().addMonths(9);
      tb.Unique_Id__c = tb.PIDM__c + '-' + tb.EffectiveTermCode__c;
      studentTermBreaks.add(tb);
    }
  }

  public void saveAccounts() {
    atu.save();
  }

  public void onlyWorkWith(String pidm) {
    atu.onlyWorkWith(pidm);
    atu.save();
    AccountTestingUtility.TestingStudentInfo stu;
    for(AccountTestingUtility.TestingStudentInfo student : students) {
      if(stu.pidm == pidm) {
        stu = student;
      }
    }
    students.clear();
    students.add(stu);
  }

  public List<StudentCourseRegistration__c> addEnrolledCourse(WGUCourse__c course, Date pWhen) {
    for(AccountTestingUtility.TestingStudentInfo student : students) {
      StudentCourseRegistration__c scr = new StudentCourseRegistration__c();
      scr.PIDM__c = student.PIDM;
      scr.TermCode__c = FDPUtilities.generateTermCode(pWhen);
      scr.StartDate__c = pWhen;
      scr.EndDate__c = pWhen;
      scr.BannerActivityDate__c = pWhen;
      scr.CourseCode__c = course.Name;
      studentCourseRegistrations.add(scr);
    }
    return studentCourseRegistrations;
  }


  public void addCompletionCourse(WGUCourse__c course, Date pWhen, CourseCompletionType pType) {
    CompletedCourse c = new CompletedCourse();
    c.course = course;
    c.completionDate = pWhen;
    c.cType = pType;
    String foo = String.valueOf(course.Id) + ':' + String.valueOf(pWhen);
    completedCourses.put(foo,c);
    completedCourseIds.add(course.Id);
  }

  public void addPassedCourse(WGUCourse__c course, Date pWhen) {
    addCompletionCourse(course,pWhen,CourseCompletionType.Passed);
  }

  public void addFailedCourse(WGUCourse__c course, Date pWhen) {
    addCompletionCourse(course,pWhen,CourseCompletionType.Failed);
  }

  public void addTransferCourse(WGUCourse__c course) {
    addCompletionCourse(course,null,CourseCompletionType.Transfer);
  }

  public void addRequirementMetCourse(WGUCourse__c course, Date pWhen) {
    addCompletionCourse(course,pWhen,CourseCompletionType.RequirementMet);
  }

  public void addRequirementSatisfiedCourse(WGUCourse__c course, Date pWhen) {
    addCompletionCourse(course,pWhen,CourseCompletionType.RequirementMet);
  }

  public void addWaivedCourse(WGUCourse__c course) {
    addCompletionCourse(course,null,CourseCompletionType.Waived);
  }

  public void addPreviousProgramCourse(WGUCourse__c course, Date pWhen) {
    addCompletionCourse(course,pWhen,CourseCompletionType.PreviousProgram);
  }

  public void addPassedCourseVersion(WGUCourseVersion__c cv, Date pWhen) {
    for(StudentCompletionCourse__c c : addCompletedCourseVersion(cv,pWhen)) {
      c.Status__c = 'Passed';
    }
  }

  public void addFailedCourseVersion(WGUCourseVersion__c cv, Date pWhen) {
    for(StudentCompletionCourse__c c : addCompletedCourseVersion(cv,pWhen)) {
      c.Status__c = 'Not Passed';
    }
  }

  public void addRequirementSatisfiedCourseVersion(WGUCourseVersion__c cv, Date pWhen) {
    for(StudentCompletionCourse__c c : addCompletedCourseVersion(cv,pWhen)) {
      c.Status__c = 'Requirement Satisfied';
    }
  }

  public void addRequirementMetCourseVersion(WGUCourseVersion__c cv, Date pWhen) {
    for(StudentCompletionCourse__c c : addCompletedCourseVersion(cv,pWhen)) {
      c.Status__c = 'Requirement Met';
    }
  }

  public void addWaivedCourseVersion(WGUCourseVersion__c cv) {
    Date pWhen = Date.newInstance(1901,1,1);
    for(StudentCompletionCourse__c c : addCompletedCourseVersion(cv,pWhen)) {
      c.Status__c = 'Waived';
    }
  }

  public void addPreviousProgramCourseVersion(WGUCourseVersion__c cv, Date pWhen) {
    for(StudentCompletionCourse__c c : addCompletedCourseVersion(cv,pWhen)) {
      c.Status__c = 'Passed';
      c.InPreviousProgram__c = true;
    }
  }

  public void addTransferCourseVersion(WGUCourseVersion__c cv) {
    Date pWhen = Date.newInstance(1901,1,1);
    for(StudentCompletionCourse__c c : addCompletedCourseVersion(cv,pWhen)) {
      c.Status__c = 'Transferred';
    }
  }

  public List<StudentCompletionCourse__c> addCompletedCourseVersion(WGUCourseVersion__c cv, Date pWhen) {
    List<StudentCompletionCourse__c> courses = new List<StudentCompletionCourse__c>();
    for(AccountTestingUtility.TestingStudentInfo student : students) {
      StudentCompletionCourse__c c = new StudentCompletionCourse__c();
      c.PIDM__c = student.contact.PIDM__c;
      c.StatusDate__c = pWhen;
      c.BannerActivityDate__c = pWhen;
      c.TermCode__c = FDPTestingUtilities.generateTermCode(pWhen);
      c.Name = cv.WGUCourse__r.Name;
      //c.WGUCourseVersion__c = cv.Id;
      studentCompletionCourseVersions.add(c);
      courses.add(c);
    }
    return courses;
  }

  public void addFailedAssessment(WGUCourseCompletionTask__c task, Date pWhen) {
    for(StudentCompletionTask__c t : addCompletionTask(task,pWhen)) {
      t.RequirementComplete__c = false;
      t.AssessmentStatus__c = 'Failed';
    }
  }
  public void addPassedAssessment(WGUCourseCompletionTask__c task, Date pWhen) {
    for(StudentCompletionTask__c t : addCompletionTask(task,pWhen)) {
      t.RequirementComplete__c = true;
      t.AssessmentStatus__c = 'Passed';
    }
  }
  public void addTransferCredit(WGUCourseCompletionTask__c task) {
    Date pWhen = Date.newInstance(1901,1,1);
    for(StudentCompletionTask__c t : addCompletionTask(task,pWhen)) {
      t.RequirementComplete__c = true;
      t.AssessmentStatus__c = 'Passed';
    }
  }

  private List<StudentCompletionTask__c> addCompletionTask(WGUCourseCompletionTask__c task, Date pWhen) {
    List<StudentCompletionTask__c> tasks = new List<StudentCompletionTask__c>();
    for(AccountTestingUtility.TestingStudentInfo student : students) {
      StudentCompletionTask__c t = new StudentCompletionTask__c();
      t.StudentPIDM__c = student.contact.PIDM__c;
      t.StatusDate__c = pWhen;
      t.TermCode__c = FDPTestingUtilities.generateTermCode(pWhen);
      t.Name = task.Name;
      studentCompletionTasks.add(t);
      tasks.add(t);
    }
    return tasks;
  }

  public void fetchCourseVersions() {
    List<WGUCourseVersion__c> courseVersions = [select
      MajorVersion__c,
      WGUCourse__r.Id,
      WGUCourse__r.Name,
      WGUCourse__c,
      PAMSCourseId__c
      from WGUCourseVersion__c
      where WGUCourse__r.Id in :completedCourseIds];
    Map<String,WGUCourseVersion__c> courseToCourseVersion = new Map<String,WGUCourseVersion__c>();
    for(WGUCourseVersion__c cv : courseVersions) {
      if(!courseToCourseVersion.containsKey(cv.WGUCourse__r.Id)) {
        courseToCourseVersion.put(cv.WGUCourse__r.Id,cv);
      } else if(courseToCourseVersion.get(cv.WGUCourse__r.Id).MajorVersion__c < cv.MajorVersion__c) {
        courseToCourseVersion.put(cv.WGUCourse__r.Id,cv);
      }
    }
    for(String key : completedCourses.keySet()) {
      CompletedCourse cc = completedCourses.get(key);
      String thisId = key.split(':',2).get(0);
      cc.version = courseToCourseVersion.get(thisId);
      if(cc.cType == CourseCompletionType.Passed) {
        addPassedCourseVersion(cc.version,cc.completionDate);
      } else if(cc.cType == CourseCompletionType.Failed) {
        addFailedCourseVersion(cc.version,cc.completionDate);
      } else if(cc.cType == CourseCompletionType.RequirementMet) {
        addRequirementMetCourseVersion(cc.version,cc.completionDate);
      } else if(cc.cType == CourseCompletionType.RequirementSatisfied) {
        addRequirementSatisfiedCourseVersion(cc.version,cc.completionDate);
      } else if(cc.cType == CourseCompletionType.Waived) {
        addWaivedCourseVersion(cc.version);
      } else if(cc.cType == CourseCompletionType.PreviousProgram) {
        addPreviousProgramCourseVersion(cc.version,cc.completionDate);
      } else {
        addTransferCourseVersion(cc.version);
      }
    }
  }

  public void saveCourseVersions() {
    fetchCourseVersions();
    for(StudentCompletionCourse__c c : studentCompletionCourseVersions) {
    }
    upsert studentCompletionCourseVersions;
  }

  public void saveTermBreaks() {
    upsert studentTermBreaks;
  }

  public void saveAssessments() {
    upsert studentCompletionTasks;
  }

  public void saveCourseRegistrations() {
    upsert studentCourseRegistrations;
  }

}