src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/StudentAcademicCourse__c.object
<CustomObject>
    <description>A representation of a course being taken at WGU wither in the past, current enrollment, or tentatively planned in the future. Includes credited courses such as transferred competency units or requirements met while working on  another degree.</description>
    <fields>
        <fullName>CompetencyUnits__c</fullName>
        <description>The number of Competency Units this course is will put towards the student&apos;s degree program.</description>
        <label>Competency Units</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompositeKey__c</fullName>
        <externalId>true</externalId>
        <label>Composite Key</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CourseCode__c</fullName>
        <description>The code the course is registered within Banner and PAMS.</description>
        <label>Course Code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The last day of the term this course is enrolled. Will not be filled out on records with no term.</description>
        <inlineHelpText>The last day of the term this course is enrolled. Will not be filled out on records with no term.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FullCourseTitle__c</fullName>
        <label>Full Course Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The first day of the term this course is enrolled. Will not be filled out on records with no term.</description>
        <inlineHelpText>The first day of the term this course is enrolled. Will not be filled out on records with no term.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the course in relation to the student&apos;s progress in it or credit to it.</description>
        <inlineHelpText>The status of the course in relation to the student&apos;s progress in it or credit to it.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements Met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <description>The student for which this course is entered.</description>
        <inlineHelpText>The student for which this course is entered.</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Academic Courses</relationshipLabel>
        <relationshipName>StudentAcademicCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>If course to enroll in the future then no term code may be specified but might be if Flexible Degree Plan was completed.</description>
        <inlineHelpText>If course to enroll in the future then no term code may be specified but might be if Flexible Degree Plan was completed.</inlineHelpText>
        <label>Term</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Objective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <description>The version of the course that the student is set to take.</description>
        <label>Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Student Academic Course</label>
    <nameField>
        <label>Course Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Academic Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentAcademicCourseFromBanner__c.object
<CustomObject>
    <description>Control object for receiving Student Academic Course records from Banner</description>
    <fields>
        <fullName>ActionNeeded__c</fullName>
        <label>Action Needed</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompetencyUnitsIN__c</fullName>
        <label>Competency Units (IN)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompositeKeyIN__c</fullName>
        <description>PIDM + Course Code + Term Code</description>
        <externalId>true</externalId>
        <label>Composite Key (IN)</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CourseCodeIN__c</fullName>
        <label>Course Code (IN)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CourseTitleIn__c</fullName>
        <label>Course Title (IN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndDateIN__c</fullName>
        <label>End Date (IN)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDateIN__c</fullName>
        <label>Start Date (IN)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusIN__c</fullName>
        <description>Status of the assessment (passed, not passed, transferred, etc)</description>
        <label>Status (IN)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAcademicCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Academic Course</label>
        <referenceTo>StudentAcademicCourse__c</referenceTo>
        <relationshipLabel>Student Academic Courses From Banner</relationshipLabel>
        <relationshipName>StudentAcademicCoursesFromBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentPIDMIN__c</fullName>
        <label>Student PIDM (IN)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SynchronizationError__c</fullName>
        <label>Synchronization Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TermIN__c</fullName>
        <label>Term (IN)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeIN__c</fullName>
        <description>Obj/Prfm etc</description>
        <label>Type (IN)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Student Academic Course From Banner</label>
    <nameField>
        <displayFormat>SACFB-{0}</displayFormat>
        <label>Student Academic Course From Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Academic Courses From Banner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentAcademicCourseRequirement__c.object
<CustomObject>
    <description>Stores the requirements to complete a version of a course. For many records early on, this will only be one assessment to a course. Nursing will be the first group to apply multiple assessments to course. Several roll up summaries will be placed on the parent object to summarize status and engagement.</description>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RequirementCode__c</fullName>
        <label>Requirement Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The text status from Course of Study.</description>
        <label>Status</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAcademicCourse__c</fullName>
        <label>Student Academic Course</label>
        <referenceTo>StudentAcademicCourse__c</referenceTo>
        <relationshipLabel>Student Academic Course Requirements</relationshipLabel>
        <relationshipName>StudentAcademicCourseRequirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Objective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Student Academic Course Requirement</label>
    <nameField>
        <label>Assessment / Task Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Academic Course Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Term__c.object
<CustomObject>
    <description>Term</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End Date referenced the end date for the term.</description>
        <inlineHelpText>End Date referenced the end date for the term.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Start Date referenced the start date for the term.</description>
        <inlineHelpText>Start Date referenced the start date for the term.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Term</label>
    <nameField>
        <label>Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Term</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StudentAcademicCourseUtility.cls
/*****************************************************************************************
* Name: StudentAcademicCourseUtility
* Author: Will Slade
* Purpose: Upserts Student Academic Courses based on control object
* Revisions: 
*    - 10/21/2013 Created Class
*
******************************************************************************************/

public class StudentAcademicCourseUtility
{
    public static void upsertCourses(String sacfbListJSON)
    {
        if (Limits.getFutureCalls() > 3 || System.isFuture())
        {
            processUpsertCourses(sacfbListJSON);
        }
        else
        {
            asyncUpsertCourses(sacfbListJSON);
        }
    }
    
    @future
    public static void asyncUpsertCourses(String sacfbListJSON)
    {
        processUpsertCourses(sacfbListJSON);
    }

    public static void processUpsertCourses(String sacfbListJSON)
    {
        List<StudentAcademicCourseFromBanner__c> sacfbList = (List<StudentAcademicCourseFromBanner__c>) JSON.deserialize(sacfbListJSON, List<StudentAcademicCourseFromBanner__c>.class);
        List<StudentAcademicCourse__c> sacInsertList = new List<StudentAcademicCourse__c>();
        List<StudentAcademicCourse__c> sacUpdateList = new List<StudentAcademicCourse__c>();
        List<StudentAcademicCourse__c> sacDeleteList = new List<StudentAcademicCourse__c>();
        Map<String, Id> pidmToContactIdMap = new Map<String, Id>();
        String courseStatus = null;
        Id studentContact = null;       
        
        //get a keyset of the student pidms for the contact map
        for (StudentAcademicCourseFromBanner__c thisSACFB : sacfbList)
        {
            pidmToContactIdMap.put(thisSACFB.studentPIDMIN__c, null);
        }      
        
        //find all contact records within pidm set
        List<Contact> contactList = [SELECT Id, PIDM__c FROM Contact WHERE PIDM__c IN :pidmToContactIdMap.keyset()];
        
        //populate contact IDs in map
        for (Contact thisContact : contactList)
        {
            pidmToContactIdMap.put(thisContact.PIDM__c, thisContact.Id);
        }
        
        //loop through map and upsert source records
        for (StudentAcademicCourseFromBanner__c thisSACFB : sacfbList)
        {
            if (pidmToContactIdMap.get(thisSACFB.studentPIDMIN__c) != null)
            {
                studentContact = pidmToContactIdMap.get(thisSACFB.studentPIDMIN__c);
            }
            else
            {
                studentContact = null;
            }
        
            if (thisSACFB.StatusIN__c == 'NP')
            {
                courseStatus = 'Not Passed';
            }
            else if (thisSACFB.StatusIN__c == 'WD')
            {
                courseStatus = 'Not Passed';
            }             
            else if (thisSACFB.StatusIN__c == 'P')
            {
                courseStatus = 'Passed';
            }
            else if (thisSACFB.StatusIN__c == 'PA')
            {
                courseStatus = 'Passed';
            }            
            else if (thisSACFB.StatusIN__c == 'WV')
            {
                courseStatus = 'Waived';
            }            
            else if (thisSACFB.StatusIN__c == 'TR')
            {
                courseStatus = 'Transferred';
            }            
            else if (thisSACFB.StatusIN__c == 'RM')
            {
                courseStatus = 'Requirements Met';
            } 
            else if (thisSACFB.StatusIN__c == 'RE')
            {
                courseStatus = 'Registered';
            }     
            else if (thisSACFB.StatusIN__c == 'DD')
            {
                courseStatus = 'Unenrolled';
            }                              
            else
            {
                courseStatus = 'Planned';
            }            
            
            if ((thisSACFB.ActionNeeded__c == 'Insert' || thisSACFB.ActionNeeded__c == 'Update' || thisSACFB.ActionNeeded__c == 'Upsert')
                && thisSACFB.SynchronizationError__c == null && studentContact != null)
            {
                if (thisSACFB.StudentAcademicCourse__c == null)
                {                                    
                    sacInsertList.add(new StudentAcademicCourse__c(CompositeKey__c = thisSACFB.CompositeKeyIn__c,
                                                                   Name = thisSACFB.CourseTitleIN__c.length()>80 ? thisSACFB.CourseTitleIN__c.substring(0,80) : thisSACFB.CourseTitleIN__c,
                                                                   FullCourseTitle__c = thisSACFB.CourseTitleIN__c,
                                                                   CompetencyUnits__c = thisSACFB.CompetencyUnitsIN__c,
                                                                   CourseCode__c = thisSACFB.CourseCodeIN__c,
                                                                   StartDate__c = thisSACFB.StartDateIN__c,
                                                                   EndDate__c = thisSACFB.EndDateIN__c,
                                                                   Status__c = courseStatus,
                                                                   StudentContact__c = studentContact,
                                                                   Term__c = thisSACFB.TermIN__c,
                                                                   Type__c = thisSACFB.TypeIN__c,
                                                                   Version__c = thisSACFB.Version__c));
                }
                if (thisSACFB.StudentAcademicCourse__c != null)
                {                                    
                    sacUpdateList.add(new StudentAcademicCourse__c(Id = thisSACFB.StudentAcademicCourse__c,
                                                                   Name = thisSACFB.CourseTitleIN__c.length()>80 ? thisSACFB.CourseTitleIN__c.substring(0,80) : thisSACFB.CourseTitleIN__c,
                                                                   FullCourseTitle__c = thisSACFB.CourseTitleIN__c,
                                                                   CompositeKey__c = thisSACFB.CompositeKeyIn__c,
                                                                   CompetencyUnits__c = thisSACFB.CompetencyUnitsIN__c,
                                                                   CourseCode__c = thisSACFB.CourseCodeIN__c,
                                                                   StartDate__c = thisSACFB.StartDateIN__c,
                                                                   EndDate__c = thisSACFB.EndDateIN__c,
                                                                   Status__c = courseStatus,
                                                                   StudentContact__c = studentContact,
                                                                   Term__c = thisSACFB.TermIN__c,
                                                                   Type__c = thisSACFB.TypeIN__c,
                                                                   Version__c = thisSACFB.Version__c));
                }                
            }
            else if (thisSACFB.ActionNeeded__c == 'Delete' && thisSACFB.StudentAcademicCourse__c != null)
            {
                sacDeleteList.add(new StudentAcademicCourse__c(Id = thisSACFB.StudentAcademicCourse__c));
            }                     
            //some key value is missing
            else
            {
                //do not add the record to any update or insert lists as it has an error
            }
        }
        
        update sacUpdateList;
        insert sacInsertList;
        delete sacDeleteList;
    }
    
   public static void insertSFAWcrseReq(String sacJson){
        if (Limits.getFutureCalls() > 3 || System.isFuture()){
            processInsertSFAWcrseReq(sacJson);
        }else{
            asyncInsertSFAWcrseReq(sacJson);
        }
    }
    
    @future
    public static void asyncInsertSFAWcrseReq(String sacJson){
        processInsertSFAWcrseReq(sacJson);
    }

    public static void processInsertSFAWcrseReq(String sacJson){
        List<StudentAcademicCourse__c> sacList = (List<StudentAcademicCourse__c>)JSON.deserialize(sacJson, List<StudentAcademicCourse__c>.class);
        List<StudentAcademicCourseRequirement__c> sacrList = new List<StudentAcademicCourseRequirement__c>();
        for(StudentAcademicCourse__c sac : sacList){
            if('SFAW'.equals(sac.CourseCode__c) && 'Passed'.equals(sac.Status__c)){
                StudentAcademicCourseRequirement__c sacr = new StudentAcademicCourseRequirement__c(Name = sac.Name,
                                                                    UniqueKey__c = sac.CompositeKey__c,
                                                                    RequirementCode__c = sac.CourseCode__c,
                                                                    Status__c = sac.Status__c,
                                                                    Completed__c = TRUE,
                                                                    StudentAcademicCourse__c = sac.Id);
                sacrList.add(sacr);
            }
        }
        insert sacrList;
    }
}