src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/StudentProcess__c.object
<CustomObject>
    <description>Custom object to manage student processes by record type.</description>
    <fields>
        <fullName>ApplicationReceived__c</fullName>
        <description>A date field representing the date the student submitted the student process application.</description>
        <label>Application Received</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>A picklist field indicating the reason for the student process.</description>
        <label>Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Assessment Delivery staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business/financial aid staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competency-based model doesn&apos;t fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Death in the Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Degree Interests Changed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demonstration Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demonstration Teaching (DT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distance learning model doesn&apos;t fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t have the time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial aid or financial problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Following a Term Break</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduation / Program Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical / Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentoring Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Military Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Disaster / Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Never Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursing Clinical Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other student services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pers Circ - Bereavement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pers Circ - Care Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pers Circ - Disaster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pers Circ - Economy</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>The stage of the student process.</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assign Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Student Reply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student spoke with Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student spoke with other personnel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student was submitted too early</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correction Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counsel Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Degree Plan Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diploma and Transcripts Mailed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diploma and Transcripts Mailed - Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midterm Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOU Accepted by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOU Needed - Custom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup field to the contact of the student process object.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>StudentProcesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Process</label>
    <nameField>
        <label>Student Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Processes</pluralLabel>
    <recordTypes>
        <fullName>Withdrawal</fullName>
        <active>true</active>
        <description>The record type used to manage the withdrawal process for student records.</description>
        <label>Withdrawal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TestWithdrawalController.cls
/*
Test class  for Withdrawal Controller
Author- Bhavadeep Raavi
*/


@isTest
private with sharing class TestWithdrawalController{
    
    private static testmethod void TestMethodWithdrawalController(){
        User testUser = [SELECT Id,pidm__c from User WHERE Profile.Name = 'Records User' AND isActive = true LIMIT 1];
        System.runAs(testUser){
        Test.startTest();
        WithdrawalController wc1= new WithdrawalController();    
        
        Contact contact= new Contact();
        contact.LastName=UserInfo.getLastName();
        contact.FirstName=UserInfo.getFirstName();
        contact.pidm__c=testUser.pidm__c;
        insert contact;
        System.assertEquals(contact.LastName,UserInfo.getLastName());
        StudentProcess__c sp=new StudentProcess__c();
        sp.name='Test sp';
        sp.student__c=contact.id;
        sp.Stage__c='MOU Accepted by Student';
        sp.ApplicationReceived__c=System.now();
        sp.reason__c='Customer Service;Death in the Family;Demonstration Teaching (DT);Military;Nursing Clinical Alignment;Pers Circ - Bereavement;Technical Issues;Posting Delay;Term Break';
        insert sp;
        System.assertEquals(sp.name,'Test sp');
        System.assertEquals(sp.Stage__c,'MOU Accepted by Student');
        WithdrawalController wc2= new WithdrawalController();  
        wc2.sp=sp;
        wc2.submit(); 
        wc2.sp=null;
        wc2.submit();    
        Test.stopTest();
        }
     }
    
    private static testmethod void TestMethodWithdrawalController2(){
        User testUser = [SELECT Id,pidm__c from User WHERE Profile.Name = 'Records User' AND isActive = true LIMIT 1];
        System.runAs(testUser){
        Test.startTest();
        Contact contact= new Contact();
        contact.LastName=UserInfo.getLastName();
        contact.FirstName=UserInfo.getFirstName();
        contact.pidm__c=testUser.pidm__c;
        insert contact;
        StudentProcess__c sp1=new StudentProcess__c();
        sp1.name='Test sp';
        sp1.student__c=contact.id;
        sp1.Stage__c='MOU Accepted by Student';
        sp1.ApplicationReceived__c=System.now();
        sp1.reason__c='Demonstration Teaching (DT);Military;Nursing Clinical Alignment;Pers Circ - Bereavement';    
        WithdrawalController wc= new WithdrawalController();    
        wc.sp=sp1;
        wc.submit();
        wc.cancel();      
        Test.stopTest();
        }
     }
}