src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for wguProgram</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/StudentCompletionCourse__c.object
<CustomObject>
    <description>This stores the information for the results of the courses.</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The student whom this completion task belongs to.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Completion Courses</relationshipLabel>
        <relationshipName>StudentCompletionCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The WGUCourse Version for this completed course</description>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Student Completion Courses</relationshipLabel>
        <relationshipName>StudentCompletionCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>link to wgucourse</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>Student Completion Courses</relationshipLabel>
        <relationshipName>Student_Completion_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>Status of the course</description>
        <label>status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Student Completion Course</label>
    <nameField>
        <label>PAMS Course ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Completion Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentCourse__c.object
<CustomObject>
    <description>Represents a course that a student may take at WGU. Multiple Assessments or Tasks may be required to complete the course.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the course (Completed,Enrolled,Planned).</description>
        <inlineHelpText>The status of the course (Completed,Enrolled,Planned).</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InProgress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentCourseVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The student course version associated with this student course.</description>
        <label>Student Course Version</label>
        <referenceTo>StudentCourseVersion__c</referenceTo>
        <relationshipLabel>Student Courses</relationshipLabel>
        <relationshipName>StudentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentTerm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term this course instance is scheduled</description>
        <label>Student Term</label>
        <referenceTo>StudentTerm__c</referenceTo>
        <relationshipLabel>Student Course</relationshipLabel>
        <relationshipName>StudentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Course</relationshipLabel>
        <relationshipName>StudentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Course</label>
    <nameField>
        <label>Student Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentCourseVersion__c.object
<CustomObject>
    <description>The version of a course that the student is set to take (or has taken).</description>
    <fields>
        <fullName>StudentCompletionCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The student completion course that has this courses completion info.</description>
        <label>Student Completion Course</label>
        <referenceTo>StudentCompletionCourse__c</referenceTo>
        <relationshipLabel>Student Course Versions</relationshipLabel>
        <relationshipName>StudentCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Course Version</relationshipLabel>
        <relationshipName>StudentCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The version of the Course that this student is taking.</description>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Student Course Versions</relationshipLabel>
        <relationshipName>StudentCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Course Version</label>
    <nameField>
        <label>Studentid+&apos;-&apos;+Wgucourseid</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentDegreePlans__c.object
<CustomObject>
    <description>Student instance of a WGU degree plan, provisioned from the WGUDegreeProgram__c object.</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Degree Plans</relationshipLabel>
        <relationshipName>StudentDegreePlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Degree Plan</label>
    <nameField>
        <label>Student Degree Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Degree Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentTerm__c.object
<CustomObject>
    <description>Instance of a student period of time, using recordtype to designate between academic terms, term breaks, withdraw/drops, etc.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The date that the term ends.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The starting date of the term. WGU Terms are normally 6 months but it is possible that one may be smaller because it is a term break.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StudentDegreePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Student&apos;s Degree Plan instance this term is schedule within.</description>
        <label>Student Degree Plan</label>
        <referenceTo>StudentDegreePlans__c</referenceTo>
        <relationshipLabel>Student Terms</relationshipLabel>
        <relationshipName>StudentTerms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Terms</relationshipLabel>
        <relationshipName>myTerms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Term</label>
    <nameField>
        <label>Student Term Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>LatestVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The latest version of this particular WGU Course.</description>
        <label>Latest Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>LatestVersionRelation</relationshipLabel>
        <relationshipName>LatestVersionRelation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseInProgram__c.object
<CustomObject>
    <description>A many to many mapping that assigns which course are required to accomplish any degree program.</description>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipName>PAMS_Course_In_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>WGU Course In Programs</relationshipLabel>
        <relationshipName>WGUCourseInPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course In Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WGU Course In Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The course that this course version belongs to</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>WGU Course Versions</relationshipLabel>
        <relationshipName>WGUCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchFixForHistory.cls
global class BatchFixForHistory implements Database.Batchable<sObject> {
   global final String query;

   global BatchFixForHistory (String q) {
     query = q;
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

   global void execute(Database.BatchableContext BC, List<sObject> scope){
      List<Studentcompletioncourse__C>stccs=scope;
  List<studentcourseversion__C> stvs=[select id ,student__C from studentcourseversion__C where studentcompletioncourse__C in :stccs];
  List<studentcourse__C>oldcourses=[select id from studentcourse__C where studentcourseversion__C in :stvs];
  Set<String> ss=new Set<String>();
  for(studentcourseversion__C sc: stvs){
  ss.add(sc.student__C);
  }
  List<Contact> students=[select id,wgudegreeprogram__C from contact where id in :ss];
  delete stvs;
  delete oldcourses;
  
  List<studentcourseversion__C> cvs=new  List<studentcourseversion__C>();
  List<studentcourse__C> cs=new  List<studentcourse__C>();
  for(Contact student:students){
  List<studentcourseversion__C> rr=    [select wgucourseversion__r.wgucourse__C from studentcourseversion__C where student__C=:student.id ];
  set<String> cours=new set<String>();
      for (studentcourseversion__C c:rr){
      cours.add(c.wgucourseversion__r.wgucourse__C);
      }
      List<wguCourseinProgram__C> missings= [select id,course__r.latestversion__C,course__r.name from wgucourseinprogram__C where  program__C = :student.WGUDegreeProgram__C and course__C not in :cours];
   List<studentdegreeplans__C> dps= [select id,student__c, (select id,name,student__c from studentterms__r where startdate__C> TODAY  or (startdate__C<TODAY and enddate__C > TODAY)  order by startdate__C asc limit 2) from studentdegreeplans__C  where student__C =:student.id]; 
      
         for (studentdegreeplans__C plan:dps){
           if (plan.studentterms__r.size()>0){
            studentterm__C term=plan.studentterms__r[0];
            if (plan.studentterms__r.size()>1)
              term=plan.studentterms__r[1];
            
             for (wguCourseinProgram__C c:missings){
                StudentCourseversion__C cv=new StudentCourseversion__C();
                cv.status__C='Planned';
                cv.name=c.course__r.name;
                cv.student__C=plan.student__C;
                cv.wgucourseversion__C=c.course__r.latestversion__C;
                cvs.add(cv);
                StudentCourse__c sc=new Studentcourse__c();
                sc.name=c.course__r.name;
                sc.student__C=plan.student__C;
                sc.studentterm__c=term.id;
                sc.studentcourseversion__r=cv;
                sc.status__c='Planned';
                cs.add(sc);
             }
           }
         }
         }
        
          if (cvs.size()>0)
         insert cvs;
         if (cs.size()>0){
        for(Studentcourse__C c:cs){
          c.studentcourseversion__c=c.studentcourseversion__r.id;
        }
        insert cs;
      
        }
  
   }

   global void finish(Database.BatchableContext BC){}
}