src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/EmailAddress__c.object
<CustomObject>
    <description>All Email addresses related to a contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Addresses</relationshipLabel>
        <relationshipName>EmailAddresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EmailCode__c</fullName>
        <label>Email Code</label>
        <picklist>
            <picklistValues>
                <fullName>CPMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WORK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <label>PIDM</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StatusIndicator__c</fullName>
        <label>Status Indicator</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Email Address</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EmailAddressToBanner__c.object
<CustomObject>
    <description>A control object for the synchronization between Banner table general.goremal and Salesforce object Email Address</description>
    <fields>
        <fullName>ContactIdIN__c</fullName>
        <label>Contact Id (IN)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailAddressIN__c</fullName>
        <externalId>true</externalId>
        <label>Email Address (IN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailAddress__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Email Address object that this sync records connects to in Salesforce.</description>
        <label>Email Address</label>
        <referenceTo>EmailAddress__c</referenceTo>
        <relationshipLabel>Email Addresses To Banner</relationshipLabel>
        <relationshipName>EmailAddressesToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EmailCodeIN__c</fullName>
        <label>Email Code (IN)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDMIN__c</fullName>
        <label>PIDM (IN)</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryEmailIN__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Email (IN)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StatusIndicatorIN__c</fullName>
        <label>Status Indicator (IN)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SynchronizationError__c</fullName>
        <label>Synchronization Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Email Address To Banner</label>
    <nameField>
        <displayFormat>emailsync-{0}</displayFormat>
        <label>Email Address To Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Addresses To Banner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestEmailAddressToBannerUtilities.cls
@IsTest
public class TestEmailAddressToBannerUtilities{
    @IsTest
    public static void testLinkingErrors() {   
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        
        Contact baggins = [SELECT Id, PIDM__C FROM Contact WHERE LastName = 'Baggins'];    
        EmailAddress__c email = new EmailAddress__c(Contact__c = baggins.Id, Email__c = 'iexist@unit.test', 
                                                    EmailCode__c = 'CPMA', PIDM__c = baggins.PIDM__c,
                                                    PrimaryEmail__c = false, StatusIndicator__c = 'Inactive');

        insert email;
        
        Test.startTest();

        List<EmailAddressToBanner__c> testRecords = new List<EmailAddressToBanner__c>();
        
        // New Email.
        EmailAddressToBanner__c e2b1 = new EmailAddressToBanner__c(ContactIdIN__c = 'fhjkhfjkdlhfjkh', PIDMIN__c = baggins.PIDM__c, EmailCodeIN__c = 'EM', 
                                                                   PrimaryEmailIN__c = true, StatusIndicatorIN__c = 'A', EmailAddressIN__c = 'testme@unit.test');
        
        testRecords.add(e2b1);
        
        // New Bad Email.
        EmailAddressToBanner__c e2b3 = new EmailAddressToBanner__c(ContactIdIN__c = 'fhjkhfjkdlhfjkh', PIDMIN__c = baggins.PIDM__c, EmailCodeIN__c = 'EM', 
                                                                   PrimaryEmailIN__c = true, StatusIndicatorIN__c = 'A', EmailAddressIN__c = 'testme@unit.test.');
        testRecords.add(e2b3);   
        
        // Existing Email.
        EmailAddressToBanner__c e2b2 = new EmailAddressToBanner__c(ContactIdIN__c = baggins.Id, PIDMIN__c = baggins.PIDM__c, EmailCodeIN__c = 'EM', 
                                                                   PrimaryEmailIN__c = true, StatusIndicatorIN__c = 'I', EmailAddressIN__c = 'iexist@unit.test');
        
        testRecords.add(e2b2);        
        insert testRecords; 
        
        testRecords = [SELECT Id, EmailAddress__c, EmailAddressIN__c, SynchronizationError__c FROM EmailAddressToBanner__c];
        
        Boolean record1Mapped = false;
        Boolean record2Mapped = false;
        
        for (EmailAddressToBanner__c record : testRecords) {
            if (record.EmailAddressIN__c == 'testme@unit.test') {
                record1Mapped = record.SynchronizationError__c != null;
            }
            
            if (record.EmailAddressIN__c == 'iexist@unit.test') {
                record2Mapped = record.SynchronizationError__c != null;
            }            
        }
        
        System.assert(record1Mapped && record2Mapped);        
    }
    
    @IsTest
    public static void testLinkingAndUpdate() {
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        
        Contact baggins = [SELECT Id, PIDM__C FROM Contact WHERE LastName = 'Baggins'];
        
        EmailAddress__c email = new EmailAddress__c(Contact__c = baggins.Id, Email__c = 'iexist@unit.test', 
                                                    EmailCode__c = 'CPMA', PIDM__c = baggins.PIDM__c,
                                                    PrimaryEmail__c = false, StatusIndicator__c = 'Inactive');
        
        insert email;
        
        Test.startTest();

        List<EmailAddressToBanner__c> testRecords = new List<EmailAddressToBanner__c>();
        
        // New Email.
        EmailAddressToBanner__c e2b1 = new EmailAddressToBanner__c(ContactIdIN__c = baggins.Id, PIDMIN__c = baggins.PIDM__c, EmailCodeIN__c = 'EM', 
                                                                   PrimaryEmailIN__c = true, StatusIndicatorIN__c = 'A', EmailAddressIN__c = 'testme@unit.test');
        
        testRecords.add(e2b1);
        
        // Existing Email.
        EmailAddressToBanner__c e2b2 = new EmailAddressToBanner__c(ContactIdIN__c = baggins.Id, PIDMIN__c = baggins.PIDM__c, EmailCodeIN__c = 'OT', 
                                                                   PrimaryEmailIN__c = false, StatusIndicatorIN__c = 'I', EmailAddressIN__c = 'iexist@unit.test');
        
        testRecords.add(e2b2);        
        
        
        insert testRecords;
        
        Test.stopTest();
        
        testRecords = [SELECT Id, EmailAddress__c, EmailAddressIN__c, SynchronizationError__c, EmailCodeIN__c FROM EmailAddressToBanner__c];
        
        Boolean record1Mapped = false;
        Boolean record2Mapped = false;
        
        for (EmailAddressToBanner__c record : testRecords) {
            if (record.EmailAddressIN__c == 'testme@unit.test') {
                record1Mapped = record.EmailAddress__c != null && record.SynchronizationError__c == null;
            }
            
            if (record.EmailAddressIN__c == 'iexist@unit.test') {
                record2Mapped = record.EmailAddress__c  == email.Id && record.SynchronizationError__c == null && record.EmailCodeIN__c == 'OT';
                
            }            
        }
        
        System.assert(record1Mapped && record2Mapped);
    }
}