src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OtherEmail__c</fullName>
        <description>Alternate email address for contact</description>
        <label>Other Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WGUEmail__c</fullName>
        <description>The student&apos;s @wgu.edu email address.</description>
        <label>WGU Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TestBogifyEmailBatchUtility.cls
/*
 * Author Paul Coleman
 * Western Governors University
 *
 * Date January 22, 2013 @ 1044 hrs
 * 
 * Test class for BogifyEmailBatchUtility class 
 *
 *
 */

@isTest
private class TestBogifyEmailBatchUtility {

    static testMethod void testBogifyEmail() {
        
      String environment = TestStudentUser.getEnvironment();
        ID studentRecordTypeId = [Select Id from RecordType where DeveloperName = 'StudentRecord' and SObjectType = 'Contact'].id;
        Contact studentContact = new Contact( Status__c='AS', pidm__c='p002233', firstName='Dudley', Email='dasterdlytesterson@bogify.edu', WGUEmail__c='dasterdlytesterson@bogify.edu', OtherEmail__c='dasterdlytesterson@bogify.edu', MailingState='UT', LastName='DasterdlyTesterson', RecordTypeId=studentRecordTypeId );
        insert studentContact;
        
        User testUser = TestStudentUser.getSAdminUser();
        System.RunAs( testUser ) {   

   
       Test.StartTest();
          
          BogifyEmailBatchUtility bogify = new BogifyEmailBatchUtility('select Id, Email, WGUEmail__c, OtherEmail__c from Contact WHERE id = \'' + studentContact.Id +'\'');
          ID batchprocessid = Database.executeBatch(bogify);
          
       Test.StopTest();

      String newEmail = [select Email from Contact where Id = :studentContact.Id].Email;
      System.Assert( ( environment=='prod'? newEmail==studentContact.Email: true ), 'Email has not been processed correctly by BogifyEmailBatchUtility in org (' + environment + ')');     
   }
        
    }
}