src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>InitialFEEmailSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if Field Experience email has been sent</description>
        <label>Initial FE Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SFAWEmailSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Triggered field when the student passes SFAW that shows the corresponding email was sent to them.</description>
        <label>SFAW Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/StudentAcademicCourse__c.object
<CustomObject>
    <description>A representation of a course being taken at WGU wither in the past, current enrollment, or tentatively planned in the future. Includes credited courses such as transferred competency units or requirements met while working on  another degree.</description>
    <fields>
        <fullName>CompetencyUnits__c</fullName>
        <description>The number of Competency Units this course is will put towards the student&apos;s degree program.</description>
        <label>Competency Units</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompositeKey__c</fullName>
        <externalId>true</externalId>
        <label>Composite Key</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CourseCode__c</fullName>
        <description>The code the course is registered within Banner and PAMS.</description>
        <label>Course Code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the course in relation to the student&apos;s progress in it or credit to it.</description>
        <inlineHelpText>The status of the course in relation to the student&apos;s progress in it or credit to it.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements Met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <description>The student for which this course is entered.</description>
        <inlineHelpText>The student for which this course is entered.</inlineHelpText>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Academic Courses</relationshipLabel>
        <relationshipName>StudentAcademicCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>If course to enroll in the future then no term code may be specified but might be if Flexible Degree Plan was completed.</description>
        <inlineHelpText>If course to enroll in the future then no term code may be specified but might be if Flexible Degree Plan was completed.</inlineHelpText>
        <label>Term</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Objective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student Academic Course</label>
    <nameField>
        <label>Course Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Academic Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentAcademicCourseReqFromBanner__c.object
<CustomObject>
    <description>Control Object for Student Academic Course</description>
    <fields>
        <fullName>ActionNeeded__c</fullName>
        <label>Action Needed</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EngagedPreassessment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Engaged Preassessment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RequirementCode__c</fullName>
        <label>Requirement Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAcademicCourseRequirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Academic Course Requirement</label>
        <referenceTo>StudentAcademicCourseRequirement__c</referenceTo>
        <relationshipLabel>Student Academic Course Reqs From Banner</relationshipLabel>
        <relationshipName>StudentAcademicCourseReqsFromBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Objective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueParentKey__c</fullName>
        <label>Unique Parent Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Student Academic Course Req From Banner</label>
    <nameField>
        <label>Student Academic Course Req From Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Academic Course Reqs From Banner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentAcademicCourseRequirement__c.object
<CustomObject>
    <description>Stores the requirements to complete a version of a course. For many records early on, this will only be one assessment to a course. Nursing will be the first group to apply multiple assessments to course. Several roll up summaries will be placed on the parent object to summarize status and engagement.</description>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EngagedPreassessment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Engaged Preassessment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RequirementCode__c</fullName>
        <label>Requirement Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The text status from Course of Study.</description>
        <label>Status</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAcademicCourse__c</fullName>
        <label>Student Academic Course</label>
        <referenceTo>StudentAcademicCourse__c</referenceTo>
        <relationshipLabel>Student Academic Course Requirements</relationshipLabel>
        <relationshipName>StudentAcademicCourseRequirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Objective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Student Academic Course Requirement</label>
    <nameField>
        <label>Assessment / Task Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Academic Course Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Term__c.object
<CustomObject>
    <description>Term</description>
    <label>Term</label>
    <nameField>
        <label>Term</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Term</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestStudentAcademicCourseReqUtility.cls
/*****************************************************************************************
* Name: TestStudentAcademicCourseReqUtility
* Author: Will Slade
* Purpose: Test StudentAcademicCourseReqUtility class and trigger
* Revisions: 
*    - 1/13/2014 Created Class
*
******************************************************************************************/
@isTest
public class TestStudentAcademicCourseReqUtility{
    private static testmethod void testUpsertSourceObject()
    {
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        Contact baggins = [SELECT Id, PIDM__c, FirstName, LastName FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        StudentAcademicCourse__c sac = new StudentAcademicCourse__c(
                                                         CompetencyUnits__c=2,
                                                         CompositeKey__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         CourseCode__c='CRSE',name='test class course',
                                                         Status__c='Passed',StudentContact__c=baggins.Id,
                                                         Term__c='201310', Type__c='Task');
        StudentAcademicCourseReqFromBanner__c sacrfb = new StudentAcademicCourseReqFromBanner__c(
                                                         ActionNeeded__c='Upsert',
                                                         UniqueKey__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         UniqueParentKey__c = baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         //EngagedPreassessment__c = date.valueOf('2013-10-01'),
                                                         RequirementCode__c='CRSE', Status__c = 'PA',
                                                         Type__c='Task');
        insert sac;
        Test.startTest();
         insert sacrfb;
        Test.stopTest();
       
        List<StudentAcademicCourseRequirement__c> sacList = [SELECT Id, UniqueKey__c, RequirementCode__c, EngagedPreassessment__c, Status__c, Type__c
                                                             FROM StudentAcademicCourseRequirement__c
                                                             WHERE UniqueKey__c = :sacrfb.UniqueKey__c ];        
        System.assertEquals(1, sacList.size(), 'Excess control records created - expected 1, found ' + sacList.size() ); 
        System.assertEquals(sacrfb.RequirementCode__c, sacList[0].RequirementCode__c, 'Incorrect asmt-task-code');
        System.assertEquals(sacrfb.UniqueKey__c, sacList[0].UniqueKey__c, 'Incorrect comp-key');
        System.assertEquals(sacrfb.Type__c, sacList[0].Type__c, 'Incorrect Type');
    }
    
    private static testmethod void testUpsertSourceObject2(){
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        Contact baggins = [SELECT Id, PIDM__c, FirstName, LastName FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        StudentAcademicCourseReqFromBanner__c sacrfb = new StudentAcademicCourseReqFromBanner__c(
                                                         ActionNeeded__c='Insert',
                                                         UniqueKey__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         RequirementCode__c='CRSE', Status__c='PA',
                                                         Type__c='Task');
         StudentAcademicCourse__c sac = new StudentAcademicCourse__c(
                                                         competencyUnits__c=2,
                                                         compositeKey__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         coursecode__c='CRSE',name='test class course',
                                                         status__c='Passed',StudentContact__c=baggins.Id,
                                                         term__c='201310',Type__c='Task');
        StudentAcademicCourseReqFromBanner__c sacrfb2 = new StudentAcademicCourseReqFromBanner__c(
                                                         ActionNeeded__c='Upsert',
                                                         UniqueKey__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         UniqueParentKey__c = baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         RequirementCode__c='CRSE' );
        Test.startTest();
         insert sacrfb;
         insert sacrfb2;
        Test.stopTest();
        List<StudentAcademicCourseRequirement__c> sacList = [ select Id,UniqueKey__c,RequirementCode__c,
                                                  Status__c, Type__c
                                                 from StudentAcademicCourseRequirement__c
                                                 where UniqueKey__c = :sacrfb.UniqueKey__c ];        
        System.assertEquals(sacList.size(), 0, 'Incorrect record size when wrong insertion.');
    }
    
    private static testmethod void testUpsertSourceObject3(){
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        Contact baggins = [SELECT Id, PIDM__c, FirstName, LastName FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        StudentAcademicCourse__c sac = new StudentAcademicCourse__c(
                                                         competencyUnits__c=2,
                                                         compositeKey__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         coursecode__c='CRSE',name='test class course',
                                                         status__c='Passed',StudentContact__c=baggins.Id,
                                                         term__c='201310',Type__c='Task');
        StudentAcademicCourseReqFromBanner__c sacrfb = new StudentAcademicCourseReqFromBanner__c(
                                                         ActionNeeded__c='Delete',
                                                         UniqueKey__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         UniqueParentKey__c = baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         RequirementCode__c='CRSE', Status__c='PA',
                                                         Type__c='Task',StudentAcademicCourseRequirement__c =sac.id);
        insert sac;
        Test.startTest();
           insert sacrfb;
        Test.stopTest();
        List<StudentAcademicCourseRequirement__c> sacList = [SELECT Id, UniqueKey__c, RequirementCode__c,
                                                             Status__c, Type__c
                                                             FROM StudentAcademicCourseRequirement__c
                                                             WHERE UniqueKey__c = :sacrfb.UniqueKey__c ];        
        System.assertEquals(sacList.size(), 0, 'Incorrect record size when wrong insertion.');
    }
    
    private static testmethod void testUpsertSourceObject4()
    {
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        Contact baggins = [SELECT Id, PIDM__c, FirstName, LastName FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        StudentAcademicCourse__c sac = new StudentAcademicCourse__c( competencyUnits__c=2,
                                                         compositeKey__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         coursecode__c='CRSE',name='test class course',
                                                         status__c='Passed',StudentContact__c=baggins.Id,
                                                         term__c='201310',Type__c='Task');
        StudentAcademicCourseReqFromBanner__c sacrfb = new StudentAcademicCourseReqFromBanner__c(
                                                         ActionNeeded__c='Upsert',
                                                         UniqueKey__c=baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         UniqueParentKey__c = baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                         RequirementCode__c='CRSE', Status__c = 'PA',
                                                         Type__c='Task');
        insert sac;
        insert sacrfb;
        Test.startTest();
         List<StudentAcademicCourseRequirement__c> sacrList = [SELECT Id, UniqueKey__c, RequirementCode__c,
                                                               Status__c, Type__c
                                                               FROM StudentAcademicCourseRequirement__c
                                                               WHERE UniqueKey__c = :sac.CompositeKey__c ];
         StudentAcademicCourseReqFromBanner__c sacrfb2 = new StudentAcademicCourseReqFromBanner__c(
                                                          StudentAcademicCourseRequirement__c=sacrList[0].Id,
                                                          ActionNeeded__c = 'Update',
                                                          UniqueKey__c = sacrList[0].UniqueKey__c,
                                                          UniqueParentKey__c = baggins.PIDM__c+'-'+'CRSE'+'-'+'201310',
                                                          RequirementCode__c='CRSE', Status__c = 'PA',
                                                          Type__c='Task');
         insert sacrfb2;
        Test.stopTest();
       
        List<StudentAcademicCourseRequirement__c> sacList = [SELECT Id, UniqueKey__c, RequirementCode__c,
                                                             Status__c, Type__c
                                                             FROM StudentAcademicCourseRequirement__c
                                                             WHERE UniqueKey__c = :sacrfb.UniqueKey__c];        
        System.assertEquals(1, sacList.size(), 'Excess control records created - expected 1, found ' + sacList.size() ); 
        System.assertEquals(sacrfb.RequirementCode__c, sacList[0].RequirementCode__c, 'Incorrect asmt-task-code');
        System.assertEquals(sacrfb.UniqueKey__c, sacList[0].UniqueKey__c, 'Incorrect comp-key');
        System.assertEquals(sacrfb.Status__c, sacList[0].Status__c, 'Incorrect passed-status');
        System.assertEquals(sacrfb.Type__c, sacList[0].Type__c, 'Incorrect Type');
    }
    
    private static testmethod void testUpdateContactEmailSent(){
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        Contact baggins = [SELECT Id, PIDM__c FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        StudentAcademicCourse__c sac = new StudentAcademicCourse__c(
                                           StudentContact__c = baggins.Id,
                                           CompositeKey__c = baggins.PIDM__c+'-'+'ABP1'+'-'+'201403',
                                           CourseCode__c='ABP1', Status__c='Passed',
                                           term__c='201403',Type__c='Performance');
        insert sac;
        StudentAcademicCourse__c sacNew = [Select Id,CompositeKey__c FROM StudentAcademicCourse__c
                                           where CompositeKey__c =: sac.CompositeKey__c];
        StudentAcademicCourseRequirement__c cr = new StudentAcademicCourseRequirement__c(
                                                     StudentAcademicCourse__c = sacNew.Id,
                                                     UniqueKey__c = sacNew.CompositeKey__c,
                                                     Completed__c = True);
        Test.startTest();
          insert cr;
          cr.UniqueKey__c = baggins.PIDM__c+'-'+'SFAW'+'-'+'201403';
          update cr;
        Test.stopTest();
        Contact bagginsNew = [SELECT Id,InitialFEEmailSent__c,SFAWEmailSent__c  FROM Contact WHERE Id =: baggins.Id];
        System.assertEquals(True, bagginsNew.InitialFEEmailSent__c, 'PCE email error');
        System.assertEquals(True, bagginsNew.SFAWEmailSent__c, 'SFAW email error');
    }
 
}