src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for wguProgram</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/StudentCourseVersion__c.object
<CustomObject>
    <description>The version of a course that the student is set to take (or has taken).</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Course Version</relationshipLabel>
        <relationshipName>StudentCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The version of the Course that this student is taking.</description>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Student Course Versions</relationshipLabel>
        <relationshipName>StudentCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Course Version</label>
    <nameField>
        <label>Studentid+&apos;-&apos;+Wgucourseid</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseInProgram__c.object
<CustomObject>
    <description>A many to many mapping that assigns which course are required to accomplish any degree program.</description>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipName>PAMS_Course_In_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAMSCourseID__c</fullName>
        <description>The unique ID that represents the course in PAMS that this mapping should be linked to in SalesForce.</description>
        <label>PAMS Course ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>WGU Course In Programs</relationshipLabel>
        <relationshipName>WGUCourseInPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course In Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WGU Course In Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <fields>
        <fullName>PAMSCOURSEID__c</fullName>
        <description>related course in pams</description>
        <label>PAMSCOURSEID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <description>The overall version of the Course</description>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The course that this course version belongs to</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>WGU Course Versions</relationshipLabel>
        <relationshipName>WGUCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <description>The ID that represents the program in PAMS.</description>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestStudentCourseVersionUtility.cls
/*****************************************************************************************
* Name: TestStudentCourseVersionUtility
* Author: Will Slade
* Purpose: Test StudentCourseVersionUtility class
* Revisions: 
*    -  2/26/2014 Created Class
*
******************************************************************************************/
@isTest
public class TestStudentCourseVersionUtility
{
    private static testmethod void testDeleteNonProgramCourses()
    {
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();
        Contact baggins = [SELECT Id, PIDM__c, FirstName, LastName, WGUDegreeProgram__c FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        
        WGUCourse__c testWGUCourse1 = new WGUCourse__c(Name = 'TWC1', PAMSId__c = 45);
        WGUCourse__c testWGUCourse2 = new WGUCourse__c(Name = 'TWC2', PAMSId__c = 46);
        insert testWGUCourse1;
        insert testWGUCourse2;         
        
        WGUCourseVersion__c testWGUCourseV1 = new WGUCourseVersion__c(Name = 'TCV1', WGUCourse__c = testWGUCourse1.Id, Version__c = 1, PamsCourseId__c = 45);
        WGUCourseVersion__c testWGUCourseV2 = new WGUCourseVersion__c(Name = 'TCV2', WGUCourse__c = testWGUCourse2.Id, Version__c = 2, PamsCourseId__c = 46);
        insert testWGUCourseV1;
        insert testWGUCourseV2;
        
        testWGUCourseV1 = [SELECT Id, Name, WGUCourse__c, Version__c FROM WGUCourseVersion__c WHERE Id = :testWGUCourseV1.Id];
        testWGUCourseV2 = [SELECT Id, Name, WGUCourse__c, Version__c FROM WGUCourseVersion__c WHERE Id = :testWGUCourseV2.Id];              
        
        WGUDegreeProgram__c testDegProg1 = new WGUDegreeProgram__c(Name = 'TESTME8', PAMSId__c = 47);
        WGUDegreeProgram__c testDegProg2 = new WGUDegreeProgram__c(Name = 'TESTME9', PAMSId__c = 48);
        insert testDegProg1;  
        insert testDegProg2;
        
        WGUCourseInProgram__c testCrsInProg1 = new WGUCourseInProgram__c(Course__c = testWGUCourse1.Id, Program__c = testDegProg1.Id);
        WGUCourseInProgram__c testCrsInProg2 = new WGUCourseInProgram__c(Course__c = testWGUCourse2.Id, Program__c = testDegProg2.Id);
        insert testCrsInProg1;
        insert testCrsInProg2;
        
        StudentCourseVersion__c testSCV1 = new StudentCourseVersion__c(Name = 'TESTSCV1', WGUCourseVersion__c = testWGUCourseV1.Id, Student__c = baggins.Id);
        StudentCourseVersion__c testSCV2 = new StudentCourseVersion__c(Name = 'TESTSCV2', WGUCourseVersion__c = testWGUCourseV2.Id, Student__c = baggins.Id);
        insert testSCV1;
        insert testSCV2;
        
        baggins.WGUDegreeProgram__c = testDegProg1.Id;
        update baggins;
        
        List<StudentCourseVersion__c> scvList = [SELECT Id FROM StudentCourseVersion__c WHERE Student__c = :baggins.Id LIMIT 20];
        System.assertEquals(scvList.size(), 2);
        
        Test.startTest();
            baggins.WGUDegreeProgram__c = testDegProg2.Id;
            update baggins;            
        Test.stopTest();
        
        scvList = [SELECT Id FROM StudentCourseVersion__c WHERE Student__c = :baggins.Id LIMIT 20];
        System.assertEquals(scvList.size(), 1);
        System.assertEquals(scvList[0].Id, testSCV2.Id);                                  
    }
}