src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>College__c</fullName>
        <label>College</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <label>Program Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StudentProcess__c.object
<CustomObject>
    <description>Custom object to manage student processes by record type.</description>
    <fields>
        <fullName>ApplicationInstitution__c</fullName>
        <description>Text area that displays the institutions the student attended after withdrawing from WGU</description>
        <label>Application Institution</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ApplicationProgramOfStudy__c</fullName>
        <description>Field to house the student&apos;s program of study from the student process application.</description>
        <label>Application Program of Study</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>College__c</fullName>
        <description>Picklist to select the new college.</description>
        <label>College</label>
        <picklist>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Professions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher Education</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FinancePaymentType__c</fullName>
        <description>A picklist field that indicates how the student pays tuition (e.g., self pay, financial aid, scholarship)</description>
        <label>Finance Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Self Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Aid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Aid / Self Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Aid / Private Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Pay / VA Benefits</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProgramName__c</fullName>
        <description>Picklist field used for students to select the program name they are interested in returning to.</description>
        <label>Program Name</label>
        <picklist>
            <controllingField>College__c</controllingField>
            <picklistValues>
                <fullName>B.S. in Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S. in Business - HR Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S. in Business - IT Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S. in Business Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S. in Marketing Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S. in Sales and Sales Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.B.A., IT Management Emphasis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.B.A.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S in Health Informatics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S. in Nursing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Nursing Curriculum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.B.A., Healthcare Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.S. in Nursing - Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.S. in Nursing - Leadership and Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S. in Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S. in IT - Network Design and Management Emphasis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S. in IT - Network Administration Emphasis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S. in IT - Security Emphasis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.S. in IT - Software Emphasis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.S in Information Security and Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.S. in IT Network Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endorsement Prep. Program in Educational Leadership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.S. in Educational Leadership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.A. in Educational Studies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B.A. in Interdisciplinary Studies (K-8)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.A. in Educational Studies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.A. in Educational Studies and Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.A. in Teaching (K-8)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-bacc Teacher Prep (K-8)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M.Ed. in Instructional Design</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ReadmissionAppeal__c</fullName>
        <description>Open text field used for readmission appeal form to allow the student to indicate the circumstances that led to their withdrawal; why they believe the WGU model is appropriate; how they have prepared for return; and why they believe they can make SAP if readmitted.</description>
        <label>Readmission Appeal</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReadmissionDesiredDate__c</fullName>
        <description>A date field indicating the term start date the student wishes to be readmitted on.</description>
        <label>Readmission Desired Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StudentProcessAutoNumber__c</fullName>
        <description>Auto number for the student process object used for student facing forms.</description>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Student Process Auto Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup field to the contact of the student process object.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>StudentProcesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WaiveFee__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating that the readmission fee should be waived.</description>
        <label>Waive Fee</label>
        <type>Checkbox</type>
    </fields>
    <label>Student Process</label>
    <nameField>
        <label>Student Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Processes</pluralLabel>
    <recordTypes>
        <fullName>Readmission</fullName>
        <active>true</active>
        <description>The record type used to manage the readmission process for student records.</description>
        <label>Readmission</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestReadmissionController.cls
/*
Test class  for Readmission Controller
Author- Bhavadeep Raavi
*/

@isTest
private with sharing class TestReadmissionController{
    
    private static testmethod void TestMethodReadmissionController(){
        
        Contact contact= new Contact();
        contact.LastName='Test Cont';
        insert contact;
        
        StudentProcess__c sp=new StudentProcess__c();
        sp.name='Test sp';
        sp.student__c=contact.id;
        sp.ReadmissionDesiredDate__c=Date.today();
        insert sp;
        
        User testUser = [SELECT Id from User WHERE Profile.Name = 'Records User' AND isActive = true LIMIT 1];
      
            System.runAs(testUser){
            Test.startTest();
            //sp=[select StudentProcessAutoNumber__c from StudentProcess__c where id=:sp.Id];
            PageReference pr = Page.Readmission;
            ///pr.getParameters().put('StudentProcessAutoNumber',sp.StudentProcessAutoNumber__c);
            Test.setCurrentPage(pr);
            ApexPages.StandardController sc = new ApexPages.StandardController(sp);
            ReadmissionController rac= new ReadmissionController(sc);
            rac.stdProcess.ApplicationProgramOfStudy__c='';
            rac.stdProcess.ReadmissionDesiredDate__c=null;
            rac.stdProcess.FinancePaymentType__c='';
            rac.stdProcess.ReadmissionAppeal__c='';
            rac.stdProcess.ApplicationInstitution__c ='test';
            rac.stdProcess.WaiveFee__c=false;
            rac.incrementRowFlg();
            rac.decrementRowFlg();
            rac.saveReadmission();
            rac.cancel();
            System.assertEquals('',rac.stdProcess.ApplicationProgramOfStudy__c);
            System.assertEquals('',rac.stdProcess.FinancePaymentType__c);
            rac.stdProcess.ReadmissionDesiredDate__c=Date.today().adddays(22);
            ReadmissionController.StdAdditionalInfo sai=new ReadmissionController.StdAdditionalInfo();
            sai.inName='Test';
            sai.doa=Date.today().adddays(-30)+'';
            rac.studentProcessList.add(sai);
            rac.saveReadmission();
            rac.cancel();
            Test.stopTest();
        }
    }
    private static testmethod void TestMethodReadmissionController2(){
        
        Contact contact= new Contact();
        contact.LastName='Test Cont';
        insert contact;
        
        StudentProcess__c sp=new StudentProcess__c();
        sp.name='Test sp';
        sp.student__c=contact.id;
        sp.ReadmissionDesiredDate__c=Date.today();
        insert sp;
        
        User testUser = [SELECT Id from User WHERE Profile.Name = 'Records User' AND isActive = true LIMIT 1];
      
            System.runAs(testUser){
            Test.startTest();
            //sp=[select StudentProcessAutoNumber__c from StudentProcess__c where id=:sp.Id];
            PageReference pr = Page.Readmission;
            //pr.getParameters().put('StudentProcessAutoNumber',sp.StudentProcessAutoNumber__c);
            Test.setCurrentPage(pr);
            ApexPages.StandardController sc = new ApexPages.StandardController(sp);
            ReadmissionController rac= new ReadmissionController(sc);
            rac.stdProcess.ReadmissionDesiredDate__c=Date.today().adddays(29);
            rac.stdProcess.WaiveFee__c=true;
            rac.stdProcess.FinancePaymentType__c='Self Pay';
            rac.stdProcess.ReadmissionAppeal__c='Test';
            rac.stdProcess.ApplicationInstitution__c ='test';
            rac.stdProcess.College__c='Business';
            rac.stdProcess.ProgramName__c='M.B.A.';
           
            rac.saveReadmission();
            rac.cancel();
            System.assertEquals('Self Pay',rac.stdProcess.FinancePaymentType__c);
            rac.stdProcess=null;
            rac.saveReadmission();
            
            Test.stopTest();
        }
    }
    
}