src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The mentor pidm so we can use external id&apos;s</description>
        <externalId>true</externalId>
        <inlineHelpText>The WGU PIDM assigned to this mentor.</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/WGUStudentNote__c.object
<CustomObject>
    <description>This object stores notes about a student&apos;s interaction with service personnel such as mentors, etc.</description>
    <fields>
        <fullName>AuthorPidm__c</fullName>
        <label>Author Pidm</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user pidm</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WGUStudentNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InteractionID__c</fullName>
        <description>This is the interacitonId in talisma that this note came from.</description>
        <externalId>true</externalId>
        <label>InteractionID</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level1Image__c</fullName>
        <formula>&apos; &apos;</formula>
        <label>Level 1 Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MentorId__c</fullName>
        <formula>Student__r.StudentMentor__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MentorId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonalizationActions__c</fullName>
        <description>These actions are for the Student Personalization project and are for mentors to communicate how they are helping a student if the Student At Risk Score is Red or Yellow</description>
        <inlineHelpText>Enter in the action for this student if they are an At Risk Student.</inlineHelpText>
        <label>Personalization Actions</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create an entire term plan with weekly progress goals that allow the student to achieve OTP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enroll the student in a cohort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>When the student fails to achieve the weekly goal, set a follow up call later in the week or the day to provide time for them to accomplish the goal that week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create a study calendar with specific times blocked out for schoolwork and ask the student to share it with his or her family/support system</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ask questions to determine if the student is struggling with the content, time management, or motivation. Then set a follow up appointment with an additional person (course mentor, student success mentor, etc.) based upon the student’s response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Share screens with the student and walk through a learning resource or task together</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Share screens and watch a welcome video together then create a plan for finishing the course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>When a goal is achieved, discuss what actions the student took to achieve that goal and look for ways to replicate those actions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review communities with the students and search out tips and information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Share screens and watch a clip of a graduation speaker and then craft a graduation goal and plan for achieving that goal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Use questions in the course of study to quiz the student. Set up a course mentor appointment to further discuss the topic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PersonalizationMenu__c</fullName>
        <description>Categories of personalization : Personal, Motivational, Academic, Technical.</description>
        <inlineHelpText>Categories of personalization : Personal, Motivational, Academic, Technical.</inlineHelpText>
        <label>PersonalizationMenu</label>
        <picklist>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Motivational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ShortText__c</fullName>
        <description>Field to store a portion of the Text__c field data in plain text</description>
        <label>ShortText</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>The contact record for this student</description>
        <inlineHelpText>The student associated with this note.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>WGUStudentNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <label>Note Sub Type</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>AAV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demonstration Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excess Attempts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Academic Instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goals and Tasks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Student On-Boarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term Break</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provided Information on Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provided Information on Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provided Non-Academic Instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reminded Student of Inactive Protocol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested a Return Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Responded to a Community Post</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested a Phone Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested an Appointment Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested an Email Update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>The basic rich text area for details of this note</description>
        <inlineHelpText>Please enter any details for this note.</inlineHelpText>
        <label>Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Level 1 Note Type</description>
        <inlineHelpText>This note type.</inlineHelpText>
        <label>Note Type</label>
        <picklist>
            <picklistValues>
                <fullName>Live Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instant Message (IM) / Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webinar Attendance Noted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outreach (CM only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration (MGR only)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WGUCreationDateTime__c</fullName>
        <description>This holds the date time stamp of a note.</description>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <label>WGU Student Note</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGUStudentNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WGUStudentPerformanceSurvey__c.object
<CustomObject>
    <description>Answers to student performance survey questions, completed by student mentors via the student notes UI. NOTE: The Labels are different than the Object Name to match verbiage of the Notes.</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Student (Contact) whose WGUStudentNote__c record is associated with this Performance Survey Record (1:1)</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>WGUStudentPerformanceSurveys</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Student Performance Question</label>
    <nameField>
        <label>Note Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Performance Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NotesController.cls
/*
 * Author Paul Coleman
 * Western Governors University 
 *
 * Date Nov 13 2012 @ 1354 hrs
 * Revised: Oct 30, security audit compliance: with sharing
 * Revised: Nov 13, added student performance survey section
 * 
 * NotesController for Notes.page and Javascript Custom Button dialogs
 *
 */ 
global with sharing class NotesController {

    private final static String noteSELECT = 'Select ShortText__c, WGUCreationDateTime__c, Text__c, SystemModstamp, SubType__c, Student__c, PIDM__c, Name, MentorId__c, Level1Image__c, LastModifiedDate, LastModifiedById, LastActivityDate, IsDeleted, InteractionID__c, Id, CreatedDate, CreatedById, Type__c, Author__c, Author__r.Name, CreatedBy.Name, AuthorPidm__c,PersonalizationActions__c,PersonalizationMenu__c,PersonalizationMenuSubType__c From WGUStudentNote__c';
    private final static String surveySELECT = 'Select EvidenceOfAcademicActivity__c, GoalPerformanceSinceLastCall__c, WGUStudentNote__c, Student__c, Name, LastModifiedDate, LastModifiedById, LastActivityDate, IsDeleted, Id, CreatedDate, CreatedById, CreatedBy.Name From WGUStudentPerformanceSurvey__c';
    
    public NotesController(ApexPages.StandardController controller) {

    }

    public String getIE8SubHeader() {
      String userAgent = Test.isRunningTest()? '': ApexPages.currentPage().getHeaders().get('User-Agent').tolowercase();
      return (userAgent.contains('msie 8.0') || userAgent.contains('msie 7.0'))? 'ie8subheader': '';
    }
    
    public String getIE8Header() {
      String userAgent = Test.isRunningTest()? '': ApexPages.currentPage().getHeaders().get('User-Agent').tolowercase();
      return (userAgent.contains('msie 8.0') || userAgent.contains('msie 7.0'))? 'ie8header': '';
    }
    
    public String getIE8Footer() {
      String userAgent = Test.isRunningTest()? '': ApexPages.currentPage().getHeaders().get('User-Agent').tolowercase();
      return (userAgent.contains('msie 8.0') || userAgent.contains('msie 7.0')) ? 'ie8footer': '';
    }
    
    public String getLt(){
        return '<';
    }
    public String getGt(){
        return '>';
    }

    @RemoteAction
    webService static String getStudentJSONByContactId( String contactId ) {
        Id studentAccountId;
        if ( contactId != null ) {
             studentAccountId = [select count() from Contact where Id = :contactId]>0?[select AccountId from Contact where Id = :contactId LIMIT 1].AccountId: null;
        }
        if ( studentAccountId == null ) {
          throw new StudentException('No student found for Contact Id: ' + contactId);
        }
        return getStudentJSON( studentAccountId, false );
    }
    
    @RemoteAction
    webService static String getStudentJSONByStudentWGUId( String studentWGUId ) {
        Id studentAccountId;
        if ( studentWGUId != null ) {
             studentAccountId = [select count() from Contact where StudentID__c = :studentWGUId]>0?[select AccountId from Contact where StudentID__c = :studentWGUId LIMIT 1].AccountId: null;
        }
        if ( studentAccountId == null ) {
          throw new StudentException('No student found for WGU Student Id: ' + studentWGUId );
        }
        return getStudentJSON( studentAccountId, false );
    }
    
    @RemoteAction
    webService static String getStudentJSON( String studentAccountId, boolean isPidm ) {    
    
        List<Contact> student = new List<Contact>();
        if ( studentAccountId != null ) {
            if ( isPidm ) {
                student = [select count() from Contact where PIDM__c = :studentAccountId]==1?[select AccountId,Name,FirstName,LastName,Email,PIDM__c,Id,Phone,OtherPhone,MobilePhone,HomePhone,TermCode__c,MentorPidm__c,Mentor__c,StudentMentor__c,StudentRiskScore__c from Contact where PIDM__c = :studentAccountId LIMIT 1]: new List<Contact>();
            } else {
                student = [select count() from Contact where Accountid = :studentAccountId]==1?[select AccountId,Name,FirstName,LastName,Email,PIDM__c,Id,Phone,OtherPhone,MobilePhone,HomePhone,TermCode__c,MentorPidm__c,Mentor__c,StudentMentor__c,StudentRiskScore__c from Contact where AccountId = :studentAccountId LIMIT 1]: new List<Contact>();
            }
        }
        return JSONUtil.getJSON(student);
    }
        
    @RemoteAction
    webService static String getNoteJSONById( String noteId ) 
    {    
        List<WGUStudentNote__c> note;
        if ( noteId != null ) {
           String noteSOQL = noteSELECT + ' where id = \''+ String.escapeSingleQuotes(noteId) +'\' LIMIT 1';
           note= [select count() from WGUStudentNote__c where id = :noteId]==1? Database.query(noteSOQL): new List<WGUStudentNote__c>();
           if ( !note.isEmpty() ){
               note[0].Text__c = EncodingUtil.base64Encode( Blob.ValueOf( note[0].Text__c ) );
           }
        }
        return JSONUtil.getJSON(note);
    }
        
    @RemoteAction
    webService static String saveNoteJSON( String noteJSON ) {
    	System.debug('####### saveNoteJSON 1');
        WGUStudentNote__c pageNote = (WGUStudentNote__c)JSON.deserialize( noteJSON, WGUStudentNote__c.class );
        WGUStudentNote__c note = pageNote.Id == null? new WGUStudentNote__c(): new WGUStudentNote__c(Id=pageNote.Id); //use new note for saving/inserting for security abstraction 
        note.Text__c = EncodingUtil.base64Decode( pageNote.Text__c ).toString();
        String textString = String.valueOf(note.Text__c).replaceAll('//<.*?//>', '');
        Integer textLength = textString.length() > 254 ? 254 : textString.length()-1;
        note.ShortText__c = textString.subString(0,textLength);
        note.SubType__c = pageNote.SubType__c;
        note.Name = pageNote.Name;
        note.Type__c = pageNote.Type__c;
        note.Author__c = UserInfo.getUserId();
        note.AuthorPIDM__c = pageNote.AuthorPIDM__c;
        note.PIDM__c = pageNote.PIDM__c;
        note.Student__c = pageNote.Student__c;
        note.PersonalizationActions__c= pageNote.PersonalizationActions__c;
        note.PersonalizationMenu__c= pageNote.PersonalizationMenu__c;
        note.PersonalizationMenuSubType__c= pageNote.PersonalizationMenuSubType__c;
        if ( note.id == null ) {
          note.WGUCreationDateTime__c = System.now();
          if(note.Student__c!=null)
          {
          	Contact current = [select id, StudentRiskScore__c from contact where id = :note.Student__c]; 
          	note.StudentRiskValue__c = current.StudentRiskScore__c;
          }
    	  System.debug('####### saveNoteJSON -Insert'+note);
          insert note;
        } else {
    	  System.debug('####### saveNoteJSON -update'+note);
          update note;
        }
    	System.debug('####### saveNoteJSON 2');
        return getNoteJSONById(note.Id);
    }
        
   @RemoteAction
    webService static String getNotesJSONByOffset( String contactId, Integer offset )  {
        
        List<WGUStudentNote__c> notes = new List<WGUStudentNote__c>();
        Integer noteCount = 0;
        Integer batchSize = 50;
        if ( contactId != null ) {
          Id studentContactId = String.escapeSingleQuotes(contactId);
          noteCount = [select count() from WGUStudentNote__c where Student__c = :studentContactId];
          if ( noteCount != 0 ) {
               String noteSOQL = noteSELECT + ' where Student__c = \''+studentContactId+'\' order by WGUCreationDateTime__c DESC LIMIT '+String.valueOf(batchSize)+' OFFSET ' + string.ValueOf(offset);
               notes = Database.query(noteSOQL);
          } 
        }
        if ( !notes.isEmpty() ) {
          for ( WGUStudentNote__c note: notes ) {
            note.Text__c = EncodingUtil.base64Encode( Blob.ValueOf( note.Text__c==null?'':note.Text__c ) );
          }
        }
        return JSONUtil.getJSON(notes, ((offset+batchSize) >= noteCount), String.valueOf(offset + notes.size()) );
    }

    @RemoteAction
    webService static Integer getNotesCountByContactId( String contactId )  {        
        return [select count() from WGUStudentNote__c where Student__c = :contactId];
    }
 
    public String getNoteTypeJSON() {
        Schema.DescribeFieldResult f = Schema.sObjectType.WGUStudentNote__c.fields.Type__c;
        f = f.getSObjectField().getDescribe();
        List<Schema.PicklistEntry> ple = f.getPicklistValues();
        String jsonString ='[';
        boolean isFirst = true;
        for ( Schema.PicklistEntry entry: ple ) {
            if ( isFirst ) {
                isFirst = false;
                jsonString += '{\"value\":\"'+entry.getValue()+'\", \"name\":\"'+entry.getLabel()+'\"}';
            } else {
                jsonString += ',{\"value\":\"'+entry.getValue()+'\", \"name\":\"'+entry.getLabel()+'\"}';
            }
        }
        jsonString += ']';
        return jsonString;
    } 
    
    public String getNoteTypeFilterJSON() {
        Schema.DescribeFieldResult f = Schema.sObjectType.WGUStudentNote__c.fields.Type__c;
        f = f.getSObjectField().getDescribe();
        List<Schema.PicklistEntry> ple = f.getPicklistValues();
        String jsonString = '[{\"value\":\"'+'All'+'\", \"name\":\"'+'All'+'\"}';
        for ( Schema.PicklistEntry entry: ple ) {
            jsonString += ',{\"value\":\"'+entry.getValue()+'\", \"name\":\"'+entry.getLabel()+'\"}';
        }
        jsonString += ']';
        return jsonString;
    } 
    
    public String getNoteSubTypeMetaJSON() {
        //new winter '13 schema capabilities
        return JSON.serialize( Schema.sObjectType.WGUStudentNote__c.fields.SubType__c.getSObjectField().getDescribe() );
    } 
    //12-10 action subtype
    public String getActionTypeJSON() {
        Schema.DescribeFieldResult f = Schema.sObjectType.WGUStudentNote__c.fields.PersonalizationMenu__c;
        f = f.getSObjectField().getDescribe();
        List<Schema.PicklistEntry> ple = f.getPicklistValues();
        String jsonString ='[';
        boolean isFirst = true;
        for ( Schema.PicklistEntry entry: ple ) {
            if ( isFirst ) {
                isFirst = false;
                jsonString += '{\"value\":\"'+entry.getValue()+'\", \"name\":\"'+entry.getLabel()+'\"}';
            } else {
                jsonString += ',{\"value\":\"'+entry.getValue()+'\", \"name\":\"'+entry.getLabel()+'\"}';
            }
        }
        jsonString += ']';
        return jsonString;
    } 
    public String getActionSubTypeMetaJSON() {
        //new winter '13 schema capabilities
        return JSON.serialize( Schema.sObjectType.WGUStudentNote__c.fields.PersonalizationMenuSubType__c.getSObjectField().getDescribe() );
    } 
//******************************************************************************************
//******************************************************************************************
//********************** BEGIN STUDENT PERFORMANCE SURVEY SECTION **************************
//******************************************************************************************
//* Added November 13, 2012 by Paul Coleman
    
    /*public String getEvidenceOfAcademicActivityMetaJSON() {
        return JSON.serialize( Schema.sObjectType.WGUStudentPerformanceSurvey__c.fields.EvidenceOfAcademicActivity__c.getSObjectField().getDescribe() );
    } 
    
    public String getGoalPerformanceSinceLastCallMetaJSON() {
        return JSON.serialize( Schema.sObjectType.WGUStudentPerformanceSurvey__c.fields.GoalPerformanceSinceLastCall__c.getSObjectField().getDescribe() );
    }*/
    
   @RemoteAction
    webService static String getPerformanceSurveyJSONByOffset( String contactId, Integer offset )  {
        
        List<WGUStudentPerformanceSurvey__c> surveys = new List<WGUStudentPerformanceSurvey__c>();
        Integer surveyCount = 0;
        Integer batchSize = 50;
        if ( contactId != null ) {
          Id studentContactId = String.escapeSingleQuotes(contactId);
          surveyCount = [select count() from WGUStudentPerformanceSurvey__c where Student__c = :studentContactId];
          if ( surveyCount != 0 ) {
               String surveySOQL = surveySELECT + ' where Student__c = \''+studentContactId+'\' LIMIT '+String.valueOf(batchSize)+' OFFSET ' + string.ValueOf(offset);
               surveys = Database.query( surveySOQL );
          } 
        }
        return JSONUtil.getJSON(surveys, ((offset+batchSize) >= surveyCount), String.valueOf(offset + surveys.size()) );
    }

    @RemoteAction
    webService static String saveSurveyJSON( String surveyJSON )   {
        WGUStudentPerformanceSurvey__c pageSurvey = (WGUStudentPerformanceSurvey__c )JSON.deserialize( surveyJSON , WGUStudentPerformanceSurvey__c.class );
        WGUStudentPerformanceSurvey__c survey = pageSurvey.Id == null? new WGUStudentPerformanceSurvey__c (): new WGUStudentPerformanceSurvey__c (Id=pageSurvey.Id); //use new survey for saving/inserting for security abstraction 
        survey.EvidenceOfAcademicActivity__c = pageSurvey.EvidenceOfAcademicActivity__c;
        survey.GoalPerformanceSinceLastCall__c = pageSurvey.GoalPerformanceSinceLastCall__c;
        survey.Name = pageSurvey.Name;
        survey.Student__c = pageSurvey.Student__c;
        survey.WGUStudentNote__c = pageSurvey.WGUStudentNote__c;
        if ( survey.id == null ) {
          insert survey;
        } else {
          update survey;
        }
        String surveySOQL = surveySELECT + ' where Id = \'' + survey.Id + '\' LIMIT 1';
        return JSONUtil.getJSON(Database.query( surveySOQL ));
    }

//****************************************************************************************
//********************** END STUDENT PERFORMANCE SURVEY SECTION **************************
//****************************************************************************************
//****************************************************************************************


}