src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/EmailAddress__c.object
<CustomObject>
    <description>All Email addresses related to a contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Addresses</relationshipLabel>
        <relationshipName>EmailAddresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <label>PIDM</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Email Address</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/TransferEvaluation__c.object
<CustomObject>
    <description>A Transfer evaluation is the parent object of the equivalent courses that will given to the student from their transfer work. It controls the overall status and assignment of the evaluation.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The Link Between opportunities and transfer evaluations</description>
        <label>CARE Profile Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transfer Evaluations</relationshipLabel>
        <relationshipName>TransferEvaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transfer Evaluation</label>
    <nameField>
        <label>Transfer Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfer Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TestProgramChangeEmailHandler.cls
/*
 * Author Brad King
 * Western Governors University 
 *
 * Date April 2 2013
 * 
 * Test EmailHandlers  
 *
 */

@isTest
private with sharing class TestProgramChangeEmailHandler
{      
    private static testMethod void testProgramChangeEmailHandler()
    {
        // create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        User testUser = new User();
        Contact testContact1 = new Contact();
        Contact testContact2 = new Contact();
        List<Contact> testContacts = new List<Contact>();
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'Field Experiences User' LIMIT 1].Id;
        
        testUser.Firstname = 'TestFEPlEm';
        testUser.Lastname = 'UserFEPlEm';
        testUser.Pidm__c = 'QA95050QA';
        testUser.Username = 'testuserFEPlEm@testuser.testuser';
        testUser.Email = 'testuserFEPlEm@testuser.testuser.wgu.edu';
        testUser.Alias = 'testFEPl';
        testUser.CommunityNickname = 'testua6123se';
        testUser.TimeZoneSidKey = 'America/Denver';
        testUser.LocaleSidKey = 'en_US';
        testUser.EmailEncodingKey = 'ISO-8859-1';
        testUser.ProfileId = profileId;
        testUser.LanguageLocaleKey = 'en_US';    
  
        testContact1.FirstName = 'Willtest';
        testContact1.Lastname = 'Slayedtest';
        testContact1.Email = 'wslayed@my.wgu.edu';
        testContact1.PIDM__c = 'EMQAPIDM1';
             
        testContact2.FirstName = 'Willtest1';
        testContact2.Lastname = 'Slayedtest1';
        testContact2.Email = 'wslayed@my.wgu.edu';
        testContact2.PIDM__c = 'EMQAPIDM2';
        testContacts.add(testContact1);
        testContacts.add(testContact2);
        insert testContacts;
        
                  System.assert(testContact1.Id != NULL, 'testProgramChangeEmailHandler TestContact1.id IS NULL');
        
        Date oppCloseDate = date.valueOf('2012-10-02');
        Opportunity testOpp = new Opportunity(name = 'Opp Case Feed Tester43', StageName = 'Applicant', CloseDate = oppCloseDate);
        insert testOpp;
        
        TransferEvaluation__c testTransferEval = new TransferEvaluation__c(Name = 'Eval Case Feed Tester43', Opportunity__c = testOpp.Id);
        insert testTransferEval;
        
        EmailAddress__c emailAddressObj = new EmailAddress__c(Email__c = 'qanewobj@qanewobj.qanewobj1', Contact__c = testContact1.Id);
        insert emailAddressObj;
             
  
        // setup the data for the email
        email.subject = 'Crazy Subject Line [ ref:999999999_999999999:ref ]';
        email.fromname = 'Will Slayed';
        email.htmlBody = '<br><b>This is the email body @!$654654654654654$!@' + testTransferEval.Id + '</b><br> ref:999999999_999999999:ref';
        email.fromAddress = 'wslayed@wgu.edu';
        Messaging.InboundEmail.Header hditem= new Messaging.InboundEmail.Header();
        email.headers=new Messaging.InboundEmail.Header[1];
        hditem.name='Date';
        hditem.value='Tue, 28 Apr 2009 14:08:37 -0700';
        email.headers[0]=hditem;        
       
        id[] fixedSearchResults = new id[2];
        fixedSearchResults[0] = testContact1.Id;
        fixedSearchResults[1] = testContact2.Id;
        Test.setFixedSearchResults(fixedSearchResults);
          
       // Use startTest and stopTest to break up calls to not exceed query limits
       Test.startTest();  
        insert testUser;
         
       User sysAdmin = [SELECT Id from User where alias = 'sadmi' LIMIT 1];
       
       System.runAs( sysAdmin ) {
           
        ProgramChangeEmailHandler emailHandler7 = new ProgramChangeEmailHandler();
        emailHandler7.handleInboundEmail(email, env); 
        //NEED ASSERTION HERE
                
      }
  
      Test.stopTest();
    }
}