src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for wguProgram</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/StudentLicenseHistory__c.object
<CustomObject>
    <description>link student and license</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>student link</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>StudentLicenseHistorys</relationshipLabel>
        <relationshipName>StudentLicenseHistorys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUStateLicensure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>link to the WGUStateLicensure</description>
        <label>WGU State Licensure</label>
        <referenceTo>WGUStateLicensure__c</referenceTo>
        <relationshipLabel>StudentLicenseHistorys</relationshipLabel>
        <relationshipName>StudentLicenseHistorys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student License History</label>
    <nameField>
        <label>StudentLicense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StudentLicenseHistorys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGULicenseRequirement__c.object
<CustomObject>
    <description>License Requirement</description>
    <fields>
        <fullName>Program__c</fullName>
        <description>The title of the program</description>
        <label>Program</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUStateLicensure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>state license that this requirement is linked to.</description>
        <label>WGU State Licensure</label>
        <referenceTo>WGUStateLicensure__c</referenceTo>
        <relationshipLabel>WGU License Requirements</relationshipLabel>
        <relationshipName>WGULicenseRequirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU License Requirement</label>
    <nameField>
        <label>WGU License Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU License Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUStateLicensure__c.object
<CustomObject>
    <description>Licenses available for all students.</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nebraska</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>WGU State Licensure</label>
    <nameField>
        <label>WGU Licensure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU State Licensure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FDPStateAndLicensure.cls
public with sharing class FDPStateAndLicensure {
  Map<String,Set<WGUStateLicensure__c>> statemaps;
  Contact student;
  public FDPStateAndLicensure(Contact s) {
    student = s;
  }
  Public Map<String,Set<WGUStateLicensure__c>> getStateLicensureMap(){
    if(this.statemaps==null){
      Set<String> states=new Set<String>();
      this.statemaps = new Map<String,Set<WGUStateLicensure__c>>();
      List <WGULicenseRequirement__c> lis = [select Id,
        WGUStateLicensure__r.Name,
        WGUStateLicensure__r.State__c,
        WGUStateLicensure__r.Id,
        Program__c
        from WGULicenseRequirement__c
        where Program__c = :student.WGUDegreeProgram__r.Name];
      for (WGULicenseRequirement__c li:lis){
        states.add(li.WGUStateLicensure__r.State__c);
        Set<WGUStateLicensure__c> licensures=statemaps.get(li.WGUStateLicensure__r.State__c);
        if(licensures==null) {
          licensures=new Set<WGUStateLicensure__c>();
          this.statemaps.put(li.WGUStateLicensure__r.State__c,licensures);
        }
        licensures.add(li.WGUStateLicensure__r);
      }
    }
    return statemaps;
  }
  public boolean needLicensure() {
    List<StudentLicenseHistory__c> lis = [select Id
      from StudentLicenseHistory__c
      where Student__c = :student.Id];
    if(lis.size() > 0)
      return false;
    return this.getStateLicensureMap().keyset().size() > 0;
  }
}