src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>Student Identification number, also known as Banner ID.</description>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TermEndDate__c</fullName>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/StudentProcess__c.object
<CustomObject>
    <description>Custom object to manage student processes by record type.</description>
    <fields>
        <fullName>ApplicationReceived__c</fullName>
        <description>A date field representing the date the student submitted the student process application.</description>
        <label>Application Received</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Student_Processes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>A picklist field indicating the reason for the student process.</description>
        <label>Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Assessment Delivery staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business/financial aid staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competency-based model doesn&apos;t fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Death in the Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Degree Interests Changed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demonstration Teaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demonstration Teaching (DT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distance learning model doesn&apos;t fit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t have the time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial aid or financial problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Following a Term Break</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduation / Program Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical / Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentoring Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Military Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Disaster / Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Never Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursing Clinical Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other student services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pers Circ - Bereavement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pers Circ - Care Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pers Circ - Disaster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pers Circ - Economy</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>A formula field that pulls in the student ID number.</description>
        <formula>Student__r.StudentID__c</formula>
        <label>Student ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup field to the contact of the student process object.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>StudentProcesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TermEndDate__c</fullName>
        <formula>Student__r.TermEndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <label>Student Process</label>
    <nameField>
        <label>Student Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Processes</pluralLabel>
    <recordTypes>
        <fullName>Withdrawal</fullName>
        <active>true</active>
        <description>The record type used to manage the withdrawal process for student records.</description>
        <label>Withdrawal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/WithdrawalController.cls
/*
This Controller is for Withdrawal VF page used by Students.
Author- Bhavadeep Raavi
*/
public with sharing class WithdrawalController{
    public Contact studentInfo{get;set;}
    public Boolean disFlag{get;set;}
    public StudentProcess__c sp{get{
        if(sp==null){
            sp=new StudentProcess__c();
            return sp;
        }else{
            return sp;
        }
    }set;}
    public WithdrawalController(){
        try{
            string userPidm = [select pidm__c from User where id=:UserInfo.getUserId()].pidm__c; 
            studentInfo=[select Id,Name,firstname,Lastname,studentID__c,Mentor__r.Name,TermEndDate__c from Contact where firstName=:UserInfo.getFirstName() and lastName=:UserInfo.getLastName() and PIDM__c =:userPidm  limit 1];    
            List<StudentProcess__c> spLst=[select id,ApplicationReceived__c from StudentProcess__c where ApplicationReceived__c!=null and Student__c=:studentInfo.Id order by ApplicationReceived__c desc];
            system.debug('raaviList '+spLst);
            system.debug('raaviDate '+spLst[0].ApplicationReceived__c);
            if(spLst!=null && spLst.size()>0 && spLst.get(0)!=null && spLst.get(0).ApplicationReceived__c.date().daysBetween(Date.today())<=30){
                system.debug('raaviDate1 '+spLst[0].ApplicationReceived__c);
                System.debug('spLst.get(0).ApplicationReceived__c.date() : '+Date.today().daysBetween(spLst.get(0).ApplicationReceived__c.date()));
                disFlag=true;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Your withdrawal request has already been submitted.  If you have questions concerning your withdrawal please contact Student Services at (866) 903-0110.'));          
            }
        }catch(Exception e){
             disFlag=true;
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Your record cannot be found.Please contact WGU'));      
        }
    }
    public PageReference submit(){
        try{
            sp.student__c=studentInfo.Id;
            sp.Name=studentInfo.lastname+','+studentInfo.firstname+' '+'Withdraw Request';
            sp.recordTypeId =  [Select ID from RecordType where DeveloperName='Withdrawal' and sObjectType = 'StudentProcess__c' ].id; 
            sp.ApplicationReceived__c=System.now();
            system.debug('multi '+sp.reason__c);
            if(sp.reason__c.split(';').size()>5){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select a maximum of 5 values.'));  
                return null;    
            }
            insert sp;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Thank you for your request.  A withdrawal counselor will be in touch with you soon.  In the meantime, if you have any questions, please contact Student Services at (866) 903-0110.')); 
            disFlag=true;     
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You got an error.Please contact your Administrator.'));      
        }
    return null;
    }
    public PageReference cancel(){
            PageReference pf = new PageReference('https://my.wgu.edu'); 
            pf.setRedirect(true); 
            return pf;
    }
    
}