src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BalanceDue__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This just shows if a balance is due from the student.</description>
        <inlineHelpText>Student has a balance due.</inlineHelpText>
        <label>Balance Due</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>Student Identification number, also known as Banner ID.</description>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StudentProcess__c.object
<CustomObject>
    <description>Custom object to manage student processes by record type.</description>
    <fields>
        <fullName>ApplicationReceived__c</fullName>
        <description>A date field representing the date the student submitted the student process application.</description>
        <label>Application Received</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BestTimeToContact__c</fullName>
        <description>Student disclosed when is the best time to contact the student</description>
        <inlineHelpText>When is the best time to contact the student?</inlineHelpText>
        <label>Best Time To Contact</label>
        <picklist>
            <picklistValues>
                <fullName>7:00 - 8:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00 - 9:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00 - 10:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00 - 11:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00 - 12:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00 - 1:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 - 2:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 - 3:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00 - 4:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00 - 5:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00 - 6:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00 - 7:00 PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>A formula field that pulls in the student ID number.</description>
        <formula>Student__r.StudentID__c</formula>
        <label>Student ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup field to the contact of the student process object.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>StudentProcesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TBGradAppSubmitted__c</fullName>
        <description>Have you or do you plan to submit a Graduation Application?</description>
        <inlineHelpText>Have you or do you plan to submit a Graduation Application?</inlineHelpText>
        <label>TB Grad App Submitted</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TBReasonComments__c</fullName>
        <description>In your own words, describe how this break will support your goal to graduate.</description>
        <inlineHelpText>In your own words, describe how this break will support your goal to graduate.</inlineHelpText>
        <label>TB Reason Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TBReason__c</fullName>
        <description>Reason For Requesting a Term Break</description>
        <inlineHelpText>Reason For Requesting a Term Break</inlineHelpText>
        <label>TB Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Work related circumstances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obligations/Personal &amp; Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Aid Appeal Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical (your own)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Military (3 months max.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teaching Term Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursing Term Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan to withdraw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government Shutdown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WorkSubmittedAfterTerm__c</fullName>
        <description>Have you submitted any tasks/revisions to TaskStream or completed an exam after the end of your most recent term?</description>
        <inlineHelpText>Have you submitted any tasks/revisions to TaskStream or completed an exam after the end of your most recent term?</inlineHelpText>
        <label>Work Submitted After Term</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student Process</label>
    <nameField>
        <label>Student Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Processes</pluralLabel>
    <recordTypes>
        <fullName>Graduation</fullName>
        <active>true</active>
        <description>The record type used to manage the graduation process for student records.</description>
        <label>Graduation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TestTermBreakRequestController.cls
/*
Test class  for TermBreakRequestController
Author- Bhavadeep Raavi

Revised: 12/02/2013 Comment out work submitted after term and graduation application submitted questions - Kristin Hasna
*/
@isTest
private with sharing class TestTermBreakRequestController{
     
     private static testmethod void TestTermBreakRequestController(){
        User testUser = [SELECT Id,pidm__c from User WHERE Profile.Name = 'Mentor' AND isActive = true LIMIT 1];
        System.runAs(testUser){
           
        Contact contact= new Contact();
        contact.LastName=UserInfo.getLastName();
        contact.FirstName=UserInfo.getFirstName();
        contact.pidm__c=testUser.pidm__c;
        contact.studentId__c ='12345';
        contact.BalanceDue__c = true;
        insert contact;
        
        StudentProcess__c sp=new StudentProcess__c();
        sp.name='Test sp';
        sp.student__c=contact.id;
        sp.ApplicationReceived__c=System.now();
        insert sp;
        
        
        Test.startTest();
        System.assertEquals(sp.name,'Test sp');
        
        System.assertEquals(contact.LastName,UserInfo.getLastName());
        System.assertEquals(contact.FirstName,UserInfo.getFirstName());
        
        TermBreakRequestController tb1= new TermBreakRequestController();
        tb1.stdId= '12345';
        tb1.selReqMonths ='1';
        tb1.getStudentRecord();
        tb1.sp = sp;
        /* tb1.sp.TBGradAppSubmitted__c = 'Yes';*/
        tb1.saveTermBreak();
        tb1.cancel();
        TermBreakRequestController tb2= new TermBreakRequestController();
        tb2.sp=null;
        tb2.stdId= '12345';
        tb2.getStudentRecord();
        tb2.selReqMonths ='1';
        tb2.sp.TBReason__c ='Financial';
        /*tb2.sp.WorkSubmittedAfterTerm__c ='Yes';*/
        /*tb2.sp.TBGradAppSubmitted__c ='No';*/
        tb2.sp.TBReasonComments__c = 'test';
        tb2.sp.BestTimeToContact__c ='9:00 - 10:00 AM';
        tb2.saveTermBreak();
       
        System.assertEquals(tb2.sp.TBReasonComments__c, 'test');
        System.assertEquals(tb2.sp.TBReason__c,'Financial');
        
     
        Test.stopTest();
        }
     }
    
  private static testmethod void TestTermBreakRequestController1(){
        User testUser = [SELECT Id,pidm__c from User WHERE Profile.Name = 'Student Profile' AND isActive = true LIMIT 1];
        System.runAs(testUser){
        
        
        Contact contact= new Contact();
        contact.LastName=UserInfo.getLastName();
        contact.FirstName=UserInfo.getFirstName();
        contact.pidm__c=testUser.pidm__c;
        contact.studentId__c ='12345';
        contact.BalanceDue__c = false;
        insert contact;
        
        Test.startTest();
        TermBreakRequestController tb1= new TermBreakRequestController();
        tb1.selReqMonths ='1';   
        tb1.saveTermBreak();
        tb1.cancel();
        TermBreakRequestController tb2= new TermBreakRequestController(); 
        tb2.selReqMonths = '';
        tb2.saveTermBreak();
        
        Test.stopTest();
        }
     }
     private static testmethod void TestTermBreakRequestController2(){
        User testUser = [SELECT Id,pidm__c from User WHERE Profile.Name = 'Mentor' AND isActive = true LIMIT 1];
        System.runAs(testUser){
        
           
        Contact contact= new Contact();
        contact.LastName=UserInfo.getLastName();
        contact.FirstName=UserInfo.getFirstName();
        contact.pidm__c=testUser.pidm__c;
        contact.studentId__c ='00012345';
        contact.BalanceDue__c = true;
        insert contact;
        
        StudentProcess__c sp=new StudentProcess__c();
        sp.name='Test sp';
        sp.student__c=contact.id;
        sp.ApplicationReceived__c=System.now();
        insert sp;
        
        
        Test.startTest();
        System.assertEquals(contact.LastName,UserInfo.getLastName());
       
        TermBreakRequestController tb2= new TermBreakRequestController();
        tb2.sp=null;
        tb2.stdId= '12345';
        tb2.getStudentRecord();
        tb2.selReqMonths ='1';
        tb2.sp.TBReason__c ='Financial';
        /*tb2.sp.WorkSubmittedAfterTerm__c ='Yes';*/
        /*tb2.sp.TBGradAppSubmitted__c ='No';*/
        tb2.sp.TBReasonComments__c = 'test';
        tb2.sp.BestTimeToContact__c ='9:00 - 10:00 AM';
        tb2.saveTermBreak();
        
        System.assertEquals(tb2.sp.TBReasonComments__c, 'test');
        System.assertEquals(tb2.sp.TBReason__c,'Financial');
     
        Test.stopTest();
        }
     }
    

}