src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TermCode__c</fullName>
        <description>The current TERM Code year + month</description>
        <formula>TEXT(YEAR(TermStartDate__c))  &amp; 
IF(MONTH(TermStartDate__c) &lt; 10, &apos;0&apos;, NULL) &amp;
TEXT(Month( TermStartDate__c ))</formula>
        <inlineHelpText>Term Code</inlineHelpText>
        <label>Term Code</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StudentCourseRegistration__c.object
<CustomObject>
    <description>This is an object for pulling current term registration  information from WGUFDP. No FDP user should have direct access to this Object,</description>
    <fields>
        <fullName>CourseCode__c</fullName>
        <description>Banner code for the course</description>
        <label>CourseCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The student associated with this registration. (used to speed up queries on this table)</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>StudentCourseRegistrations</relationshipLabel>
        <relationshipName>StudentCourseRegistrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Termcode__c</fullName>
        <label>Termcode</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pidm__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for referential integrity</description>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>pidm</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>uniqueid__c</fullName>
        <externalId>true</externalId>
        <label>uniqueid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Student Course Registration</label>
    <nameField>
        <label>StudentCourseRegistration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Course Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StudentCourseRegistrationBatchMapping.cls
global class StudentCourseRegistrationBatchMapping
  implements Database.Batchable<sObject> {
  global String Query;
  global List<String> emails;
  global StudentCourseRegistrationBatchMapping(List<String> pEmails) {
    if(pEmails != null) {
      emails = pEmails;
    }
    init();
  }
  global StudentCourseRegistrationBatchMapping() {
    emails = new List<String>();
    init();
  }
  private void init() {
    Query = 'select Student__c,PIDM__c ,name'
      + ' from StudentCourseRegistration__c '
      + ' where Student__c = null ';
    emails.add('gchild@solutionstream.com');
  }
  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(Query);
  }

  global void execute(Database.BatchableContext BC, List<sObject> scope) {
    List<StudentCourseRegistration__c> SCRs = (List<StudentCourseRegistration__c>)scope;
    List<String> pidms = new List<String>();
    for(StudentCourseRegistration__c scr : SCRs) {
      pidms.add(scr.PIDM__c);
    }

    List<Contact> students = [
      select PIDM__c
      from Contact
      where PIDM__c in :pidms
    ];
    Map<String,Id> pidmToId = new Map<String,Id>();
    for(Contact s : students) {
      pidmToId.put(s.PIDM__c,s.Id);
    }
    List<StudentCourseRegistration__c> updateScrs = new List<StudentCourseRegistration__c>();
    for(StudentCourseRegistration__c scr : SCRs) {
      scr.Student__c = pidmToId.get(scr.PIDM__c);
      scr.name=scr.coursecode__C;
      //if(scr.UniqueId__c.split('-',5).size() < 3) {
      //  scr.UniqueId__c = scr.UniqueId__c + '-' + scr.TermCode__c;
     // }
      updateScrs.add(scr);
    }
    update updateScrs;
  }

  global void finish(Database.BatchableContext BC){
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

    mail.setToAddresses(emails);
    mail.setReplyTo('gchild@solutionstream.com');
    mail.setSenderDisplayName('Salesforce Batch Processing');
    mail.setSubject('StudentCourseRegistration Mapping Completed');
    mail.setPlainTextBody('Batch Process has completed');

    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
  }
}