src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MilitaryStatus__c</fullName>
        <description>This displays the Military status of an individual if any.</description>
        <inlineHelpText>This displays the Military status of an individual if any.</inlineHelpText>
        <label>Military Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/StudentAttributes__c.object
<CustomObject>
    <description>Custom object to manage student attributes via portal and sites, with update triggers to Contact/Account</description>
    <fields>
        <fullName>Affiliation__c</fullName>
        <description>WGU affiliate the student belongs to</description>
        <inlineHelpText>Set the student&apos;s WGU affiliation.</inlineHelpText>
        <label>University Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>WGU</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU-TN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CitizenshipStatus__c</fullName>
        <description>Self disclosed information from the application form</description>
        <label>Citizenship Status</label>
        <picklist>
            <picklistValues>
                <fullName>Non-Citizen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>U.S. Citizen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Resident Alien</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CommunityType__c</fullName>
        <description>Community type gathered from the Application form</description>
        <label>Community Type</label>
        <picklist>
            <picklistValues>
                <fullName>Rural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suburban</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urban</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <description>Self disclosed from the application form</description>
        <label>Marital Status</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Separated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divorced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Widowed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MilitaryStatus__c</fullName>
        <description>self disclosed from the application form</description>
        <label>Military Status</label>
        <picklist>
            <picklistValues>
                <fullName>Air Force Active Duty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Army Active Duty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter 1606 MGIBill Reserve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter 1607</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter 30 MGIBill Active Duty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter 31 Voc Rehab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter 32 VEAP Vietnam Era</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter 33 Post 9/11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chapter 35 Veterans Dependents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coast Guard Active Duty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOD/TA Active Duty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOD/TA Active Duty - Top Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decline to Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marines Active Duty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navy Active Duty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Never in Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Veteran</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Veteran Complete Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Veteran No Benefits</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <label>Nickname</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentsAttendedACollegeOrUniversity__c</fullName>
        <description>Self-disclosed information from the Application form</description>
        <label>Parents Attended a College or University</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ParentsGraduated__c</fullName>
        <label>Parents Graduated</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related contact record for this student&apos;s attributes</description>
        <label>Student Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Students Attributes</relationshipLabel>
        <relationshipName>Students_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Attributes</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentAttributesToBanner__c.object
<CustomObject>
    <description>Control object for synchronization of Student Attributes with information in Banner</description>
    <fields>
        <fullName>CampusCodeOUT__c</fullName>
        <formula>text(StudentAttributes__r.Affiliation__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campus Code (OUT)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CitizenshipOUT__c</fullName>
        <formula>text( StudentAttributes__r.CitizenshipStatus__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Citizenship (OUT)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunityTypeOUT__c</fullName>
        <formula>text( StudentAttributes__r.CommunityType__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Community Type (OUT)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaritalStatusOUT__c</fullName>
        <formula>text( StudentAttributes__r.MaritalStatus__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Marital Status (OUT)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MilitaryStatusOUT__c</fullName>
        <formula>text( StudentAttributes__r.MilitaryStatus__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Military Status (OUT)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NicknameOUT__c</fullName>
        <formula>StudentAttributes__r.Nickname__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nickname (OUT)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentsAttendedCollegeOUT__c</fullName>
        <formula>text( StudentAttributes__r.ParentsAttendedACollegeOrUniversity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parents Attended College (OUT)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentsGraduatedCollegeOUT__c</fullName>
        <formula>text( StudentAttributes__r.ParentsGraduated__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parents Graduated College (OUT)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAttributes__c</fullName>
        <label>Student Attributes</label>
        <referenceTo>StudentAttributes__c</referenceTo>
        <relationshipLabel>Students Attributes To Banner</relationshipLabel>
        <relationshipName>StudentsAttributesToBanner</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student Attributes To Banner</label>
    <nameField>
        <displayFormat>SATB-{0}</displayFormat>
        <label>Student Attributes To Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students Attributes To Banner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestStudentAttributesUtility.cls
/*******************************************************************
 * Author Will Slade
 * Western Governors University 
 *
 * Created Date Aug 29, 2013 
 *
 * Test Trigger Utility for StudentAttributes Trigger processing
 *
 *******************************************************************/
 
 @isTest
 public with sharing class TestStudentAttributesUtility
 {
     private static testMethod void TestCreateSAToBanner()
     {
        AccountTestingUtility util = new AccountTestingUtility('test');
        util.save();

        Contact baggins = [SELECT Id, PIDM__c, FirstName, LastName FROM Contact WHERE LastName = 'Baggins' LIMIT 1];
        StudentAttributes__c testSA = new StudentAttributes__c(StudentContact__c = baggins.Id, ParentsAttendedACollegeOrUniversity__c = 'Yes',
                                                               ParentsGraduated__c = 'No', Nickname__c = 'CleverHobbitses', MilitaryStatus__c = 'Active Army Duty',
                                                               MaritalStatus__c = 'Divorced', CommunityType__c = 'Urban', CitizenshipStatus__c = 'U.S. Citizen',
                                                               Affiliation__c = 'WGU-TX');
        insert testSA;
        testSA.Nickname__c='test';
        Test.startTest();
            update testSA;
        Test.stopTest();  
        
        List<StudentAttributesToBanner__c> testSATBList = [SELECT Id, CampusCodeOUT__c, CitizenshipOUT__c, CommunityTypeOUT__c, MaritalStatusOUT__c, MilitaryStatusOUT__c,
                                                             NicknameOUT__c, ParentsAttendedCollegeOUT__c, ParentsGraduatedCollegeOUT__c, StudentAttributes__c
                                                             FROM StudentAttributesToBanner__c
                                                             WHERE StudentAttributes__c = :testSA.Id
                                                             LIMIT 5];
        System.assertEquals(testSATBList.size(), 1, 'Excess control records created - expected 1, found ' + testSATBList.size() );                                                             
        System.assertEquals(testSATBList[0].StudentAttributes__c,testSA.Id, 'Control record linked to incorrect Student Attributes record');
        System.assertEquals(testSATBList[0].CampusCodeOUT__c,testSA.Affiliation__c, 'Incorrect campus code control record' );
        System.assertEquals(testSATBList[0].CitizenshipOUT__c,testSA.CitizenshipStatus__c, 'Incorrect Citizenship Status on control record' );
        System.assertEquals(testSATBList[0].CommunityTypeOUT__c,testSA.CommunityType__c, 'Incorrect Community Type found on control record' );
        System.assertEquals(testSATBList[0].MaritalStatusOUT__c,testSA.MaritalStatus__c, 'Incorrect Marital Status found on control record' );
        System.assertEquals(testSATBList[0].MilitaryStatusOUT__c ,testSA.MilitaryStatus__c, 'Incorrect Military Status found on control record' );
        System.assertEquals(testSATBList[0].NicknameOUT__c,'test', 'Incorrect Nickname found on control record' ); 
        System.assertEquals(testSATBList[0].ParentsAttendedCollegeOUT__c,testSA.ParentsAttendedACollegeOrUniversity__c, 'Incorrect Parents College found on control record' );
        System.assertEquals(testSATBList[0].ParentsGraduatedCollegeOUT__c,testSA.ParentsGraduated__c, 'Incorrect Parents Graduation found on control record' );

     }
 }