src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>Student Identification number, also known as Banner ID.</description>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>StudentRecord</fullName>
        <active>true</active>
        <description>For non-Person Account Student Records</description>
        <label>StudentRecord</label>
    </recordTypes>
</CustomObject>

src/objects/StudentDisposition__c.object
<CustomObject>
    <description>Contains information about student disposition concerns. This object contains sensitive student information and should only be available to a limited number of profiles.</description>
    <fields>
        <fullName>AssessmentName__c</fullName>
        <label>Assessment Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Concerns</relationshipLabel>
        <relationshipName>StudentDispositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Concern</label>
    <nameField>
        <label>Concern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Concerns</pluralLabel>
    <recordTypes>
        <fullName>ArticulationConcern</fullName>
        <active>true</active>
        <description>Student Concern on Articulation</description>
        <label>Articulation Concern</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TaskStreamAssessment__c.object
<CustomObject>
    <description>Data for a Task Stream Assessment that a student is enrolled</description>
    <fields>
        <fullName>AssessmentCode__c</fullName>
        <label>Assessment Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssessmentIDKey__c</fullName>
        <description>Assessment ID Key from the Task Stream database table.</description>
        <externalId>true</externalId>
        <label>Assessment ID Key</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OverallStatus__c</fullName>
        <label>Overall Status</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Task_Stream_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Taskstream Assessment</label>
    <nameField>
        <label>Task Stream Assessment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taskstream Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TestStudentDispositionTrigger.cls
/*
Test class  for StudentDispositionTrigger
Author- Bhavadeep Raavi
*/

@isTest
private with sharing class TestStudentDispositionTrigger{
     
     private static testmethod void TestStudentDispositionTrigger(){
     
     // This code runs as the system user
     User testUser = [SELECT Id from User WHERE Profile.Name = 'Records User' AND isActive = true LIMIT 1];
      
     System.runAs(testUser)    {
     
     Test.startTest();
     
     ID studentContactRecordTypeId = [Select Id from RecordType where DeveloperName = 'StudentRecord' and SObjectType = 'Contact'].id;     
     Contact con = new Contact();
     con.RecordTypeId = studentContactRecordTypeId ;
     con.LastName='testCon';
     con.FirstName ='testFname';
     con.Email='test@test.com';
     con.StudentID__c ='000123456';
     con.pidm__c ='0000101';
     insert con;
     
     System.assertEquals(con.Email,'test@test.com');
     System.assertEquals(con.LastName,'testCon');
     
     ID sdRecordTypeId = [Select Id from RecordType where DeveloperName = 'ArticulationConcern' and SObjectType = 'StudentDisposition__c'].id;     
     StudentDisposition__c sd= new StudentDisposition__c();
     sd.RecordTypeId = sdRecordTypeId;
     sd.Name = 'test';
     sd.StudentID__c ='123456';
     sd.AssessmentName__c ='tsa test';
     insert sd;
     
     System.assertEquals(sd.Name,'test');
     System.assertEquals(sd.StudentID__c,'123456');
     
     TaskStreamAssessment__c tsa = new TaskStreamAssessment__c();
     tsa.Name = 'tsa test';
     tsa.PIDM__c ='0000101';
     tsa.AssessmentCode__c ='test code';
     tsa.Student__c = con.Id;
     tsa.AssessmentIDKey__c =12345;
     tsa.OverallStatus__c ='ns';
     insert tsa;
     
      
     Test.stopTest();
    }
  }
  
    private static testmethod void TestStudentDispositionTrigger1(){
     
     // This code runs as the system user
     User testUser = [SELECT Id from User WHERE Profile.Name = 'Records User' AND isActive = true LIMIT 1];
      
     System.runAs(testUser)    {
     
     Test.startTest();
     
     ID studentContactRecordTypeId = [Select Id from RecordType where DeveloperName = 'StudentRecord' and SObjectType = 'Contact'].id;     
     Contact con = new Contact();
     con.RecordTypeId = studentContactRecordTypeId ;
     con.LastName='testCon';
     con.FirstName ='testFname';
     con.Email='test@test.com';
     con.StudentID__c ='000123456';
     con.pidm__c ='0000102';
     insert con;
     
     System.assertEquals(con.Email,'test@test.com');
     System.assertEquals(con.LastName,'testCon');
     
     ID sdRecordTypeId = [Select Id from RecordType where DeveloperName = 'ArticulationConcern' and SObjectType = 'StudentDisposition__c'].id;     
     StudentDisposition__c sd= new StudentDisposition__c();
     sd.RecordTypeId = sdRecordTypeId;
     sd.Name = 'test';
     sd.StudentID__c ='000123456';
     sd.AssessmentName__c ='tsa test';
     insert sd;
    
     
     Test.stopTest();
    }
  }
}