src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>StatusDate__c</fullName>
        <label>Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TermCode__c</fullName>
        <description>The current TERM Code year + month</description>
        <formula>TEXT(YEAR(TermStartDate__c))  &amp; 
IF(MONTH(TermStartDate__c) &lt; 10, &apos;0&apos;, NULL) &amp;
TEXT(Month( TermStartDate__c ))</formula>
        <inlineHelpText>Term Code</inlineHelpText>
        <label>Term Code</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StudentCompletionTask__c.object
<CustomObject>
    <description>Custom object to manage student assessments, requirements, and zero CU tasks by recordtype.</description>
    <fields>
        <fullName>AssessmentStatus__c</fullName>
        <label>Assessment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Attempted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Satisfied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement Met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdraw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Recheck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CompetencyUnits__c</fullName>
        <label>Competency Units</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StatusDate__c</fullName>
        <label>Status Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>StudentAssessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TermCode__c</fullName>
        <label>Term Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUCourseCompletionTask__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Course Completion Task</label>
        <referenceTo>WGUCourseCompletionTask__c</referenceTo>
        <relationshipName>StudentCourseCompletionTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Completion Task</label>
    <nameField>
        <label>Student Task Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Completion Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentCourse__c.object
<CustomObject>
    <description>Represents a course that a student may take at WGU. Multiple Assessments or Tasks may be required to complete the course.</description>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the course (Completed,Enrolled,Planned).</description>
        <inlineHelpText>The status of the course (Completed,Enrolled,Planned).</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InProgress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentDegreePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Degree Plan</label>
        <referenceTo>StudentDegreePlans__c</referenceTo>
        <relationshipLabel>Student Courses</relationshipLabel>
        <relationshipName>StudentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentTerm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Term this course instance is scheduled</description>
        <label>Student Term</label>
        <referenceTo>StudentTerm__c</referenceTo>
        <relationshipLabel>Student Course</relationshipLabel>
        <relationshipName>StudentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Course</relationshipLabel>
        <relationshipName>StudentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Course</label>
    <nameField>
        <label>Student Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentDegreePlans__c.object
<CustomObject>
    <description>Student instance of a WGU degree plan, provisioned from the WGUDegreeProgram__c object.</description>
    <fields>
        <fullName>CurrentPlan__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only one degree plan can be current.</inlineHelpText>
        <label>Current Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Degree Plans</relationshipLabel>
        <relationshipName>StudentDegreePlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Degree Plan</label>
    <nameField>
        <label>Student Degree Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Degree Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentTerm__c.object
<CustomObject>
    <description>Instance of a student period of time, using recordtype to designate between academic terms, term breaks, withdraw/drops, etc.</description>
    <fields>
        <fullName>CompetencyUnits__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the summed value of all CUs in courses assigned to the term.</description>
        <label>Competency Units</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The starting date of the term. WGU Terms are normally 6 months but it is possible that one may be smaller because it is a term break.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StudentDegreePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Student&apos;s Degree Plan instance this term is schedule within.</description>
        <label>Student Degree Plan</label>
        <referenceTo>StudentDegreePlans__c</referenceTo>
        <relationshipLabel>Student Terms</relationshipLabel>
        <relationshipName>StudentTerms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Terms</relationshipLabel>
        <relationshipName>myTerms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Term</label>
    <nameField>
        <label>Student Term Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>CompetencyUnits__c</fullName>
        <label>Competency Units</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PAMSID__c</fullName>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseCompletionTask__c.object
<CustomObject>
    <description>Custom object to manage template definitions for course assessments, requirements, or tasks. Student instances of assessments are managed via the StudentCourseCompletionTask__c object.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <description>The Unique ID represented as a combination of fields from PAMS. type-courseversionid-assessment.</description>
        <label>PAMS ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Course that this task is a requirement to complete.</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>WGU Course Completion Task</relationshipLabel>
        <relationshipName>WGUCourseCompletionTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course Completion Task</label>
    <nameField>
        <label>WGU Course Task Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Completion Task</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestFDPUtilities.cls
@IsTest
public class TestFDPUtilities {

    @IsTest
    static void formatDateLongMonthYearTest() {
        Date myDate = Date.newInstance(2010, 5, 1);
        String output = FDPUtilities.formatDateLongMonthYear(myDate);
        System.assertEquals('May 2010',output);
    }

    @isTest
    static void testFormatDateLong() {
      Date myDate = Date.newInstance(2010,5,1);
      String output = FDPUtilities.formatDateLong(myDate);
      System.assertEquals('May 1, 2010',output);
    }

    @isTest
    static void getidfromcoursepamsid(){
        FDPUtilities.PAMSMappings mapping=new FDPUtilities.PAMSMappings();
        mapping.getidfromcoursepamsid(1232);
        mapping.getidfromprogrampamsid(1232);

    }

    @isTest
    static void testBatchdelete(){
        FDPUtilities.batchdelete();

    }

    @isTest
    static void testFormatCurrency() {
        System.assertEquals(FDPUtilities.formatCurrency(5000.00,0),'$5,000');
        System.assertEquals(FDPUtilities.formatCurrency(100.0,0),'$100');
        System.assertEquals(FDPUtilities.formatCurrency(1000000.0,0),'$1,000,000');
        System.assertEquals(FDPUtilities.formatCurrency(10000000.0,0),'$10,000,000');
    }

    @isTest
    static void testGetTermEndDateByCode() {
        Date one=FDPUtilities.getTermEndDateByCode('201205');
        System.assertEquals(31,one.day());
    }

    //@isTest
     static void testGetPlanStartDate() {
         FDPTestingUtilities utility = new FDPTestingUtilities();
        Date one=FDPUtilities.getPlanStartDate(utility.plan.id);
        System.assertEquals(utility.terms[0].startDate__C,one);

    }

    //@IsTest
     static void testMappingCompletedCourses(){
            FDPTestingUtilities utility = new FDPTestingUtilities();
            WGUCourseCompletionTask__c task1=utility.generateWGUCourseCompletionTask(utility.definitions[0]);
             WGUCourseCompletionTask__c task2=utility.generateWGUCourseCompletionTask(utility.definitions[0]);
             WGUCourseCompletionTask__c task3=utility.generateWGUCourseCompletionTask(utility.definitions[1]);
            StudentCompletionTask__c one=new StudentCompletionTask__c();
            one.WGUCourseCompletionTask__c=task1.id;
            one.StatusDate__c=Date.today();
            one.Student__c=utility.contact.id;
            one.TermCode__c='201004';
            one.AssessmentStatus__c = 'Passed';
            insert one;
               StudentCompletionTask__c three=new StudentCompletionTask__c();
            three.WGUCourseCompletionTask__c=task3.id;
            three.Student__c=utility.contact.id;
              three.StatusDate__c=Date.today();
               three.TermCode__c='201004';
               three.AssessmentStatus__c = 'Passed';
            insert three;
           System.assertequals('Planned',utility.courses[0].Status__c);
             System.assertequals('Planned',utility.courses[1].Status__c);
            String course0Id = utility.courses[0].Id;
            String course1Id = utility.courses[1].Id;
            System.debug('course0Id: ' + course0Id);
            System.debug('course1Id: ' + course1Id);

            StudentCourse__c course1= [select Status__c from StudentCourse__c where id= :course0Id];
            System.assertequals('Planned',course1.Status__c);
             List<StudentCourse__c> emptyCourseList= [select Status__c from StudentCourse__c where id= :course1Id];
            System.assertEquals(1,emptyCourseList.size());
            List<StudentCourse__c> completedCourses = [select Status__c from StudentCourse__c where id = :utility.currentPlanCourses[1].Id];
            System.assertequals('Completed',completedCourses[0].Status__c);

            StudentCompletionTask__c two=new StudentCompletionTask__c();
            two.WGUCourseCompletionTask__c=task2.id;
             two.Student__c=utility.contact.id;
              two.StatusDate__c=Date.today();
               two.TermCode__c='201004';
               two.AssessmentStatus__c = 'Passed';
            insert two;
              
              emptyCourseList= [select status__C from StudentCourse__C where id= :utility.courses[0].id];
              System.assertEquals(1,emptyCourseList.size());
            completedCourses = [select Status__c from StudentCourse__c where id = :utility.currentPlanCourses[0].Id];
            System.assertequals('Completed',completedCourses[0].Status__c);
    }

    //@IsTest
      static void testMappingCompletedCoursesWithNonmappedCourse(){
            FDPTestingUtilities utility = new FDPTestingUtilities();
            WGUCourseCompletionTask__c task1=utility.generateWGUCourseCompletionTask(utility.definitions[0]);
             WGUCourseCompletionTask__c task2=utility.generateWGUCourseCompletionTask(utility.definitions[0]);
             WGUCourseCompletionTask__c task3=utility.generateWGUCourseCompletionTask(utility.definitions[1]);
            StudentCompletionTask__c one=new StudentCompletionTask__c();
            one.WGUCourseCompletionTask__c=task1.id;
            one.StatusDate__c=Date.today();
            one.Student__c=utility.contact.id;
            one.AssessmentStatus__c = 'Passed';
            insert one;
               StudentCompletionTask__c three=new StudentCompletionTask__c();
            three.WGUCourseCompletionTask__c=task3.id;
            three.Student__c=utility.contact.id;
              three.StatusDate__c=Date.today();
              three.AssessmentStatus__c = 'Passed';
            insert three;
            
            StudentCompletionTask__c two=new StudentCompletionTask__c();
            two.WGUCourseCompletionTask__c=task2.id;
             two.Student__c=utility.contact.id;
              two.StatusDate__c=Date.today();
              two.AssessmentStatus__c = 'Passed';
            insert two;
            WGUCourse__c definition = new WGUCourse__c();
            definition.name = 'test course that not mapped';
            definition.competencyunits__c = 5;
            definition.PAMSID__c = Math.random();
            insert definition;
            WGUCourseCompletionTask__c tie = new WGUCourseCompletionTask__c();
            tie.WGUCourse__c = definition.id;
            insert tie;
           
            StudentCompletionTask__c four=new StudentCompletionTask__c();
            four.WGUCourseCompletionTask__c=tie.id;
            four.Student__c=utility.contact.id;
            four.StatusDate__c=Date.today();
            four.TermCode__c='199812';
            four.AssessmentStatus__c = 'Passed';
            insert four;
          
            List<StudentCourse__c> created= [select StudentTerm__c,Status__c from StudentCourse__C where name='test course that not mapped'];
            System.assertEquals(1,created.size());
            System.assertequals('Completed',created[0].Status__c);
            List<StudentTerm__c> termcreated= [select name,StudentDegreePlan__c from Studentterm__C where id=:created[0].StudentTerm__c];
                System.assertequals('199812',termcreated[0].name);
                StudentDegreePlans__c plan=[select id from StudentDegreePlans__c where CurrentPlan__c = true];
                System.assertequals(plan.id,termcreated[0].StudentDegreePlan__c);
            List<StudentCourse__c>  emptyCourseList= [select status__C from StudentCourse__C where id= :utility.courses[0].id];
            System.assertEquals(1,emptyCourseList.size());
            List<StudentCourse__c> completedCourses = [select Status__c from StudentCourse__c where id = :utility.currentPlanCourses[0].Id];
            System.assertequals('Completed',completedCourses[0].Status__c);
    }

    //@isTest
    //TODO remove all references to FDPTestingUtilities and delete the class
     static void testClonePlan(){
      FDPTestingUtilities util = new FDPTestingUtilities();
      StudentDegreePlans__C plan=FDPUtilities.cloneStudentDegreePlan(util.plan.id,  'test');
      System.debug(plan);
      System.assert(plan.name=='test');
      System.assert(plan.id!=null);
     }
}