src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Student Status,
TB – Term Break
AS – Active Student
AP - Applied
DD – Dropped – Do Not Contact
DR - Dropped
HD - Hold
IG – Inactive due to Graduation
IN - Intake
NA – Not Admitted
ND – Non-Degree
NS – Never Start
WA – Withdrawn Admitted
WE – Withdrawn Enrolled
WI - Withdrawn
XX – Duplicate – Do Not Use</description>
        <inlineHelpText>Indicate the student&apos;s current status at WGU.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WGUDegreeProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for wguProgram</description>
        <label>WGU Degree Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/StudentCourseRegistration__c.object
<CustomObject>
    <description>This is an object for pulling current term registration  information from WGUFDP. No FDP user should have direct access to this Object,</description>
    <fields>
        <fullName>EngagementNotedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who noted the student engagement with the course.</description>
        <label>Engagement Noted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>StudentCourseRegistrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EngagementNotedDate__c</fullName>
        <description>Date and time when student engagement with the course was noted.</description>
        <label>Engagement Noted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IsEngaged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes whether the student is marked as being currently engaged with the course.</description>
        <label>Is Engaged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The student associated with this registration. (used to speed up queries on this table)</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>StudentCourseRegistrations</relationshipLabel>
        <relationshipName>StudentCourseRegistrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookout for wgucourse.</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>Student Course Registrations</relationshipLabel>
        <relationshipName>StudentCourseRegistrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Course Registration</label>
    <nameField>
        <label>StudentCourseRegistration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Course Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentCourseVersion__c.object
<CustomObject>
    <description>The version of a course that the student is set to take (or has taken).</description>
    <fields>
        <fullName>CompletedDate__c</fullName>
        <description>The date when the course was completed</description>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The hard and fast status on whether the course is completed or not.</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InProgress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentCourseRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Course Registration</label>
        <referenceTo>StudentCourseRegistration__c</referenceTo>
        <relationshipLabel>Student Course Versions</relationshipLabel>
        <relationshipName>StudentCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Course Version</relationshipLabel>
        <relationshipName>StudentCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The version of the Course that this student is taking.</description>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Student Course Versions</relationshipLabel>
        <relationshipName>StudentCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Course Version</label>
    <nameField>
        <label>Studentid+&apos;-&apos;+Wgucourseid</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseInProgram__c.object
<CustomObject>
    <description>A many to many mapping that assigns which course are required to accomplish any degree program.</description>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipName>PAMS_Course_In_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>WGU Course In Programs</relationshipLabel>
        <relationshipName>WGUCourseInPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course In Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WGU Course In Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The course that this course version belongs to</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>WGU Course Versions</relationshipLabel>
        <relationshipName>WGUCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StudentCourseVersionUtility.cls
/*
* Utility class for the StudentCourseVersionNameTrigger
* Created by Katarina Melki 4/10/2013 
*   Edit by Will Slade 2/18/14 for program change course version updates
*	Edit by Yemeng Zhu Mar 2014 "Pass" no longer change the CaseLoad of this course after we switch to StudentAcademicCourse.
*/
public class StudentCourseVersionUtility
{
    //Clears Student Course Engagement information from StudentCourseRegistration__c when Completed__c is set to true.
    public static void removeStudentEngagement(List<StudentCourseVersion__c> triggernew, List<StudentCourseVersion__c> triggerold)
    {
        List<StudentCourseRegistration__c> CourseRegistrations=new List<StudentCourseRegistration__c>();
        Map<Id, boolean> mapOldCompleted=new Map<Id, boolean>();
      //  List<StudentCourseVersion__c> completes=new List<StudentCourseVersion__c>();
        
        for(StudentCourseVersion__c oldCourseVersion: triggerold)
        {
            mapOldCompleted.put(oldCourseVersion.Id, oldCourseVersion.Completed__c);
        }
        
        for(StudentCourseVersion__c CourseVersion: triggernew)
        {
            if (CourseVersion.Completed__c && CourseVersion.CompletedDate__c>date.today().addDays(-1) && !mapOldCompleted.get(CourseVersion.Id) && CourseVersion.StudentCourseRegistration__c!=null)
            {
                CourseRegistrations.add(new StudentCourseRegistration__c(Id=CourseVersion.StudentCourseRegistration__c, IsEngaged__c=false, EngagementNotedBy__c=null, EngagementNotedDate__c=null));
                system.debug(CourseVersion);
            }
         /*   if(CourseVersion.Completed__c||CourseVersion.Status__c =='Completed')
            {
                completes.add(CourseVersion);
            }*/
        }
        
        update CourseRegistrations;
      //  CourseMentorStudentAssignmentUtility.removeAssignmentsForPassedCourses(completes,'Pass');
    }

///////////////////////////// Begin Program Change Course Section ///////////////////////////////////

    public static void checkValidCourses(String degreeUpdatedListJSON)
    {
        if (Limits.getFutureCalls() > 3 || System.isFuture())
        {
            processCheckValidCourses(degreeUpdatedListJSON);
        }
        else
        {
            asyncCheckValidCourses(degreeUpdatedListJSON);
        }
    }
    
    @future
    public static void asyncCheckValidCourses(String degreeUpdatedListJSON)
    {
        processCheckValidCourses(degreeUpdatedListJSON);
    }

    public static void processCheckValidCourses(String degreeUpdatedListJSON)
    {
        List<Contact> degreeUpdatedList = (List<Contact>) JSON.deserialize(degreeUpdatedListJSON, List<Contact>.class);
        List<Id> wguDegreePrograms = new List<Id>(); 
        List<Id> contactIds = new List<Id>();       
        List<WGUCourseInProgram__c> wguCourseInPrograms = new List<WGUCourseInProgram__c>();
        List<StudentCourseVersion__c> fullSCVList = new List<StudentCourseVersion__c>();
        Set<StudentCourseVersion__c> deleteSet = new Set<StudentCourseVersion__c>();
        List<StudentCourseVersion__c> deleteList = new List<StudentCourseVersion__c>();        
        Set<Id> scvSet = new Set<Id>();
        Map<Id, Id> studentToDPMap = new Map<Id, Id>();        
        Map<Id, Id> cipToDPMap = new Map<Id, Id>();
        Map<Id, Id> cipToCourseMap = new Map<Id, Id>();
        Map<Id, Id> wcvToWcMap = new Map<Id, Id>();
        Map<Id, Id> scvToStudentMap = new Map<Id, Id>();
        Map<Id, Id> scvToCourseMap = new Map<Id, Id>();
        Map<Id, Set<Id>> studentToCourseListMap = new Map<Id, Set<Id>>();
        
        //Build map linking students to their new degree plans
        //Build lists of degree programs and contact ids
        for (Contact degreeUpdated : degreeUpdatedList)
        {                
            wguDegreePrograms.add(degreeUpdated.WGUDegreeProgram__c);
            studentToDPMap.put(degreeUpdated.Id, degreeUpdated.WGUDegreeProgram__c);
            contactIds.add(degreeUpdated.Id);
        }
        
        //Build list of all student course version records for contacts in trigger
        fullSCVList = [SELECT Id, Student__c, WGUCourseVersion__r.WGUCourse__c
                       FROM StudentCourseVersion__c
                       WHERE Student__c IN :contactIds];                       
        
        //Build list of all WGU Courses in Program for degree programs in list                      
        wguCourseInPrograms = [SELECT Id, Program__c, Course__c
                               FROM WGUCourseInProgram__c
                               WHERE Program__c IN :wguDegreePrograms];
        
        //Build map for course in program to degree program
        //Build map for course in program to WGU course                       
        for (WGUCourseInProgram__c wcip : wguCourseInPrograms)
        {             
            cipToDPMap.put(wcip.Id, wcip.Program__c);
            cipToCourseMap.put(wcip.Id, wcip.Course__c);
        }
        
        //Build map for student course version to contact
        //Build map for student course version to WGU course
        for (StudentCourseVersion__c scv : fullSCVList)
        {              
            scvToStudentMap.put(scv.Id, scv.Student__c);
            scvToCourseMap.put(scv.Id, scv.WGUCourseVersion__r.WGUCourse__c);
        }
        
        scvSet = scvToStudentMap.keySet();
        
        //For each contact, build a list of WGU courses in their current program and add it to a map
        for (Contact degreeUpdated : degreeUpdatedList)
        {      
            Set<Id> thisCourseSet = new Set<Id>();
            
            for (Id cipId : cipToDPMap.keySet())
            {             
                if (cipToDPMap.get(cipId) == studentToDPMap.get(degreeUpdated.Id))
                {               
                    thisCourseSet.add(cipToCourseMap.get(cipId));
                }
            }
            
            studentToCourseListMap.put(degreeUpdated.Id, thisCourseSet);
        }
        
        //For each student course version, verify the corresponding WGU course exists in the list of the map for the student
        for (StudentCourseVersion__c scv : fullSCVList)
        {      
            Set<Id> thisCourseSet = studentToCourseListMap.get(scvToStudentMap.get(scv.Id));
            
            for (Id thisCourse : thisCourseSet)
            {          
                if (!thisCourseSet.contains(scvToCourseMap.get(scv.Id)) && !deleteSet.contains(scv))
                {
                    deleteSet.add(scv);               
                    deleteList.add(scv);
                }
            }          
        }
        
        delete deleteList;                          
    }
}

////////////////////////////// End Program Change Course Section ////////////////////////////////////