src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>Identifier referencing this contact&apos;s Sungard Banner UUID, which is the key value used internally by SunGard Banner for  referential integrity</description>
        <externalId>true</externalId>
        <inlineHelpText>Specify the numerical identifier of this contact&apos;s SunGard Banner record identifier</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentID__c</fullName>
        <description>Student Identification number, also known as Banner ID.</description>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentRiskScore__c</fullName>
        <label>Student Risk Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/WGUStudentNote__c.object
<CustomObject>
    <description>This object stores notes about a student&apos;s interaction with service personnel such as mentors, etc.</description>
    <fields>
        <fullName>AuthorPidm__c</fullName>
        <label>Author Pidm</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user pidm</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WGUStudentNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShortText__c</fullName>
        <description>Field to store a portion of the Text__c field data in plain text</description>
        <label>ShortText</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <description>The contact record for this student</description>
        <inlineHelpText>The student associated with this note.</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>WGUStudentNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>The basic rich text area for details of this note</description>
        <inlineHelpText>Please enter any details for this note.</inlineHelpText>
        <label>Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Level 1 Note Type</description>
        <inlineHelpText>This note type.</inlineHelpText>
        <label>Note Type</label>
        <picklist>
            <picklistValues>
                <fullName>Live Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voicemail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instant Message (IM) / Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webinar Attendance Noted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outreach (CM only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration (MGR only)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WGUCreationDateTime__c</fullName>
        <description>This holds the date time stamp of a note.</description>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <label>WGU Student Note</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGUStudentNotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WGUStudentPerformanceSurvey__c.object
<CustomObject>
    <description>Answers to student performance survey questions, completed by student mentors via the student notes UI. NOTE: The Labels are different than the Object Name to match verbiage of the Notes.</description>
    <fields>
        <fullName>EvidenceOfAcademicActivity__c</fullName>
        <inlineHelpText>What evidence is present that this student has been academically active since the previous call?</inlineHelpText>
        <label>Evidence Of Academic Activity</label>
        <picklist>
            <picklistValues>
                <fullName>Engaged in New Student Protocols</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged in a Learning Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilized a Community Resource</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended a Seminar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Met with a Course Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Took a Pre-Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled an Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Took and Failed an Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Took and Passed an Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted a TaskStream Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revised a TaskStream Task</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Evidence is Present</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>GoalPerformanceSinceLastCall__c</fullName>
        <inlineHelpText>How has student performed against academic goals set in the last call?</inlineHelpText>
        <label>Goal Performance Since Last Call</label>
        <picklist>
            <picklistValues>
                <fullName>Yes - 100%</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No - 0%</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Student (Contact) whose WGUStudentNote__c record is associated with this Performance Survey Record (1:1)</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>WGUStudentPerformanceSurveys</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUStudentNote__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WGUStudentNote</label>
        <referenceTo>WGUStudentNote__c</referenceTo>
        <relationshipName>WGUStudentPerformanceSurveys</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Student Performance Question</label>
    <nameField>
        <label>Note Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Performance Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestNoteController.cls
/**
 *  Author Paul Stay and Paul Coleman
 *  Test the WGU Student Notes class, controller, and page.
 *
 *  Date: Oct 30 2012, 1147 hrs
 *  Revised: (security audit compliance: with sharing) 
 *
 */
@isTest
private with sharing class TestNoteController {

    private static testMethod void getStudentJSONByContactId() {
        // Create a new Student
        Contact studentContact = TestStudentUser.getTestStudentContact();   
        
        // Test method
        Test.startTest();
            String json = NotesController.getStudentJSONByContactId(studentContact.Id);
            System.debug('  ' + json);
            System.assert(json.length() > 0);
            
            // Test for a null contactId
            try {
                json = NotesController.getStudentJSONByContactId(null);
            } catch (StudentException e){
                System.assert(true);
            }
            
        Test.stopTest();
        
    }
    
    private static testMethod void getStudentJSONByStudentWGUId() {
        // Create a new Student
        Contact studentContact = TestStudentUser.getTestStudentContact();  
        
        if ( studentContact.StudentID__c == null ) {
         studentContact.StudentId__c = '0012334567';
         update studentContact;
        }
        
        // Test method
        Test.startTest();
            String json = NotesController.getStudentJSONByStudentWGUId(studentContact.StudentId__c);
            System.debug('  ' + json);
            System.assert(json.length() > 0);
            
            // Test for a null contactId
            try {
                json = NotesController.getStudentJSONByStudentWGUId(null);
            } catch (StudentException e){
                System.assert(true);
            }
            
        Test.stopTest();
                
    }
    
    private static testMethod void getStudentJSON() {
        // Create a new Student
        Contact studentContact = TestStudentUser.getTestStudentContact();
        
        Test.startTest();
            String json = NotesController.getStudentJSON( studentContact.PIDM__C, true);
            System.assert(json.length() > 0);
            
            json = NotesController.getStudentJSON(studentContact.AccountId, false);
            System.assert(json.contains(studentContact.AccountId));
        Test.stopTest();        
    }

    private static testMethod void getNoteJSONById() {
        Contact studentContact = TestStudentUser.getTestStudentContact();  

        ID mentorProfileId = [SELECT id from Profile where name = 'Mentor'].ID;
        User mentorUser = new User(LastName='Mentor',FirstName='Standard',pidm__c='m198765',Username='a@wgu.edu', Email='a@wgu.edu', Alias='a', CommunityNickname='a', TimeZoneSidKey='GMT'
        , LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=mentorProfileId , LanguageLocaleKey='en_US');
        insert mentorUser ;
        
        WGUStudentNote__c note1 = getTestNote(mentorUser, studentContact, '1');
        
        insert note1; 
        
        System.runAs(mentorUser) {
            Test.startTest();
                String json = NotesController.getNoteJSONById(note1.id);
                System.assert(json.contains('short text'));
            Test.stopTest();
        }
    } 

    private static testMethod void saveNoteJSON(){
        
        Contact studentContact = TestStudentUser.getTestStudentContact();  
        studentContact.StudentRiskScore__c = 3;
        update studentContact;       
        ID mentorProfileId = [SELECT id from Profile where name = 'Mentor'].ID;
        User mentorUser = new User(LastName='Mentor',FirstName='Standard',pidm__c='m198765',Username='a@wgu.edu', Email='a@wgu.edu', Alias='a', CommunityNickname='a', TimeZoneSidKey='GMT'
        , LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=mentorProfileId , LanguageLocaleKey='en_US');
        insert mentorUser ;
        
        WGUStudentNote__c note = getTestNote(mentorUser,studentContact, '1');
        note.Text__c = EncodingUtil.base64Encode(Blob.ValueOf(note.text__c));
        
        WGUStudentNote__c note2 = getTestNote(mentorUser, studentContact, '2');
        insert note2;
        
        note2.Text__c = EncodingUtil.base64Encode(Blob.ValueOf(note.text__c));        
        
        String jsonStr = JSON.serialize(note);
        String jsonStr2 =  JSON.serialize(note2);
        
        Test.startTest();
            String jsonNote = NotesController.saveNoteJSON(jsonStr);
            System.assert(jsonNote.contains('m198765'));
        
            String updateNote = NotesController.saveNoteJSON(jsonStr2);
            System.assert(updateNote.contains('Subject line2'));
        Test.stopTest();
                
    }
    
    private static testMethod void getNotesJSONByOffset() {
        
        Contact studentContact = TestStudentUser.getTestStudentContact();  

        ID mentorProfileId = [SELECT id from Profile where name = 'Mentor'].ID;
        User mentorUser = new User(LastName='Mentor',FirstName='Standard',pidm__c='m198765',Username='a@wgu.edu', Email='a@wgu.edu', Alias='a', CommunityNickname='a', TimeZoneSidKey='GMT'
        , LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=mentorProfileId , LanguageLocaleKey='en_US');
        insert mentorUser ;
        
        List<WguStudentNote__c> noteList = new List<WguStudentNote__c>();
        for(Integer i=0; i < 60; i++){
            WGUStudentNote__c note = getTestNote(mentorUser, studentContact, i.format());
            noteList.add(note);
        }
        insert noteList;
        
        Test.startTest();
            // First test the count
            Integer count = NotesController.getNotesCountByContactId(studentContact.Id);
            System.debug('Motherload    -----> Note count is ' + count);
            System.assert(count> 50);
        
            String jsonStr = NotesController.getNotesJSONByOffset(studentContact.Id, 0);
            System.assert(jsonStr.contains('line49'));
            
            jsonStr = NotesController.getNotesJSONByOffset(studentContact.Id, 50);
            System.assert(jsonStr.contains('isDone'));
        Test.stopTest();
    }

    private static testMethod void nonStaticMethods(){
        
        Contact studentContact = TestStudentUser.getTestStudentContact(); 
        
        if ( studentContact.StudentID__c == null ) {
         studentContact.StudentId__c = '0012334567';
         update studentContact;
        }
        
        PageReference pageRef = new PageReference('/apex/Notes?accountId=' + studentContact.Id);
        test.setCurrentPage(pageRef);
        ApexPages.StandardController stdController = new ApexPages.StandardController(new WGUStudentNote__c());
        NotesController controller = new NotesController(stdController);        
        
        Test.startTest();
            
            String jsonStr = controller.getNoteSubTypeMetaJSON();
            System.assert(jsonStr.contains('controllerName'));

            jsonStr = controller.getNoteTypeJSON();
            System.assert(jsonStr.contains('name'));
             
            jsonStr = controller.getActionSubTypeMetaJSON();
            System.assert(jsonStr.contains('controllerName'));

            jsonStr = controller.getActionTypeJSON();
            System.assert(jsonStr.contains('name'));
            
            jsonStr = controller.getNoteTypeFilterJSON();
            System.assert(jsonStr.length() > 0);

            jsonStr = controller.getIE8SubHeader();
            System.assert(jsonStr.length() == 0);

            jsonStr = controller.getIE8Header();
            System.assert(jsonStr.length() == 0);

            jsonStr = controller.getIE8Footer();
            System.assert(jsonStr.length() == 0);

            jsonStr = controller.getLt();
            System.assert(jsonStr.length() > 0);

            jsonStr = controller.getGt();
            System.assert(jsonStr.length() > 0);

        Test.stopTest();
    } 
    
    private static testMethod void getPerformanceSurveyJSONByOffsetAndSave(){

        Contact studentContact = TestStudentUser.getTestStudentContact(); 

        ID mentorProfileId = [SELECT id from Profile where name = 'Mentor'].ID;
        User mentorUser = new User(LastName='Mentor',FirstName='Standard',pidm__c='m198765',Username='a@wgu.edu', Email='a@wgu.edu', Alias='a', CommunityNickname='a', TimeZoneSidKey='GMT'
        , LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=mentorProfileId , LanguageLocaleKey='en_US');
        insert mentorUser ;
        
        WGUStudentNote__c note = getTestNote(mentorUser, studentContact, '1');
        insert note;
        
        WGUStudentPerformanceSurvey__c survey = new WGUStudentPerformanceSurvey__c(); 
        survey.EvidenceOfAcademicActivity__c = 'Yes - 100%';
        survey.GoalPerformanceSinceLastCall__c = 'Attended a Seminar';
        survey.Name = 'Testing Note';
        survey.Student__c = studentContact.Id;
        survey.WGUStudentNote__c = note.Id;
        
        Test.startTest();
            String surveyJSON = NotesController.saveSurveyJSON( JSON.serialize( survey ) ); //INSERT
            System.assert( surveyJSON.contains( '"Id":"'), 'Survey Id NOT Present after save' );
            surveyJSON = NotesController.saveSurveyJSON( JSON.serialize( [SELECT id,EvidenceOfAcademicActivity__c,GoalPerformanceSinceLastCall__c,Name,Student__c,WGUStudentNote__c FROM WGUStudentPerformanceSurvey__c LIMIT 1][0] ) ); //UPDATE
            System.assert( NotesController.getPerformanceSurveyJSONByOffset(studentContact.Id,0).contains('"count":1,'), 'Survey fetch returned no records' );
        Test.stopTest();
    } 
        
    private static WGUStudentNote__c getTestNote(User mentorUser, Contact student, String indexNumber) {
        WGUStudentNote__c note1 = new WGUStudentNote__c(Student__c=student.Id, AuthorPidm__c=mentorUser.PIDM__c, WGUCreationDateTime__c=Date.today(), 
            Type__c='Live Call', PIDM__C=student.PIDM__c, ShortText__c='short text',
            Name='Subject line' + indexNumber, Text__c='This is some text', Author__c=mentorUser.id);
        return note1;
    }
}