src/objects/CourseArticle__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>ArticleType__c</fullName>
        <label>Article Type</label>
        <picklist>
            <picklistValues>
                <fullName>Welcome Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Getting Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Resource Navigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course At-a-Glance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RichTextArea__c</fullName>
        <label>Rich Text Area</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Course Article</label>
    <pluralLabel>Course Articles</pluralLabel>
</CustomObject>

src/objects/KBCourseManagement__c.object
<CustomObject>
    <description>This is a junction object from WGU Courses to Mentor.
This is being used for assignment of Course(s) the Community Specialist will be assigned to enter in KB for.</description>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipName>CMKB_CourseManagment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mentor__c</fullName>
        <label>Mentor</label>
        <referenceTo>Mentor__c</referenceTo>
        <relationshipName>CMKBCourseManagement</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>KB Course Management</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KB Course Management</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KnowledgeBaseReporting__c.object
<CustomObject>
    <description>This object is used to report on KB.</description>
    <fields>
        <fullName>ArticleType__c</fullName>
        <description>Course Article Custom Field pick-list.  Prevent upkeep of pick-list here.</description>
        <label>Article Type</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Article version id&apos;s from knowledge base (kav objects)</description>
        <externalId>true</externalId>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Knowledge Base Reporting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>KB Reporting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Base Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KnowledgeBaseWguCourseVersionLink__c.object
<CustomObject>
    <description>Junction object between a Knowledge Article Reporting (Knowledge Article) and Course Versions</description>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <externalId>true</externalId>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KnowledgeBaseReporting__c</fullName>
        <label>Knowledge Base Reporting</label>
        <referenceTo>KnowledgeBaseReporting__c</referenceTo>
        <relationshipLabel>WGU Course Version</relationshipLabel>
        <relationshipName>Knowledge_Article_Course_Version_Link</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MajorVersion__c</fullName>
        <formula>WGUCourseVersion__r.MajorVersion__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Major Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Knowledge Base Reporting</relationshipLabel>
        <relationshipName>Knowledge_Article_Course_Version_Link</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Knowledge Base WGU Course Version Link</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Knowledge Base WGU Course Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Base WGU Course Version Link</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The User with a mentor role for this record</description>
        <inlineHelpText>The user that has these attributes</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Student_Mentors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>MajorVersion__c</fullName>
        <label>Major Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <fields>
        <fullName>MajorVersion__c</fullName>
        <description>The major version of the course</description>
        <label>Major Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The course that this course version belongs to</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>WGU Course Versions</relationshipLabel>
        <relationshipName>WGUCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>title__c</fullName>
        <label>title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseArticleEditorController.cls
/*
*Author John Chan
*Slalom
*Refactor to include Add and Edit articles to one location
*@4/9/13 add delete for draft articles
*@4/25/13 add validation for rich text field, and requiring course association when creating an article
*@5/7/13 - Update to global to work within iframes/console for remote actions
*/
global with sharing class CourseArticleEditorController {
    
    public enum EditorType {
        Create,
        Edit
    }
    
    public String subHeaderTitle { get; private set; }
    public String displayProperty { get; private set; }
    
    public transient Blob uploadFileContents {get;set;}
    public transient Integer uploadFileSize { get;set; }
    public String uploadContentType { get;set; }
    public String uploadFileName { get;set; }
    public String uploadFileTitle { get; set; }
    public CourseArticle__kav courseArticle { get; private set; }
    public String previousUrl { get; private set; } 
    public String courseAssignmentsString { get; set; }
    public List<KnowledgeBaseWguCourseVersionLink__c> courseAssignmentList { get; private set; }
    public String errorMessage { get; private set; }
    public boolean updateArticle { get; set; }
    
    private Id newKnoweldgeArticleVersionId;
    private EditorType currentEditorType;
    public final String createText = 'Create';
    public final String editText = 'Edit';
    public final String displayPropertyNone = 'none';
    public final String displayPropertyBlock = 'table'; 
    
    public CourseArticleEditorController() {
        //construct return url TODO: Need to update those pages to return this as a single param... why constrcut it here...
        if (string.isNotEmpty(ApexPages.currentPage().getParameters().get('rtn'))) {
            previousUrl =  ApexPages.currentPage().getParameters().get('rtn');
            if (string.isNotEmpty(ApexPages.currentPage().getParameters().get('searchTerm'))) {
                previousUrl += '&SearchTerm=' + ApexPages.currentPage().getParameters().get('searchTerm');
            }
            if (string.isNotEmpty(ApexPages.currentPage().getParameters().get('courseCode'))) {
                previousUrl += '&CourseCode=' + ApexPages.currentPage().getParameters().get('courseCode');
            }
            if (string.isNotEmpty(ApexPages.currentPage().getParameters().get('courseId'))) {
                previousUrl += '&CourseId=' + ApexPages.currentPage().getParameters().get('courseId');
            }
            if (string.isNotEmpty(ApexPages.currentPage().getParameters().get('refineSearchTerm'))) {
                previousUrl += '&RefineSearchTerm=' + ApexPages.currentPage().getParameters().get('refineSearchTerm');
            }
        } else {
            previousUrl = Page.WGUArticles.getUrl();
        }
        
        updateArticle = false;
        //Create Article init
        String knoweldgeArticleVersionId = ApexPages.currentPage().getParameters().get('id');
        if (String.isNotEmpty(knoweldgeArticleVersionId)) {
            setEditDisplay(knoweldgeArticleVersionId);
        } else {
            currentEditorType = EditorType.Create;
            subHeaderTitle = createText;
            displayProperty = displayPropertyNone;
            courseArticle = new CourseArticle__kav(isVisibleInCsp = true);
        }
    }
    
    public List<SelectOption> getArticleTypes() 
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('None','--None--'));
        for(Schema.PicklistEntry pickList : CourseArticle__kav.ArticleType__c.getDescribe().getPickListValues()) {
            options.add(new SelectOption(pickList.getValue(), pickList.getValue()));
        }        
        return options;
    }
    
    @RemoteAction
    global static JsTreeUtility.JsTree getCourseListJson(String courseAssignments) {
    	Set<String> courseVersionIds = null;
        if (string.isNotEmpty(courseAssignments)) {
            courseVersionIds = new Set<String>(courseAssignments.split(','));
        }
        List<WGUCourse__c> courseList = [SELECT Id, Name, (Select Id, Name, MajorVersion__c, Title__c From WGUCourseVersions__r) FROM WGUCourse__c 
            WHERE Id IN (SELECT Course__c FROM KBCourseManagement__c WHERE Mentor__r.User__c = :UserInfo.getUserId())];
		courseList.addAll([SELECT Name, (Select Id, Name, MajorVersion__c, Title__c From WGUCourseVersions__r) FROM WGUCourse__c 
            WHERE Id IN (SELECT WGUCourse__c FROM WGUCourseVersion__c WHERE Id IN :courseVersionIds) AND Id NOT IN :courseList]);
        
        return JsTreeUtility.createJsTreeFromCourseList(courseList, courseVersionIds);
    }
    
    public PageReference publishArticle() {
        if (saveArticle(true)) {
            PageReference pageRef = new PageReference(previousUrl);
            pageRef.setRedirect(true);
            return pageRef;
        }
        return null;
    }
    
    public PageReference save() {
        if(saveArticle(false)) {
            PageReference pageRef = new PageReference(Page.CourseArticleEditor.getUrl() + '?id=' + newKnoweldgeArticleVersionId);
            pageRef.setRedirect(true);
            return pageRef;
        }
        return null;
    }
    
    public PageReference saveAndClose() {
        if (saveArticle(false)) {
            PageReference pageRef = new PageReference(previousUrl);
            pageRef.setRedirect(true);
            return pageRef;
        }
        return null;
    }
    
    public PageReference deleteArticle() {
        Savepoint sp = Database.setSavepoint();
        try {
        	errorMessage = null;
            CourseArticleDAO.deleteKnowledgeBaseArticle(courseArticle);
            PageReference pageRef = new PageReference(previousUrl);
            pageRef.setRedirect(true);
            return pageRef;
        } catch (Exception ex) {
            displayException(ex);
            Database.rollback(sp);
        }
        return null;
    }
    
    private boolean saveArticle(boolean publishArticle) {
    	errorMessage = null;
        boolean succesful = false;
        boolean editOnlineArticle = false;
        if (courseArticle.PublishStatus == kbArticleConstants.PublicationStatus.Online.name()) {
            publishArticle = true;
            editOnlineArticle = true;
        }
        if (validateInput(publishArticle)) {
            Savepoint sp = Database.setSavepoint(); //Ran into some weird saving issues so trying to employ a rollback just in case
            try {
                if (editOnlineArticle) {
                    courseArticle.Id = KBManagement.PublishingService.editOnlineArticle(courseArticle.KnowledgeArticleId, true);
                    courseAssignmentList = null; //reset courseAssignmentList as this is a new version and prior version should keep all it's existing links and new version needs to create all new links
                    KnowledgeBaseReportingUtility.removeKbArticlesFromLatestVersion(courseArticle); //update reporting table to remove all previous versions as the latest version.
                }
                
                CourseArticle__kav courseArticleUpdate = courseArticle.clone(true, true, false, true);
                
                //set file properties for course article if file was uploaded
                if (uploadFileContents != null || updateArticle) {
                    courseArticleUpdate.FileUpload__Body__s = uploadFileContents;
                    courseArticleUpdate.FileUpload__Name__s = uploadFileName;
                    courseArticleUpdate.FileUpload__ContentType__s = uploadContentType;
                    updateArticle = false;
                }
                CourseArticleUtility.upsertCourseArticle(courseArticleUpdate, uploadFileTitle);
                
                if (publishArticle) {
                    KBManagement.PublishingService.publishArticle(courseArticle.KnowledgeArticleId, false); //Is there a reason we are only doing minor versions?
                }
                
                courseArticleUpdate = CourseArticleDAO.getForKnowledgeBaseUpsert(courseArticleUpdate.Id);
                KnowledgeBaseReporting__c kbReport = KnowledgeBaseReportingUtility.createKbReportByArticle(courseArticleUpdate);
                upsert kbReport KnowledgeArticleVersionId__c;
                
                //Create KnowledgeBaseWguCourseVersionLink__c 
                if (String.isNotEmpty(courseAssignmentsString)) {
                    KnowledgeBaseReportingDAO.updateCourseVersionLink(courseAssignmentList, courseArticleUpdate.Id, kbReport.Id, new Set<String>(courseAssignmentsString.split(',')));
                }
                
                newKnoweldgeArticleVersionId = courseArticleUpdate.Id; 
                succesful = true;
            } catch (Exception ex) {
                displayException(ex);
                Database.rollback(sp);
            }
        }
        return succesful;
    }
    
    private Boolean validateInput(boolean publishArticle) {
        Boolean returnValue = true;
        if (publishArticle) {
            String[] validationMsgs = new String[] {};
            returnValue = CourseArticleUtility.validatePublishArticle(courseArticle, courseAssignmentsString, validationMsgs);
            for (String message : validationMsgs) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, message));
            }
        }
        
        if(uploadFileSize > 5242880){  
            //maximum attachment size is 5MB.  Show an error
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Error, 'The file was NOT uploaded, because it is too big. 5MB is the limit.'));
            returnValue = false;
        }
        
        if (String.isEmpty(courseAssignmentsString)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Course Assignment is required.'));   
            returnValue = false;        
        }
        
        if (uploadFileContents != null) {
            if (String.isEmpty(uploadFileTitle)) { //If no file title is declared we use the file name
                if (uploadFileName.length() > 40) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Upload File Name is too long (maximum 40 characters). Please enter a File Title that is less than 40 characters long.'));
                    returnValue = false;
                }
            } else {
                if (uploadFileTitle.length() > 40) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Upload File Title is too long (maximum 40 characters). Please enter a File Title that is less than 40 characters long.'));
                    returnValue = false;
                }
            }
        }
        
        //SFDC strips out newlines and blank space encodings before inserting into rich text, so had to strip those out to get the correct character count for now...  This might eventually break if SFDC decides to change this
        if (String.isNotEmpty(courseArticle.RichTextArea__c)) {
            String richTextArea = courseArticle.RichTextArea__c.replace('\n', '').replace('&nbsp;', ' ').trim();
            if (richTextArea.length() > 32768) {
                returnValue = false;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Article Body is too long (maximum 32768 characters; current ' + richTextArea.length() + ' characters). Please enter a Article Body that is less than 32768 characters long.'));
            }
        }
        return returnValue;
    }
    
    private void setEditDisplay(String knowledgeArticleVersionId) {
        courseArticle = CourseArticleDAO.getForCreateArticleControllerDisplay(knowledgeArticleVersionId);
        uploadFileTitle = courseArticle.FileUpload__Name__s;
        currentEditorType = EditorType.Edit;
        subHeaderTitle = editText;
        displayProperty = displayPropertyBlock;
        courseAssignmentList = [SELECT Id, WGUCourseVersion__c FROM KnowledgeBaseWguCourseVersionLink__c WHERE KnowledgeArticleVersionId__c = :knowledgeArticleVersionId];
        courseAssignmentsString = KnowledgeBaseReportingUtility.getCourseVersionsStringByRelatedList(courseAssignmentList);
    }
    
    private void displayException(Exception ex) {
        //TODO: Move this to a exception handler and potentially with logging to a custom object
        errorMessage = 'Errors occurred while saving the Article information.\n\nError Type: '+ ex.getTypeName() + '\nError Cause: ' + ex.getCause() + 
            '\nError Message: ' + ex.getMessage() + '\nError Line: ' + ex.getLineNumber() + ex.getStackTraceString();
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unable to process article action.'));
    }
    
    public class CourseArticleEditorControllerException extends Exception { }
}