src/objects/CourseArticle__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Course Article</label>
    <pluralLabel>Course Articles</pluralLabel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <fields>
        <fullName>CourseOfStudyId__c</fullName>
        <description>The ID for the course of study associated with this WGUCourseVersion.  Relationship is 1 to 1 WGUCourseVersion to Course Of Study</description>
        <label>Course Of Study ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The course that this course version belongs to</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>WGU Course Versions</relationshipLabel>
        <relationshipName>WGUCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSearchArticlesController.cls
@isTest
private class TestSearchArticlesController {
	
	private static final String courseMajorVersionDefault = 'All';
	private static final String courseCode = 'UT1';
	private static final String mentorEmail = 'unit.test@test.com';
	private static final String mentorName = 'Unit Test';
	private static User studentUser;
	static {
		User adminUser = TestCourseArticleHelper.getTestUser('testadmin', 'System Administrator', true);
		System.runAs(adminUser) {
			studentUser = TestCourseArticleHelper.getTestStudent('teststudent', 'Test', 'Student');
			TestCourseArticleHelper.createCourseArticleFull('SearchArticles', KbArticleConstants.ArticleTypeCourseAtAGlance,
					Schema.SObjectType.CourseArticle__kav.fields.FileUpload__ContentType__s.getPickListValues()[0].getValue(), courseCode);
		}
	}

    public static testMethod void testInitByCourseIdNoMentor() {
    	System.runAs(studentUser) {
	    	TestCourseArticleHelper.createMentorContact('NOTFOUND', mentorEmail, mentorName);
	    	WGUCourseVersion__c courseVersion = [SELECT CourseOfStudyId__c FROM WGUCourseVersion__c WHERE WGUCourse__r.Name = :courseCode LIMIT 1];
	    	PageReference pageRef = new PageReference(Page.CourseArticleEditor.getUrl() + '?searchTerm=Unit Test&courseId=' + courseVersion.CourseOfStudyId__c);
			Test.setCurrentPage(pageRef);
			
			Test.startTest();
			SearchArticlesController controller = new SearchArticlesController();
			Test.stopTest();
			
			System.assertEquals(courseCode, controller.courseCode);
			System.assertNotEquals(courseMajorVersionDefault, controller.majorVersionToDisplay);
			System.assert(!controller.showContactMyMentorButton);
    	}
    }
    
    public static testMethod void testInitByCourseCodeWithMentor() {
    	System.runAs(studentUser) {
	    	TestCourseArticleHelper.createMentorContact(courseCode, mentorEmail, mentorName);
	    	PageReference pageRef = new PageReference(Page.CourseArticleEditor.getUrl() + '?searchTerm=Unit Test&courseCode=' + courseCode);
			Test.setCurrentPage(pageRef);
			
			Test.startTest();
			SearchArticlesController controller = new SearchArticlesController();
			Test.stopTest();
			
			System.assertEquals(courseCode, controller.courseCode);
			System.assertEquals(courseMajorVersionDefault, controller.majorVersionToDisplay);
	    	System.assert(controller.showContactMyMentorButton);
	    	System.assertEquals(mentorName, controller.mentorName);
	    	System.assertEquals(mentorEmail, controller.mentorEmail);
	    	
	    	System.assert(!controller.componentAttributes.isVisible);
	    	controller.showPopup();
	    	System.assert(controller.componentAttributes.isVisible);
	    	System.assertEquals(URL.getSalesforceBaseUrl().toExternalForm() + '/', controller.getBaseURL());
    	}
    }
    
    public static testMethod void testSearchArticleValidation() {
    	System.runAs(studentUser) {
	    	PageReference pageRef = Page.SearchArticles;
	        Test.setCurrentPage(pageRef);
	        
	        Test.startTest();
	        SearchArticlesController controller = new SearchArticlesController();
	        system.debug('testSearchArticleValidation messages: ' + ApexPages.getMessages());
	        System.assertEquals(1, ApexPages.getMessages().size());
	        System.assert(ApexPages.getMessages()[0].getSummary().contains('Search Term may not be blank.'));
	        
	        controller.searchTerm = 'a';
	        controller.doSearch();
	        System.assertEquals(2, ApexPages.getMessages().size());
	        System.assert(ApexPages.getMessages()[1].getSummary().contains('Search Term must be longer than one character.'));
	        Test.stopTest();
    	}
    }
}