src/objects/CourseArticle__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>ArticleType__c</fullName>
        <label>Article Type</label>
        <picklist>
            <picklistValues>
                <fullName>Welcome Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Getting Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Resource Navigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course At-a-Glance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RichTextArea__c</fullName>
        <label>Rich Text Area</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Course Article</label>
    <pluralLabel>Course Articles</pluralLabel>
</CustomObject>

src/objects/KnowledgeBaseWguCourseVersionLink__c.object
<CustomObject>
    <description>Junction object between a Knowledge Article Reporting (Knowledge Article) and Course Versions</description>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <externalId>true</externalId>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Knowledge Base WGU Course Version Link</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Knowledge Base WGU Course Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Base WGU Course Version Link</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/CourseArticleUtility.cls
/*
*Author John Chan
*Slalom
*/
public with sharing class CourseArticleUtility {
	public static void upsertCourseArticle(CourseArticle__kav courseArticle, String uploadFileTitle) {
		//set file title
		if (courseArticle.FileUpload__Body__s != null && String.isNotEmpty(uploadFileTitle)) {
			if (!uploadFileTitle.contains('.')) { //file title does not contain extension
				Integer fileExtPosition = courseArticle.FileUpload__Name__s.lastIndexOf('.');
                if (fileExtPosition > 0) { 
                    uploadFileTitle += courseArticle.FileUpload__Name__s.substring(fileExtPosition);
                }
			}
			courseArticle.FileUpload__Name__s = uploadFileTitle;
		}
		
		setUniqueUrlName(courseArticle);
		if (courseArticle.Id == null) {
			insert courseArticle;
		} else {
			update courseArticle;
		}
	}
	
	public static void setUniqueUrlName(CourseArticle__kav courseArticle) {
		if (string.isNotEmpty(courseArticle.Title)) {
			string urlName = 'Course-Article-';
			if (string.isNotEmpty(courseArticle.ArticleType__c)) {
				urlName += stripInvalidCharactersForUrlName(courseArticle.ArticleType__c) + '-';
			}
			
			urlName += stripInvalidCharactersForUrlName(courseArticle.Title) + '-' + stripInvalidCharactersForUrlName(String.valueOf(Date.today()));
			
			User currentUser = [SELECT PIDM__c FROM User WHERE Id = :UserInfo.getUserId()];
			if (string.isNotEmpty(currentUser.PIDM__c)) {
				urlName += 	stripInvalidCharactersForUrlName(currentUser.PIDM__c);
			}
			courseArticle.UrlName = urlName;
		} else {
			throw new CourseArticleUtilityException('Cannot create Url Name without having a title set for the Course Article.');
		}
	}
	
	private static String stripInvalidCharactersForUrlName(String urlName) {
		string validUrlName = urlName.replace(' ', '-');
		validUrlName = validUrlName.replaceAll('[^a-zA-Z0-9 -]', '-');
		return validUrlName;
	}
	
	public static boolean validatePublishArticle(CourseArticle__kav article) {
    	List<KnowledgeBaseWguCourseVersionLink__c> kbCourseVersionLinks = [SELECT Id FROM KnowledgeBaseWguCourseVersionLink__c WHERE KnowledgeArticleVersionId__c = :article.Id];
        return validatePublishArticle(article.ArticleType__c, article.Summary, article.RichTextArea__c, null, kbCourseVersionLinks, null);
    }
    
    public static boolean validatePublishArticle(CourseArticle__kav article, String courseVersions, String[] validationMsgs) {
        return validatePublishArticle(article.ArticleType__c, article.Summary, article.RichTextArea__c, courseVersions, null, validationMsgs);
    }
    
    public static boolean validatePublishArticle(String articleType, String articleSummary, String richTextField, String courseVersions, 
    		List<KnowledgeBaseWguCourseVersionLink__c> kbCourseVersionLinks, String[] validationMsgs) {
        boolean isValid = true;
        if ((String.isEmpty(articleType)) || (articleType == 'None')) {
            if (validationMsgs != null) {
                validationMsgs.add('Article Type is required for Publishing.');
            }
            isValid = false;
        }
        if (String.isEmpty(articleSummary)) {
            if (validationMsgs != null) {
                validationMsgs.add('Article Summary is required for Publishing.');
            }
            isValid = false;
        }
        if (String.isEmpty(richTextField)) {
            if (validationMsgs != null) {
                validationMsgs.add('Article Body Text is required for Publishing.');
            }
            isValid = false;
        }
        if (String.isEmpty(courseVersions) && kbCourseVersionLinks == null) {
            if (validationMsgs != null) {
                validationMsgs.add('At least one Course / Version must be assigned prior to Publishing.');
            }
            isValid = false;
        } else if (kbCourseVersionLinks != null && kbCourseVersionLinks.size() == 0) {
        	if (validationMsgs != null) {
                validationMsgs.add('At least one Course / Version must be assigned prior to Publishing.');
            }
            isValid = false;
        }
        return isValid;
    }
	
	public class CourseArticleUtilityException extends Exception { }
}