src/objects/CourseArticle__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>ArticleType__c</fullName>
        <label>Article Type</label>
        <picklist>
            <picklistValues>
                <fullName>Welcome Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Getting Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Resource Navigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course At-a-Glance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>InternalTagging__c</fullName>
        <inlineHelpText>This is used to add terms that might not be included in the body the article but student still might search.
Text in here will be searchable but will NOT be displayed to the student.</inlineHelpText>
        <label>Internal Tagging</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RichTextArea__c</fullName>
        <label>Rich Text Area</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Edit</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Publish</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Approved for Publish</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
                <color>#A53711</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course Article</label>
    <pluralLabel>Course Articles</pluralLabel>
</CustomObject>

src/objects/KnowledgeBaseReporting__c.object
<CustomObject>
    <description>This object is used to report on KB.</description>
    <fields>
        <fullName>ArticleType__c</fullName>
        <description>Course Article Custom Field pick-list.  Prevent upkeep of pick-list here.</description>
        <label>Article Type</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Article version id&apos;s from knowledge base (kav objects)</description>
        <externalId>true</externalId>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ScheduledArchiveDate__c</fullName>
        <description>Duplication of schedule date to track in reporting and display custom vf pages</description>
        <label>Scheduled Archive Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ScheduledPublishDate__c</fullName>
        <description>Duplication of schedule date to track in reporting and display custom vf pages</description>
        <label>Scheduled Publish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Course Article Custom Field pick-list.  This is set as a text field so an update will not have to occur here and keep both pick-lists in sync.</description>
        <label>Stage</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Knowledge Base Reporting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>KB Reporting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Base Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KnowledgeBaseWguCourseVersionLink__c.object
<CustomObject>
    <description>Junction object between a Knowledge Article Reporting (Knowledge Article) and Course Versions</description>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <externalId>true</externalId>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KnowledgeBaseReporting__c</fullName>
        <label>Knowledge Base Reporting</label>
        <referenceTo>KnowledgeBaseReporting__c</referenceTo>
        <relationshipLabel>WGU Course Version</relationshipLabel>
        <relationshipName>Knowledge_Article_Course_Version_Link</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Knowledge Base Reporting</relationshipLabel>
        <relationshipName>Knowledge_Article_Course_Version_Link</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Knowledge Base WGU Course Version Link</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Knowledge Base WGU Course Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Base WGU Course Version Link</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <fields>
        <fullName>CourseOfStudyId__c</fullName>
        <description>The ID for the course of study associated with this WGUCourseVersion.  Relationship is 1 to 1 WGUCourseVersion to Course Of Study</description>
        <label>Course Of Study ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseArticleDAO.cls
/*
*Author John Chan
*Slalom
*@4/9/13 Article delete and Online article search
*@4/24/13 Add new query fields to support new reporting fields and data migration from course articles
*@5/22/13 New view object to hold css class, view count.
*@5/24/13 New static method to build new internal wrapper view class
*/
public with sharing class CourseArticleDAO {
	private static final String kbReportDataMigrationQuery = 'SELECT Id, CreatedById, CreatedDate, LastModifiedById, ArchivedDate, KnowledgeArticleId, ArticleType__c,' + 
							' LastPublishedDate, PublishStatus, Stage__c, Summary, Title, UrlName, IsVisibleInCsp, IsVisibleInApp, IsVisibleInPrm, IsVisibleInPkb,' + 
							' IsLatestVersion, VersionNumber FROM CourseArticle__kav WHERE ';
	public static List<CourseArticle__kav> getForKnowledgeBaseReportBatch(String publishStatus, String language) {
		String query = kbReportDataMigrationQuery;
		query += ' PublishStatus = \'' + string.escapeSingleQuotes(publishStatus) + '\'';
		query += 'AND Language = \'' + string.escapeSingleQuotes(language) + '\'';
		
		return Database.query(query); 
	}
	
	public static CourseArticle__kav getForKnowledgeBaseUpsert(Id knoweldgeArticleVersionId) {
		String query = kbReportDataMigrationQuery;
		query += 'Id = \'' + knoweldgeArticleVersionId + '\'';
		return Database.query(query);
	}
	
	public static CourseArticle__kav getForCreateArticleControllerDisplay(String Id) {
		return [SELECT Id, PublishStatus, ArticleNumber, CreatedBy.Name, LastModifiedBy.Name, Title, ArticleType__c, Summary, RichTextArea__c, FileUpload__Name__s, 
			KnowledgeArticleId, InternalTagging__c FROM CourseArticle__kav WHERE Id = :Id];
	}
	
	public static final integer maxPublishStatusSize = 5;
	//TODO: Need to chunk out in case it reaches character limit for soql
	public static Map<Id, CourseArticle__kav> getForKnowledgeBaseReportCleanupBatch(KbArticleConstants.PublicationStatus[] publishStatus, String[] languages) {
		//Because we are doing a forloop that contains a soql call we are restricting this call to no more then 5 status.  In theory there are only 3 Publish Status.
		if (publishStatus.size() > maxPublishStatusSize) {
			throw new CourseArticleDAOException('Unable to call CourseArticleDAO.getForKnowledgeBaseReportCleanupBatch.  Limiting DAO call to 5 publish status because this function loops through the publish status to make SOQL calls to prevent hitting governer limits.');
		}
		Map<Id, CourseArticle__kav> courseArticles = new Map<Id, CourseArticle__kav>();	
		for (KbArticleConstants.PublicationStatus status : publishStatus) {
			//String query = queryToken.replace(publishStatusToken, status);
			Map<Id, CourseArticle__kav> courseArticlePartialList = null;
			if (status == KbArticleConstants.PublicationStatus.Draft) {
				courseArticlePartialList = new Map<Id, CourseArticle__kav>([SELECT Id from CourseArticle__kav where PublishStatus = 'Draft' and Language in :languages]);
			} else if (status == KbArticleConstants.PublicationStatus.Online) {
				courseArticlePartialList = new Map<Id, CourseArticle__kav>([SELECT Id from CourseArticle__kav where PublishStatus = 'Online' and Language in :languages]);
			} else if (status == KbArticleConstants.PublicationStatus.Archived) {
				courseArticlePartialList = new Map<Id, CourseArticle__kav>([SELECT Id from CourseArticle__kav where PublishStatus = 'Archived' and Language in :languages]);
			}
			if (courseArticlePartialList != null && courseArticlePartialList.size() > 0) {
				courseArticles.putAll(courseArticlePartialList);
			}
		}
		
		return courseArticles;
	}
	
	/*DELETE ARTICLE BEGIN*/
	public static void deleteKnowledgeBaseArticle(CourseArticle__kav courseArticle) {
		if (courseArticle.PublishStatus == KbArticleConstants.PublicationStatus.Draft.name()) {
    		KbManagement.PublishingService.deleteDraftArticle(courseArticle.KnowledgeArticleId);
    	} else if (courseArticle.PublishStatus == KbArticleConstants.PublicationStatus.Archived.name()) {
        	KbManagement.PublishingService.deleteArchivedArticle(courseArticle.KnowledgeArticleId);
    	}
    	delete [SELECT Id FROM KnowledgeBaseReporting__c WHERE KnowledgeArticleVersionId__c = :courseArticle.Id];
	}
	
	public static void deleteKnowledgeBaseArticles(List<CourseArticle__kav> courseArticles) {
		//Should we just let the batch job delete this?  This might run into potential governer limits if mass records are selected
    	List<Id> knowledgeArticleVersionIds = new List<Id>();
        for (CourseArticle__kav article : courseArticles) {
        	knowledgeArticleVersionIds.add(article.Id);
        	if (article.PublishStatus == KbArticleConstants.PublicationStatus.Draft.name()) {
        		KbManagement.PublishingService.deleteDraftArticle(article.KnowledgeArticleId);
        	} else if (article.PublishStatus == KbArticleConstants.PublicationStatus.Archived.name()) {
            	KbManagement.PublishingService.deleteArchivedArticle(article.KnowledgeArticleId);
        	}
        }
        delete [SELECT Id FROM KnowledgeBaseReporting__c WHERE KnowledgeArticleVersionId__c IN :knowledgeArticleVersionIds];
	}
	/*DELETE ARTICLE END*/
	
	/*ONLINE ARTICLE SEARCH BEGIN*/
	public static List<CourseArticle__kav> searchEnglishUsArticles(SearchAppType searchAppType, String publishStatus, String courseCode, String courseOfStudyId, String searchTerm, List<Id> courseVersionIds,
			String ownerId) {
		List<List<sObject>> courseArticlesSearch = null;
		List<CourseArticle__kav> courseArticleList = null;
		final String searchTermToken = '[[searchTerm]]';
		final String publishStatusToken = '[[publishStatus]]';
		final String courseArticleIdFilterToken = '[[courseArticleIdFilter]]';
		final String queryFieldsToken = '[[queryFields]]';
		final String ownerFilterToken = '[[ownerFilter]]';
		final String queryFieldsInteral = 'Id, Title, ArticleType__c, CreatedDate, LastModifiedDate, KnowledgeArticleId';
		final String queryFieldsStudent = 'Id, KnowledgeArticleId, Title, UrlName, Summary, LastPublishedDate, ArticleType__c';
		final String soslQuery = 'FIND ' + searchTermToken + ' IN ALL FIELDS RETURNING CourseArticle__kav (' + queryFieldsToken + ' WHERE PublishStatus = \'' + publishStatusToken + 
				'\' AND Language = \'en_US\' ' + courseArticleIdFilterToken + ownerFilterToken + ')';
		final String soqlQuery = 'SELECT ' + queryFieldsToken + ' FROM CourseArticle__kav WHERE PublishStatus = \'' + publishStatusToken + '\' AND Language = \'en_US\' ' + courseArticleIdFilterToken + ownerFilterToken;
		
		boolean filteredByCourseVersion = (String.isNotEmpty(courseCode) || String.isNotEmpty(courseOfStudyId) || (courseVersionIds != null && courseVersionIds.size() > 0));
		List<AggregateResult> kbCourseVersionLinks = null;
		if (String.isNotEmpty(courseCode)) {
			kbCourseVersionLinks = [SELECT KnowledgeArticleVersionId__c FROM KnowledgeBaseWguCourseVersionLink__c WHERE WGUCourseVersion__r.Name = :courseCode GROUP BY KnowledgeArticleVersionId__c];
		} else if (String.isNotEmpty(courseOfStudyId)) {
			kbCourseVersionLinks = [SELECT KnowledgeArticleVersionId__c FROM KnowledgeBaseWguCourseVersionLink__c WHERE WGUCourseVersion__r.CourseOfStudyId__c = :Decimal.valueOf(courseOfStudyId) GROUP BY KnowledgeArticleVersionId__c];
		} else if (courseVersionIds != null && courseVersionIds.size() > 0) {
			kbCourseVersionLinks = [SELECT KnowledgeArticleVersionId__c FROM KnowledgeBaseWguCourseVersionLink__c WHERE WGUCourseVersion__c IN :courseVersionIds GROUP BY KnowledgeArticleVersionId__c];
		}
		
		//query only if we have linked course versions or we are not querying by linked course versions.
		if ((!filteredByCourseVersion || kbCourseVersionLinks != null && kbCourseVersionLinks.size() > 0) && String.isNotEmpty(publishStatus)) {
			String query = '';
			String commaSeperateArticleVersionIds = null;
			if (kbCourseVersionLinks != null && kbCourseVersionLinks.size() > 0) {
				for (AggregateResult versionLink : kbCourseVersionLinks) {
					if (String.isEmpty(commaSeperateArticleVersionIds)) {
						commaSeperateArticleVersionIds = '\'' + versionLink.get('KnowledgeArticleVersionId__c') + '\'';
					} else {
						commaSeperateArticleVersionIds += (',\'' + versionLink.get('KnowledgeArticleVersionId__c') + '\'');
					}
				}
			}
			
			if (String.isNotEmpty(searchTerm)) {
				query = soslQuery.replace(searchTermToken, '{' + searchTerm + '}');
			} else {
				query = soqlQuery;
			}
			if (String.isNotEmpty(ownerId))  {
				query = query.replace(ownerFilterToken, ' AND OwnerId = \'' + ownerId + '\'');
			} else {
				query = query.replace(ownerFilterToken, '');
			}
			query = query.replace(publishStatusToken, publishStatus);
			
			if (searchAppType == CourseArticleDAO.SearchAppType.Internal) {
				query = query.replace(queryFieldsToken, queryFieldsInteral);
			} else if (searchAppType == CourseArticleDAO.SearchAppType.Student) {
				query = query.replace(queryFieldsToken, queryFieldsStudent);
			}
			
			if (String.isNotEmpty(commaSeperateArticleVersionIds)) {
				query = query.replace(courseArticleIdFilterToken, 'AND Id IN (' + commaSeperateArticleVersionIds + ')');
				//Salesforce has a limit of 10,000 characters in dynamic soql/sosl.  We will throw an exception preventing them from hitting this limit
				if (query.length() >= 10000) {
					throw new CourseArticleDAOException('Unable to perform search.  Please narrow your search parameters and try again.');
				}
			} else {
				query = query.replace(courseArticleIdFilterToken, '');
			}
			
			system.debug('searchEnglishUsArticles query string: ' + query);
			//search term exists then we use a sosl query
			if (String.isNotEmpty(searchTerm)) {
				courseArticlesSearch = search.query(query);
			} else {
				courseArticleList = Database.query(query);
			}
		}
		 
		if (courseArticlesSearch != null && courseArticlesSearch.size() > 0 && courseArticlesSearch[0].size() > 0) {
			return (List<CourseArticle__kav>)courseArticlesSearch[0];
		} else if (courseArticleList != null && courseArticleList.size() > 0) {
			return courseArticleList;
		}else {
			return null;
		}
	}
	
	public static List<CourseArticleStudentView> getCourseArticleStudentView(List<CourseArticle__kav> courseArticles) {
		if (courseArticles != null && courseArticles.size() > 0) {
			Map<Id, CourseArticleStudentView> articleViewMap = new Map<Id, CourseArticleStudentView>();
			for (CourseArticle__kav courseArticle : courseArticles) {
				articleViewMap.put(courseArticle.KnowledgeArticleId, new CourseArticleStudentView(courseArticle));
			}
			
			for (CourseArticle__ViewStat articleViewStat : [SELECT ParentId, ViewCount FROM CourseArticle__ViewStat WHERE ParentId IN :articleViewMap.keySet() AND Channel = :KbArticleConstants.Channel.Csp.Name()]) {
				articleViewMap.get(articleViewStat.ParentId).viewCount = articleViewStat.ViewCount;
			}
			return articleViewMap.values();
		}
		return null;
	}
	
	public class CourseArticleStudentView {
		public CourseArticleStudentView(CourseArticle__kav courseArticle) {
			this.courseArticle = courseArticle;
			setImageClass();
		}
		public CourseArticle__kav courseArticle { get; private set; }
		private String imageClass;
		public integer viewCount { get; set; }
		
		public String getImageClass() {
			return this.imageClass;
		}
		
		private void setImageClass() {
			if (courseArticle.ArticleType__c == KbArticleConstants.ArticleTypeWelcomeVideo) {
				imageClass = 'welcome-video-icon';
			} else if (courseArticle.ArticleType__c == KbArticleConstants.ArticleTypeGettingStarted) {
				imageClass = 'getting-started-icon';
			} else if (courseArticle.ArticleType__c == KbArticleConstants.ArticleTypeLearningResource) {
				imageClass = 'learning-resource-icon';
			} else if (courseArticle.ArticleType__c == KbArticleConstants.ArticleTypeCourseAtAGlance) {
				imageClass = 'course-at-a-glance-icon';
			} else if (courseArticle.ArticleType__c == KbArticleConstants.ArticleTypeOther) {
				imageClass = 'other-icon';
			}
		}
	}
	
	public static List<CourseArticleInternalView> getCourseArticleInternalView(List<CourseArticle__kav> courseArticles) {
		if (courseArticles != null && courseArticles.size() > 0) {
			Map<Id, CourseArticleInternalView> articleViewMap = new Map<Id, CourseArticleInternalView>();
			for (CourseArticle__kav courseArticle : courseArticles) {
				articleViewMap.put(courseArticle.Id, new CourseArticleInternalView(courseArticle));
			}
			
			for (KnowledgeBaseReporting__c kbReport : [SELECT KnowledgeArticleVersionId__c, ScheduledArchiveDate__c, ScheduledPublishDate__c FROM KnowledgeBaseReporting__c WHERE KnowledgeArticleVersionId__c IN :articleViewMap.keySet()]) {
				articleViewMap.get(kbReport.KnowledgeArticleVersionId__c).ScheduledPublishDate = kbReport.ScheduledPublishDate__c;
				articleViewMap.get(kbReport.KnowledgeArticleVersionId__c).ScheduledArchiveDate = kbReport.ScheduledArchiveDate__c;
			}
			return articleViewMap.values();
		}
		return null;
	}
	
	public enum SearchAppType {
		Internal,
		Student
	}
	/*ONLINE ARTICLE SEARCH END*/
	
	public class CourseArticleDAOException extends Exception { }
}