src/objects/EmailAddress__c.object
<CustomObject>
    <description>All Email addresses related to a contact</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Addresses</relationshipLabel>
        <relationshipName>EmailAddresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EmailCode__c</fullName>
        <label>Email Code</label>
        <picklist>
            <picklistValues>
                <fullName>CPMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WGU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WORK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <label>PIDM</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StatusIndicator__c</fullName>
        <label>Status Indicator</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Email Address</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EmailAddressToBanner__c.object
<CustomObject>
    <description>A control object for the synchronization between Banner table general.goremal and Salesforce object Email Address</description>
    <fields>
        <fullName>ContactIdIN__c</fullName>
        <label>Contact Id (IN)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailAddressIN__c</fullName>
        <externalId>true</externalId>
        <label>Email Address (IN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailAddress__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Email Address object that this sync records connects to in Salesforce.</description>
        <label>Email Address</label>
        <referenceTo>EmailAddress__c</referenceTo>
        <relationshipLabel>Email Addresses To Banner</relationshipLabel>
        <relationshipName>EmailAddressesToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EmailCodeIN__c</fullName>
        <label>Email Code (IN)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDMIN__c</fullName>
        <label>PIDM (IN)</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryEmailIN__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Email (IN)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StatusIndicatorIN__c</fullName>
        <label>Status Indicator (IN)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SynchronizationError__c</fullName>
        <label>Synchronization Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Email Address To Banner</label>
    <nameField>
        <displayFormat>emailsync-{0}</displayFormat>
        <label>Email Address To Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Addresses To Banner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmailAddressToBannerUtilities.cls
public class EmailAddressToBannerUtilities {
    
    private static Boolean alreadyAssigning = false;
    private static Boolean alreadyUpdating = false;
    
    private static String convertActiveIndicator(String bannerCode) {
        return bannerCode == 'A' ? 'Active' : 'Inactive';
    }

    private static Boolean validateEmail(String emailAddress) {
        String emailRegex = '([a-zA-Z0-9_\\-\\.]+)@((\\[a-z]{1,3}\\.[a-z]{1,3}\\.[a-z]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})';
        Pattern MyPattern = Pattern.compile(emailRegex);
        
        // Then instantiate a new Matcher object "MyMatcher"
        Matcher MyMatcher = MyPattern.matcher(emailAddress);
        
        // Check for underscores after @ symbol.
        
        return MyMatcher.matches();  
    }
  
    // Needs to be run as before set the EmailAddress__c.id value that is either looked up or created. 
    // Records cannot be saved without this value.
    public static void matchIdOrCreateSync(String jsonNew) {
        if (alreadyAssigning)
            return;
        
        alreadyAssigning = true;
        
        List<EmailAddressToBanner__c> newValues = (List<EmailAddressToBanner__c>)JSON.deserialize(jsonNew, List<EmailAddressToBanner__c>.class);
        List<EmailAddressToBanner__c> records = new List<EmailAddressToBanner__c>();
        Map<String, EmailAddressToBanner__c> recordsToProcess = new Map<String, EmailAddressToBanner__c>();
        Set<String> emailsAddresses = new Set<String>();
        List<EmailAddressToBanner__c> badEmails = new List<EmailAddressToBanner__c>();
        Set<Integer> badEmailIndexes = new Set<Integer>();
        
        // Remove invalid Emails from the list to be run through.
        for (Integer i = 0; i < newValues.size(); i++) {
            EmailAddressToBanner__c record = newValues.get(i);
            // Check email address is valid for salesforce, if not no reason to bother looking for it.
            if (!validateEmail(record.EmailAddressIN__c)) {
                record.SynchronizationError__c = 'Email address format not valid for Salesforce.';
                badEmails.add(record);
                badEmailIndexes.add(i);
            } else {
                records.add(record);
            }
        }
        
        if (badEmails.size() > 0)
            update badEmails;
        
        // Create a list of records that need to have the EmailAddress__c.Id filled in. Already assigned values
        // can be ignored. Ignore invalid email addresses.
        for (EmailAddressToBanner__c record : records) {
            if (record.EmailAddress__c == null) {
                emailsAddresses.add(record.EmailAddressIN__c);
                recordsToProcess.put(record.PIDMIN__c + '-' + record.EmailAddressIN__c, record);                    
            }
        }
        
        List<EmailAddress__c> emails;
        String currentId;
        
        try {
            String statusIndicator;    
            EmailAddressToBanner__c current; 
            
            // Match up existing Email records to new sync records and update original record with changes from sync.
            emails = [SELECT Id, PIDM__c, Email__c, EmailCode__c, PrimaryEmail__c, StatusIndicator__c FROM EmailAddress__c WHERE Email__c = :emailsAddresses];
            
            for (EmailAddress__c email : emails) {
                currentId = email.Id;
                
                if (recordsToProcess.containsKey(email.PIDM__c + '-' + email.Email__c)) {
                    current = recordsToProcess.get(email.PIDM__c + '-' + email.Email__c);
                    
                    current.EmailAddress__c = email.Id;
                }
            }
        
            emails = new List<EmailAddress__c>();
            
            // Scan for records that are still not matched, create if doesn't exist then link.
            for (EmailAddressToBanner__c record : recordsToProcess.values()) {
                currentId = record.Id;
                
                if (record.EmailAddress__c == null) {
                    statusIndicator = convertActiveIndicator(record.StatusIndicatorIN__c);
                    emails.add(new EmailAddress__c(Contact__c = record.ContactIdIN__c, Email__c = record.EmailAddressIN__c, 
                                                   EmailCode__c = record.EmailCodeIN__c, PIDM__c = record.PIDMIN__c,
                                                   PrimaryEmail__c = record.PrimaryEmailIN__c, StatusIndicator__c = statusIndicator ));
                }
            }
        
        
            insert emails;
            
            // Link emails to sync records.
            for (EmailAddress__c email : emails) {
                currentId = email.Id;
                
                if (recordsToProcess.containsKey(email.PIDM__c + '-' + email.Email__c)) {
                    recordsToProcess.get(email.PIDM__c + '-' + email.Email__c).EmailAddress__c = email.Id;
                }
            }            
        } catch (Exception ex) {
            String message = ex.getMessage().substring(0, ex.getMessage().length() > 200 ? 200 : ex.getMessage().length());
            SynchronizeToBannerLogUtilities log = new SynchronizeToBannerLogUtilities();
            
            for (EmailAddressToBanner__c sync : recordsToProcess.values()) {
                sync.SynchronizationError__c = message + ' on record ' + currentId;
                log.add('EmailAddressToBanner__c', sync.Id, message + ' on record ' + currentId);
            }
            
            log.save();
        }
        
        update recordsToProcess.values();
    }
    
    @Future
    public static void processUpdate(String jsonNew) {
        processUpdateSync(jsonNew);
    }        
        
    public static void processUpdateSync(String jsonNew) {
        if (alreadyUpdating)
            return;
        
        alreadyUpdating = true;        
        
        List<EmailAddressToBanner__c> newValues = (List<EmailAddressToBanner__c>)JSON.deserialize(jsonNew, List<EmailAddressToBanner__c>.class);
        List<EmailAddressToBanner__c> records = new List<EmailAddressToBanner__c>();
        Set<Id> emailIds = new Set<Id>();
        Map<Id, EmailAddressToBanner__c> syncMap = new Map<Id, EmailAddressToBanner__c>();
        List<EmailAddressToBanner__c> badEmails = new List<EmailAddressToBanner__c>();
        Set<Integer> badEmailIndexes = new Set<Integer>();
        
        // Remove invalid Emails from the list to be run through.
        for (Integer i = 0; i < newValues.size(); i++) {
            EmailAddressToBanner__c record = newValues.get(i);
            // Check email address is valid for salesforce, if not no reason to bother looking for it.
            if (!validateEmail(record.EmailAddressIN__c)) {
                record.SynchronizationError__c = 'Email address format not valid for Salesforce.';
                badEmails.add(record);
                badEmailIndexes.add(i);
            } else {
                records.add(record);
            }
        }
        
        if (badEmails.size() > 0)
            update badEmails;
        
        for (EmailAddressToBanner__c newValue : records) {
            emailIds.add(newValue.EmailAddress__c);
            syncMap.put(newValue.EmailAddress__c, newValue);
        }
        
        String currentId;
        
        try {        
            List<EmailAddress__c> emails = [SELECT Id, PIDM__c, Email__c, EmailCode__c, PrimaryEmail__c, StatusIndicator__c FROM EmailAddress__c WHERE Id = :emailIds];
        
            EmailAddressToBanner__c current;
            String statusIndicator;
            
            for (EmailAddress__c email : emails) {
                currentId = email.Id;
                
                if (syncMap.containsKey(email.Id)) {
                    current = syncMap.get(email.Id);        
                    currentId = current.Id;
                    statusIndicator = convertActiveIndicator(current.StatusIndicatorIN__c);
                    
                    email.EmailCode__c = current.EmailCodeIN__c;
                    email.PrimaryEmail__c = current.PrimaryEmailIN__c;
                    email.StatusIndicator__c = statusIndicator;
                }
            }   
             
            update emails;
        } catch (Exception ex) {
            String message = ex.getMessage().substring(0, ex.getMessage().length() > 200 ? 200 : ex.getMessage().length());
            SynchronizeToBannerLogUtilities log = new SynchronizeToBannerLogUtilities();
            
            for (EmailAddressToBanner__c sync : newValues) {
                sync.SynchronizationError__c = message + ' on record ' + currentId;
                log.add('EmailAddressToBanner__c', sync.Id, message + ' on record ' + currentId);
            }
            
            update records;
            log.save();
        }        
    }
}