src/objects/EnrollmentAnswers__c.object
<CustomObject>
    <description>answers that pertain to the inquiry and potentially the application form</description>
    <fields>
        <fullName>AnswerText__c</fullName>
        <label>Answer Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MultiplierValue__c</fullName>
        <description>used for the grading algorithm</description>
        <label>Multiplier Value</label>
        <precision>18</precision>
        <scale>16</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Multiplier__c</fullName>
        <description>Used in the grading algorithm</description>
        <label>Multiplier</label>
        <precision>18</precision>
        <scale>16</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuestionKey__c</fullName>
        <label>Question Key</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuestionText__c</fullName>
        <formula>EnrollmentQuestion__r.QuestionText__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>used to place information on the inquiry form</description>
        <label>Value</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Enrollment Answers</label>
    <nameField>
        <label>Enrollment Answer Discription</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GradeAccessRestService.cls
// Accesible from ~/services/apexrest/leadqual
@RestResource(urlMapping='/gradeaccess')
global class GradeAccessRestService{
    
    @HttpPost
    global static String gradLeadCare(String jsonstring)
    {

        
        AnswerInternalClass student= (AnswerInternalClass)JSON.deserialize(jsonstring, AnswerInternalClass.class);
        
       Set<String> questions = student.data.keySet();
      List<String> answrs = new List<String>();
      
      for (String q : questions)
      {
          answrs.add(student.data.get(q));
      }
      
      
      List<EnrollmentAnswers__C> activeAnswers = [SELECT AnswerText__c, Id, QuestionKey__c, QuestionText__c, Multiplier__c ,MultiplierValue__c, Value__c FROM EnrollmentAnswers__c
        where answertext__C in :answrs];
       
       Double leadScoreResult = 0.0;
        
       for (EnrollmentAnswers__C ans : activeAnswers)
       {
       
           if (ans.QuestionText__c.equals('What year did you graduate from high school?'))
           {
             System.debug('GRAD');
                Long gradYear = Long.valueOf(ans.AnswerText__c);
                Long expectedAge = (2014 - gradYear) + 18;
                System.debug(expectedAge);
                // Possitive grade if between 25 and 40
                if (expectedAge >= 25 && expectedAge <= 40){
                    leadScoreResult += 0.206504671635885;
                } 
                // Otherwise, no change
                else {
                    leadScoreResult += 0.0;
                }
             
             
           }
           else
           {
                    leadScoreResult += (ans.Multiplier__c * ans.MultiplierValue__c);  
           
           }
         
         }
         leadScoreResult += -5.56783865284557;
        Double finalResult = Math.exp(leadScoreResult)/ (1 + Math.exp(leadScoreResult));
        
        System.debug(finalResult );
        
        // Return as ScoreResult Object
        System.debug( CAREforceUtility.decodeGrade(finalResult));
       
       
       
       
       
        
       return null;
                     
    }
    
    
    
  public class AnswerInternalClass{
      String wguainf {get;set;}
      Map<String,String> data {get;set;}
      
        
  
        
  }
    

}