src/objects/ExternalLeadContactControl__c.object
<CustomObject>
    <description>This object will control the integration with LeadQual and allow the modification of parameters for 
the assignment of pre-leads to external vendor 
ExternalLeadContactControl</description>
    <label>External Lead Contact Control</label>
    <nameField>
        <label>ExternalLeadContactControl Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Lead Contact Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ExternalLeadContactControl__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Lead Contact Control</label>
        <referenceTo>ExternalLeadContactControl__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StopEmails__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Opts the student out of emails.</description>
        <label>Stop Emails</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StopPhoneCalls__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Opts the student out of phone calls</description>
        <label>Stop Dialer</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/CAREforceLeadQualRESTServices.cls
// Accesible from ~/services/apexrest/leadqual
@RestResource(urlMapping='/leadqual')
global class CAREforceLeadQualRESTServices {

    @HttpPost
    global static Map<String, String> leadQual(String CAREProfileID, String CallDisposition, String EnrollmentNoteType, String Notes,
                                                String ContactTimestamp, String DoNotCall, String DoNotEmail) 
    {
         system.debug('~~~~~~~~~ CAREProfileID ~~~~~~~~~~~~~~~~~~~ ' + CAREProfileID);                         
        Map<String, String> retVal = new Map<String, String>{};                          
        Opportunity careProf = [Select id, ExternalLeadContactControl__c, StopPhoneCalls__c, StopEmails__c 
                                from Opportunity where id = :CAREProfileID];
   //     System.debug('careProf'); 
   //     System.debug(careProf); 
        if (careProf.ExternalLeadContactControl__c <> null)
        {
            ExternalLeadContactControl__c elcc = [Select id, name  from ExternalLeadContactControl__c where id = :careProf.ExternalLeadContactControl__c]; 
     //       System.debug('elcc' + elcc);
            
            if (elcc.name <> 'LeadQual')
            {
                System.debug('LeadQual Post Error(not a leadqual lead): ' + CAREProfileID);
                retVal.put('Status','Failure');
            }
            else
            {
                Task t = new Task();
                t.WhatId = careProf.id ;
                t.CallDisposition__c = CallDisposition;
                t.Description = Notes;
                t.Subject = 'LeadQual - See Notes ';
                DateTime dt = Datetime.parse(ContactTimestamp);
               // t.ActivityDate = dt;
                t.EnrollmentNoteType__c = EnrollmentNoteType;
                if (DoNotCall == 'Yes')
                {
                    careProf.StopPhoneCalls__c = true;
                }
                if (DoNotEmail == 'Yes')
                {
                    careProf.StopEmails__c = true;
                }
                insert t;
                update careProf;
                retVal.put('Status','Success');
         }
         }
         else
         {
            System.debug('LeadQual Post Error(null lead): ' + CAREProfileID);
            retVal.put('Status','Failure'); 
                                         
         }   
        
        return retVal;
    }
}