src/objects/FDPCourseCancel__c.object
<CustomObject>
    <description>Cancellation of registered courses. used for import from oracle.</description>
    <fields>
        <fullName>TermCode__c</fullName>
        <label>Term Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>uniqueid__c</fullName>
        <externalId>true</externalId>
        <label>uniqueid</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>FDP Course Cancel</label>
    <nameField>
        <label>FDPCourseCancel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FDP Course Cancels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentCompletionCourse__c.object
<CustomObject>
    <description>This stores the information for the results of the courses.</description>
    <fields>
        <fullName>BannerActivityDate__c</fullName>
        <description>Banner activity date</description>
        <label>Banner Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if the course was passed.  False if the course was failed for that term.</description>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The internal identifier of the student.</description>
        <label>PIDM</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusDate__c</fullName>
        <description>The date when this occurred</description>
        <label>Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The student whom this completion task belongs to.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Completion Courses</relationshipLabel>
        <relationshipName>StudentCompletionCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TermCode__c</fullName>
        <description>The term code when this course was completed (or failed)</description>
        <label>Term Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueId__c</fullName>
        <description>The unique ID for this record. Externally set.</description>
        <externalId>true</externalId>
        <label>UniqueId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The WGUCourse Version for this completed course</description>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Student Completion Courses</relationshipLabel>
        <relationshipName>StudentCompletionCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Completion Course</label>
    <nameField>
        <label>PAMS Course ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Completion Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestFDPTriggers.cls
@isTest
public class TestFDPTriggers{
   @IsTest
    public static void testFDPCourseCancelTrigger(){
   FDPCourseCancel__C cal=new FDPCourseCancel__C();
   cal.uniqueid__c='test';
   insert cal;

}
 @IsTest
    public static void testStudentCompletionCourseTrigger(){
     //StudentCompletionCourse__c cal=new  StudentCompletionCourse__c(BannerActivityDate__c =Date.now(),Complete__c='Completed',PIDM__c='11' ,StatusDate__c=Date.now(),Student__c  ='12312', TermCode__c='201206',UniqueId__c='test' , WGUCourseVersion__c='123123' );
    // insert cal;

    }

}