src/objects/FieldExperience__c.object
<CustomObject>
    <description>This object represents the field experiences application. Students have access to the this object in the customer portal. There are multiple record types including PCE/DT, BSHI, MSSP, etc.</description>
    <label>Field Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieldExperienceProcess__c.object
<CustomObject>
    <description>The object that represents field experience-related processes such as placements, observations, appeals, etc.</description>
    <fields>
        <fullName>FieldExperience__c</fullName>
        <label>Field Experience</label>
        <referenceTo>FieldExperience__c</referenceTo>
        <relationshipLabel>Field Experience Processes</relationshipLabel>
        <relationshipName>FieldExperiencesProcesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Field Experience Process</label>
    <nameField>
        <label>Field Experiences Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experience Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FinancialApplication__c.object
<CustomObject>
    <description>Financial Application used by the Scholarship department for evaluation scholarship application and award or deny based on the information provided by the student.</description>
    <fields>
        <fullName>FieldExperience__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Field Experience</label>
        <referenceTo>FieldExperience__c</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>FinancialApplications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application</label>
    <nameField>
        <label>Financial Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinancialAward__c.object
<CustomObject>
    <description>Details information specific to each scholarship/fund that can be awarded to a student.</description>
    <fields>
        <fullName>FinancialApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look-up field linking Financial Award to Financial Application</description>
        <label>Financial Application</label>
        <referenceTo>FinancialApplication__c</referenceTo>
        <relationshipLabel>Financial Awards</relationshipLabel>
        <relationshipName>FinancialAwards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Award</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Financial Award Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentProcess__c.object
<CustomObject>
    <description>Custom object to manage student processes by record type.</description>
    <fields>
        <fullName>FieldExperience__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Field Experience</label>
        <referenceTo>FieldExperience__c</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>StudentProcesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Process</label>
    <nameField>
        <label>Student Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentTaskAttempt__c.object
<CustomObject>
    <description>Object Description: Used to track vendor assessment scores information.</description>
    <label>Student Task Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Task Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TeacherSuccess__c.object
<CustomObject>
    <description>Contains information about student disposition concerns, field concerns and cohort seminar. This object contains sensative student information and should only be available to a limited number of profiles (Teacher Success, Student Services, etc).</description>
    <label>Teacher Success</label>
    <nameField>
        <label>Teacher Success Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teacher Success</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TransferEvaluation__c.object
<CustomObject>
    <description>A Transfer evaluation is the parent object of the equivalent courses that will given to the student from their transfer work. It controls the overall status and assignment of the evaluation.</description>
    <label>Transfer Evaluation</label>
    <nameField>
        <label>Transfer Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfer Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuickCaseController.cls
/*Case Controller Extension Created to manage the quick case functionality
 * Author Mike Slade
 * Western Governors University 
 *
 * Date Feb 20 2013
 * Modified 09/27/2013 - Added Student Task Attempt to the case.
 */
public class QuickCaseController{

    private contact cont {get;set;}
    private string contactId {get;set;}
    private string caseId {get;set;}
    private string objectId {get;set;}
    private string testVal {get;set;}
    private string caseTag {get;set;}
    string recordType;
    public string queueName;
    id ownerId;
    
    public QuickCaseController(ApexPages.StandardController controller)
    {
        this.cont = [select id from contact where id =:ApexPages.CurrentPage().getParameters().get('ContactId')];
        contactID =cont.id;
        objectId = ApexPages.CurrentPage().getParameters().get('ObjectId');
        recordType =ApexPages.CurrentPage().getParameters().get('RecordType');
        queueName =ApexPages.CurrentPage().getParameters().get('QueueName');
        //testVal = 'Initial';
    }
    
    public void createCase()
    {
        ID RtId;
         try
       {
         if (recordType != null)
          RtId = [select id from recordType where sObjectType='Case' and name = :RecordType].id;
           
         if (queueName !=null) //get the queue ID if queue specified, else use the current user for owner
            ownerId=[Select id From QueueSobject where Queue.Name=:queueName].id;
         else
            ownerId=UserInfo.getUserId();
       }
       catch(exception exp)
       {
           testVal = 'Invalid Record Type or Queue Name'; 
           return;
       }
       
      Try
      {
        //check to see if there is already a case for this user and this person in progress for accidental page refreshes or unfinished emails
        list<case> ExistingCase = [select id,refTag__c from case 
                                   where ownerId = :OwnerId 
                                   and contactId=:cont.id 
                                   and QuickCase__c=true 
                                   and Status = 'New'];
          
        if (ExistingCase.size() >0 ) 
        {   
         if (RtID !=ExistingCase[0].recordTypeId )//update the record type if different
         {
             ExistingCase[0].recordTypeId=RtID;
             update existingCase[0];
         }
         caseID=ExistingCase[0].id;
         caseTag=ExistingCase[0].refTag__c;
        }
        else
        {
            Case newCase;
        //if no case exists, create one with the quick case flag set to true
         	list<case> Cases = new list<case>();
            if (recordType != null)
        	   newCase = new Case(contactid =cont.id , Subject='Outgoing Message', recordTypeid=RtId, QuickCase__c=true, ownerId=this.ownerId) ;  
            else
               newCase = new Case(contactid =cont.id , Subject='Outgoing Message', QuickCase__c=true, ownerId=this.ownerId) ; //let the default record type
                
			insert newCase ;  
        	caseId =newCase.id;
            caseTag  = [select refTag__c from case where Id=:caseId limit 1].refTag__c;
        }
        
       caseTag = '<BR/> ' + caseTag ;
        //if linked to an object make that link
		if (objectID != null)
        {
           Case currCase = [SElECT Id, 
                                    FieldExperienceProcess__c,
                                    FieldExperience__c,
                                    TransferEvaluation__c,
                                    FinancialApplication__c,
                                    FinancialAward__c,
                                    TeacherSuccess__c,
                                    StudentProcess__c,
                            		StudentTaskAttempt__c
                             FROM Case 
                             WHERE Id = :caseId 
                             LIMIT 1];
            
            currCase = InboundEmailHandler.attachParentObject(currCase, ObjectID);
            //testVal =currCase.TeacherSuccess__c;
        }
       }
        catch(Exception e)
       {
            String tr=e.getMessage();
            Integer lineNum = e.getLineNumber();
            system.debug(tr);
            ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'Error Occurred in Case Creation ' + lineNum +  ' ' + tr);
            ApexPages.addMessage(errormsg )  ;  
       }
        
    }  
    
    public string getCaseID()   { return this.caseId; }
    public string getCaseTag() {return this.caseTag;}
    public string getObjectId() {return this.objectId;}
    public string getContactId() {return this.contactId;}
    public string getTestVal() {return this.testVal;}
    
  	
}