src/objects/FieldExperience__c.object
<CustomObject>
    <description>This object represents the field experiences application. Students have access to the this object in the customer portal. There are multiple record types including PCE/DT, BSHI, MSSP, etc.</description>
    <fields>
        <fullName>ClinicalSupervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person observing the student during DT.</description>
        <label>Clinical Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experiences (Clinical Supervisor)</relationshipLabel>
        <relationshipName>FEClinicalSupervisor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experiences</relationshipLabel>
        <relationshipName>FieldExperiences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieldExperienceProcess__c.object
<CustomObject>
    <description>The object that represents field experience-related processes such as placements, observations, appeals, etc.</description>
    <fields>
        <fullName>CheckFinalObservationOverride__c</fullName>
        <description>For split placements sometimes the last observation the HT/CS has to do is not the Final.  This override will control that</description>
        <inlineHelpText>For split placements sometimes the last observation the HT/CS has to do is not the Final.  This override will control that</inlineHelpText>
        <label>Check Final Observation Override</label>
        <picklist>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midterm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CheckReadyForEval__c</fullName>
        <description>Whether or not the student should be picked up by the check process to finish and process the check.</description>
        <formula>IF( CheckWorkComplete__c, &apos;Y&apos;,
  CASE  ( $RecordType.Name, 
   &apos;CS Request&apos;,
               IF(  BLANKVALUE(TEXT(CheckFinalObservationOverride__c),&apos;Final&apos;)=&apos;Final&apos;, 
                                                                                                                 IF( FieldExperience__r.ObservationCSFinalComplete__c = TRUE, &apos;Y&apos;,&apos;N&apos;),
                                                                                                                    IF(AND(TEXT(CheckFinalObservationOverride__c)=&apos;Midterm&apos;, 
                                                                                                                        FieldExperience__r.ObservationCSMidtermComplete__c =TRUE ),&apos;Y&apos;,&apos;N&apos;  )  ),
    &apos;Placement Attempt&apos;,  
             IF(  BLANKVALUE(TEXT(CheckFinalObservationOverride__c),&apos;Final&apos;)=&apos;Final&apos;, 
                                                                                                                 IF( FieldExperience__r.ObservationHTFinalComplete__c = TRUE, &apos;Y&apos;,&apos;N&apos;),  
                                                                                                                     IF(AND(TEXT(CheckFinalObservationOverride__c)=&apos;Midterm&apos;, 
                                                                                                                 FieldExperience__r.ObservationHTMidtermComplete__c =TRUE ),&apos;Y&apos;,&apos;N&apos;  )  ),              
    null
   )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Whether or not the student should be picked up by the check process to finish and process the check.</inlineHelpText>
        <label>Check Ready for Eval</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CheckStatus__c</fullName>
        <description>The check status is the final check/approval before a check gets generated for the prescribed amounts</description>
        <inlineHelpText>The check status is the final check/approval before a check gets generated for the prescribed amounts</inlineHelpText>
        <label>Check Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Payment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CheckTotalAmount__c</fullName>
        <formula>CheckBaseAmount__c  +  CheckMileageAmout__c +  CheckExpenseAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Check Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CheckWorkComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manual override to appear on the pending check list even if all observations are not in</description>
        <inlineHelpText>This field is a manual override for the auto mechanisms based on observations</inlineHelpText>
        <label>Check Work Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ClinicalSupervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experience Processes (Clinical Supervisor)</relationshipLabel>
        <relationshipName>FieldExperienceProcesses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldExperience__c</fullName>
        <label>Field Experience</label>
        <referenceTo>FieldExperience__c</referenceTo>
        <relationshipLabel>Field Experience Processes</relationshipLabel>
        <relationshipName>FieldExperiencesProcesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HostTeacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The teacher hosting our student for demonstration teaching</description>
        <label>Host Teacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>FE Host Teacher</relationshipLabel>
        <relationshipName>Field_Experience_Processes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ObservationOutcome__c</fullName>
        <description>Indicates the final result on this Field Experience Process record</description>
        <inlineHelpText>Indicates the final result on this Field Experience Process record</inlineHelpText>
        <label>Observation Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed but Watch</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ObservationStatus__c</fullName>
        <description>Indicates the current phase this Field Experience Process is in</description>
        <inlineHelpText>Indicates the current phase this Field Experience Process is in</inlineHelpText>
        <label>Observation Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requires Teacher Success Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed by Teacher Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Placeholder 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Placeholder 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Reply</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ObservationType__c</fullName>
        <description>The observation number / type.</description>
        <inlineHelpText>Indicates the type of observation or evaluation</inlineHelpText>
        <label>Observation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Final - Clinical Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final – CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final EDL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final ELL &amp; MSSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midterm EDL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCSS Midterm Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCSS Final Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation BASP 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation BASP 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation BASP 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation BASP – Extra 1 (if required)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation BASP – Extra 2 (if required)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation EDL 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation EDL 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation ELL 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation ELL 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation ELL – Additional 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation MSSP 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation MSSP 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation MSSP 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation MSSP 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation MSSP 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation MSSP 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observation MSSP – Extra 1 (if required)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Field Experience Processes</relationshipLabel>
        <relationshipName>Field_Experience_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Experience Process</label>
    <nameField>
        <label>Field Experiences Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Experience Processes</pluralLabel>
    <recordTypes>
        <fullName>Observation</fullName>
        <active>true</active>
        <label>Observation</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RelatedListFEP.cls
public class RelatedListFEP {

private List<FieldExperienceProcess__c> FEPs;
private FieldExperience__c FE;
public RelatedListFEP(ApexPages.standardController controller) {
    this.FE= (FieldExperience__c)controller.getRecord();
    }
public List<FieldExperienceProcess__c> getFEPs()
    {
        FEPs = [Select Id, Name, Student__c, CheckReadyForEval__c, CheckStatus__c, CheckWorkComplete__c, HostTeacher__c, ClinicalSupervisor__c, CheckTotalAmount__c, CheckFinalObservationOverride__c, ObservationStatus__c, ObservationType__c, ObservationOutcome__c from FieldExperienceProcess__c where RecordType.Name in ('Placement Attempt','Observation','CS Request') and FieldExperience__r.Id = :FE.Id];
        return FEPs;
    }
}