src/objects/FinancialApplication__c.object
<CustomObject>
    <description>Financial Application used by the Scholarship department for evaluation scholarship application and award or deny based on the information provided by the student.</description>
    <fields>
        <fullName>ApplicationStatus__c</fullName>
        <description>Status of application as it moves through the workflow.</description>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Application</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Document Gathering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Prep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending FA Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DUPLICATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount Applied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount Appealed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Bi-Weekly Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait for Tuition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait for CU&apos;s</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look-up to Opportunity Object (CARE)</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>FinancialApplications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Link to the contact from financial application</description>
        <inlineHelpText>The student that this financial application belongs to</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>FinancialApplications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application</label>
    <nameField>
        <label>Financial Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>StudentContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>StudentContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CARE Profile</relationshipLabel>
        <relationshipName>CAREProfile</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/MethodOfPaymentUtility.cls
/* 
Utility class for MethodOfPaymentTrigger.
Author- Bhavadeep Raavi
Modified by Mike Slade and Brian Johnson to add 3rd party
Sharing rules are enforced
Modified 3/18/2013 by Will Slade to use future method
*/

public with sharing class MethodOfPaymentUtility{

// To create a Financial Application for Military Funding
    public static void createFinApp( String oppIdListJSON, String recordTypeName )
    {
        if (Limits.getFutureCalls() > 8 || System.isFuture())
        {
            processCreateFinApp( oppIdListJSON, recordTypeName);
        }
        else
        {
            asyncCreateFinApp( oppIdListJSON, recordTypeName);
        }
    }
    
    @future
    private static void asyncCreateFinApp(String oppIdListJSON, String recordTypeName)
    {
        processCreateFinApp( oppIdListJSON, recordTypeName);
    }

    private static void processCreateFinApp(String oppIdListJSON, String recordTypeName )
    {
        List<Id> oppIdList = (List<Id>)JSON.deserialize( oppIdListJSON, List<Id>.class );        
        Map<Id,Id> oppFAMap = new Map<Id,Id>();
        List<FinancialApplication__c> faListNew=new List<FinancialApplication__c>();
        id RtId =[select id from RecordType 
                    where SobjectType='FinancialApplication__c'  
                    and developerName = :recordTypeName limit 1].id;
        
        List<FinancialApplication__c> faList=[select id,Opportunity__c, recordTypeId
                                              from FinancialApplication__c 
                                              where Opportunity__c in:oppIdList 
                                              and RecordtypeId=:RtId];
        for(FinancialApplication__c fa: faList)
        {
            oppFAMap.put(fa.Opportunity__c,fa.Id);    
        }
        List<Opportunity> oppList=[select id,StudentContact__c from Opportunity where id in:oppIdList];
        for(Opportunity opp: oppList){
            if((oppFAMap!=null && oppFAMap.get(opp.id)==null) || (faList.isEmpty())){
                FinancialApplication__c faNew=new FinancialApplication__c();
                faNew.Opportunity__c = opp.id;
                faNew.Student__c =opp.StudentContact__c;
                faNew.recordtypeId=RtId;
                faNew.ApplicationStatus__c='New Application';
                faListNew.add(faNew);        
            }                    
        }
        if(faListNew!=null && faListNew.size()>0){
            insert faListNew;
        }   
    
    }


}