src/objects/FinancialApplication__c.object
<CustomObject>
    <description>Financial Application used by the Scholarship department for evaluation scholarship application and award or deny based on the information provided by the student.</description>
    <fields>
        <fullName>FinancialAwardAmount__c</fullName>
        <description>Roll-up of Total Amount from the Financial Award object through trigger.</description>
        <label>Financial Award Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Link to the contact from financial application</description>
        <inlineHelpText>The student that this financial application belongs to</inlineHelpText>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>FinancialApplications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalTermAmount__c</fullName>
        <description>Roll-up of Total term amount from the Financial Award object through trigger.</description>
        <label>Total Term Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Application</label>
    <nameField>
        <label>Financial Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinancialAward__c.object
<CustomObject>
    <description>Details information specific to each scholarship/fund that can be awarded to a student.</description>
    <fields>
        <fullName>FinancialApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look-up field linking Financial Award to Financial Application</description>
        <label>Financial Application</label>
        <referenceTo>FinancialApplication__c</referenceTo>
        <relationshipLabel>Financial Awards</relationshipLabel>
        <relationshipName>FinancialAwards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TermAmount__c</fullName>
        <description>The total amount to be paid out each term.</description>
        <label>Term Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <description>Total awarded fund amount.</description>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Award</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Financial Award Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestFinaincialAwardUtility.cls
/*
This test class is for code coverage for FinancialAwardUtility class and FinancialAwardTrigger
Author- Bhavadeep Raavi
Updated 02/01/2013 By Mike Slade for Person Account Refactor.  Changed to contact and added appropriate assertions
*/
@isTest(SeeAllData=false)
public class TestFinaincialAwardUtility{
private static testmethod void FinaincialAwardUtilityTest()
{
    Contact con =  TestStudentUser.getTestStudentContact();
    
    User testUser = [Select id from User where Profile.Name = 'System Administrator' AND isActive = true LIMIT 1];
    System.RunAs( testUser ) 
    {   
    Test.startTest();
    FinancialApplication__c fapp = new FinancialApplication__c(Name='Test',Student__c = con.Id ,FinancialAwardAmount__c=0,TotalTermAmount__c=0);
    insert fapp;
    
    FinancialAward__c fa = new FinancialAward__c(FinancialApplication__c =fapp.Id,TotalAmount__c=400,TermAmount__c=200);
    insert fa;
    Test.stopTest();
        
    list<financialApplication__c> fappAfter=[select FinancialAwardAmount__c,TotalTermAmount__c from financialApplication__c where id = :fapp.id];
   
    System.assert(fappAfter[0].FinancialAwardAmount__c== 400, 'Award Amount Updated');
    System.assert(fappAfter[0].TotalTermAmount__c== 200, 'Term Amount Updated');
     }

   }
    
//This method test the deletion of the award which should zero out the applciation award amount
private static testmethod void FinaincialAwardUtilityDeleteTest()
{
      Contact con =  TestStudentUser.getTestStudentContact();
    
    User testUser = [Select id from User where Profile.Name = 'System Administrator' AND isActive = true LIMIT 1];
    System.RunAs( testUser ) 
    {   
    Test.startTest();
    FinancialApplication__c fapp = new FinancialApplication__c(Name='Test',Student__c = con.Id ,FinancialAwardAmount__c=0,TotalTermAmount__c=0);
    insert fapp;
    
    FinancialAward__c fa = new FinancialAward__c(FinancialApplication__c =fapp.Id,TotalAmount__c=400,TermAmount__c=200);
    insert fa;
        
    delete fa;
   Test.stopTest();
        list<financialApplication__c> fappAfterDel=[select FinancialAwardAmount__c,TotalTermAmount__c 
                                             from financialApplication__c 
                                             where id = :fapp.id];
    System.assert(fappAfterDel[0].FinancialAwardAmount__c== 0, 'Award Amount Removed');
    System.assert(fappAfterDel[0].TotalTermAmount__c== 0, 'Term Amount Removed');
    }
}
}