src/objects/FinancialApplication__c.object
<CustomObject>
    <description>Financial Application used by the Scholarship department for evaluation scholarship application and award or deny based on the information provided by the student.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look-up to Opportunity Object (CARE)</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>FinancialApplications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application</label>
    <nameField>
        <label>Financial Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Applications</pluralLabel>
    <recordTypes>
        <fullName>Scholarship</fullName>
        <active>true</active>
        <description>A Scholarship application</description>
        <label>Scholarship</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FinancialRequirement__c.object
<CustomObject>
    <description>Details about each requirement for a specific fund associated to the Financial Application.</description>
    <fields>
        <fullName>FinancialApplication__c</fullName>
        <description>Master-detail relationship linking Financial Requirements to Financial Application. Financial Application being the parent.</description>
        <label>Financial Application</label>
        <referenceTo>FinancialApplication__c</referenceTo>
        <relationshipLabel>Financial Requirements</relationshipLabel>
        <relationshipName>FinancialRequirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Requirement</label>
    <nameField>
        <label>Financial Requirements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requirements</pluralLabel>
    <recordTypes>
        <fullName>Scholarship</fullName>
        <active>true</active>
        <description>Requirement of scholarship application.</description>
        <label>Scholarship</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KeyValue__c.object
<CustomObject>
    <description>Represents the Key Value pairs with record types.</description>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>The external reference code for the title in the group.</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Key Value</label>
    <nameField>
        <label>Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RequirementRule__c.object
<CustomObject>
    <description>This is a rule table for all objects that add requirements through an automated proces.</description>
    <fields>
        <fullName>FinRequirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Financial Requirement Value</description>
        <inlineHelpText>The Financial Requirement Value</inlineHelpText>
        <label>Fin Requirement</label>
        <referenceTo>KeyValue__c</referenceTo>
        <relationshipLabel>RequirementRules</relationshipLabel>
        <relationshipName>RequirementRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requirement Rule</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Requirement Rules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RequirementRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestFinancialApplicationUtility.cls
/*******************************************************************************
* Test Class for FinancialApplicationUtility and FinancialApplicationTrigger.
* Author - Will Slade
* 3/20/2013 - Created class
********************************************************************************/
@isTest()
private class TestFinancialApplicationUtility
{  
    private static testmethod void TestFinancialApplicationUtility()
    {
        List<RecordType> thirdPartyRT = [SELECT Id FROM RecordType WHERE SobjectType = 'FinancialApplication__c' AND Name = 'Third Party' LIMIT 1];
        List<RecordType> reqRuleBadRT = [SELECT Id FROM RecordType WHERE SObjectType = 'RequirementRule__c' AND Name = 'Scholarship Import' LIMIT 1];
        List<RecordType> reqRuleRT = [SELECT Id FROM RecordType WHERE SObjectType = 'RequirementRule__c' AND Name = 'Third Party' LIMIT 1];        
            
        Opportunity opp1 = new Opportunity( Name = 'TestFinApp Opp1', CloseDate = Date.today().addDays(3), StageName = 'Prospecting');
        insert opp1;
        
        System.assert(opp1.Id != null);
        
        KeyValue__c kv = new KeyValue__c( Name = 'Third Party Voucher', Value__c = 'Third Party Voucher', ExternalID__c = 'Third Party Voucher');
        insert kv;
        
        RequirementRule__c reqRule1 = new RequirementRule__c( RecordTypeId = reqRuleRT[0].Id, FinRequirement__c = kv.Id );
        insert reqRule1;
        
        RequirementRule__c reqRule2 = new RequirementRule__c( RecordTypeId = reqRuleRT[0].Id, FinRequirement__c = kv.Id );
        insert reqRule2;                
        
        RequirementRule__c reqRule3 = new RequirementRule__c( RecordTypeId = reqRuleBadRT[0].Id, FinRequirement__c = kv.Id );
        insert reqRule3;
        
        List<RequirementRule__c> reqRules = [SELECT Id FROM RequirementRule__c LIMIT 5];
        System.assertEquals(reqRules.size(), 3);                            
        
        Test.startTest();   
         
        FinancialApplication__c fa = new FinancialApplication__c(Name = 'Test FAReq1', Opportunity__c = opp1.id, RecordTypeId = thirdPartyRT[0].Id);
        insert fa;
        
        System.assert(fa.Id != null);
        
        Test.stopTest();
        
        List<FinancialRequirement__c> finReqs = [SELECT Id, FinancialRequirement__c.RecordTypeId FROM FinancialRequirement__c WHERE FinancialApplication__c = :fa.Id LIMIT 5];
        System.assertEquals(finReqs.size(), 2);
        
        List<RecordType> finReqRT = [SELECT Id FROM RecordType WHERE SObjectType = 'FinancialRequirement__c' AND Name = 'Third Party' LIMIT 1];
        System.assertEquals(finReqs[0].RecordTypeId, finReqRT[0].Id);
    }
}