src/objects/KeyValue__c.object
<CustomObject>
    <description>Represents the Key Value pairs with record types.</description>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Key Value</label>
    <nameField>
        <label>Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentTranscript__c.object
<CustomObject>
    <description>Object to manage the transcripts that must be collected through in-take and viewed by Mentors</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Student Transfer Institution</relationshipLabel>
        <relationshipName>opportunityTransferInstitution</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <formula>Opportunity__r.Account.PIDM__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PIDM</label>
        <type>Text</type>
    </fields>
    <label>Student Transfer Institution</label>
    <nameField>
        <displayFormat>Institution-{0000}</displayFormat>
        <label>Student Transfer Institution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transfer Institution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TranscriptToBanner__c.object
<CustomObject>
    <description>Sync object to house Transcripts being pushed to Banner</description>
    <fields>
        <fullName>ActionNeeded__c</fullName>
        <label>Action Needed</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DegreeCode__c</fullName>
        <description>Degree code from the transfer attendance</description>
        <label>Degree Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>PIDM of the related Opportunity</description>
        <label>PIDM</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <description>Salesforce ID of the parent object as it relates to the BANNER tables</description>
        <label>Parent Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RefId__c</fullName>
        <description>Id of the Salesforce record to which this control object is directly linked</description>
        <externalId>true</externalId>
        <label>Ref Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentTransferInstitution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Transfer Institution</label>
        <referenceTo>StudentTranscript__c</referenceTo>
        <relationshipLabel>Transcripts to Banner</relationshipLabel>
        <relationshipName>TranscriptsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransferAttendance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer Attendance</label>
        <referenceTo>TransferAttendance__c</referenceTo>
        <relationshipLabel>Transcripts to Banner</relationshipLabel>
        <relationshipName>TranscriptsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transcript to Banner</label>
    <nameField>
        <displayFormat>T2B-{0000000}</displayFormat>
        <label>Transcript to Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcripts to Banner</pluralLabel>
    <recordTypes>
        <fullName>TransferAttendance</fullName>
        <active>true</active>
        <label>TransferAttendance</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TransferAttendance__c.object
<CustomObject>
    <description>This is a record of attendance at other institutions including any degrees awarded, program, GPA, and dates of attendance.</description>
    <fields>
        <fullName>DegreeAwarded__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the degree awarded at a prior institution.</description>
        <label>Degree Awarded</label>
        <referenceTo>KeyValue__c</referenceTo>
        <relationshipLabel>Transfer Attendance</relationshipLabel>
        <relationshipName>TransferAttendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentTransferInstitution__c</fullName>
        <label>Student Transfer Institution</label>
        <referenceTo>StudentTranscript__c</referenceTo>
        <relationshipLabel>Transfer Attendance</relationshipLabel>
        <relationshipName>TransferAttendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transfer Attendance</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Transfer Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transfer Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TransferAttendanceUtility.cls
/*****************************************************************************************
* Name: TransferAttendanceUtility
* Author: Will Slade
* Purpose: Creates data integration records for Transfer Attendance via trigger of same name
* Revisions: 
*    - 4/17/2013 Created Class
*
******************************************************************************************/

public class TransferAttendanceUtility
{
    public static void createTranscriptsToBanner(String attendanceListJSON)
    {
        if (Limits.getFutureCalls() > 8 || System.isFuture())
        {
            processCreateTranscriptsToBanner(attendanceListJSON);
        }
        else
        {
            asyncCreateTranscriptsToBanner(attendanceListJSON);
        }
    }
    
    @future
    public static void asyncCreateTranscriptsToBanner(String attendanceListJSON)
    {
        processCreateTranscriptsToBanner(attendanceListJSON);
    }

    public static void processCreateTranscriptsToBanner(String attendanceListJSON)
    {
        List<TransferAttendance__c> attendanceList = (List<TransferAttendance__c>) JSON.deserialize(attendanceListJSON, List<TransferAttendance__c>.class);
        List<TranscriptToBanner__c> trToBanInsertList = new List<TranscriptToBanner__c>();
        RecordType trAttRT = [SELECT Id FROM RecordType WHERE SObjectType = 'TranscriptToBanner__c' AND DeveloperName = 'TransferAttendance' LIMIT 1];
        Map<Id, Id> attToCtrlMap = new Map<Id, Id>();
        
        //Loop through the list of attendances and populate the keyset of the map with the record ids
        for (TransferAttendance__c attendance : attendanceList)
        {
            attToCtrlMap.put(attendance.Id, null);
        }
        
        Set<Id> attIdSet = attToCtrlMap.keySet();
        
        attendanceList = [SELECT Id, StudentTransferInstitution__c, DegreeAwarded__r.ExternalId__c, StudentTransferInstitution__r.Pidm__c
                          FROM TransferAttendance__c
                          WHERE Id IN :attIdSet];                           
        
        List<TranscriptToBanner__c> trToBanUpdateList = [SELECT Id, RefId__c, ParentId__c, ActionNeeded__c, TransferAttendance__c,
                                                                TransferAttendance__r.DegreeAwarded__r.ExternalId__c,
                                                                TransferAttendance__r.StudentTransferInstitution__r.Opportunity__r.Pidm__c                                                                
                                                         FROM TranscriptToBanner__c
                                                         WHERE RecordTypeId = :trAttRT.Id
                                                         AND TransferAttendance__c IN :attIdSet];
        
        //2nd pass through map - update values with existing control object ids and mark them as Update needed                                         
        for (TranscriptToBanner__c trToBan : trToBanUpdateList)
        {
            attToCtrlMap.put(trToBan.TransferAttendance__c, trToBan.Id);
            trToBan.actionNeeded__c = trToBan.actionNeeded__c == 'Insert' ? 'Insert' : 'Update';
            trToBan.DegreeCode__c = trToBan.TransferAttendance__r.DegreeAwarded__r.ExternalId__c;
            trToBan.Pidm__c = trToBan.TransferAttendance__r.StudentTransferInstitution__r.Opportunity__r.Pidm__c;
        }                                          
        
        for (TransferAttendance__c attendance : attendanceList)
        {
            if (attToCtrlMap.get(attendance.Id) == null)
            {
                trToBanInsertList.add(new TranscriptToBanner__c(TransferAttendance__c = attendance.Id,
                                                                StudentTransferInstitution__c = attendance.StudentTransferInstitution__c,
                                                                RefId__c = String.valueOf(attendance.Id),
                                                                ParentId__c = String.valueOf(attendance.StudentTransferInstitution__c),
                                                                RecordTypeId = trAttRT.Id,
                                                                ActionNeeded__c = 'Insert',
                                                                DegreeCode__c = attendance.DegreeAwarded__r.ExternalId__c,
                                                                Pidm__c = attendance.StudentTransferInstitution__r.Pidm__c));
            }
        }
        
        update trToBanUpdateList;
        insert trToBanInsertList;
    }    
}