src/objects/KnowledgeBaseReporting__c.object
<CustomObject>
    <description>This object is used to report on KB.</description>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Article version id&apos;s from knowledge base (kav objects)</description>
        <externalId>true</externalId>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Knowledge Base Reporting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>KB Reporting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Base Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KnowledgeBaseWguCourseVersionLink__c.object
<CustomObject>
    <description>Junction object between a Knowledge Article Reporting (Knowledge Article) and Course Versions</description>
    <fields>
        <fullName>KnowledgeArticleVersionId__c</fullName>
        <externalId>true</externalId>
        <label>KnowledgeArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KnowledgeBaseReporting__c</fullName>
        <label>Knowledge Base Reporting</label>
        <referenceTo>KnowledgeBaseReporting__c</referenceTo>
        <relationshipLabel>WGU Course Version</relationshipLabel>
        <relationshipName>Knowledge_Article_Course_Version_Link</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WGUCourseVersion__c</fullName>
        <label>WGU Course Version</label>
        <referenceTo>WGUCourseVersion__c</referenceTo>
        <relationshipLabel>Knowledge Base Reporting</relationshipLabel>
        <relationshipName>Knowledge_Article_Course_Version_Link</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Knowledge Base WGU Course Version Link</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Knowledge Base WGU Course Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Base WGU Course Version Link</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KnowledgeBaseReportingDAO.cls
/*
*Author John Chan
*Slalom
*/
public with sharing class KnowledgeBaseReportingDAO {
	public static void updateCourseVersionLink(List<KnowledgeBaseWguCourseVersionLink__c> kbCourseVersionLinks, 
			String knowledgeArticleVersionId, Id kbReportId, Set<String> courseVersionIds) {
		//Add
		Map<Id, KnowledgeBaseWguCourseVersionLink__c> existingCourseVersions = new Map<Id, KnowledgeBaseWguCourseVersionLink__c>();
		if (kbCourseVersionLinks != null) {
			for (KnowledgeBaseWguCourseVersionLink__c courseVersionLink : kbCourseVersionLinks) {
				existingCourseVersions.put(courseVersionLink.WGUCourseVersion__c, courseVersionLink);
			}
		}
		
		List<KnowledgeBaseWguCourseVersionLink__c> newKbCourseVersionLinks = null;
		for (String courseVersionId : courseVersionIds) {
			if (!existingCourseVersions.containsKey(courseVersionId)) {
				if (newKbCourseVersionLinks == null) {
					newKbCourseVersionLinks = new List<KnowledgeBaseWguCourseVersionLink__c>();
				}
				newKbCourseVersionLinks.add(new KnowledgeBaseWguCourseVersionLink__c(KnowledgeArticleVersionId__c = knowledgeArticleVersionId, KnowledgeBaseReporting__c = kbReportId, 
					WGUCourseVersion__c = courseVersionId));
			}
		}
		system.debug(newKbCourseVersionLinks);
		if (newKbCourseVersionLinks != null) {
			insert newKbCourseVersionLinks;
		}
		
		//Delete
		List<KnowledgeBaseWguCourseVersionLink__c> deleteCourseVersionLinks = null;
		for (Id courseVersionId : existingCourseVersions.keySet()) {
			if (!courseVersionIds.contains(courseVersionId)) {
				if (deleteCourseVersionLinks == null) {
					deleteCourseVersionLinks = new List<KnowledgeBaseWguCourseVersionLink__c>();
				}
				deleteCourseVersionLinks.add(existingCourseVersions.get(courseVersionId));
			}
		}
		if (deleteCourseVersionLinks != null) {
			delete deleteCourseVersionLinks;
		}
	}
}