src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>MentorRole__c</fullName>
        <description>The mentors can have a specific role assigned, to help with the automatic mentor assignments.</description>
        <inlineHelpText>Please specify a role if this mentor can help 
    At risk students
    Starter Students
    Concentrated 

Of if this mentor is a program manager.</inlineHelpText>
        <label>Mentor Role</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Provost Mentoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapStone Evaluator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capstone Facilitator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capstone Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor Cohort Facilitator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor Project Facilitator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor Technology Facilitator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEPTCHG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Mentoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduation Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Separated From University</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Mentor (Team Lead)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MonthlyProjection__c</fullName>
        <label>Monthly Projection</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The mentor pidm so we can use external id&apos;s</description>
        <externalId>true</externalId>
        <inlineHelpText>The WGU PIDM assigned to this mentor.</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Priority1ProgramCodes__c</fullName>
        <label>Priority 1 Program Codes</label>
        <picklist>
            <picklistValues>
                <fullName>BAECE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAISK8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMA12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMA9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASC9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCB12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCCH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCG12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCPH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASS12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSBUHR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSBUITM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSHI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSITDB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSITND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSITNW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSITSEC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSITSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSMK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSNU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSPRN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSRN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENDEDL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENDELL</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>ProgramCodes__c</fullName>
        <description>The program codes that this mentor can work with students who have that program.</description>
        <inlineHelpText>Enter the programs codes that this mentor is allowed to be assigned students from.</inlineHelpText>
        <label>Program Codes</label>
        <picklist>
            <picklistValues>
                <fullName>AAGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AASITCNE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AASITNA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAECE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESB12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESCH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESG12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESMA12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESMA9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESPH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESSC9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAISK8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAISPK8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMA12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMA9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASC9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCB12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCCH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCG12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCPH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASPNV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASS12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASSPX12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSBUHR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSITNW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSPRN</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>StudentCapacity__c</fullName>
        <description>The number of students that this mentor can handle</description>
        <inlineHelpText>THe number of students that this mentor can be assigned to.</inlineHelpText>
        <label>Student Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TestCustomMentorLookupController.cls
@isTest
private class TestCustomMentorLookupController{

static testMethod void CustomMentorLookUpTest(){   
    Profile prof = [SELECT id from Profile where name = 'LockDown'];
    List<User> users = new List<user>();
    User user1 = new User(LastName='Mentor',FirstName='Standard',pidm__c='123123',Username='a@wgu.edu', Email='a@wgu.edu', Alias='a', CommunityNickname='a', TimeZoneSidKey='GMT'
    , LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=prof.id, LanguageLocaleKey='en_US');
    users.add(user1);
    User user2 = new User(LastName='Mentor',FirstName='State',pidm__c='123124',Username='b@wgu.edu', Email='b@wgu.edu', Alias='b', CommunityNickname='b', TimeZoneSidKey='GMT'
    , LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=prof.id, LanguageLocaleKey='en_US');
    users.add(user2);
    User user3 = new User(LastName='Mentor',FirstName='Starter',pidm__c='123125',Username='c@wgu.edu', Email='c@wgu.edu', Alias='c', CommunityNickname='c', TimeZoneSidKey='GMT'
    , LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=prof.id, LanguageLocaleKey='en_US');
    users.add(user3);
    User user4 = new User(LastName='Mentor',FirstName='Concentrated',pidm__c='123126',Username='d@wgu.edu', Email='d@wgu.edu', Alias='d', CommunityNickname='d', TimeZoneSidKey='GMT'
    , LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=prof.id, LanguageLocaleKey='en_US',state='IN');
    users.add(user4);
    insert users;
    List<Mentor__c> mentors = new List<Mentor__c>();
    Mentor__c mentor1 = new Mentor__c(mentorRole__c='Student Mentor',pidm__c=user1.pidm__c,studentcapacity__c=80,monthlyprojection__c=1,priority1programcodes__c='BSITNW;BSIT',programcodes__c='BSITND;BSITSF');
    Mentor__c mentor2 = new Mentor__c(mentorRole__c='Student Mentor (Concentrated)',pidm__c=user2.pidm__c,studentcapacity__c=80,monthlyprojection__c=0,priority1programcodes__c='BSAC',programcodes__c='BSITND;BSITSF');
    Mentor__c mentor3 = new Mentor__c(mentorRole__c='Student Mentor (Starter)',pidm__c=user3.pidm__c,studentcapacity__c=80,monthlyprojection__c=0,priority1programcodes__c='BSPRN',programcodes__c='BSITND;BSITSF');
    Mentor__c mentor4 = new Mentor__c(mentorRole__c='Student Mentor',pidm__c=user4.pidm__c,studentcapacity__c=80,monthlyprojection__c=0,priority1programcodes__c='BSIT',programcodes__c='BAECE;BSITSF');
    mentors.add(mentor1);
    mentors.add(mentor2);
    mentors.add(mentor3);
    mentors.add(mentor4);
    insert mentors;
    CustomMentorLookUpController controller = new CustomMentorLookUpController();
    PageReference pageRef = new PageReference('/apex/CustomMentorLookup?txt=j_id0%3AmyForm%3Aj_id46%3Aj_id47%3A0%3AMentor__c1&frm=j_id0%3AmyForm&lksearch=&lksrch=');
    test.setCurrentPage(pageRef);
    controller.searchString = 'BSITNW';
    controller.search();
    System.assert(controller.results != null);
    controller.getFormTag();
    System.assertEquals(controller.getFormTag(),pageRef.getParameters().get('frm'));
    controller.getTextBox();
    System.assertEquals(controller.getTextBox(),pageRef.getParameters().get('txt'));
}
}