src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>MentorCeiling__c</fullName>
        <description>Actual amount assigned in a month. Decremented during Auto Mentor Assignment.</description>
        <label>Monthly Remaining (Balance)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MentorRole__c</fullName>
        <description>The mentors can have a specific role assigned, to help with the automatic mentor assignments.</description>
        <inlineHelpText>Please specify a role if this mentor can help 
    At risk students
    Starter Students
    Concentrated 

Of if this mentor is a program manager.</inlineHelpText>
        <label>Mentor Role</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate Provost Mentoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapStone Evaluator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capstone Facilitator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capstone Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor Cohort Facilitator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor Project Facilitator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor Technology Facilitator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEPTCHG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Mentoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduation Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations Analyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Separated From University</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Mentor (Team Lead)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Manager</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Priority1ProgramCodes__c</fullName>
        <label>Priority 1 Program Codes</label>
        <picklist>
            <picklistValues>
                <fullName>BAECE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAISK8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMA12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMA9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASC9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCB12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCCH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCG12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCPH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASS12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSBUHR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSBUITM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSHI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSITDB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSITND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSITNW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSITSEC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSITSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSMK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSNU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSPRN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSRN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENDEDL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENDELL</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>ProgramCodes__c</fullName>
        <description>The program codes that this mentor can work with students who have that program.</description>
        <inlineHelpText>Enter the programs codes that this mentor is allowed to be assigned students from.</inlineHelpText>
        <label>Program Codes</label>
        <picklist>
            <picklistValues>
                <fullName>AAGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AASITCNE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AASITNA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASBU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAECE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESB12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESCH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESG12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESMA12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESMA9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESPH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESSC9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAESSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAISK8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAISPK8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMA12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMA9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASC9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCB12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCCH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCG12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASCPH12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASPNV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASS12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BASSPX12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSBUHR</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>SOSLPriorityPrograms__c</fullName>
        <label>SOSL Priority Programs</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The User with a mentor role for this record</description>
        <inlineHelpText>The user that has these attributes</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Student_Mentors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomMentorLookupController.cls
public class CustomMentorLookupController {
 
  public List<Mentor__c> results{get;set;} // search results
  public string searchString{get;set;} // search keyword
 
  public CustomMentorLookupController() {
    // get the current search string
    searchString = System.currentPageReference().getParameters().get('lksrch');
    runSearch();  
  }
 
  // performs the keyword search
  public PageReference search() {
    runSearch();
    return null;
  }
 
  // prepare the query and issue the search command
  private void runSearch() {
    // TODO prepare query string for complex serarches & prevent injections
    results = performSearch(searchString);               
  } 
 
  // run the search and return the records found. 
  private List<Mentor__c> performSearch(string searchString) {
    List<Mentor__c> mentors;
    if(searchString != '' && searchString != null){
        searchString = '*' + searchString + '*';
        mentors = (List<Mentor__c>)[FIND :searchString RETURNING Mentor__c(user__r.name,id,name,programcodes__c,priority1programcodes__c,mentorrole__c,mentorceiling__c,user__c,soslpriorityprograms__c)][0];        
    }
    return mentors;
 
  }
 
  // used by the visualforce page to send the link to the right dom element
  public string getFormTag() {
    return System.currentPageReference().getParameters().get('frm');
  }
 
  // used by the visualforce page to send the link to the right dom element for the text box
  public string getTextBox() {
    return System.currentPageReference().getParameters().get('txt');
  }
}