src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The mentor pidm so we can use external id&apos;s</description>
        <externalId>true</externalId>
        <inlineHelpText>The WGU PIDM assigned to this mentor.</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentCapacity__c</fullName>
        <description>The number of students that this mentor can handle</description>
        <inlineHelpText>THe number of students that this mentor can be assigned to.</inlineHelpText>
        <label>Student Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StudentsAssigned__c</fullName>
        <description>The current number of students assigned to this mentor</description>
        <inlineHelpText>The number of students that are currently assigned to this mentor.</inlineHelpText>
        <label>Students Assigned</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The User with a mentor role for this record</description>
        <inlineHelpText>The user that has these attributes</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Student_Mentors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IsEmployee__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this user is an employee please check this</description>
        <inlineHelpText>Checked if this user is an employee</inlineHelpText>
        <label>IsEmployee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TestMentorUtility.cls
/**
 * Author Paul R. Stay
 * Western Governors University @ 2012
 * Created Date: February 2012
 *
 *  Modified November 3, 2012 @1044 hrs by Paul Coleman ver APIVersion 20.0->26.0 and test method compliance
 * Modified 01/28/2013 to match standard naming conventions by Katarina Melki
 */
@isTest
private with sharing class TestMentorUtility {

    //Tests the MentorUtility.mapUserPidm function
    static testMethod void testPIDMAssignmentFromUserToMentorObjBeforeInsert() {
                
        User runAsUser = [SELECT Id FROM User where username like 'sadmin@wgu.edu%' LIMIT 1];

        System.runAs( runAsUser ) {
        
            // First create a user so that we can test against it
            ID mentorProfileID = [SELECT id from Profile where name = 'Mentor'].id;
            User testUser = new User(LastName='Mentor', FirstName='Standard', pidm__c='m1942_test', Username='a_test_mentor@wgu.edu', email='a_test_mentor@wgu.edu', Alias='a_test_m', CommunityNickname='a_test_mentor', TimeZoneSidKey='GMT', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=mentorProfileId, LanguageLocaleKey='en_US', isEmployee__c=true);
      
            System.debug(LoggingLevel.DEBUG, 'TEST USER FOR TEST: ' + JSON.serialize( testUser ) );
        
            Test.startTest();
            
            // Test PIDM__c match and assignment by creating a Mentor__c record, seeking confirmation of User Record assignment (User__c) by before insert trigger
            Mentor__c newMentor = new Mentor__c();
            newMentor.PIDM__c = testUser.PIDM__c;
            newMentor.StudentCapacity__c = 90.0;
            newMentor.StudentsAssigned__c = 45;
            System.debug(LoggingLevel.DEBUG, 'NEW TEST MENTOR__C BEFORE INSERT: ' + JSON.serialize( newMentor ) );
            insert newMentor;
            System.debug(LoggingLevel.DEBUG, 'NEW TEST MENTOR__C AFTER INSERT: ' + JSON.serialize( newMentor ) );
            
            // Check to see of the user ID has been set.
            Mentor__c mentorAfterInsert = [select Id, user__c from Mentor__c where id = :newMentor.Id];
            System.assertEquals( mentorAfterInsert.user__c, testUser.Id, 'Mentor__c.user__c DOES NOT MATCH User.Id for User.PIDM__c of ' + testUser.PIDM__c );
            
            Test.stopTest();
        }
    }
}