src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The mentor pidm so we can use external id&apos;s</description>
        <externalId>true</externalId>
        <inlineHelpText>The WGU PIDM assigned to this mentor.</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>StudentCapacity__c</fullName>
        <description>The number of students that this mentor can handle</description>
        <inlineHelpText>THe number of students that this mentor can be assigned to.</inlineHelpText>
        <label>Student Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The User with a mentor role for this record</description>
        <inlineHelpText>The user that has these attributes</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Student_Mentors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/NewStudentMentorController.cls
public class NewStudentMentorController {

    public User acct;
    
    // The extension constructor initializes the private member 
    
    // variable acct by using the getRecord method from the standard 
    
    // controller. 
    
    public NewStudentMentorController(ApexPages.StandardController stdController) {
        this.acct = (User)stdController.getRecord();
    }

public Id uid = System.currentPageReference().getParameters().get('id');

private User currentUser = new User(id = uid);

public Mentor__c studentMentor {
   get {
     if (studentMentor == null)
       studentMentor = new Mentor__c(user__c = currentUser.id,pidm__c = acct.pidm__c);       
     return studentMentor;
   }
   set;
  }
  
//inserts the note  
public PageReference saveStudentMentor() {
  try {
      insert studentMentor;
      }
  catch (DMLException e)
      {
      System.debug('Student Mentor already exists');
      }
  return null;
}



static testMethod void testNewStudentMentorController() {
    Profile prof = [SELECT id from profile where name = 'Lockdown'];
    User user1 = new User(LastName='Mentor',FirstName='Standard',pidm__c='123123',Username='a@wgu.edu', Email='a@wgu.edu', Alias='a', CommunityNickname='a', TimeZoneSidKey='GMT'
    , LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=prof.id, LanguageLocaleKey='en_US');
    insert user1;
    ApexPages.StandardController con = new ApexPages.StandardController(user1);
    NewStudentMentorController controller = new NewStudentMentorController(con);
    controller.studentMentor = new Mentor__c(user__c = controller.currentUser.id,pidm__c = controller.acct.pidm__c,studentCapacity__c = 12);
    controller.saveStudentMentor();
    Mentor__c savedMentor = [SELECT id,user__c from Mentor__c where id = :controller.studentMentor.id];
    System.assertEquals(savedMentor.user__c,controller.acct.id);
}

}