src/objects/Mentor__c.object
<CustomObject>
    <description>This custom object is used to support the AMA tool, and for showing who is assigned to student mentors (students)</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The mentor pidm so we can use external id&apos;s</description>
        <externalId>true</externalId>
        <inlineHelpText>The WGU PIDM assigned to this mentor.</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MentorCourseAssignment__c.object
<CustomObject>
    <description>This object holds the mentor course assignments, it is a one to many relationship as a Mentor can be assigned to more than course.</description>
    <fields>
        <fullName>AcademicTableKey__c</fullName>
        <externalId>true</externalId>
        <label>AcademicTableKey</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ActiveChk__c</fullName>
        <description>This is the course code i.e. LET1</description>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>True</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>False</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CourseNumber__c</fullName>
        <label>Course Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MentorOfficeHours__c</fullName>
        <label>Mentor Office Hours</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MentorPidm__c</fullName>
        <description>This stores the mentor pidm so we can do the lookup.</description>
        <label>Mentor Pidm</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mentor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Mentor_Course_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>Mentor Course Assignments</relationshipLabel>
        <relationshipName>Mentor_Course_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mentor Course Assignment</label>
    <nameField>
        <label>Mentor Course Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentor Course Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MentorCourseAssignToBanner__c.object
<CustomObject>
    <fields>
        <fullName>AcademicTableKey__c</fullName>
        <label>AcademicTableKey</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CourseNumber__c</fullName>
        <label>Course Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MentorCourseAssignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor Course Assignment</label>
        <referenceTo>MentorCourseAssignment__c</referenceTo>
        <relationshipLabel>Mentor Course Assigns To Banner</relationshipLabel>
        <relationshipName>MentorCourseAssignsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MentorOfficeHours__c</fullName>
        <description>Text value of JSON mentor office hours</description>
        <label>Mentor Office Hours</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MentorPIDM__c</fullName>
        <label>Mentor PIDM</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Mentor Course Assign To Banner</label>
    <nameField>
        <displayFormat>MCA-{0000}</displayFormat>
        <label>Mentor Course Assign To Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mentor Course Assigns To Banner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MentorCourseGroup__c.object
<CustomObject>
    <description>This table contains the course grouping for mentors. A common email, phone, etc.</description>
    <fields>
        <fullName>CourseNumber__c</fullName>
        <description>The course number for this grouping.</description>
        <label>Course Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TableKey__c</fullName>
        <externalId>true</externalId>
        <label>Mentor Group TableKey</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>Mentor Course Groups</relationshipLabel>
        <relationshipName>Mentor_Course_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mentor Course Group</label>
    <nameField>
        <label>Mentor Course Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentor Course Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MentorCourseGroupToBanner__c.object
<CustomObject>
    <fields>
        <fullName>CourseNumber__c</fullName>
        <label>Course Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MentorCourseGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentor Course Group</label>
        <referenceTo>MentorCourseGroup__c</referenceTo>
        <relationshipLabel>Mentor Course Groups To Banner</relationshipLabel>
        <relationshipName>MentorCourseGroupsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mentor Course Group To Banner</label>
    <nameField>
        <displayFormat>MCG-{0000}</displayFormat>
        <label>Mentor Course Group To Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mentor Course Groups To Banner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IsEmployee__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this user is an employee please check this</description>
        <inlineHelpText>Checked if this user is an employee</inlineHelpText>
        <label>IsEmployee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>PAMSID__c</fullName>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>bannercode__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>bannercode</label>
        <type>Text</type>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseCompletionTask__c.object
<CustomObject>
    <description>Custom object to manage template definitions for course assessments, requirements, or tasks. Student instances of assessments are managed via the StudentCourseCompletionTask__c object.</description>
    <fields>
        <fullName>BannerCode__c</fullName>
        <description>The code represented in Banner if different than the code represented in PAMS.</description>
        <label>Banner Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PAMSID__c</fullName>
        <description>The Unique ID represented as a combination of fields from PAMS. type-courseversionid-assessment.</description>
        <label>PAMS ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Objective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Course that this task is a requirement to complete.</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>WGU Course Completion Task</relationshipLabel>
        <relationshipName>WGUCourseCompletionTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course Completion Task</label>
    <nameField>
        <label>WGU Course Task Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Completion Task</pluralLabel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestMentorCourseAssignmentUtility.cls
/**
 * Author Paul Stay
 * Western Governors University
 *
 * Date November 12, 2012 
 * Revised: (security audit compliance: with sharing)
 * 
 */

@isTest
private with sharing class TestMentorCourseAssignmentUtility 
{
    static testMethod void testMentorCourseAssignmentInsert()
    {
        // Setup the test mentor
        ID mentorProfileID = [SELECT id from Profile where name = 'Mentor'].id;
        ID newUserId;
        User thisUser;
        
        thisUser = (thisUser == null) ? new User(LastName='Mentor1', FirstName='Standard1', pidm__c='m19421', Username='a1@wgu.edu', email='a1@wgu.edu', Alias='a1', CommunityNickname='a1', TimeZoneSidKey='GMT', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=mentorProfileID, LanguageLocaleKey='en_US', isEmployee__c=true): thisUser;
        insert thisUser;
        
        // Set up the test Mentor Assignment 
        WGUCourseCompletionTask__c task=new WGUCourseCompletionTask__c(BannerCode__c='LET1', Type__c='Performance');
        insert task;
        
        MentorCourseAssignment__c course = new MentorCourseAssignment__c(AcademicTableKey__c=1234, ActiveChk__c='True', CourseNumber__c='LET1', MentorPidm__c='m19421',MentorOfficeHours__c='9-10'  );
        
        Test.startTest();
            insert course;            
        Test.stopTest();
        
        MentorCourseAssignment__c newCourse = [select Mentor__c, ID, CourseNumber__c from MentorCourseAssignment__c where AcademicTableKey__c=1234];
        
        System.assert(newCourse.Mentor__c != null);
        System.debug('Mentor found ' + newCOurse.Mentor__c);
        
        newCourse.MentorOfficeHours__c='Test Value';
        update newCourse;
        
        delete newCourse;
        
        System.assert([select ID from MentorCourseAssignment__c where AcademicTableKey__c=1234].size()==0);
        System.assert([select ID from MentorCourseAssignToBanner__c].size()==1);
    }
    
    static testMethod void testMentorCourseAssignmentLookUpWGUCourse()
    {
        // Setup the test mentor
        ID mentorProfileID = [SELECT  id from Profile where name = 'Mentor'].id;
        ID newUserId;
        User thisUser=  new User(LastName='Mentor', FirstName='Standard', pidm__c='m1942', Username='a@wgu.edu', email='a@wgu.edu', Alias='a', CommunityNickname='a', TimeZoneSidKey='GMT', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=mentorProfileId, LanguageLocaleKey='en_US', isEmployee__c=true) ;
        insert thisUser;
        WGUCourse__c thisCourse= new WGUCourse__c(Name='LET1',PAMSID__c=92);
        insert thisCourse;
        // Set up the test Mentor Assignment 

        MentorCourseAssignment__c course1 = new MentorCourseAssignment__c(AcademicTableKey__c=1234, ActiveChk__c='TRUE', CourseNumber__c='LET1', MentorPidm__c='m1942',MentorOfficeHours__c='9-10'  );
        MentorCourseAssignment__c course2 = new MentorCourseAssignment__c(AcademicTableKey__c=1235, ActiveChk__c='TRUE', CourseNumber__c='LET2', MentorPidm__c='m1942',MentorOfficeHours__c='9-10'  );
        Test.startTest();
            insert course1;
            insert course2;
        Test.stopTest();
        MentorCourseAssignment__c newCourse1 = [select Mentor__c, ID, CourseNumber__c,WGUCourse__c from MentorCourseAssignment__c where AcademicTableKey__c=1234];
        MentorCourseAssignment__c newCourse2 = [select Mentor__c, ID, CourseNumber__c,WGUCourse__c from MentorCourseAssignment__c where AcademicTableKey__c=1235];
        System.assert(newCourse1.WGUCourse__c==thisCourse.id); 
        System.assert(newCourse2.WGUCourse__c==null);
    }
    
    static testMethod void testMentorCourseGroupLookUpWGUCourse()
    {  
        WGUCourse__c thisCourse= new WGUCourse__c(Name='LET1',PAMSID__c=92);
        insert thisCourse;
        // Set up the test Mentor Group 

        MentorCourseGroup__c course1 = new MentorCourseGroup__c(  CourseNumber__c='LET2',TableKey__c=11311  );
        MentorCourseGroup__c course2 = new MentorCourseGroup__c(  CourseNumber__c='LET1',TableKey__c=11312  );
        Test.startTest();
            insert course2;
            insert course1;            
        Test.stopTest();
        MentorCourseGroup__c newCourse1 = [select id, WGUCourse__c,TableKey__c from MentorCourseGroup__c where TableKey__c=11311];
        MentorCourseGroup__c newCourse2 = [select id, WGUCourse__c,TableKey__c from MentorCourseGroup__c where TableKey__c=11312];
        System.assert(newCourse1.WGUCourse__c==null); 
        System.assert(newCourse2.WGUCourse__c==thisCourse.id);
        
        delete newCourse2;
        
        System.assert([select ID from MentorCourseGroupToBanner__c where CourseNumber__c='LET1'].size()==1);
    }
}