src/objects/MentorCourseAssignment__c.object
<CustomObject>
    <description>This object holds the mentor course assignments, it is a one to many relationship as a Mentor can be assigned to more than course.</description>
    <fields>
        <fullName>AcademicTableKey__c</fullName>
        <externalId>true</externalId>
        <label>AcademicTableKey</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ActiveChk__c</fullName>
        <description>This is the course code i.e. LET1</description>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>True</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>False</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CourseNumber__c</fullName>
        <label>Course Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MentorPidm__c</fullName>
        <description>This stores the mentor pidm so we can do the lookup.</description>
        <label>Mentor Pidm</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Mentor Course Assignment</label>
    <nameField>
        <label>Mentor Course Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentor Course Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CoursesIManage__c</fullName>
        <label>Courses I Manage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <defaultValue>&quot;000000&quot;</defaultValue>
        <description>User PIDM which is unique across the global WGU scheme</description>
        <externalId>true</externalId>
        <inlineHelpText>User PIDM</inlineHelpText>
        <label>PIDM</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/TestMyStudentsInACourseController.cls
/**
 * Author Paul Stay
 * Test the MyCourseAssignmentsController and visualforce page
 *
 * Date Jan. 2013
 * 
 */
 @isTest
 private with sharing class TestMyStudentsInACourseController {
 
     private static testMethod void testController() {
        
        // Add create user and mentor course assignments for testing.
        ID mentorProfileId = [SELECT id from Profile where name = 'Mentor'].ID;
        User mentorUser = new User(LastName='Mentor',FirstName='Standard',pidm__c='m198765',Username='a@wgu.edu', Email='a@wgu.edu', Alias='a', CommunityNickname='a', TimeZoneSidKey='GMT', 
            LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',ProfileId=mentorProfileId , LanguageLocaleKey='en_US');
        mentorUser.CoursesIManage__c = 'TEST';
       
        insert mentorUser ;

        MentorCourseAssignment__c course = new MentorCourseAssignment__c( AcademictableKey__c=1.0,
            ActiveChk__c='Y', CourseNumber__c='QAT1', MentorPidm__c='m198765'     );
    
        insert course;
        
        // Used to simulate selecting courses
        String selectedCourses = 'TEST,QAT1,FOO1';

        Test.startTest();
                
            System.RunAs(mentorUser) {
            
                PageReference pageRef = new PageReference('/apex/MyStudentsInACourse');
                test.setCurrentPage(pageRef);
                ApexPages.StandardController stdController = new ApexPages.StandardController( new MentorCourseAssignment__c());
                MyStudentsInACourseController controller = new MyStudentsInACourseController(stdController);
                             
                                
                controller.setSelectedCourses(selectedCourses);
                
                String getCourses = controller.getSelectedCourses();
                System.assertEquals(getCourses, 'TEST,QAT1,FOO1');
                
                controller.loadCourses();
                    
                User testUser = [Select id,CoursesIManage__c from User where ID= :mentorUser.Id];
                    
                System.assertEquals(testUser.CoursesIManage__c, 'TEST,QAT1,FOO1');
                   
            }
            
            System.RunAs(mentorUser) {
                MyStudentsInACourseController controller = new MyStudentsInACourseController();
                controller.setSelectedCourses(selectedCourses);
                String getCourses = controller.getSelectedCourses();
                System.assertEquals(getCourses, 'TEST,QAT1,FOO1');
                
                controller.loadCourses();
                    
                User testUser = [Select id,CoursesIManage__c from User where ID= :mentorUser.Id];
                    
                System.assertEquals(testUser.CoursesIManage__c, 'TEST,QAT1,FOO1');
                   
            }
        
        Test.stopTest();
     }
      
 }