src/objects/MentorCourseAssignToBanner__c.object
<CustomObject>
    <fields>
        <fullName>PushResult__c</fullName>
        <label>Push Result</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Mentor Course Assign To Banner</label>
    <nameField>
        <displayFormat>MCA-{0000}</displayFormat>
        <label>Mentor Course Assign To Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mentor Course Assigns To Banner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SynchronizeToBannerLog__c.object
<CustomObject>
    <description>A object to track the issues various *ToBanner__c objects have. All will be coded to create a single tracking object list that can be viewed and followed up on in Salesforce.</description>
    <fields>
        <fullName>ReferenceId__c</fullName>
        <label>Reference Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceType__c</fullName>
        <description>The Salesforce object type this record refers to.</description>
        <label>Reference Type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SynchronizationError__c</fullName>
        <description>The error that occurred in the referenced object.</description>
        <label>Synchronization Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Synchronize To Banner Log</label>
    <nameField>
        <displayFormat>BSL-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Synchronize To Banner Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MentorCourseAssignToBannerUtility.cls
/*****************************************************************************************
* Name: MentorCourseAssignToBannerUtility
* Author: Will Slade
* Purpose: Creates error logs for failed attempts at pushing a Mentor Course Groups To Banner
* Revisions: 
*    7-12-2013 - Created Class
*
******************************************************************************************/

public class MentorCourseAssignToBannerUtility
{
    public static void createSyncToBannerLogs(String wtbListJSON)
    {
        if (Limits.getFutureCalls() > 8 || System.isFuture())
        {
            processCreateSyncToBannerLogs(wtbListJSON);
        }
        else
        {
            asyncCreateSyncToBannerLogs(wtbListJSON);
        }
    }
    
    @future
    public static void asyncCreateSyncToBannerLogs(String wtbListJSON)
    {
        processCreateSyncToBannerLogs(wtbListJSON);
    }    

    public static void processCreateSyncToBannerLogs(String wtbListJSON)
    {     
        List<MentorCourseAssignToBanner__c> wtbList = (List<MentorCourseAssignToBanner__c>) JSON.deserialize(wtbListJSON, List<MentorCourseAssignToBanner__c>.class);
        List<SynchronizeToBannerLog__c> stblList = new List<SynchronizeToBannerLog__c>();

        for (MentorCourseAssignToBanner__c wtb : wtbList)
        {
            stblList.add(new SynchronizeToBannerLog__c(ReferenceType__c = 'MentorCourseAssignToBanner__c',
                                                       ReferenceId__c = wtb.Id,
                                                       SynchronizationError__c = wtb.PushResult__c));                                                       
        }
        
        insert stblList;
    }    
}