src/objects/OpportunityToBanner__c.object
<CustomObject>
    <description>Synchronization object for moving data from Salesforce to Banner for the Opportunity (CARE Profile) Object</description>
    <fields>
        <fullName>CurrentStatus__c</fullName>
        <formula>/* -0.0416 is used to adjust Daylight Saving Time changing. 
  Delete -0.0416 in Summer; 
  Keep -0.0416 in Winter, 
  Winter: (LastSynchronizedToBanner__c - Opportunity__r.LastModifiedDate) &lt; -0.0011 - 0.0416
  Summer: (LastSynchronizedToBanner__c - Opportunity__r.LastModifiedDate) &lt; -0.0011 
*/ 

IF(AND(NOT(ResynchronizeToBanner__c), NOT(SynchronizationError__c = &apos;None&apos;), NOT(OR(ISNULL(SynchronizationError__c), ISBLANK(SynchronizationError__c)))), 
   &apos;Error&apos;, 
   IF(AND(NOT(OR(ISNULL( Opportunity__r.PIDM__c ), ISBLANK(Opportunity__r.PIDM__c))), OR((LastSynchronizedToBanner__c - Opportunity__r.LastModifiedDate ) &lt; -0.0011, ResynchronizeToBanner__c, ISNULL(LastSynchronizedToBanner__c)), 
   NOT(AND( Opportunity__r.LastModifiedBy.FirstName = &apos;System&apos;, Opportunity__r.LastModifiedBy.LastName = &apos;Administrator&apos;))), 
      &apos;Update&apos;, 
      IF(AND( Opportunity__r.StudentContact__r.BannerReady__c , OR(ISNULL(Opportunity__r.PIDM__c), ISBLANK(Opportunity__r.PIDM__c))), 
         &apos;Insert&apos;, 
         IF(Opportunity__r.StudentContact__r.BannerReady__c, &apos;Current&apos;, &apos;Ignore&apos;) 
      ) 
   ) 
)</formula>
        <label>Current Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities To Banner</relationshipLabel>
        <relationshipName>OpportunitiesToBanner</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PIDMOUT__c</fullName>
        <formula>Opportunity__r.PIDM__c</formula>
        <label>PIDM (OUT)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SynchronizationError__c</fullName>
        <label>Synchronization Error</label>
        <type>TextArea</type>
    </fields>
    <label>Opportunity To Banner</label>
    <nameField>
        <displayFormat>OTB-{0}</displayFormat>
        <label>Opportunity To Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities To Banner</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OpportunityToBannerUtility.cls
public with sharing class OpportunityToBannerUtility{
    
    public static boolean firstRun = true;
    public static boolean firstCheck = true;
    
    ///////////////// START SECTION: Create OpportunityToBanner ///////////
    
    public static void createOpportunityToBanner(String listNewJSON){
        if( Limits.getFutureCalls()>3 || System.isFuture() || System.isBatch() || System.isScheduled() ){
            processCreateOpportunityToBanner(listNewJSON);
        }else{
            try{
                asyncCreateOpportunityToBanner(listNewJSON);
            }catch(Exception e){
                processCreateOpportunityToBanner(listNewJSON);
            }
        }
    }
    
    @future
    private static void asyncCreateOpportunityToBanner(String listNewJSON){
        processCreateOpportunityToBanner(listNewJSON);
    }
    
    private static void processCreateOpportunityToBanner(String listNewJSON){
        List<Opportunity> oppList = (List<Opportunity>)JSON.deserialize(listNewJSON, List<Opportunity>.class);
        List<Id> oppIdList = new List<Id>();
        Map<Id,Id> oppToCtrlMap = new Map<Id,Id>();
        List<OpportunityToBanner__c> insertList = new List<OpportunityToBanner__c>();
        
        for(Opportunity thisOpp : oppList){
            oppIdList.add(thisOpp.Id);
            oppToCtrlMap.put(thisOpp.Id, null);
        }
        
        List<OpportunityToBanner__c> oppToBanList = [ SELECT Id, Opportunity__c, CurrentStatus__c
                                                      FROM OpportunityToBanner__c
                                                      WHERE Opportunity__c IN :oppIdList ];
        for(OpportunityToBanner__c oppToBan : oppToBanList){
            oppToCtrlMap.put(oppToBan.Opportunity__c, oppToBan.Id);
        }
        
        for(Opportunity opp : oppList){
            if(oppToCtrlMap.get(opp.Id) == null){
                insertList.add( new OpportunityToBanner__c(Opportunity__c = opp.Id) );
            }
        }
        insert insertList;
    }
    
    ///////////////// END SECTION: Create OpportunityToBanner   ///////////
    
    public static void updateStatus(String newJson){
        if(Limits.getFutureCalls()>3 || System.isFuture() || System.isBatch() || System.isScheduled() ){
            processUpdateStatus(newJson);
        }else{
            asyncUpdateStatus(newJson);
        }
    }
    @future
    public static void asyncUpdateStatus(String newJson){
        processUpdateStatus(newJson);
    }
    public static void processUpdateStatus(String newJson){
        List<OpportunityToBanner__c> optbList = new List<OpportunityToBanner__c>();
        List<Opportunity> opList = (List<Opportunity>)JSON.deserialize(newJson, List<Opportunity>.class);
        List<Id> opIdList = new List<Id>();
        for(Opportunity op : opList){
            opIdList.add(op.Id);
        }
        optbList = [select id, pidmOUT__c,SynchronizationError__c from OpportunityToBanner__c
                    where Opportunity__c IN :opIdList];
        for(OpportunityToBanner__c optb : optbList){
            if(optb.PIDMOUT__c != null && optb.SynchronizationError__c != null && optb.SynchronizationError__c.startsWith('No pidm')){
                optb.SynchronizationError__c = null;
            }
        }
        update optbList;
    }
}