src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CareStatus__c</fullName>
        <label>CARE Status</label>
        <picklist>
            <picklistValues>
                <fullName>PROS – Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PRAP – Prospect Applied Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APNN – Application Incomplete PRAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APIN – Application Incomplete APCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APCO – Application Complete, Unpaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC – Application Complete, Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REDI - Admission Decision Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEND - Additional Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAMT - Auto Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMT – Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTV – Fit and EWB Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLRD - Cleared to Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENRL – Enrolled and Assigned a Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEVR – Never completed EWOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DROP – Dropped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAMT - Not Admitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAYT - Not Admitted Yet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MATR – Matriculated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRAD – Ready for Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALUMNI - Graduated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/TransferEvaluation__c.object
<CustomObject>
    <description>A Transfer evaluation is the parent object of the equivalent courses that will given to the student from their transfer work. It controls the overall status and assignment of the evaluation.</description>
    <fields>
        <fullName>CAREStatus__c</fullName>
        <formula>TEXT( Opportunity__r.CareStatus__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CARE Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EvaluationStatus__c</fullName>
        <label>Evaluation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready for Evaluation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appealed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The Link Between opportunities and transfer evaluations</description>
        <label>CARE Profile Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transfer Evaluations</relationshipLabel>
        <relationshipName>TransferEvaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transfer Evaluation</label>
    <nameField>
        <label>Transfer Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfer Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCARENoAdmitUtility.cls
@isTest
public with sharing class TestCARENoAdmitUtility
{    
    @isTest
    public static void testCancelEvals()
    {
        test.startTest();
        Opportunity newLead = new Opportunity(Name = 'Tester NAMTCancel', CareStatus__c = 'PROS – Prospect', StageName = 'Prospect', CloseDate = Date.today());
        insert newLead;
        
        TransferEvaluation__c newEval = new TransferEvaluation__c(Opportunity__c = newLead.Id, EvaluationStatus__c = 'In Progress');
        insert newEval;
        
        System.assert(newEval.EvaluationStatus__c.equals('In Progress'));
        
        newLead.CareStatus__c = 'NAMT - Not Admitted';
        update newLead;
        
        test.stopTest();
        
        newEval = [SELECT EvaluationStatus__c FROM TransferEvaluation__c WHERE Id = :newEval.Id];        
        
        try
        {
            System.assert(newEval.EvaluationStatus__c.equals('Canceled'));
        }
        catch (Exception e) {}
    }
}