src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>The PIDM which is unique in the WGU global scheme</description>
        <externalId>true</externalId>
        <label>PIDM</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/StudentEquivalentCourse__c.object
<CustomObject>
    <description>WGU&apos;s courses and the link between transfered course for which a student may receive credit.</description>
    <fields>
        <fullName>PushedToBanner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pushed To Banner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SatisfiedInd__c</fullName>
        <description>Evaluation Satisfied.</description>
        <formula>IF ( UnderReview__c &amp;&amp; RequirementSatisfied__c = FALSE, &apos;N&apos;, IF (LEN ( TransferredCourse__c ) &gt; 0, &apos;Y&apos;, IF (LEN ( TransferredGroup__c ) &gt; 0, &apos;Y&apos;, IF (LEN ( TransferAttendance__c ) &gt; 0, &apos;Y&apos;, IF ( RequirementSatisfied__c , &apos;Y&apos;, &apos;N&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Satisfied Ind</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TransferAttendance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Transfer Attendance</description>
        <label>Transfer Attendance</label>
        <referenceTo>TransferAttendance__c</referenceTo>
        <relationshipLabel>Student Equivalent Courses</relationshipLabel>
        <relationshipName>Student_Equivalent_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransferEvaluation__c</fullName>
        <description>Related Transfer Evaluation</description>
        <label>Transfer Evaluation</label>
        <referenceTo>TransferEvaluation__c</referenceTo>
        <relationshipLabel>Student Equivalent Courses</relationshipLabel>
        <relationshipName>StudentEquivalentCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TransferredCourse__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transferred Course</label>
        <referenceTo>StudentTransferredCourse__c</referenceTo>
        <relationshipLabel>Student Equivalent Courses</relationshipLabel>
        <relationshipName>StudentEquivalentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransferredGroup__c</fullName>
        <description>The Group of Courses that Satisfies this requirement</description>
        <inlineHelpText>The Group of Courses that Satisfies this requirement.  This must match exactly to course groups from the institution</inlineHelpText>
        <label>Transferred Group</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <formula>WGUCourseInProgram__r.Course__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>WGU Course</label>
        <type>Text</type>
    </fields>
    <label>Student Equivalent Course</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Student Equivalent Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Equivalent Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentTranscript__c.object
<CustomObject>
    <description>Object to manage the transcripts that must be collected through in-take and viewed by Mentors</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Student Transfer Institution</relationshipLabel>
        <relationshipName>opportunityTransferInstitution</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <formula>Opportunity__r.Account.PIDM__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PIDM</label>
        <type>Text</type>
    </fields>
    <label>Student Transfer Institution</label>
    <nameField>
        <displayFormat>Institution-{0000}</displayFormat>
        <label>Student Transfer Institution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transfer Institution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentTransferredCourse__c.object
<CustomObject>
    <description>Shows courses that were transferred to WGU. Child object of Student Transfer Instituition.</description>
    <fields>
        <fullName>PushedToBanner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pushed To Banner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StudentTransferInstitution__c</fullName>
        <label>Student Transfer Institution</label>
        <referenceTo>StudentTranscript__c</referenceTo>
        <relationshipName>TransferCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TransferAttendance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer Attendance</label>
        <referenceTo>TransferAttendance__c</referenceTo>
        <relationshipLabel>Student Transferred Courses</relationshipLabel>
        <relationshipName>StudentTransferredCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Transferred Course</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transferred Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TranscriptToBanner__c.object
<CustomObject>
    <description>Sync object to house Transcripts being pushed to Banner</description>
    <fields>
        <fullName>ActionNeeded__c</fullName>
        <label>Action Needed</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>PIDM of the related Opportunity</description>
        <label>PIDM</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <description>Salesforce ID of the parent object as it relates to the BANNER tables</description>
        <label>Parent Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RefId__c</fullName>
        <description>Id of the Salesforce record to which this control object is directly linked</description>
        <externalId>true</externalId>
        <label>Ref Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentEquivalentCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Equivalent Course</label>
        <referenceTo>StudentEquivalentCourse__c</referenceTo>
        <relationshipLabel>Transcripts to Banner</relationshipLabel>
        <relationshipName>TranscriptsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentTransferInstitution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Transfer Institution</label>
        <referenceTo>StudentTranscript__c</referenceTo>
        <relationshipLabel>Transcripts to Banner</relationshipLabel>
        <relationshipName>TranscriptsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentTransferredCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Transferred Course</label>
        <referenceTo>StudentTransferredCourse__c</referenceTo>
        <relationshipLabel>Transcripts to Banner</relationshipLabel>
        <relationshipName>TranscriptsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransferAttendance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer Attendance</label>
        <referenceTo>TransferAttendance__c</referenceTo>
        <relationshipLabel>Transcripts to Banner</relationshipLabel>
        <relationshipName>TranscriptsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourseCode__c</fullName>
        <description>WGU Course Code for the equivalent course</description>
        <label>WGU Course Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Transcript to Banner</label>
    <nameField>
        <displayFormat>T2B-{0000000}</displayFormat>
        <label>Transcript to Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcripts to Banner</pluralLabel>
    <recordTypes>
        <fullName>StudentEquivalentCourse</fullName>
        <active>true</active>
        <label>StudentEquivalentCourse</label>
    </recordTypes>
    <recordTypes>
        <fullName>StudentTransferredCourse</fullName>
        <active>true</active>
        <label>StudentTransferredCourse</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TransferAttendance__c.object
<CustomObject>
    <description>This is a record of attendance at other institutions including any degrees awarded, program, GPA, and dates of attendance.</description>
    <fields>
        <fullName>StudentTransferInstitution__c</fullName>
        <label>Student Transfer Institution</label>
        <referenceTo>StudentTranscript__c</referenceTo>
        <relationshipLabel>Transfer Attendance</relationshipLabel>
        <relationshipName>TransferAttendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transfer Attendance</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Transfer Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transfer Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TransferEvaluation__c.object
<CustomObject>
    <description>A Transfer evaluation is the parent object of the equivalent courses that will given to the student from their transfer work. It controls the overall status and assignment of the evaluation.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The Link Between opportunities and transfer evaluations</description>
        <label>CARE Profile Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Transfer Evaluations</relationshipLabel>
        <relationshipName>TransferEvaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transfer Evaluation</label>
    <nameField>
        <label>Transfer Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfer Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TransferEvaluationUtility.cls
/***************************************************************************************************************
*
* Purpose: Create TranscriptToBanner records from TransferEvaluationTrigger
* Author: Will Slade
* Revisions:
*     4-16-2013 - Created Class
*
****************************************************************************************************************/

public class TransferEvaluationUtility
{
    public static void createTranscriptsToBanner(String trEvalListJSON)
    {
        if (Limits.getFutureCalls() > 8 || System.isFuture())
        {
            processCreateTranscriptsToBanner(trEvalListJSON);
        }
        else
        {
            asyncCreateTranscriptsToBanner(trEvalListJSON);
        }
    }
    
    @future
    public static void asyncCreateTranscriptsToBanner(String trEvalListJSON)
    {
        processCreateTranscriptsToBanner(trEvalListJSON);
    }

    public static void processCreateTranscriptsToBanner(String trEvalListJSON)
    {
        Id trCrsRT = [SELECT Id FROM RecordType WHERE SObjectType = 'TranscriptToBanner__c' AND Name = 'StudentTransferredCourse' LIMIT 1].Id;
        Id eqCrsRT = [SELECT Id FROM RecordType WHERE SObjectType = 'TranscriptToBanner__c' AND Name = 'StudentEquivalentCourse' LIMIT 1].Id;
        List<TransferEvaluation__c> trEvalList = (List<TransferEvaluation__c>) JSON.deserialize(trEvalListJSON, List<TransferEvaluation__c>.class);        
        List<Id> trEvalIds = new List<Id>(); 
        List<Id> trCrsIds = new List<Id>();
        List<Id> eqCrsIds = new List<Id>();              
        
        Map<Id, Id> eqCrsToControlMap = new Map<Id, Id>();
        Map<Id, Id> trCrsToControlMap = new Map<Id, Id>();
        Map<Id, String> eqCrsToPidmMap = new Map<Id, String>();
        Map<Id, String> trCrsToPidmMap = new Map<Id, String>();
        Map<Id, Id> eqCrsToTrCrsMap = new Map<Id, Id>();
        Map<Id, Id> trCrsToTrAttMap = new Map<Id, Id>();
        Map<Id, Id> transcriptMap = new Map<Id, Id>();
        Map<Id, Id> attendanceMap = new Map<Id, Id>();
        
        List<StudentEquivalentCourse__c> eqCrsList = new List<StudentEquivalentCourse__c>();
        List<StudentTransferredCourse__c> trCrsList = new List<StudentTransferredCourse__c>(); 
        List<TranscriptToBanner__c> trToBannerList = new List<TranscriptToBanner__c>();
        List<TranscriptToBanner__c> trToBannerUpdateList = new List<TranscriptToBanner__c>();
        List<TranscriptToBanner__c> trToBannerInsertList = new List<TranscriptToBanner__c>();
        
        //Compile list of Ids in Transfer Evaluations and pull the equivalent/transferred courses associated with them
        for (TransferEvaluation__c trEval : trEvalList)
        {
            trEvalIds.add(trEval.Id);
        }
        
        eqCrsList = [SELECT Id, TransferredCourse__c, TransferEvaluation__r.Opportunity__r.Pidm__c, PushedToBanner__c, TransferredCourse__r.TransferAttendance__c,
                            TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__r.Pidm__c, TransferredGroup__c, WGUCourse__c,
                            TransferredCourse__r.StudentTransferInstitution__c, TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__c
                     FROM StudentEquivalentCourse__c
                     WHERE TransferEvaluation__c IN :trEvalIds
                     AND SatisfiedInd__c = 'Y'];            
        
        //Build maps to link the transfer/equivalent courses to their control objects (if they exist)
        for (StudentEquivalentCourse__c eqCrs : eqCrsList)
        {
            eqCrsIds.add(eqCrs.Id);   
            eqCrsToPidmMap.put(eqCrs.Id, eqCrs.TransferEvaluation__r.Opportunity__r.Pidm__c);
            
            if (eqCrs.TransferredCourse__c != null)
            {
                trCrsToPidmMap.put(eqCrs.TransferredCourse__c, eqCrs.TransferEvaluation__r.Opportunity__r.Pidm__c);
                trCrsIds.add(eqCrs.TransferredCourse__c);
            }                    
        
            if (!eqCrsToControlMap.containsKey(eqCrs.Id))
            {
                System.debug('======> adding equiv course to map: ' + eqCrs.Id);
                eqCrsToControlMap.put(eqCrs.Id, null);               
            }
            
            if (!trCrsToControlMap.containsKey(eqCrs.TransferredCourse__c) && eqCrs.TransferredCourse__c != null)
            {
                System.debug('======> adding trans course to map: ' + eqCrs.TransferredCourse__c);
                trCrsToControlMap.put(eqCrs.TransferredCourse__c, null);
            }
            
            if (!attendanceMap.containsKey(eqCrs.TransferredCourse__r.TransferAttendance__c))
            {
                attendanceMap.put(eqCrs.TransferredCourse__r.TransferAttendance__c, null);
            }
            
            if (!transcriptMap.containsKey(eqCrs.TransferredCourse__r.StudentTransferInstitution__c))
            {
                transcriptMap.put(eqCrs.TransferredCourse__r.StudentTransferInstitution__c, null);
            }
        }
        
        List<TransferAttendance__c> attendanceUpdateList = [SELECT Id FROM TransferAttendance__c WHERE Id IN :attendanceMap.keySet()];
        List<StudentTranscript__c> transcriptUpdateList = [SELECT Id FROM StudentTranscript__c WHERE Id IN :transcriptMap.keySet()];
        
        update attendanceUpdateList;
        update transcriptUpdateList;

        //Pull the list of existing control objects related to the courses        
        trToBannerList = [SELECT Id, StudentEquivalentCourse__c, StudentTransferredCourse__c, StudentEquivalentCourse__r.WGUCourse__c, ActionNeeded__c
                          FROM TranscriptToBanner__c 
                          WHERE StudentEquivalentCourse__c IN :eqCrsIds
                          OR StudentTransferredCourse__c IN :trCrsIds];
                          
        System.debug('=====> existing control object size: ' + trToBannerList.size());
        
        Map<Id, String> trBanToActionMap = new Map<Id, String>();                          
        
        //Repopulate the maps, this time including the control object ids as values to the course keys                  
        for (TranscriptToBanner__c trToBanner : trToBannerList)
        {
            trBanToActionMap.put(trToBanner.Id, trToBanner.ActionNeeded__c);
            
            if (eqCrsToControlMap.containsKey(trToBanner.StudentEquivalentCourse__c))
            {
                eqCrsToControlMap.put(trToBanner.StudentEquivalentCourse__c, trToBanner.Id);
            }
            
            if (trCrsToControlMap.containsKey(trToBanner.StudentTransferredCourse__c))
            {
                trCrsToControlMap.put(trToBanner.StudentTransferredCourse__c, trToBanner.Id);
            }            
        }
        
        System.debug('=====> loading from list size ' + eqCrsList.size());
        Map<Id, Id> dupeCheck = new Map<Id, Id>();
        
        //Populate the lists of control objects with which ones need to be updated vs inserted (null value on course key means new control object needed)                
        for (StudentEquivalentCourse__c eqCrs : eqCrsList)
        {
            System.debug('=====> Transferred Course: ' + eqCrs.TransferredCourse__c);
            if (eqCrs.TransferredCourse__c != null && trCrsToControlMap.containsKey(eqCrs.TransferredCourse__c) && trCrsToControlMap.get(eqCrs.TransferredCourse__c) == null
                && !dupeCheck.containsKey(eqCrs.TransferredCourse__c))
            {
                System.debug('====> Creating new control object for trans course: ' + eqCrs.TransferredCourse__c);
                trToBannerInsertList.add(new TranscriptToBanner__c(RecordTypeId = trCrsRT, 
                                                                   ActionNeeded__c = 'Insert', 
                                                                   StudentTransferredCourse__c = eqCrs.TransferredCourse__c,
                                                                   TransferAttendance__c = eqCrs.TransferredCourse__r.TransferAttendance__c,
                                                                   StudentTransferInstitution__c = eqCrs.TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__c,
                                                                   RefId__c = eqCrs.TransferredCourse__c,
                                                                   ParentId__c = eqCrs.TransferredCourse__r.TransferAttendance__c,
                                                                   Pidm__c = eqCrs.TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__r.Pidm__c,
                                                                   WGUCourseCode__c = eqCrs.WGUCourse__c));
                dupeCheck.put(eqCrs.TransferredCourse__c, null);
            }
            else if (eqCrs.TransferredCourse__c != null && trCrsToControlMap.containsKey(eqCrs.TransferredCourse__c) 
                     && !dupeCheck.containsKey(trCrsToControlMap.get(eqCrs.TransferredCourse__c))
                     && !dupeCheck.containsKey(eqCrs.TransferredCourse__c))
            {   
                System.debug('====> Updating control object for trans course: ' + eqCrs.TransferredCourse__c);
                
                String action = trBanToActionMap.get(trCrsToControlMap.get(eqCrs.TransferredCourse__c)) == 'Insert' ? 'Insert' : 'Update';                              
                        
                trToBannerUpdateList.add(new TranscriptToBanner__c(Id = trCrsToControlMap.get(eqCrs.TransferredCourse__c), 
                                                                   ActionNeeded__c = action,
                                                                   ParentId__c = eqCrs.TransferredCourse__r.TransferAttendance__c,
                                                                   StudentTransferredCourse__c = eqCrs.TransferredCourse__c,
                                                                   TransferAttendance__c = eqCrs.TransferredCourse__r.TransferAttendance__c,
                                                                   StudentTransferInstitution__c = eqCrs.TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__c,                                                                   
                                                                   WGUCourseCode__c = eqCrs.WGUCourse__c,
                                                                   Pidm__c = eqCrs.TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__r.Pidm__c));
                //Prevent duplicate Transfer Courses from being added to update list
                dupeCheck.put(trCrsToControlMap.get(eqCrs.TransferredCourse__c), null);                                                   
            }
                     
            if (eqCrsToControlMap.containsKey(eqCrs.Id) && eqCrsToControlMap.get(eqCrs.Id) == null
                && !dupeCheck.containsKey(eqCrs.Id))
            {
                System.debug('====> Creating new control object for equiv course: ' + eqCrs.Id);
                trToBannerInsertList.add(new TranscriptToBanner__c(RecordTypeId = eqCrsRT, 
                                                                   StudentEquivalentCourse__c = eqCrs.Id,
                                                                   StudentTransferredCourse__c = eqCrs.TransferredCourse__c,
                                                                   TransferAttendance__c = eqCrs.TransferredCourse__r.TransferAttendance__c,
                                                                   StudentTransferInstitution__c = eqCrs.TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__c,                                                                    
                                                                   ActionNeeded__c = 'Insert',
                                                                   RefId__c = eqCrs.Id,
                                                                   ParentId__c = eqCrs.TransferredCourse__c,
                                                                   Pidm__c = eqCrs.TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__r.Pidm__c));
                dupeCheck.put(eqCrs.Id, null);
            }
            else if (eqCrsToControlMap.containsKey(eqCrs.Id) 
                     && !dupeCheck.containsKey(eqCrsToControlMap.get(eqCrs.Id))
                     && !dupeCheck.containsKey(eqCrs.Id))
            {  
                System.debug('====> Updating control object for equiv course: ' + eqCrs.Id);  
                
                String action = trBanToActionMap.get(eqCrsToControlMap.get(eqCrs.Id)) == 'Insert' ? 'Insert' : 'Update'; 
                            
                trToBannerUpdateList.add(new TranscriptToBanner__c(Id = eqCrsToControlMap.get(eqCrs.Id),
                                                                   StudentTransferredCourse__c = eqCrs.TransferredCourse__c,
                                                                   TransferAttendance__c = eqCrs.TransferredCourse__r.TransferAttendance__c,
                                                                   StudentTransferInstitution__c = eqCrs.TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__c,                 
                                                                   ActionNeeded__c = action,
                                                                   ParentId__c = eqCrs.TransferredCourse__c,
                                                                   Pidm__c = eqCrs.TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__r.Pidm__c));
                dupeCheck.put(eqCrsToControlMap.get(eqCrs.Id), null);
            }
            
            eqCrs.PushedToBanner__c = true;
        }
        
        insert trToBannerInsertList;
        update trToBannerUpdateList; 
        update eqCrsList;       
    }                
}