src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CAREStatusListView__c</fullName>
        <formula>LEFT(TEXT(CareStatus__c), 4)</formula>
        <label>CARE Status List View</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CareStatus__c</fullName>
        <label>CARE Status</label>
        <picklist>
            <picklistValues>
                <fullName>PROS – Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PRAP – Prospect Applied Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APNN – Application Incomplete PRAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APIN – Application Incomplete APCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APCO – Application Complete, Unpaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC – Application Complete, Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REDI - Admission Decision Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEND - Additional Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAMT - Auto Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMT – Admitted, Ready for Intake Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTV – Fit and EWB Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLRD - Cleared to Start</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENRL – Enrolled and Assigned a Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEVR – Never completed EWOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DROP – Dropped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAMT - Not Admitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAYT - Not Admitted Yet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MATR – Matriculated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRAD – Ready for Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALUMNI - Graduated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/ClearedToEnrolled.cls
/*
* Schedulable Class for updating Opportunity records with CAREStatusListView of 'CLRD' 
* and CloseDate occuring in the current calendar month to CAREStatus of 'ENRL – Enrolled and Assigned a Mentor'.
*
* Created 12/11/2013 by Katarina Melki
*/
global class ClearedToEnrolled implements Schedulable
{
    private static String CRON_EXP = '0 0 1 1 * ?';
    
    global static String schedule()
	{
		return System.schedule('CARE Status CLRD->ENRL Update', CRON_EXP, new EnrolltoMatriculated());
	}
    
    global void execute(SchedulableContext sc)
    {
        List<Opportunity> opps=[SELECT Id, CAREStatus__c FROM Opportunity WHERE CAREStatusListView__c='CLRD' AND CloseDate=THIS_MONTH];

        for (Opportunity opp : opps) 
        {
            opp.CAREStatus__c='ENRL – Enrolled and Assigned a Mentor';
        }
        
        update opps;
    }
}