src/objects/PKB_Article_Feedback_Deflection__c.object
<CustomObject>
    <description>Stores data about feedback provided to an article and any customer deflection the article may have contributed to.</description>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_ID__c</fullName>
        <label>Session ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PKB Article Deflection</label>
    <nameField>
        <displayFormat>AFD-{0000000}</displayFormat>
        <label>PKB Article Feedback &amp; Deflection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PKB Article Deflection</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PkbWguArticleViewController.cls
public with sharing class PkbWguArticleViewController extends pkb_Controller {
	public PkbWguArticleViewController(ApexPages.KnowledgeArticleVersionStandardController ctl) {
		setQueryStringParms();
    	getSessionCookie();

	    SObject article = ctl.getRecord();
	    String knowledgeArticleId = (String)article.get('KnowledgeArticleId');
	    theKad = new KnowledgeArticleData(knowledgeArticleId, selectedLanguage);
      	theAV = theKad.theAV;
        List<PKB_Article_Feedback_Deflection__c> afds = [
          select
            Id
          from PKB_Article_Feedback_Deflection__c
          where
            Session_ID__c = :sessionId and
            Article_Number__c = :theKad.articleNumber
        ];
        feedbackRecorded = !afds.isEmpty();
		theArticle = [SELECT Id FROM KnowledgeArticle WHERE Id = :knowledgeArticleId];
	}
}