src/objects/ProgramFeedback__c.object
<CustomObject>
    <description>Item to house course and other product information gathered from feedback forms.</description>
    <fields>
        <fullName>ChangeOwner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Change Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>College__c</fullName>
        <label>College</label>
        <picklist>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Professions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teachers College</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OriginalFeedbackSubmitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user that originally submitted the feedback</description>
        <inlineHelpText>The user that originally submitted the feedback</inlineHelpText>
        <label>Original Feedback Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProductFeedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status or stage of processing the feedback</description>
        <inlineHelpText>The status or stage of processing the feedback</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - No Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>For Future Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Scheduled Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Vendor Reply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubmitterRole__c</fullName>
        <description>The user role of the person that submitted the feedback</description>
        <label>Submitter Role</label>
        <picklist>
            <picklistValues>
                <fullName>CM Maintenance SME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor/Mentor Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff/Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Mentor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program Feedback</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>ProgramFeedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Feedback</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CoSFeedbackController.cls
public with sharing class CoSFeedbackController
{
    public Attachment fbAttachment { get;set; }
    public ProgramFeedback__c fb { get;set; }
    public string collegeOption { get;set; }
    public string userFullName { get;set; }
    public string userRole { get;set; }

    public CoSFeedbackController(ApexPages.StandardController controller) 
    {
        fbAttachment = new Attachment();
        fb = (ProgramFeedback__c)controller.getRecord();
        userFullName = this.getUserFullName();
        userRole = this.getUserRole();
    }
    
    public Attachment getFbAttachment()
    {
        return fbAttachment;
    }       
    
    public List<SelectOption> getColleges()
    {
        List<SelectOption> colleges = new List<SelectOption>();
        colleges.add(new SelectOption('Business', 'Business'));
        colleges.add(new SelectOption('Health Professions', 'Health Professions'));
        colleges.add(new SelectOption('Information Technology', 'Information Technology'));
        colleges.add(new SelectOption('Teachers College', 'Teachers College'));
        colleges.add(new SelectOption('General Education', 'General Education'));
        return colleges;
    }
    
    public String getUserFullName()
    {
        userFullName = UserInfo.getName();
        return userFullName;
    }
    
    public String getUserRole()
    {
        String thisProfileName = 'Staff/Other';

        if (UserInfo.getProfileId() == [SELECT Id FROM Profile WHERE Name = 'Student Profile' LIMIT 1].Id)
        {
            thisProfileName = 'Student';
        }
        else if (UserInfo.getProfileId() == [SELECT Id FROM Profile WHERE Name = 'Mentor' LIMIT 1].Id ||
                 UserInfo.getProfileId() == [SELECT Id FROM Profile WHERE Name = 'Mentor Manager' LIMIT 1].Id)
        {
            thisProfileName = 'Mentor/Mentor Manager';
        }
        return thisProfileName;
    }
    
    public PageReference saveWithAttachment()
    {        
        String queryString = 'SELECT QueueId FROM QueueSObject WHERE Queue.Name = \'Program Feedback Triage\' LIMIT 1';

        List<QueueSobject> queueList;                
        
        if (!Test.isRunningTest() && userRole.equals('Student')) 
        {
            RestAdapter ra = new RestAdapter();
            
            if (ra != null)
            {
                queueList = (List<QueueSObject>)ra.queryObjects(queryString); 
            }
            else
            {
                queueList = (List<QueueSObject>)Database.query(queryString);
            }
        } 
        else 
        { 
            queueList = (List<QueueSObject>)Database.query(queryString); 
        }
        
        fb.ownerId = UserInfo.getUserId();            
        fb.OriginalFeedbackSubmitter__c = UserInfo.getUserId();
        fb.college__c = collegeOption;
        fb.status__c = 'Open';
        fb.SubmitterRole__c = userRole;
        
        //Insert Program Feedback record with owner temporarily set as submitter
        insert fb;
        
        //Insert attachment while submitter is still the owner
        if (fbAttachment.body != null)
        {
            fbAttachment.parentId = fb.id;
            insert fbAttachment;
        }                
            
        //Fire the workflow to change the owner to the queue
        if (queueList.size() > 0)
        {                
            fb.changeOwner__c = true;
            update fb;
        }                                              
        
        PageReference pr = new PageReference('/apex/FeedbackReceived');
        pr.setRedirect(true);
        return pr;        
    }     
}