src/objects/ProgramFeedback__c.object
<CustomObject>
    <description>Item to house course and other product information gathered from feedback forms.</description>
    <fields>
        <fullName>OriginalFeedbackSubmitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user that originally submitted the feedback</description>
        <inlineHelpText>The user that originally submitted the feedback</inlineHelpText>
        <label>Original Feedback Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProductFeedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubmitterRole__c</fullName>
        <description>The user role of the person that submitted the feedback</description>
        <label>Submitter Role</label>
        <picklist>
            <picklistValues>
                <fullName>CM Maintenance SME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Course Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentor/Mentor Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff/Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Mentor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program Feedback</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>ProgramFeedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Feedback</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCoSFeedbackController.cls
/*****************************************************************************************
* Name: TestCoSFeedbackController
* Author: Will Slade
* Purpose: Test class CoSFeedbackController
* Revisions: 
*    - 2/7/13 Created Class
******************************************************************************************/

@isTest
global class TestCoSFeedbackController
{
    static testMethod void TestCoSFeedbackControllerAsStaff()
    {
        Profile adminProf = [select id from profile where name='System Administrator']; 
        User au = new User(alias = 'admin723', email='adminuser@testorg.com.wgu.edu', 
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
        localesidkey='en_US', profileid = adminProf.Id, 
        timezonesidkey='America/Los_Angeles', username='adminuser834@testorg.com');                
        
        Test.startTest();
        
        System.runAs(au)
        {
            ProgramFeedback__c testPF = new ProgramFeedback__c();        
            
            ApexPages.StandardController stdCont = new ApexPages.standardController(testPF);
                   
            CoSFeedbackController testController = new CoSFeedbackController(stdCont);
            
            Blob attachBody = Blob.valueOf('attachment body');
            Attachment attach = new Attachment(Name = 'testfeedbackattach.pdf', Body = attachBody);            
            
            testController.FbAttachment = attach;
            testController.getFbAttachment();        
            testController.getColleges();
            testController.getUserFullName();
            testController.getUserRole();
            testController.saveWithAttachment();                                    
        }
        Test.stopTest();
        
        List<ProgramFeedback__c> pfList = [SELECT Id, SubmitterRole__c FROM ProgramFeedback__c WHERE OriginalFeedbackSubmitter__c = :au.Id];
        
        System.assert(pfList.size() == 1, 'Found newly created Program Feedback record');
        System.assertEquals(pfList[0].SubmitterRole__c, 'Staff/Other', 'Correct Submitter Role assigned to Program Feedback record');
    }
    
    static testMethod void TestCoSFeedbackControllerAsMentor()
    {
        Profile mentorProf = [select id from profile where name='Mentor']; 
        User mu = new User(alias = 'ment723', email='mentoruser@testorg.com.wgu.edu', 
        emailencodingkey='UTF-8', lastname='Testing2', languagelocalekey='en_US', 
        localesidkey='en_US', profileid = mentorProf.Id, 
        timezonesidkey='America/Los_Angeles', username='mentoruser834@testorg.com');                
        
        Test.startTest();
        
        System.runAs(mu)
        {
            ProgramFeedback__c testPF = new ProgramFeedback__c();        
            
            ApexPages.StandardController stdCont = new ApexPages.standardController(testPF);
                   
            CoSFeedbackController testController = new CoSFeedbackController(stdCont);
            
            Blob attachBody = Blob.valueOf('attachment body');
            Attachment attach = new Attachment(Name = 'testfeedbackattach.pdf', Body = attachBody);            
            
            testController.FbAttachment = attach;
            testController.getFbAttachment();        
            testController.getColleges();
            testController.getUserFullName();
            testController.getUserRole();
            testController.saveWithAttachment();                                    
        }
        Test.stopTest();
        
        List<ProgramFeedback__c> pfList = [SELECT Id, SubmitterRole__c FROM ProgramFeedback__c WHERE OriginalFeedbackSubmitter__c = :mu.Id];
        
        System.assert(pfList.size() == 1, 'Found newly created Program Feedback record');
        System.assertEquals(pfList[0].SubmitterRole__c, 'Mentor/Mentor Manager', 'Correct Submitter Role assigned to Program Feedback record');
    }        
}