src/objects/Runtime__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Store sandbox related values for runtime context</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Runtime</label>
</CustomObject>

src/classes/TestReadinessAssessmentController.cls
@IsTest
public class TestReadinessAssessmentController {
    @IsTest
    public static void testControllerSetup() {
        Runtime__c c = new Runtime__c();
        c.Name = 'web3_domain';
        c.Value__c = 'unit.test.wgu.edu';
        insert c;
        
        Test.startTest();
            ReadinessAssessmentExtensionController controller = new ReadinessAssessmentExtensionController(null);
        Test.stopTest();
        
        System.assert(controller.actionURL == 'https://unit.test.wgu.edu/care2/AA_Assesment_Details.asp');
    }
}