src/objects/Runtime__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Store sandbox related values for runtime context</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Runtime</label>
</CustomObject>

src/classes/ReadinessAssessmentExtensionController.cls
public class ReadinessAssessmentExtensionController {
    private ApexPages.StandardController controller;
    public String actionURL {set;get;}
    
    public ReadinessAssessmentExtensionController(ApexPages.StandardController controller) {
        this.controller = controller;
        
        Runtime__c domain = Runtime__c.getValues('web3_domain');
        this.actionURL = 'https://' + domain.Value__c + '/care2/AA_Assesment_Details.asp';
    }
    
    
}