src/objects/StudentEquivalentCourse__c.object
<CustomObject>
    <description>WGU&apos;s courses and the link between transfered course for which a student may receive credit.</description>
    <fields>
        <fullName>TransferAttendance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Transfer Attendance</description>
        <label>Transfer Attendance</label>
        <referenceTo>TransferAttendance__c</referenceTo>
        <relationshipLabel>Student Equivalent Courses</relationshipLabel>
        <relationshipName>Student_Equivalent_Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransferredCourse__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transferred Course</label>
        <referenceTo>StudentTransferredCourse__c</referenceTo>
        <relationshipLabel>Student Equivalent Courses</relationshipLabel>
        <relationshipName>StudentEquivalentCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <formula>WGUCourseInProgram__r.Course__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>WGU Course</label>
        <type>Text</type>
    </fields>
    <label>Student Equivalent Course</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Student Equivalent Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Equivalent Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentTranscript__c.object
<CustomObject>
    <description>Object to manage the transcripts that must be collected through in-take and viewed by Mentors</description>
    <fields>
        <fullName>PIDM__c</fullName>
        <formula>Opportunity__r.Account.PIDM__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PIDM</label>
        <type>Text</type>
    </fields>
    <label>Student Transfer Institution</label>
    <nameField>
        <displayFormat>Institution-{0000}</displayFormat>
        <label>Student Transfer Institution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transfer Institution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentTransferredCourse__c.object
<CustomObject>
    <description>Shows courses that were transferred to WGU. Child object of Student Transfer Instituition.</description>
    <fields>
        <fullName>StudentTransferInstitution__c</fullName>
        <label>Student Transfer Institution</label>
        <referenceTo>StudentTranscript__c</referenceTo>
        <relationshipName>TransferCourses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TransferAttendance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer Attendance</label>
        <referenceTo>TransferAttendance__c</referenceTo>
        <relationshipLabel>Student Transferred Courses</relationshipLabel>
        <relationshipName>StudentTransferredCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Transferred Course</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Transferred Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TranscriptToBanner__c.object
<CustomObject>
    <description>Sync object to house Transcripts being pushed to Banner</description>
    <fields>
        <fullName>ActionNeeded__c</fullName>
        <label>Action Needed</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIDM__c</fullName>
        <description>PIDM of the related Opportunity</description>
        <label>PIDM</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <description>Salesforce ID of the parent object as it relates to the BANNER tables</description>
        <label>Parent Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RefId__c</fullName>
        <description>Id of the Salesforce record to which this control object is directly linked</description>
        <externalId>true</externalId>
        <label>Ref Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentEquivalentCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Equivalent Course</label>
        <referenceTo>StudentEquivalentCourse__c</referenceTo>
        <relationshipLabel>Transcripts to Banner</relationshipLabel>
        <relationshipName>TranscriptsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentTransferInstitution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Transfer Institution</label>
        <referenceTo>StudentTranscript__c</referenceTo>
        <relationshipLabel>Transcripts to Banner</relationshipLabel>
        <relationshipName>TranscriptsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StudentTransferredCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Transferred Course</label>
        <referenceTo>StudentTransferredCourse__c</referenceTo>
        <relationshipLabel>Transcripts to Banner</relationshipLabel>
        <relationshipName>TranscriptsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransferAttendance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer Attendance</label>
        <referenceTo>TransferAttendance__c</referenceTo>
        <relationshipLabel>Transcripts to Banner</relationshipLabel>
        <relationshipName>TranscriptsToBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WGUCourseCode__c</fullName>
        <description>WGU Course Code for the equivalent course</description>
        <label>WGU Course Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Transcript to Banner</label>
    <nameField>
        <displayFormat>T2B-{0000000}</displayFormat>
        <label>Transcript to Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcripts to Banner</pluralLabel>
    <recordTypes>
        <fullName>StudentEquivalentCourse</fullName>
        <active>true</active>
        <label>StudentEquivalentCourse</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TransferAttendance__c.object
<CustomObject>
    <description>This is a record of attendance at other institutions including any degrees awarded, program, GPA, and dates of attendance.</description>
    <fields>
        <fullName>StudentTransferInstitution__c</fullName>
        <label>Student Transfer Institution</label>
        <referenceTo>StudentTranscript__c</referenceTo>
        <relationshipLabel>Transfer Attendance</relationshipLabel>
        <relationshipName>TransferAttendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transfer Attendance</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Transfer Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transfer Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StudentEquivalentCourseUtility.cls
/*****************************************************************************************
* Name: StudentEquivalentCourseUtility
* Author: Brad King
* Purpose: 
* Revisions: 
*    - 4/23/2013 Created Class
*    - 7/08/2013 Modified class on update to re-populate PIDM
*
******************************************************************************************/

public class StudentEquivalentCourseUtility
{
    /////////////////////////// Update Transcripts To Banner ///////////////////////////    
    public static void updateTranscriptsToBanner(String equivCourseListJSON)
    {
        if (Limits.getFutureCalls() > 8 || System.isFuture())
        {
            processUpdateTranscriptsToBanner(equivCourseListJSON);
        }
        else
        {
            asyncUpdateTranscriptsToBanner(equivCourseListJSON);
        }
    }
    
    @future
    public static void asyncUpdateTranscriptsToBanner(String equivCourseListJSON)
    {
        processUpdateTranscriptsToBanner(equivCourseListJSON);
    }

    public static void processUpdateTranscriptsToBanner(String equivCourseListJSON)
    {        
        List<StudentEquivalentCourse__c> equivCourseList = (List<StudentEquivalentCourse__c>) JSON.deserialize(equivCourseListJSON, List<StudentEquivalentCourse__c>.class);
        List<Id> equivCourseIds = new List<Id>();
        List<TranscriptToBanner__c> eqToBanList = new List<TranscriptToBanner__c>();
        List<TranscriptToBanner__c> eqToBanAddList = new List<TranscriptToBanner__c>();
        Map<Id, Id> eqCrsToTrBanMap = new Map<Id, Id>();
        RecordType equivCourseRT = [SELECT Id FROM RecordType WHERE SObjectType = 'TranscriptToBanner__c' AND DeveloperName = 'StudentEquivalentCourse' LIMIT 1];
        
        //Populate map keys with all Equivalent Course Ids from the trigger
        for (StudentEquivalentCourse__c equivCourse : equivCourseList)
        {
            equivCourseIds.add(equivCourse.Id);
            eqCrsToTrBanMap.put(equivCourse.Id, null);
        }
        
        eqToBanList = [SELECT Id, StudentEquivalentCourse__c, ActionNeeded__c, StudentEquivalentCourse__r.WGUCourse__c,
                              StudentEquivalentCourse__r.TransferredCourse__c, 
                              StudentEquivalentCourse__r.TransferredCourse__r.TransferAttendance__c,
                              StudentEquivalentCourse__r.TransferredCourse__r.StudentTransferInstitution__c,
                              StudentEquivalentCourse__r.TransferredCourse__r.StudentTransferInstitution__r.Pidm__c                              
                       FROM TranscriptToBanner__c 
                       WHERE StudentEquivalentCourse__c
                       IN :equivCourseIds AND RecordTypeId = :equivCourseRT.Id];
        
        //Add control object Ids to the map where they exist - also set Action Needed field to Update for push job
        for (TranscriptToBanner__c eqToBan : eqToBanList)
        {
            eqCrsToTrBanMap.put(eqToBan.StudentEquivalentCourse__c, eqToBan.Id);
            eqToBan.ActionNeeded__c = eqToBan.ActionNeeded__c == 'Insert' ? 'Insert' : 'Update';
            eqToBan.WGUCourseCode__c = eqToBan.StudentEquivalentCourse__r.WGUCourse__c;
            eqToBan.StudentTransferredCourse__c = eqToBan.StudentEquivalentCourse__r.TransferredCourse__c;
            eqToBan.TransferAttendance__c = eqToBan.StudentEquivalentCourse__r.TransferredCourse__r.TransferAttendance__c;
            eqToBan.StudentTransferInstitution__c = eqToBan.StudentEquivalentCourse__r.TransferredCourse__r.StudentTransferInstitution__c;
            eqToBan.Pidm__c = eqToBan.StudentEquivalentCourse__r.TransferredCourse__r.StudentTransferInstitution__r.Pidm__c;
        }
        
        //For any missing control objects, create the record with Insert Action Needed
        for (StudentEquivalentCourse__c equivCourse : equivCourseList)
        {
            if (eqCrsToTrBanMap.get(equivCourse.Id) == null)
            {
                eqToBanAddList.add(new TranscriptToBanner__c(RecordTypeId = equivCourseRT.Id, 
                                                             StudentEquivalentCourse__c = equivCourse.Id,
                                                             StudentTransferredCourse__c = equivCourse.TransferredCourse__c,
                                                             TransferAttendance__c = equivCourse.TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__c, 
                                                             RefId__c = String.valueOf(equivCourse.Id),
                                                             ParentId__c = String.valueOf(equivCourse.TransferredCourse__c), 
                                                             ActionNeeded__c = 'Insert',
                                                             PIDM__c = equivCourse.TransferredCourse__r.TransferAttendance__r.StudentTransferInstitution__r.Pidm__c,
                                                             WGUCourseCode__c = equivCourse.WGUCourse__c));
            }
        }
        
        update eqToBanList;
        insert eqToBanAddList;
    }    
}