src/objects/StudentCourseRegistration__c.object
<CustomObject>
    <description>This is an object for pulling current term registration  information from WGUFDP. No FDP user should have direct access to this Object,</description>
    <fields>
        <fullName>Termcode__c</fullName>
        <label>Termcode</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student Course Registration</label>
    <nameField>
        <label>StudentCourseRegistration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Course Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FDPScheduler.cls
global class FDPScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        String termcode = generateTermCode(
          Date.Today().addMonths(-6)
        );
        String query = 'select Id '
          + ' from StudentCourseRegistration__c '
          + ' where TermCode__c <= \'' + termcode + '\' ';
        Database.executeBatch(new BatchDelete(query));
    }
     public static String generateTermCode(Date termStart) {
        String code;
        Integer month = termStart.month();

        // Term name is term code 'yyyyMM'.
        if (month < 10)
            code = String.valueOf(termStart.year()) + '0' + String.valueOf(month);
        else
            code = String.valueOf(termStart.year()) + String.valueOf(month);

        return code;
    }
}