src/objects/StudentCompletionCourse__c.object
<CustomObject>
    <description>This stores the information for the results of the courses.</description>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The student whom this completion task belongs to.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Completion Courses</relationshipLabel>
        <relationshipName>StudentCompletionCourses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Completion Course</label>
    <nameField>
        <label>PAMS Course ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Completion Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FDPHistoryFixScheduler.cls
global class FDPHistoryFixScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        LIST<AggregateResult> count=[select count(id) cnt from studentcompletioncourse__C where lastmodifieddate>Yesterday];
        if( (integer)count[0].get('cnt')>200000){
        String query = 'select id from studentcompletioncourse__C where lastmodifieddate<Yesterday order by student__C ';
        Database.executeBatch(new BatchFixForHistory(query),20);
        }
    }
   
}