src/objects/StudentAcademicCourse__c.object
<CustomObject>
    <description>A representation of a course being taken at WGU wither in the past, current enrollment, or tentatively planned in the future. Includes credited courses such as transferred competency units or requirements met while working on  another degree.</description>
    <fields>
        <fullName>Attempts__c</fullName>
        <description>Roll up summary of child Student Academic Course Attempt.</description>
        <label>Attempts</label>
        <summaryForeignKey>StudentAcademicCourseAttempt__c.StudentAcademicCourse__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CompositeKey__c</fullName>
        <externalId>true</externalId>
        <label>Composite Key</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the course in relation to the student&apos;s progress in it or credit to it.</description>
        <inlineHelpText>The status of the course in relation to the student&apos;s progress in it or credit to it.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requirements Met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unenrolled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Objective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student Academic Course</label>
    <nameField>
        <label>Course Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Academic Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentAcademicCourseAttempt__c.object
<CustomObject>
    <description>Represents an attempt against a specific assessment or task of a course.</description>
    <fields>
        <fullName>AssessmentTaskCode__c</fullName>
        <label>Assessment / Task Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attempted__c</fullName>
        <description>The date and time, this attempt was made on a required component of the course.</description>
        <inlineHelpText>The date and time, this attempt was made on a required component of the course.</inlineHelpText>
        <label>Attempted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CompositeKey__c</fullName>
        <externalId>true</externalId>
        <label>Composite Key</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Passed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StudentAcademicCourse__c</fullName>
        <label>Student Academic Course</label>
        <referenceTo>StudentAcademicCourse__c</referenceTo>
        <relationshipLabel>Student Academic Course Attempts</relationshipLabel>
        <relationshipName>StudentAcademicCourseAttempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Objective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Student Academic Course Attempt</label>
    <nameField>
        <label>Assessment / Task Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Academic Course Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/StudentAcademicCourseAttFromBan__c.object
<CustomObject>
    <description>Control object</description>
    <fields>
        <fullName>ActionNeeded__c</fullName>
        <label>Action Needed</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssessmentTaskCodeIN__c</fullName>
        <label>Assessment / Task Code IN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttemptedIN__c</fullName>
        <label>Attempted (IN)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CompositeKeyIN__c</fullName>
        <description>PIDM + Course Code + Test Date</description>
        <externalId>true</externalId>
        <label>Composite Key (IN)</label>
        <length>45</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CompositeParentKeyIN__c</fullName>
        <description>PIDM + Course Code + Term Code</description>
        <label>Composite Parent Key (IN)</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PassedIN__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passed (IN)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StudentAcademicCourseAttempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Academic Course Attempt</label>
        <referenceTo>StudentAcademicCourseAttempt__c</referenceTo>
        <relationshipLabel>Student Academic Course Atts From Banner</relationshipLabel>
        <relationshipName>StudentAcademicCourseAttsFromBanner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SynchronizationError__c</fullName>
        <label>Synchronization Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeIN__c</fullName>
        <description>Obj/Prfm etc</description>
        <label>Type (IN)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Student Academic Course Att From Banner</label>
    <nameField>
        <displayFormat>SACAFB-{0}</displayFormat>
        <label>Student Academic Course Att From Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Academic Course Atts From Banner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StudentAcademicCourseRequirement__c.object
<CustomObject>
    <description>Stores the requirements to complete a version of a course. For many records early on, this will only be one assessment to a course. Nursing will be the first group to apply multiple assessments to course. Several roll up summaries will be placed on the parent object to summarize status and engagement.</description>
    <fields>
        <fullName>Attempts__c</fullName>
        <description>The number of attempts made against this specific requirement and not the course as a whole.</description>
        <inlineHelpText>The number of attempts made against this specific requirement and not the course as a whole.</inlineHelpText>
        <label>Attempts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompletedDate__c</fullName>
        <description>The date the requirement was completed.</description>
        <inlineHelpText>The date the requirement was completed.</inlineHelpText>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The text status from Course of Study.</description>
        <label>Status</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudentAcademicCourse__c</fullName>
        <label>Student Academic Course</label>
        <referenceTo>StudentAcademicCourse__c</referenceTo>
        <relationshipLabel>Student Academic Course Requirements</relationshipLabel>
        <relationshipName>StudentAcademicCourseRequirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Objective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Student Academic Course Requirement</label>
    <nameField>
        <label>Assessment / Task Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Academic Course Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StudentAcademicCourseAttemptUtility.cls
/*****************************************************************************************
* Name: StudentAcademicCourseAttemptUtility
* Author: Will Slade
* Purpose: Upserts Student Academic Course Attempt based on control object
* Revisions: 
*    - 10/25/2013 Created Class - WS
*    -  2/26/2014 Added Functionality For Aggregate Attempts Count on Requirement Object - WS
*
******************************************************************************************/

public class StudentAcademicCourseAttemptUtility
{
    public static void upsertAttempts(String sacafbListJSON)
    {
        if (Limits.getFutureCalls() > 3 || System.isFuture())
        {
            processUpsertAttempts(sacafbListJSON);
        }
        else
        {
            asyncUpsertAttempts(sacafbListJSON);
        }
    }
    
    @future
    public static void asyncUpsertAttempts(String sacafbListJSON)
    {
        processUpsertAttempts(sacafbListJSON);
    }

    public static void processUpsertAttempts(String sacafbListJSON)
    {
        List<StudentAcademicCourseAttFromBan__c> sacafbList = (List<StudentAcademicCourseAttFromBan__c>) JSON.deserialize(sacafbListJSON, List<StudentAcademicCourseAttFromBan__c>.class);
        List<StudentAcademicCourseAttempt__c> sacaInsertList = new List<StudentAcademicCourseAttempt__c>();
        List<StudentAcademicCourseAttempt__c> sacaUpdateList = new List<StudentAcademicCourseAttempt__c>();
        List<StudentAcademicCourseAttempt__c> sacaDeleteList = new List<StudentAcademicCourseAttempt__c>(); 
        Map<String, Id> srcParentCompToIdMap = new Map<String, Id>();
        Id studentAcademicCourse = null;
               
        //get a keyset of the parent composite keys
        for (StudentAcademicCourseAttFromBan__c thisSACAFB : sacafbList)
        {
            srcParentCompToIdMap.put(thisSACAFB.CompositeParentKeyIN__c, null);
        }
        
        //find all parent records within keyset
        List<StudentAcademicCourse__c> sacList = [SELECT Id, CompositeKey__c 
                                                  FROM StudentAcademicCourse__c
                                                  WHERE CompositeKey__c IN :srcParentCompToIdMap.keyset()];
                                                  
        //populate parent IDs in the map
        for (StudentAcademicCourse__c thisSAC : sacList)
        {
            srcParentCompToIdMap.put(thisSAC.CompositeKey__c, thisSAC.Id);
        }
        
        //loop through map and upsert source records
        for (StudentAcademicCourseAttFromBan__c thisSACAFB : sacafbList)
        {       
            if (srcParentCompToIdMap.get(thisSACAFB.CompositeParentKeyIN__c) != null)
            {             
                studentAcademicCourse = srcParentCompToIdMap.get(thisSACAFB.CompositeParentKeyIN__c);
            } 
            else
            {
                studentAcademicCourse = null;
            }
        
            if ((thisSACAFB.ActionNeeded__c == 'Insert' || thisSACAFB.ActionNeeded__c == 'Update' || thisSACAFB.ActionNeeded__c == 'Upsert')
                && thisSACAFB.SynchronizationError__c == null && studentAcademicCourse != null)
            {            
                if (thisSACAFB.StudentAcademicCourseAttempt__c == null)
                {                                    
                    sacaInsertList.add(new StudentAcademicCourseAttempt__c(CompositeKey__c = thisSACAFB.CompositeKeyIn__c,
                                                                           AssessmentTaskCode__c = thisSACAFB.AssessmentTaskCodeIN__c,
                                                                           Attempted__c = thisSACAFB.AttemptedIN__c,
                                                                           Passed__c = thisSACAFB.PassedIN__c,
                                                                           StudentAcademicCourse__c = studentAcademicCourse,
                                                                           Type__c = thisSACAFB.TypeIN__c));
                }
                if (thisSACAFB.StudentAcademicCourseAttempt__c != null)
                {                                    
                    sacaUpdateList.add(new StudentAcademicCourseAttempt__c(Id = thisSACAFB.StudentAcademicCourseAttempt__c,
                                                                           CompositeKey__c = thisSACAFB.CompositeKeyIn__c,
                                                                           AssessmentTaskCode__c = thisSACAFB.AssessmentTaskCodeIN__c,
                                                                           Attempted__c = thisSACAFB.AttemptedIN__c,
                                                                           Passed__c = thisSACAFB.PassedIN__c,
                                                                           StudentAcademicCourse__c = studentAcademicCourse,                                                                           
                                                                           Type__c = thisSACAFB.TypeIN__c));
                }                
            }
            else if (thisSACAFB.ActionNeeded__c == 'Delete' && thisSACAFB.StudentAcademicCourseAttempt__c != null)
            {
                sacaDeleteList.add(new StudentAcademicCourseAttempt__c(Id = thisSACAFB.StudentAcademicCourseAttempt__c));
            }                     
            //some key value is missing
            else
            {
                //do not add the record to any update or insert lists as it has an error
            }
        }
        
        update sacaUpdateList;
        insert sacaInsertList;
        delete sacaDeleteList;                                                                                         
    }

    
    public static void updateCourseRequirement(String sacafbListJSON){
        if (Limits.getFutureCalls() > 3 || System.isFuture()){
            processUpdateCourseRequirement(sacafbListJSON);
        }else{
            asyncUpdateCourseRequirement(sacafbListJSON);
        }
    }
    
    @future
    public static void asyncUpdateCourseRequirement(String sacafbListJSON){
        processUpdateCourseRequirement(sacafbListJSON);
    }
    
    public static void processUpdateCourseRequirement(String sacafbListJSON){
        List<StudentAcademicCourseAttFromBan__c> sacafbList = (List<StudentAcademicCourseAttFromBan__c>) JSON.deserialize(sacafbListJSON, List<StudentAcademicCourseAttFromBan__c>.class);
        List<StudentAcademicCourseRequirement__c> sacrUpdateList = new List<StudentAcademicCourseRequirement__c>();
        Set<String> uniKeySet = new Set<String>();
        List<String> comPKList = new List<String>();
        Map<String,String> uniKeyComPK = new MAP<String,String>();
        Map<String,String> gradeMap = new Map<String,String>();
        Map<String,Datetime> completedDateMap = new Map<String,Datetime>();
        for(StudentAcademicCourseAttFromBan__c sacafb : sacafbList){
            if(sacafb.CompositeKeyIN__c == null || sacafb.CompositeParentKeyIN__c == null) continue;
            String compositeKey = sacafb.CompositeKeyIN__c;
            String term = sacafb.CompositeParentKeyIN__c.right(6);
            if(Integer.valueOf(term) <= 0) continue;
            String uniKey = compositeKey.substring(0,compositeKey.lastIndexOf('-')+1) + term;
            uniKeySet.add(uniKey);
            comPKList.add(sacafb.CompositeParentKeyIN__c);
            uniKeyComPK.put(uniKey, sacafb.CompositeParentKeyIN__c);
        }
        //save the latest record in Map from control object
        List<StudentAcademicCourseAttFromBan__c> crseAttFBList = [SELECT CompositeParentKeyIn__c, PassedIN__c, AttemptedIN__c
                                                                  FROM StudentAcademicCourseAttFromBan__c
                                                                  WHERE CompositeParentKeyIN__c IN: comPKList
                                                                  AND AttemptedIN__c != null
                                                                  ORDER BY CompositeParentKeyIN__c, AttemptedIN__c DESC];
        for(StudentAcademicCourseAttFromBan__c cafb : crseAttFBList){
            if(!gradeMap.containsKey(cafb.CompositeParentKeyIn__c)){
                String grade = Boolean.valueOf(cafb.PassedIN__c) ? 'P' : 'NP';
                gradeMap.put(cafb.CompositeParentKeyIn__c, grade);
                completedDateMap.put(cafb.CompositeParentKeyIn__c, cafb.AttemptedIN__c);
            }
        }
        //get corresponding data from Coure Requirement 
        List<StudentAcademicCourseRequirement__c> sacrList = [SELECT Id,UniqueKey__c,Status__c
                                                              FROM StudentAcademicCourseRequirement__c
                                                              WHERE UniqueKey__c IN: uniKeySet];
        for(StudentAcademicCourseRequirement__c sacr : sacrList){
            String comPK = uniKeyComPK.get(sacr.UniqueKey__c);
            String status = gradeMap.get(comPK);
            sacr.Status__c = status;
            if('P'.equals(status)){
                sacr.Completed__c = true;
                sacr.CompletedDate__c = completedDateMap.get(comPK).date();
            }else{
                sacr.Completed__c = false;
                sacr.CompletedDate__c = null;
            }
            sacrUpdateList.add(sacr);
        }
        update sacrUpdateList;
    }
////////////////////////////// Begin Count Attempts for Requirement Record /////////////////////////////    
    public static void countAttempts(String sacafbListJSON)
    {
        if (Limits.getFutureCalls() > 3 || System.isFuture())
        {
            processCountAttempts(sacafbListJSON);
        }
        else
        {
            asyncCountAttempts(sacafbListJSON);
        }
    }
    
    @future
    public static void asyncCountAttempts(String sacafbListJSON)
    {
        processCountAttempts(sacafbListJSON);
    }

    public static void processCountAttempts(String sacafbListJSON)
    {
        List<StudentAcademicCourseAttFromBan__c> sacafbList = (List<StudentAcademicCourseAttFromBan__c>) JSON.deserialize(sacafbListJSON, List<StudentAcademicCourseAttFromBan__c>.class);
        List<String> attemptCompKeyList = new List<String>();
        List<String> reqCompKeyList = new List<String>();        
        List<StudentAcademicCourseAttempt__c> sacaList = new List<StudentAcademicCourseAttempt__c>();
        List<StudentAcademicCourseRequirement__c> sacrList = new List<StudentAcademicCourseRequirement__c>();
        Map<String, String> attKeyToParentKeyMap = new Map<String, String>();

        for (StudentAcademicCourseAttFromBan__c sacafb : sacafbList)
        {
            reqCompKeyList.add(sacafb.CompositeParentKeyIN__c);             
        }
        
        sacafbList = [SELECT Id, CompositeKeyIN__c, CompositeParentKeyIN__c
                      FROM StudentAcademicCourseAttFromBan__c
                      WHERE CompositeParentKeyIN__c IN :reqCompKeyList];
                
        //Build lists of the composite keys for queries on source objects
        //Build map to link the attempt with its requirement parent record           
        for (StudentAcademicCourseAttFromBan__c sacafb : sacafbList)
        {
            attemptCompKeyList.add(sacafb.CompositeKeyIN__c);            
            attKeyToParentKeyMap.put(sacafb.CompositeKeyIN__c, sacafb.CompositeParentKeyIN__c);             
        }
        
        //Query lists of source attempt and requirement objects related to trigger contents
        sacaList = [SELECT Id, CompositeKey__c
                    FROM StudentAcademicCourseAttempt__c
                    WHERE CompositeKey__c IN :attemptCompKeyList];                   
                    
        sacrList = [SELECT Id, UniqueKey__c, Attempts__c
                    FROM StudentAcademicCourseRequirement__c
                    WHERE UniqueKey__c IN :reqCompKeyList];
        
        //For each requirement record, loop through the attempt records and get the total         
        for (StudentAcademicCourseRequirement__c sacr : sacrList)
        {         
            integer numAttempts = 0;            
            for (StudentAcademicCourseAttempt__c saca : sacaList)
            {                
                if (attKeyToParentKeyMap.get(saca.CompositeKey__c).equals(sacr.UniqueKey__c))
                {
                    numAttempts += 1;                    
                }
            }
            
            sacr.Attempts__c = numAttempts;            
        }
        
        update sacrList;                                                                                                                                       
    } 
/////////////////////////////// End Count Attempts for Requirement Record //////////////////////////////
}