src/objects/StudentProcess__c.object
<CustomObject>
    <description>Custom object to manage student processes by record type.</description>
    <fields>
        <fullName>Stage__c</fullName>
        <description>The stage of the student process.</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appeal Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assign Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Student Reply</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student spoke with Mentor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student spoke with other personnel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled: Student was submitted too early</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correction Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counsel Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Degree Plan Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diploma and Transcripts Mailed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diploma and Transcripts Mailed - Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midterm Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOU Accepted by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOU Needed - Custom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudentProcessAutoNumber__c</fullName>
        <description>Auto number for the student process object used for student facing forms.</description>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>Student Process Auto Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup field to the contact of the student process object.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Student Processes</relationshipLabel>
        <relationshipName>StudentProcesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Process</label>
    <nameField>
        <label>Student Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestIncompleteCourseSubmissionController.cls
/*
Test class  for IncompleteCourseSubmissionController
Author- Bhavadeep Raavi
*/


@isTest
private with sharing class TestIncompleteCourseSubmissionController {
    
    private static testmethod void TestMethodIncompleteCourseSubmissionController (){
       
        Contact contact= new Contact();
        contact.LastName='Test Cont';
        insert contact;
       
        StudentProcess__c sp=new StudentProcess__c();
        sp.name='Test sp';
        sp.student__c=contact.id;
        sp.Stage__c='MOU Accepted by Student';
        insert sp;
        
       // User testUser = [SELECT Id from User WHERE Profile.Name = 'Records User' AND isActive = true LIMIT 1];
        
   
            Test.startTest();
            PageReference pr = Page.IncompleteCourseSubmission;
            //pr.getParameters().put('StudentProcessAutoNumber__c',sp.StudentProcessAutoNumber__c);
            Test.setCurrentPage(pr);
            ApexPages.StandardController sc = new ApexPages.StandardController(sp);
            IncompleteCourseSubmissionController ics= new IncompleteCourseSubmissionController(sc);    
            ics.getNextPage();
        }
 }