src/objects/SynchronizeToBannerLog__c.object
<CustomObject>
    <description>A object to track the issues various *ToBanner__c objects have. All will be coded to create a single tracking object list that can be viewed and followed up on in Salesforce.</description>
    <fields>
        <fullName>ReferenceId__c</fullName>
        <label>Reference Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReferenceType__c</fullName>
        <description>The Salesforce object type this record refers to.</description>
        <label>Reference Type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Synchronize To Banner Log</label>
    <nameField>
        <displayFormat>BSL-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Synchronize To Banner Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WithdrawalToBanner__c.object
<CustomObject>
    <description>Control object for pushing student drops to Oracle/Banner</description>
    <fields>
        <fullName>ActionNeeded__c</fullName>
        <label>Action Needed</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Withdrawal To Banner</label>
    <nameField>
        <displayFormat>W2B-{0000000}</displayFormat>
        <label>Withdraw To Banner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Withdrawals To Banner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestWithdrawalToBannerUtility.cls
/*****************************************************************************************
* Name: TestWithdrawalToBannerUtility
* Author: Will Slade
* Purpose: Test Class for WithdrawalToBannerUtility and WithdrawalToBannerTrigger
* Revisions: 
*    5-31-2013 - Created Class
*
******************************************************************************************/

@isTest
public class TestWithdrawalToBannerUtility
{
    private static testMethod void testUtil()
    {
        WithdrawalToBanner__c wtb = new WithdrawalToBanner__c(ActionNeeded__c = 'Insert');    
        Insert wtb;
        
        List<WithdrawalToBanner__c> wtbList = [SELECT Id, ActionNeeded__c FROM WithdrawalToBanner__c WHERE ActionNeeded__c = 'Insert' LIMIT 100];        
        System.assertEquals(wtbList.size(), 1, 'Too many Withdrawal to Banner records were returned.  Test method only inserted 1.');
        
        for (WithdrawalToBanner__c wtb1 : wtbList)
        {
            wtb1.ActionNeeded__c = 'Error';
        } 
        
        Test.startTest();       
            Update wtbList;
        Test.stopTest();
        
        List<SynchronizeToBannerLog__c> stblList = [SELECT Id, ReferenceId__c FROM SynchronizeToBannerLog__c WHERE ReferenceType__c = 'WithdrawalToBanner__c'];        
        System.assertEquals(stblList.size(), 1, 'Should be 1 and only 1 Sync to Banner record as only 1 Withdrawal to Banner was updated with a status of Error');
        System.assertEquals(stblList[0].ReferenceId__c, String.valueOf(wtb.Id));
    }
}