src/objects/TransferEvaluation__c.object
<CustomObject>
    <description>A Transfer evaluation is the parent object of the equivalent courses that will given to the student from their transfer work. It controls the overall status and assignment of the evaluation.</description>
    <fields>
        <fullName>EvaluationStatus__c</fullName>
        <label>Evaluation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready for Evaluation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appealed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transfer Evaluation</label>
    <nameField>
        <label>Transfer Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transfer Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CARENoAdmitUtility.cls
public with sharing class CARENoAdmitUtility
{
    public static void cancelTransferEvals(String evalsToCancelJSON)
    {
        cancelTransferEvals(evalsToCancelJSON, !Test.isRunningTest());
    }    

    public static void cancelTransferEvals(String evalsToCancelJSON, boolean runFuture)
    {
        if (Test.isRunningTest() && runFuture == false)
        {
            processCancelTransferEvals(evalsToCancelJSON);
        }
        else
        {
            try
            {
                asyncCancelTransferEvals(evalsToCancelJSON);
            }
            catch (System.AsyncException e)
            {
                if (e.getMessage().contains('Future method cannot be called from a future'))
                {
                    processCancelTransferEvals(evalsToCancelJSON);
                }
                else
                {
                    throw e;
                }
            }
        }
    }        
    
    @future
    private static void asyncCancelTransferEvals(String evalsToCancelJSON)
    {
        processCancelTransferEvals(evalsToCancelJSON);
    }   
     
    private static void processCancelTransferEvals(String evalsToCancelJSON) 
    {   
        List<TransferEvaluation__c> evalsToCancel = (List<TransferEvaluation__c>)JSON.deserialize( evalsToCancelJSON, List<TransferEvaluation__c>.class );                       
        
        for (TransferEvaluation__c eval : evalsToCancel)
        {
            eval.EvaluationStatus__c = 'Canceled';  
        }
        
        update evalsToCancel;  
    }               
}