src/objects/UnhandledException__c.object
<CustomObject>
    <description>This is essentially an error logging object. When someone receives an exception in salesforce, an error code is referenced which will be a code to a record in this object. Additional information will be given here.</description>
    <fields>
        <fullName>AdditionalInfo__c</fullName>
        <label>Additional Info</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <description>The application where this occurred.</description>
        <label>Application</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LineNumber__c</fullName>
        <description>The line number in the object where the exception occurred.</description>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StackTrace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TypeName__c</fullName>
        <label>TypeName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Unhandled Exception</label>
    <nameField>
        <displayFormat>UE-{YYMMDD}-{0}</displayFormat>
        <label>Error Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unhandled Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UnhandledExceptionLogger.cls
public class UnhandledExceptionLogger {
  public String Application;
  public Integer LineNumber;
  public String Message;
  public String StackTrace;
  public String TypeName;
  public String ErrorCode;
  public String AdditionalInfo;
  private UnhandledException__c dbLog;

  public UnhandledExceptionLogger(Exception ex,String app,String additionalInfo) {
    this.Application = app;
    this.LineNumber = ex.getLineNumber();
    this.Message = ex.getMessage();
    this.StackTrace = ex.getStackTraceString();
    this.TypeName = ex.getTypeName();
    this.AdditionalInfo = additionalInfo;
    dbLog = new UnhandledException__c(
        Application__c = this.Application,
        LineNumber__c = this.LineNumber,
        Message__c = this.Message,
        StackTrace__c = this.StackTrace,
        TypeName__c = this.TypeName,
        AdditionalInfo__c = this.AdditionalInfo
    );
  }

  public void save() {
    insert dbLog;
    UnhandledException__c e = [select Id,Name from UnhandledException__c where Id = :dbLog.Id];
    this.ErrorCode = e.Name;
  }

  public static String logError(Exception ex,String app) {
    return logError(ex,app,'');
  }

  public static String logError(Exception ex,String app,String additionalInfo) {
    UnhandledExceptionLogger ue = new UnhandledExceptionLogger(ex,app,additionalInfo);
    ue.save();
    return ue.ErrorCode;
  }
}