src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IDMRequiresUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by the IDM to detect if changes occurred on this user record. Marked true by on update process handler, either workflow or trigger. Marked false when IDM completes processing the record.</description>
        <inlineHelpText>Used by the IDM to detect if changes occurred on this user record. Marked true by on update process handler, either workflow or trigger. Marked false when IDM completes processing the record.</inlineHelpText>
        <label>IDM Requires Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsEmployee__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this user is an employee please check this</description>
        <inlineHelpText>Checked if this user is an employee</inlineHelpText>
        <label>IsEmployee</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/TestUserTrigger.cls
@IsTest
public class TestUserTrigger{

    @IsTest static void IDMUpdateRequiredTest_True() {
        User u = [SELECT Id, City FROM User WHERE IsActive = true AND IsEmployee__c = false AND IDMRequiresUpdate__c = false LIMIT 1];
        
        u.City = 'Fakeville';
        Test.startTest();
        update u;
        Test.stopTest();
        
        User result = [SELECT Id, IDMRequiresUpdate__c FROM User WHERE Id = :u.id];
        System.assertEquals(true, result.IDMRequiresUpdate__c);
    }
    
    @IsTest static void IDMUpdateRequiredTest_False() {
        User u = [SELECT Id, City FROM User WHERE IsActive = true AND IsEmployee__c = true AND IDMRequiresUpdate__c = false LIMIT 1];
        
        u.City = 'Fakeville';
        Test.startTest();
        update u;
        Test.stopTest();
        
        User result = [SELECT Id, IDMRequiresUpdate__c FROM User WHERE Id = :u.id];
        System.assertEquals(false, result.IDMRequiresUpdate__c);
    }
    
}