src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this course is active.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PAMSID__c</fullName>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseInProgram__c.object
<CustomObject>
    <description>A many to many mapping that assigns which course are required to accomplish any degree program.</description>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipName>PAMS_Course_In_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAMSCourseID__c</fullName>
        <description>The unique ID that represents the course in PAMS that this mapping should be linked to in SalesForce.</description>
        <label>PAMS Course ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PAMSProgramID__c</fullName>
        <description>The unique id from PAMS that represents the Degree Program that this mapping should be linked to.</description>
        <label>PAMS Program ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>WGUDegreeProgram__c</referenceTo>
        <relationshipLabel>WGU Course In Programs</relationshipLabel>
        <relationshipName>WGUCourseInPrograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WGU Course In Program</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WGU Course In Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUDegreeProgram__c.object
<CustomObject>
    <description>Represents a program outline for students to follow in their way to get a degree.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Degree Program is active and can be used.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PAMSID__c</fullName>
        <description>The ID that represents the program in PAMS.</description>
        <externalId>true</externalId>
        <label>PAMS ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WGU Degree Program</label>
    <nameField>
        <label>Program Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Degree Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCourseInProgramTrigger.cls
@isTest
public class TestCourseInProgramTrigger {
     public static testMethod void testInsert(){
        WGUDegreeProgram__c program=new WGUDegreeProgram__c();
        program.Active__c=true;
        program.PAMSID__c=1234567;
        program.Name='testprogram';
        insert program;
        WGUCourse__c definition = new WGUCourse__c();
        definition.name = 'testcourse';
        definition.PAMSID__c=999999;
        insert definition;
         WGUCourseInProgram__c tie = new WGUCourseInProgram__c();
       
        tie.PAMSCourseID__c = 999999;
        tie.PAMSProgramID__c=1234567;
       
        insert tie;
       tie=[select course__C,program__C from WGUCourseInProgram__c where PAMSCourseID__c=999999 ];
        system.assertequals(tie.course__C,definition.id);
         system.assertequals(tie.program__C,program.id);
         
         
    
     
     }
      public static testMethod void testupdate(){
        WGUDegreeProgram__c program=new WGUDegreeProgram__c();
        program.Active__c=true;
        program.PAMSID__c=1234567;
        program.Name='testprogram';
        insert program;
        WGUCourse__c definition = new WGUCourse__c();
        definition.name = 'testcourse';
        definition.PAMSID__c=999999;
        insert definition;
     
         WGUCourseInProgram__c tie = new WGUCourseInProgram__c();
       
        tie.PAMSCourseID__c =7654321 ;
        tie.PAMSProgramID__c=7654322;
       
        insert tie;
       tie=[select course__C,program__C from WGUCourseInProgram__c where PAMSCourseID__c=7654321 limit 1];
         system.assertequals(tie.course__C,null);
         system.assertequals(tie.program__C,null);
           tie.PAMSCourseID__c = 999999;
        tie.PAMSProgramID__c=1234567;
        update tie;
        tie=[select course__C,program__C from WGUCourseInProgram__c where PAMSCourseID__c=999999 limit 1];
         system.assertequals(tie.course__C,definition.id);
         system.assertequals(tie.program__C,program.id);
         
         
    
     
     }
      

}