src/objects/WGUCourse__c.object
<CustomObject>
    <description>A course as is outlined in PAMS.</description>
    <fields>
        <fullName>MajorVersion__c</fullName>
        <label>Major Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGUCourseVersion__c.object
<CustomObject>
    <description>A version of a particular course.</description>
    <fields>
        <fullName>MajorVersion__c</fullName>
        <description>The major version of the course</description>
        <label>Major Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WGUCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The course that this course version belongs to</description>
        <label>WGU Course</label>
        <referenceTo>WGUCourse__c</referenceTo>
        <relationshipLabel>WGU Course Versions</relationshipLabel>
        <relationshipName>WGUCourseVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>title__c</fullName>
        <label>title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WGU Course Version</label>
    <nameField>
        <label>WGU Course Version code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGU Course Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JsTreeUtility.cls
/*
*Author John Chan
*Slalom
*/
global with sharing class JsTreeUtility {
	public static JsTree createJsTreeFromCourseList(List<WGUCourse__c> courses, Set<String> courseVersionIds) {
		JsTree jsTree = null;
		if (courses != null && courses.size() > 0) {
			List<JsTreeData> courseNode = new List<JsTreeData>();
			
			for (WGUCourse__c course : courses) {
				
				//Create Course Versions
				List<JsTreeData> courseVersionNode = null;
				if (course.WGUCourseVersions__r != null && course.WGUCourseVersions__r.size() > 0) {
					courseVersionNode = new List<JsTreeData>();
					for (WGUCourseVersion__c courseVersion : course.WGUCourseVersions__r) {
						boolean checked = (courseVersionIds != null && courseVersionIds.size() > 0 && courseVersionIds.contains(courseVersion.Id)) ? true : false;
						String courseVersionName = courseVersion.Name + ' v' + courseVersion.MajorVersion__c + ': ' + courseVersion.title__c;
						courseVersionNode.add(new JsTreeData(courseVersionName, new JsTreeDataAttr(courseVersion.Id, checked)));
					}
				}
				
				//Create Course
				courseNode.add(new JsTreeData(course.Name, courseVersionNode));
			}
			jsTree = new JsTree(courseNode);
		}
		return jsTree;
	}
	global class JsTree {
    	public JsTree(List<JsTreeData> dataNode) {
    		this.dataNode = dataNode;
    	}
    	public List<JsTreeData> dataNode;
    }
    
    public class JsTreeData {
    	public JsTreeData(String data, List<JsTreeData> children) {
    		this.data = data;
    		this.children = children;
    	}
    	public JsTreeData(String data, JsTreeDataAttr attr) {
    		this.data = data;
    		this.attr = attr;
    	}
    	public String data;
    	public JsTreeDataAttr attr;
    	public List<JsTreeData> children;
    }
    
    public class JsTreeDataAttr {
    	public JsTreeDataAttr(String value) {
    		this.value = value;
    	}
    	public JsTreeDataAttr(String value, boolean checked) {
    		this.value = value;
    		this.checked = checked;
    	}
    	public String value;
    	public boolean checked;
    }
}